export enum GlobalPermission {

  VIEW_GLOBAL_DASHBOARD="VIEW_GLOBAL_DASHBOARD",

  VIEW_REGION_DASHBOARD="VIEW_REGION_DASHBOARD",

  VIEW_COUNTRY_DASHBOARD="VIEW_COUNTRY_DASHBOARD",

  MANAGE_USERS="MANAGE_USERS",

  MANAGE_BOOKS="MANAGE_BOOKS",

  MANAGE_COURSES="MANAGE_COURSES",

  MANAGE_LANGUAGES="MANAGE_LANGUAGES",

  MANAGE_REGIONS="MANAGE_REGIONS",

  MANAGE_KPIS="MANAGE_KPIS",

  SYSTEM_ADMIN="SYSTEM_ADMIN"

}
