/** Unified Payment Catalog */
export type CatalogItemType = "membership_monthly" | "membership_annual" | "course" | "digital_product" | "book" | "event_registration" | "certification" | "consultation" | "donation" | "live_training" | "webinar" | "other";
export interface PaymentCatalogItem { id:string; name:string; description:string; type:CatalogItemType; price:number; currency:string; isRecurring:boolean; recurringInterval?:"monthly"|"annual"; membershipPlanId?:string; contentId?:string; active:boolean; metadata?:Record<string,string>; }
export const paymentCatalog: PaymentCatalogItem[] = [
  {id:"membership-basic-monthly",name:"Basic Membership — Monthly",description:"Structured learning resources, guided sessions, practical exercises, and member tools for financial literacy and competency growth.",type:"membership_monthly",price:14.99,currency:"USD",isRecurring:true,recurringInterval:"monthly",membershipPlanId:"basic",active:true},
  {id:"membership-basic-annual",name:"Basic Membership — Annual",description:"Full-year Basic membership at the annual membership rate.",type:"membership_annual",price:119.99,currency:"USD",isRecurring:true,recurringInterval:"annual",membershipPlanId:"basic",active:true},
  {id:"membership-premium-monthly",name:"Pro Membership — Monthly",description:"Expanded member benefits with deeper learning access, downloads, and AI financial coach support.",type:"membership_monthly",price:24.99,currency:"USD",isRecurring:true,recurringInterval:"monthly",membershipPlanId:"premium",active:true},
  {id:"membership-premium-annual",name:"Pro Membership — Annual",description:"Full-year Pro membership at the annual membership rate.",type:"membership_annual",price:199.99,currency:"USD",isRecurring:true,recurringInterval:"annual",membershipPlanId:"premium",active:true},
  {id:"membership-enterprise-monthly",name:"Gold Membership — Monthly",description:"Full membership access for advanced learners with priority support and premium tools.",type:"membership_monthly",price:39.99,currency:"USD",isRecurring:true,recurringInterval:"monthly",membershipPlanId:"enterprise",active:true},
  {id:"membership-enterprise-annual",name:"Gold Membership — Annual",description:"Full-year Gold membership at the annual membership rate.",type:"membership_annual",price:299.99,currency:"USD",isRecurring:true,recurringInterval:"annual",membershipPlanId:"enterprise",active:true},
  {id:"square-payment-test-001",name:"Square Payment Test",description:"Temporary $1.00 payment used to verify Edunancial's Square production checkout and webhook pipeline end to end.",type:"other",price:1,currency:"USD",isRecurring:false,active:true,metadata:{productId:"square-payment-test-001",purpose:"square-payment-test"}},
];
export function getCatalogItem(id:string){return paymentCatalog.find(item=>item.id===id);}
export function getActiveCatalogItems(type?:CatalogItemType){const active=paymentCatalog.filter(item=>item.active);return type?active.filter(item=>item.type===type):active;}
export function resolveCatalogItem(id:string){const direct=getCatalogItem(id);if(direct)return direct;return paymentCatalog.find(item=>item.membershipPlanId===id&&item.type==="membership_monthly"&&item.active);}
