// src/config/europe/countries.ts
// European country configurations with VAT rates and payment routing

import type { PaymentProviderType } from "@/lib/payments/providers";

export interface EuropeanCountry {
  code: string;
  name: string;
  nativeName: string;
  region: "europe-2a" | "europe-2b";
  currency: string;
  vatRate: number;
  reducedVatRate?: number;
  superReducedVatRate?: number;
  vatEnabled: boolean;
  defaultLanguage: string;
  supportedLanguages: string[];
  defaultProvider: PaymentProviderType;
  providers: PaymentProviderType[];
  euMember: boolean;
  gdprApplicable: boolean;
  psd2Applicable: boolean;
  timezone: string;
}

export const EUROPEAN_COUNTRIES: EuropeanCountry[] = [
  // === Europe 2A — Western Europe ===
  {
    code: "FR",
    name: "France",
    nativeName: "France",
    region: "europe-2a",
    currency: "EUR",
    vatRate: 20,
    reducedVatRate: 10,
    superReducedVatRate: 5.5,
    vatEnabled: true,
    defaultLanguage: "fr",
    supportedLanguages: ["fr", "en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Paris",
  },
  {
    code: "DE",
    name: "Germany",
    nativeName: "Deutschland",
    region: "europe-2a",
    currency: "EUR",
    vatRate: 19,
    reducedVatRate: 7,
    vatEnabled: true,
    defaultLanguage: "de",
    supportedLanguages: ["de", "en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Berlin",
  },
  {
    code: "ES",
    name: "Spain",
    nativeName: "España",
    region: "europe-2a",
    currency: "EUR",
    vatRate: 21,
    reducedVatRate: 10,
    superReducedVatRate: 4,
    vatEnabled: true,
    defaultLanguage: "es",
    supportedLanguages: ["es", "en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Madrid",
  },
  {
    code: "IT",
    name: "Italy",
    nativeName: "Italia",
    region: "europe-2a",
    currency: "EUR",
    vatRate: 22,
    reducedVatRate: 10,
    superReducedVatRate: 4,
    vatEnabled: true,
    defaultLanguage: "it",
    supportedLanguages: ["it", "en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Rome",
  },
  {
    code: "NL",
    name: "Netherlands",
    nativeName: "Nederland",
    region: "europe-2a",
    currency: "EUR",
    vatRate: 21,
    reducedVatRate: 9,
    vatEnabled: true,
    defaultLanguage: "en",
    supportedLanguages: ["en", "fr"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Amsterdam",
  },
  {
    code: "BE",
    name: "Belgium",
    nativeName: "Belgique / België",
    region: "europe-2a",
    currency: "EUR",
    vatRate: 21,
    reducedVatRate: 12,
    superReducedVatRate: 6,
    vatEnabled: true,
    defaultLanguage: "fr",
    supportedLanguages: ["fr", "en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Brussels",
  },
  {
    code: "PT",
    name: "Portugal",
    nativeName: "Portugal",
    region: "europe-2a",
    currency: "EUR",
    vatRate: 23,
    reducedVatRate: 13,
    superReducedVatRate: 6,
    vatEnabled: true,
    defaultLanguage: "pt",
    supportedLanguages: ["pt", "en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Lisbon",
  },
  {
    code: "GB",
    name: "United Kingdom",
    nativeName: "United Kingdom",
    region: "europe-2a",
    currency: "GBP",
    vatRate: 20,
    reducedVatRate: 5,
    vatEnabled: true,
    defaultLanguage: "en",
    supportedLanguages: ["en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: false,
    gdprApplicable: true,
    psd2Applicable: false,
    timezone: "Europe/London",
  },
  {
    code: "CH",
    name: "Switzerland",
    nativeName: "Schweiz / Suisse / Svizzera",
    region: "europe-2a",
    currency: "CHF",
    vatRate: 7.7,
    reducedVatRate: 2.5,
    vatEnabled: true,
    defaultLanguage: "de",
    supportedLanguages: ["de", "fr", "en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: false,
    gdprApplicable: false,
    psd2Applicable: false,
    timezone: "Europe/Zurich",
  },
  // === Europe 2B — Eastern / Central Europe ===
  {
    code: "PL",
    name: "Poland",
    nativeName: "Polska",
    region: "europe-2b",
    currency: "PLN",
    vatRate: 23,
    reducedVatRate: 8,
    superReducedVatRate: 5,
    vatEnabled: true,
    defaultLanguage: "en",
    supportedLanguages: ["en", "fr"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Warsaw",
  },
  {
    code: "CZ",
    name: "Czech Republic",
    nativeName: "Česká republika",
    region: "europe-2b",
    currency: "CZK",
    vatRate: 21,
    reducedVatRate: 12,
    vatEnabled: true,
    defaultLanguage: "en",
    supportedLanguages: ["en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Prague",
  },
  {
    code: "HU",
    name: "Hungary",
    nativeName: "Magyarország",
    region: "europe-2b",
    currency: "HUF",
    vatRate: 27,
    reducedVatRate: 18,
    superReducedVatRate: 5,
    vatEnabled: true,
    defaultLanguage: "en",
    supportedLanguages: ["en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Budapest",
  },
  {
    code: "RO",
    name: "Romania",
    nativeName: "România",
    region: "europe-2b",
    currency: "RON",
    vatRate: 19,
    reducedVatRate: 9,
    superReducedVatRate: 5,
    vatEnabled: true,
    defaultLanguage: "en",
    supportedLanguages: ["en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Bucharest",
  },
  {
    code: "SK",
    name: "Slovakia",
    nativeName: "Slovensko",
    region: "europe-2b",
    currency: "EUR",
    vatRate: 20,
    reducedVatRate: 10,
    vatEnabled: true,
    defaultLanguage: "en",
    supportedLanguages: ["en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Bratislava",
  },
  {
    code: "BG",
    name: "Bulgaria",
    nativeName: "България",
    region: "europe-2b",
    currency: "BGN",
    vatRate: 20,
    reducedVatRate: 9,
    vatEnabled: true,
    defaultLanguage: "en",
    supportedLanguages: ["en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Sofia",
  },
  {
    code: "HR",
    name: "Croatia",
    nativeName: "Hrvatska",
    region: "europe-2b",
    currency: "EUR",
    vatRate: 25,
    reducedVatRate: 13,
    superReducedVatRate: 5,
    vatEnabled: true,
    defaultLanguage: "en",
    supportedLanguages: ["en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Zagreb",
  },
  {
    code: "EE",
    name: "Estonia",
    nativeName: "Eesti",
    region: "europe-2b",
    currency: "EUR",
    vatRate: 22,
    reducedVatRate: 9,
    vatEnabled: true,
    defaultLanguage: "en",
    supportedLanguages: ["en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Tallinn",
  },
  {
    code: "LV",
    name: "Latvia",
    nativeName: "Latvija",
    region: "europe-2b",
    currency: "EUR",
    vatRate: 21,
    reducedVatRate: 12,
    superReducedVatRate: 5,
    vatEnabled: true,
    defaultLanguage: "en",
    supportedLanguages: ["en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Riga",
  },
  {
    code: "LT",
    name: "Lithuania",
    nativeName: "Lietuva",
    region: "europe-2b",
    currency: "EUR",
    vatRate: 21,
    reducedVatRate: 9,
    superReducedVatRate: 5,
    vatEnabled: true,
    defaultLanguage: "en",
    supportedLanguages: ["en"],
    defaultProvider: "stripe",
    providers: ["stripe", "paypal"],
    euMember: true,
    gdprApplicable: true,
    psd2Applicable: true,
    timezone: "Europe/Vilnius",
  },
  // === Restricted / Sanctioned — present in architecture, disabled via countryActivation.ts ===
  {
    code: "RU",
    name: "Russia",
    nativeName: "Россия",
    region: "europe-2b",
    currency: "RUB",
    vatRate: 20,
    reducedVatRate: 10,
    vatEnabled: true,
    defaultLanguage: "ru",
    supportedLanguages: ["ru"],
    defaultProvider: "stripe",
    providers: [],
    euMember: false,
    gdprApplicable: false,
    psd2Applicable: false,
    timezone: "Europe/Moscow",
  },
  {
    code: "BY",
    name: "Belarus",
    nativeName: "Беларусь",
    region: "europe-2b",
    currency: "BYN",
    vatRate: 20,
    reducedVatRate: 10,
    vatEnabled: true,
    defaultLanguage: "be",
    supportedLanguages: ["be", "ru"],
    defaultProvider: "stripe",
    providers: [],
    euMember: false,
    gdprApplicable: false,
    psd2Applicable: false,
    timezone: "Europe/Minsk",
  },
];

export const EUROPEAN_COUNTRIES_BY_CODE: Record<string, EuropeanCountry> =
  Object.fromEntries(EUROPEAN_COUNTRIES.map((c) => [c.code, c]));

export function getEuropeanCountry(code: string): EuropeanCountry | undefined {
  return EUROPEAN_COUNTRIES_BY_CODE[code.toUpperCase()];
}

export function getEuropeanCountriesByRegion(
  region: "europe-2a" | "europe-2b"
): EuropeanCountry[] {
  return EUROPEAN_COUNTRIES.filter((c) => c.region === region);
}
