/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE:
// This file is required for TypeScript projects.
// Do not edit this file unless you know what you are doing.
