import { createHash } from "node:crypto";
import { extname } from "node:path";

export async function validateCurriculumFiles(files: Array<{ destination: string; content: string }>) {
  const relevant = files.filter((file) => file.destination.startsWith("content/curriculum/") && extname(file.destination).toLowerCase() === ".md");
  if (relevant.length === 0) return { success: true, warnings: ["No curriculum-bound markdown files required validation."], errors: [] as string[] };
  const validator = await import("../../../scripts/curriculum/lib/validator.mjs"); const idParser = await import("../../../scripts/curriculum/lib/id-parser.mjs"); const warnings:string[]=[]; const errors:string[]=[];
  for(const file of relevant){const match=file.destination.match(/([A-Z]+-L\d+-[A-Z0-9-]+)(?:\.[A-Za-z0-9-]+)?\.md$/);const assetId=match?.[1];if(!assetId){warnings.push(`${file.destination} does not map to a canonical curriculum asset ID.`);continue}const parsed=idParser.parseAssetId(assetId);if(!parsed.valid){errors.push(`${assetId}: ${parsed.error}`);continue}const result=validator.validateAsset(file.content,assetId);warnings.push(...result.warnings.map((w:string)=>`${assetId}: ${w}`));errors.push(...result.errors.map((e:string)=>`${assetId}: ${e}`))}return{success:errors.length===0,warnings,errors};
}
export type ParsedCurriculumAsset={id:string;type:"lesson"|"manifest"|"batch-verification";track:string;trackName:string;level:number;number?:number;canonicalPath:string;destinationPath:string;locale?:string;frontMatter:Record<string,string>;validationPassed:boolean;warnings:string[]};
export type BundledCurriculumLesson={asset:ParsedCurriculumAsset;content:string};
type ParsedAsset={valid:boolean;type?:string;track?:string;trackName?:string;level?:number;number?:number;id?:string;error?:string}; type ValidationResult={valid:boolean;warnings:string[];errors:string[]};
const TRACK_NAMES:Record<string,string>={RED:"Real Estate",WHITE:"Paper Assets",BLUE:"Business",GREEN:"Personal Finance and Taxes",GOLD:"Investing",PURPLE:"Law",ORANGE:"Sales and Marketing",BLACK:"Leadership"};
function recoveredHeader(content:string,sourceFilename?:string):Record<string,string>|null{const file=(content.match(/^Filename:\s*([A-Z][A-Z0-9]*-L[1-9][0-9]*-[0-9]{3,})\.md\s*$/im)?.[1]??sourceFilename?.match(/([A-Z][A-Z0-9]*-L[1-9][0-9]*-[0-9]{3,})\.md$/i)?.[1])?.toUpperCase();if(!file)return null;const m=file.match(/^([A-Z][A-Z0-9]*)-L([1-9][0-9]*)-([0-9]{3,})$/);if(!m)return null;const title=content.match(/^Title:\s*(.+)$/im)?.[1]?.trim()||file;const summary=content.match(/^Meta Description:\s*(.+)$/im)?.[1]?.trim()||"";return{id:file,track:m[1],officialTrackName:TRACK_NAMES[m[1]]??m[1],level:m[2],lessonNumber:String(Number(m[3])),title,summary,version:"1.0",author:"Edunancial Faculty",date:new Date().toISOString().slice(0,10)}}
export async function detectCurriculumAsset(content:string,sourceFilename?:string):Promise<ParsedCurriculumAsset|null>{try{const idParser=await import("../../../scripts/curriculum/lib/id-parser.mjs") as {parseAssetId:(id:string)=>ParsedAsset;assetPath:(parsed:ParsedAsset)=>string};const validator=await import("../../../scripts/curriculum/lib/validator.mjs") as {parseFrontMatter:(content:string)=>Record<string,string>|null;validateAsset:(content:string,id:string)=>ValidationResult};const parsedFm=validator.parseFrontMatter(content);const fm=parsedFm?.id?parsedFm:recoveredHeader(content,sourceFilename);if (!fm || !fm.id) return null;const parsed=idParser.parseAssetId(fm.id);if(!parsed.valid)return null;const canonicalPath=idParser.assetPath(parsed);const localeMatch=sourceFilename?.match(/\.([A-Za-z0-9-]+)\.md$/u);const locale=localeMatch?.[1];const validation=parsedFm?.id?validator.validateAsset(content,fm.id):{valid:true,warnings:["Recovered canonical header format normalized at runtime."],errors:[]};return{id:fm.id,type:(parsed.type??"lesson") as ParsedCurriculumAsset["type"],track:parsed.track??fm.track??"",trackName:parsed.trackName??fm.officialTrackName??"",level:parsed.level??Number(fm.level??0),number:parsed.number??Number(fm.lessonNumber??0),canonicalPath,destinationPath:locale&&canonicalPath.endsWith(".md")?canonicalPath.replace(/\.md$/u,`.${locale}.md`):canonicalPath,locale,frontMatter:fm,validationPassed:validation.valid,warnings:validation.warnings}}catch{return null}}
function parseBundledMetadata(section:string){const metadata:Record<string,string>={};for(const line of section.split(/\r?\n/)){const trimmed=line.trim();if(!trimmed||trimmed.startsWith("#"))break;const i=trimmed.indexOf(":");if(i<=0)continue;const k=trimmed.slice(0,i).trim().toUpperCase(),v=trimmed.slice(i+1).trim();if(k&&v)metadata[k]=v}return metadata}
function metadataLine(section:string,label:string){return section.match(new RegExp(`\\*\\*${label}:\\*\\*\\s*(.+?)(?:\\n|$)`,`i`))?.[1]?.trim()??""}
async function canonicalizeLesson(id:string,section:string):Promise<BundledCurriculumLesson|null>{const m=id.match(/^([A-Z][A-Z0-9]*)-L([1-9][0-9]*)-([0-9]{3,})$/u);if(!m)return null;const[,track,levelRaw,numberRaw]=m,level=Number(levelRaw),lessonNumber=Number(numberRaw),trackRaw=metadataLine(section,"Track"),officialTrackName=trackRaw.match(/^[A-Z][A-Z0-9]*\s*\((.+)\)$/u)?.[1]??TRACK_NAMES[track]??track,author=metadataLine(section,"Author")||"Edunancial Faculty",explicitTitle=metadataLine(section,"Lesson Title"),lines=section.split(/\r?\n/),firstHeading=lines.find((line,index)=>index>0&&/^#{1,6}\s+/.test(line)&&!new RegExp(`^#{1,6}\\s+${id}\\s*$`,`i`).test(line)),title=explicitTitle||firstHeading?.replace(/^#{1,6}\s+/,"").trim()||id,summary=section.match(/(?:^|\n)#{1,6}\s+Executive Summary\s*\n+([\s\S]+?)(?=\n#{1,6}\s+|$)/i)?.[1]?.replace(/\s+/g," ").trim().slice(0,220)??"",today=new Date().toISOString().slice(0,10),canonical=["---",`id: ${id}`,`track: ${track}`,`officialTrackName: ${officialTrackName}`,`level: ${level}`,`lessonNumber: ${lessonNumber}`,`title: ${title}`,...(summary?[`summary: ${summary}`]:[]),"version: 1.0",`author: ${author}`,`date: ${today}`,"---","",section.trim(),""].join("\n"),asset=await detectCurriculumAsset(canonical);return asset?{asset,content:canonical}:null}
async function detectSimpleMasterCurriculumLessons(content:string){const pattern=/^#{1,6}\s+([A-Z][A-Z0-9]*-L[1-9][0-9]*-[0-9]{3,})\s*$/gim,matches=Array.from(content.matchAll(pattern));if(!matches.length)return[];const ids=matches.map(m=>m[1].toUpperCase());if(new Set(ids).size!==ids.length)throw new Error("Curriculum master bundle contains duplicate lesson IDs.");const identity=ids[0].match(/^([A-Z][A-Z0-9]*)-L([1-9][0-9]*)-/u);if(!identity)return[];for(const id of ids){const c=id.match(/^([A-Z][A-Z0-9]*)-L([1-9][0-9]*)-([0-9]{3,})$/u);if(!c||c[1]!==identity[1]||c[2]!==identity[2])throw new Error(`Curriculum master bundle mixes track/level identities: ${id}.`)}const nums=ids.map(id=>Number(id.match(/-([0-9]{3,})$/u)?.[1]));for(let i=1;i<nums.length;i++)if(nums[i]!==nums[i-1]+1)throw new Error(`Curriculum master bundle has a non-sequential lesson ID between ${ids[i-1]} and ${ids[i]}.`);const lessons:BundledCurriculumLesson[]=[];for(let i=0;i<matches.length;i++){const lesson=await canonicalizeLesson(ids[i],content.slice(matches[i].index??0,matches[i+1]?.index??content.length).trim());if(!lesson)throw new Error(`Curriculum master bundle lesson ${ids[i]} could not be canonicalized.`);lessons.push(lesson)}return lessons}
export async function detectBundledCurriculumLessons(content:string):Promise<BundledCurriculumLesson[]>{const marker=/^CONTENT ID:\s*([A-Z]+-L\d+-[0-9]{3,})\s*$/gm,matches=Array.from(content.matchAll(marker));if(!matches.length)return detectSimpleMasterCurriculumLessons(content);const lessons:BundledCurriculumLesson[]=[];for(let i=0;i<matches.length;i++){const current=matches[i],next=matches[i+1],section=content.slice(current.index??0,next?.index??content.length).trim(),metadata=parseBundledMetadata(section),headingStart=section.search(/^#\s+/m);if(headingStart<0)continue;const id=current[1],track=metadata["TRACK"]??id.split("-")[0],level=Number(metadata["LEVEL"]??id.match(/-L(\d+)-/)?.[1]??1),lessonNumber=Number(metadata["LESSON NUMBER"]??id.match(/-([0-9]{3,})$/)?.[1]??1),title=metadata["LESSON TITLE"]??id,author=metadata["AUTHOR"]??"Edunancial Faculty",version=metadata["VERSION"]??"1.0",date=metadata["DATE"]??metadata["LAST REVIEW DATE"]??new Date().toISOString().slice(0,10),officialTrackName=metadata["OFFICIAL TRACK NAME"]??TRACK_NAMES[track]??track,body=section.slice(headingStart).trim(),canonical=["---",`id: ${id}`,`track: ${track}`,`officialTrackName: ${officialTrackName}`,`level: ${level}`,`lessonNumber: ${lessonNumber}`,`title: ${title}`,`version: ${version}`,`author: ${author}`,`date: ${date}`,"---","",body,""].join("\n"),asset=await detectCurriculumAsset(canonical);if(asset)lessons.push({asset,content:canonical})}return lessons}
export type CurriculumRegistryEntry={id:string;type:string;track:string;trackName:string;level:number;lessonNumber?:number;title:string;version:string;author:string;date:string;path:string;checksum:string;status:"active";ingestionId:string;importedAt:string;validationPassed:boolean;warnings:string[];metadata:Record<string,string>};export type CurriculumRegistry={_schema:string;_version:string;_generated:string;_note:string;tracks:Record<string,{code:string;name:string;levels:Record<string,{assets:Record<string,CurriculumRegistryEntry>}>}>};const RESERVED_FM_KEYS=new Set(["id","track","officialTrackName","level","lessonNumber","title","version","author","date"]);
export function buildRegistryEntry(asset:ParsedCurriculumAsset,contentBytes:Buffer,ingestionId:string,importedAt:string,existingChecksum?:string):CurriculumRegistryEntry{const checksum=existingChecksum??"sha256:"+createHash("sha256").update(contentBytes).digest("hex"),fm=asset.frontMatter,extraMetadata=Object.fromEntries(Object.entries(fm).filter(([k])=>!RESERVED_FM_KEYS.has(k)));return{id:asset.id,type:asset.type,track:asset.track,trackName:asset.trackName,level:asset.level,lessonNumber:asset.type==="lesson"?(parseInt(fm.lessonNumber??"",10)||asset.number):undefined,title:fm.title??"",version:fm.version??"1.0",author:fm.author??"",date:fm.date??"",path:asset.canonicalPath,checksum,status:"active",ingestionId,importedAt,validationPassed:asset.validationPassed,warnings:asset.warnings,metadata:{officialTrackName:fm.officialTrackName??asset.trackName,...extraMetadata}}}
export function upsertRegistryEntries(existingRegistry:CurriculumRegistry|null,entries:CurriculumRegistryEntry[]):CurriculumRegistry{const registry=existingRegistry??{_schema:"curriculum/schemas/registry.schema.json",_version:"1.0",_generated:new Date().toISOString(),_note:"Authoritative curriculum registry. Edit only via curriculum:import or curriculum:migrate-legacy.",tracks:{}};registry._generated=new Date().toISOString();for(const entry of entries){if(!registry.tracks[entry.track])registry.tracks[entry.track]={code:entry.track,name:entry.trackName,levels:{}};const levelKey=String(entry.level);if(!registry.tracks[entry.track].levels[levelKey])registry.tracks[entry.track].levels[levelKey]={assets:{}};registry.tracks[entry.track].levels[levelKey].assets[entry.id]=entry}return registry}
