import { createHash } from "node:crypto";
import { extname } from "node:path";

export async function validateCurriculumFiles(files: Array<{ destination: string; content: string }>) {
  const relevant = files.filter((file) => file.destination.startsWith("content/curriculum/") && extname(file.destination).toLowerCase() === ".md");
  if (relevant.length === 0) return { success: true, warnings: ["No curriculum-bound markdown files required validation."], errors: [] as string[] };
  const validator = await import("../../../scripts/curriculum/lib/validator.mjs"); const idParser = await import("../../../scripts/curriculum/lib/id-parser.mjs"); const warnings:string[]=[]; const errors:string[]=[];
  for(const file of relevant){const match=file.destination.match(/([A-Z]+-L\d+-[A-Z0-9-]+)(?:\.[A-Za-z0-9-]+)?\.md$/);const assetId=match?.[1];if(!assetId){warnings.push(`${file.destination} does not map to a canonical curriculum asset ID.`);continue}const parsed=idParser.parseAssetId(assetId);if(!parsed.valid){errors.push(`${assetId}: ${parsed.error}`);continue}const result=validator.validateAsset(file.content,assetId);warnings.push(...result.warnings.map((w:string)=>`${assetId}: ${w}`));errors.push(...result.errors.map((e:string)=>`${assetId}: ${e}`))}return{success:errors.length===0,warnings,errors};
}
export type ParsedCurriculumAsset={id:string;type:"lesson"|"manifest"|"batch-verification";track:string;trackName:string;level:number;number?:number;canonicalPath:string;destinationPath:string;locale?:string;frontMatter:Record<string,string>;validationPassed:boolean;warnings:string[]};
export type BundledCurriculumLesson={asset:ParsedCurriculumAsset;content:string};
type ParsedAsset={valid:boolean;type?:string;track?:string;trackName?:string;level?:number;number?:number;id?:string;error?:string}; type ValidationResult={valid:boolean;warnings:string[];errors:string[]};
const TRACK_NAMES:Record<string,string>={RED:"Real Estate",WHITE:"Paper Assets",BLUE:"Business",GREEN:"Personal Finance and Taxes",GOLD:"Investing",PURPLE:"Law",ORANGE:"Sales and Marketing",BLACK:"Leadership"};
const CANONICAL_LESSON_ID_PATTERN=/^([A-Z][A-Z0-9]*)-L([1-9][0-9]*)-([0-9]{3,})$/u;
const SIMPLE_MASTER_LESSON_HEADING=/^#{1,6}\s+([A-Z][A-Z0-9]*-L[1-9][0-9]*-[0-9]{3,})\s*$/gim;
const CONTENT_ID_MARKER=/^CONTENT ID:\s*([A-Z][A-Z0-9]*-L\d+-[0-9]{3,})\s*$/gm;
function parseLessonId(id:string|null|undefined){const match=id?.trim().toUpperCase().match(CANONICAL_LESSON_ID_PATTERN);return match?{id:match[0],track:match[1],level:Number(match[2]),lessonNumber:Number(match[3])}:null}
function validateSequentialLessonIds(ids:string[]){if(!ids.length)return;const parsed=ids.map(id=>parseLessonId(id));if(parsed.some((id):id is null=>!id))throw new Error("Curriculum master bundle contains an invalid canonical lesson ID.");const [first,...rest]=parsed as NonNullable<ReturnType<typeof parseLessonId>>[];const seen=new Set<string>();for(const lesson of[first,...rest]){if(seen.has(lesson.id))throw new Error("Curriculum master bundle contains duplicate lesson IDs.");seen.add(lesson.id);if(lesson.track!==first.track||lesson.level!==first.level)throw new Error(`Curriculum master bundle mixes track/level identities: ${lesson.id}.`)}for(let i=1;i<parsed.length;i++){const current=(parsed as NonNullable<ReturnType<typeof parseLessonId>>[])[i],previous=(parsed as NonNullable<ReturnType<typeof parseLessonId>>[])[i-1];if(current.lessonNumber!==previous.lessonNumber+1)throw new Error(`Curriculum master bundle has a non-sequential lesson ID between ${previous.id} and ${current.id}.`)}}
function recoveredHeader(content:string,sourceFilename?:string):Record<string,string>|null{const parsed=parseLessonId(content.match(/^Filename:\s*([A-Z][A-Z0-9]*-L[1-9][0-9]*-[0-9]{3,})\.md\s*$/im)?.[1]??sourceFilename?.match(/([A-Z][A-Z0-9]*-L[1-9][0-9]*-[0-9]{3,})\.md$/i)?.[1]);if(!parsed)return null;const title=content.match(/^Title:\s*(.+)$/im)?.[1]?.trim()||parsed.id,summary=content.match(/^Meta Description:\s*(.+)$/im)?.[1]?.trim()||"";return{id:parsed.id,track:parsed.track,officialTrackName:TRACK_NAMES[parsed.track]??parsed.track,level:String(parsed.level),lessonNumber:String(parsed.lessonNumber),title,summary,version:"1.0",author:"Edunancial Faculty",date:new Date().toISOString().slice(0,10)}}
export async function detectCurriculumAsset(content:string,sourceFilename?:string):Promise<ParsedCurriculumAsset|null>{try{const idParser=await import("../../../scripts/curriculum/lib/id-parser.mjs") as {parseAssetId:(id:string)=>ParsedAsset;assetPath:(parsed:ParsedAsset)=>string};const validator=await import("../../../scripts/curriculum/lib/validator.mjs") as {parseFrontMatter:(content:string)=>Record<string,string>|null;validateAsset:(content:string,id:string)=>ValidationResult};const parsedFm=validator.parseFrontMatter(content);const fm=parsedFm?.id?parsedFm:recoveredHeader(content,sourceFilename);if (!fm || !fm.id) return null;const parsed=idParser.parseAssetId(fm.id);if(!parsed.valid)return null;const canonicalPath=idParser.assetPath(parsed);const localeMatch=sourceFilename?.match(/\.([A-Za-z0-9-]+)\.md$/u);const locale=localeMatch?.[1];const validation=parsedFm?.id?validator.validateAsset(content,fm.id):{valid:true,warnings:["Recovered canonical header format normalized at runtime."],errors:[]};return{id:fm.id,type:(parsed.type??"lesson") as ParsedCurriculumAsset["type"],track:parsed.track??fm.track??"",trackName:parsed.trackName??fm.officialTrackName??"",level:parsed.level??Number(fm.level??0),number:parsed.number??Number(fm.lessonNumber??0),canonicalPath,destinationPath:locale&&canonicalPath.endsWith(".md")?canonicalPath.replace(/\.md$/u,`.${locale}.md`):canonicalPath,locale,frontMatter:fm,validationPassed:validation.valid,warnings:validation.warnings}}catch{return null}}
function parseBundledMetadata(section:string){const metadata:Record<string,string>={};for(const line of section.split(/\r?\n/)){const trimmed=line.trim();if(!trimmed||trimmed.startsWith("#"))break;const i=trimmed.indexOf(":");if(i<=0)continue;const k=trimmed.slice(0,i).trim().toUpperCase(),v=trimmed.slice(i+1).trim();if(k&&v)metadata[k]=v}return metadata}
function metadataLine(section:string,label:string){return section.match(new RegExp(`\\*\\*${label}:\\*\\*\\s*(.+?)(?:\\n|$)`,`i`))?.[1]?.trim()??""}
async function canonicalizeLesson(id:string,section:string):Promise<BundledCurriculumLesson|null>{const lesson=parseLessonId(id);if(!lesson)return null;const trackRaw=metadataLine(section,"Track"),officialTrackName=trackRaw.match(/^[A-Z][A-Z0-9]*\s*\((.+)\)$/u)?.[1]??TRACK_NAMES[lesson.track]??lesson.track,author=metadataLine(section,"Author")||"Edunancial Faculty",explicitTitle=metadataLine(section,"Lesson Title"),lines=section.split(/\r?\n/),firstHeading=lines.find((line,index)=>index>0&&/^#{1,6}\s+/.test(line)&&!new RegExp(`^#{1,6}\\s+${lesson.id}\\s*$`,`i`).test(line)),title=explicitTitle||firstHeading?.replace(/^#{1,6}\s+/,"").trim()||lesson.id,summary=section.match(/(?:^|\n)#{1,6}\s+Executive Summary\s*\n+([\s\S]+?)(?=\n#{1,6}\s+|$)/i)?.[1]?.replace(/\s+/g," ").trim().slice(0,220)??"",today=new Date().toISOString().slice(0,10),canonical=["---",`id: ${lesson.id}`,`track: ${lesson.track}`,`officialTrackName: ${officialTrackName}`,`level: ${lesson.level}`,`lessonNumber: ${lesson.lessonNumber}`,`title: ${title}`,...(summary?[`summary: ${summary}`]:[]),"version: 1.0",`author: ${author}`,`date: ${today}`,"---","",section.trim(),""].join("\n"),asset=await detectCurriculumAsset(canonical);return asset?{asset,content:canonical}:null}
async function detectSimpleMasterCurriculumLessons(content:string){const matches=Array.from(content.matchAll(SIMPLE_MASTER_LESSON_HEADING));if(!matches.length)return[];const ids=matches.map(match=>match[1].toUpperCase()),recoveredId=recoveredHeader(content)?.id;if(recoveredId&&matches.length===1&&ids[0]===recoveredId)return[];validateSequentialLessonIds(ids);const lessons:BundledCurriculumLesson[]=[];for(let i=0;i<matches.length;i++){const lesson=await canonicalizeLesson(ids[i],content.slice(matches[i].index??0,matches[i+1]?.index??content.length).trim());if(!lesson)throw new Error(`Curriculum master bundle lesson ${ids[i]} could not be canonicalized.`);lessons.push(lesson)}return lessons}
export async function detectBundledCurriculumLessons(content:string):Promise<BundledCurriculumLesson[]>{const matches=Array.from(content.matchAll(CONTENT_ID_MARKER));if(!matches.length)return detectSimpleMasterCurriculumLessons(content);validateSequentialLessonIds(matches.map(match=>match[1].toUpperCase()));const lessons:BundledCurriculumLesson[]=[];for(let i=0;i<matches.length;i++){const current=matches[i],next=matches[i+1],section=content.slice(current.index??0,next?.index??content.length).trim(),metadata=parseBundledMetadata(section),headingStart=section.search(/^#\s+/m),lesson=parseLessonId(current[1]);if(headingStart<0||!lesson)continue;const track=(metadata["TRACK"]??lesson.track).trim().toUpperCase(),level=Number(metadata["LEVEL"]??lesson.level),lessonNumber=Number(metadata["LESSON NUMBER"]??lesson.lessonNumber);if(track!==lesson.track||level!==lesson.level||lessonNumber!==lesson.lessonNumber)throw new Error(`Curriculum master bundle metadata conflicts with canonical lesson ID: ${lesson.id}.`);const title=metadata["LESSON TITLE"]??lesson.id,author=metadata["AUTHOR"]??"Edunancial Faculty",version=metadata["VERSION"]??"1.0",date=metadata["DATE"]??metadata["LAST REVIEW DATE"]??new Date().toISOString().slice(0,10),officialTrackName=metadata["OFFICIAL TRACK NAME"]??TRACK_NAMES[lesson.track]??lesson.track,body=section.slice(headingStart).trim(),canonical=["---",`id: ${lesson.id}`,`track: ${lesson.track}`,`officialTrackName: ${officialTrackName}`,`level: ${lesson.level}`,`lessonNumber: ${lesson.lessonNumber}`,`title: ${title}`,`version: ${version}`,`author: ${author}`,`date: ${date}`,"---","",body,""].join("\n"),asset=await detectCurriculumAsset(canonical);if(asset)lessons.push({asset,content:canonical})}return lessons}
export async function detectCurriculumSourceLessons(content:string,sourceFilename?:string):Promise<BundledCurriculumLesson[]>{const direct=await detectCurriculumAsset(content,sourceFilename);return direct&&(!direct.locale||/^en(?:[_-][a-z0-9]+)?$/iu.test(direct.locale))?[{asset:direct,content}]:detectBundledCurriculumLessons(content)}
export function isCanonicalEnglishCurriculumPath(path:string){const locale=path.split(/[\\/]/u).at(-2)?.toLowerCase();return Boolean(locale&&/^en(?:[_-][a-z0-9]+)?$/u.test(locale))}
export type CurriculumRegistryEntry={id:string;type:string;track:string;trackName:string;level:number;lessonNumber?:number;title:string;version:string;author:string;date:string;path:string;checksum:string;status:"active";ingestionId:string;importedAt:string;validationPassed:boolean;warnings:string[];metadata:Record<string,string>};export type CurriculumRegistry={_schema:string;_version:string;_generated:string;_note:string;tracks:Record<string,{code:string;name:string;levels:Record<string,{assets:Record<string,CurriculumRegistryEntry>}>}>};const RESERVED_FM_KEYS=new Set(["id","track","officialTrackName","level","lessonNumber","title","version","author","date"]);
export function buildRegistryEntry(asset:ParsedCurriculumAsset,contentBytes:Buffer,ingestionId:string,importedAt:string,existingChecksum?:string):CurriculumRegistryEntry{const checksum=existingChecksum??"sha256:"+createHash("sha256").update(contentBytes).digest("hex"),fm=asset.frontMatter,extraMetadata=Object.fromEntries(Object.entries(fm).filter(([k])=>!RESERVED_FM_KEYS.has(k)));return{id:asset.id,type:asset.type,track:asset.track,trackName:asset.trackName,level:asset.level,lessonNumber:asset.type==="lesson"?(parseInt(fm.lessonNumber??"",10)||asset.number):undefined,title:fm.title??"",version:fm.version??"1.0",author:fm.author??"",date:fm.date??"",path:asset.canonicalPath,checksum,status:"active",ingestionId,importedAt,validationPassed:asset.validationPassed,warnings:asset.warnings,metadata:{officialTrackName:fm.officialTrackName??asset.trackName,...extraMetadata}}}
export function upsertRegistryEntries(existingRegistry:CurriculumRegistry|null,entries:CurriculumRegistryEntry[]):CurriculumRegistry{const registry=existingRegistry??{_schema:"curriculum/schemas/registry.schema.json",_version:"1.0",_generated:new Date().toISOString(),_note:"Authoritative curriculum registry. Edit only via curriculum:import or curriculum:migrate-legacy.",tracks:{}};registry._generated=new Date().toISOString();for(const entry of entries){if(!registry.tracks[entry.track])registry.tracks[entry.track]={code:entry.track,name:entry.trackName,levels:{}};const levelKey=String(entry.level);if(!registry.tracks[entry.track].levels[levelKey])registry.tracks[entry.track].levels[levelKey]={assets:{}};registry.tracks[entry.track].levels[levelKey].assets[entry.id]=entry}return registry}
