/** Curriculum auto-ingest regression coverage. */
import assert from "node:assert/strict";
import { describe, test } from "node:test";
import { buildRegistryEntry, detectBundledCurriculumLessons, detectCurriculumAsset, upsertRegistryEntries } from "@/lib/admin-content/curriculum";

const VALID_CURRICULUM_CONTENT = ["---","id: RED-L1-099","track: RED","officialTrackName: Real Estate","level: 1","lessonNumber: 99","title: Auto-Ingest Test Lesson","version: 1.0","author: Edunancial Faculty","date: 2026-01-01","---","","## What Is This?","A lesson used to validate the pipeline.","","## Why Does It Matter?","It proves auto-ingest works.","","## How Is It Used?","Upload and verify registry.","","## Common Mistakes","Skipping validation.","","## Apply This Knowledge","Inspect registry."].join("\n");
function makeRegistryEntry(id: string, lessonNumber: number) { return { id, type: "lesson" as const, track: "RED", trackName: "Real Estate", level: 1, lessonNumber, title: `Lesson ${lessonNumber}`, version: "1.0", author: "Test", date: "2026-01-01", path: `content/curriculum/RED/L1/${id}.md`, checksum: `sha256:${id}`, status: "active" as const, ingestionId: "test", importedAt: "2026-01-01T00:00:00.000Z", validationPassed: true, warnings: [], metadata: { officialTrackName: "Real Estate" } }; }

describe("curriculum auto-ingest", () => {
  test("upserts without clobbering existing assets", () => { const one = upsertRegistryEntries(null,[makeRegistryEntry("RED-L1-001",1)]); const two=upsertRegistryEntries(one,[makeRegistryEntry("RED-L1-002",2)]); assert.equal(Object.keys(two.tracks.RED.levels["1"].assets).length,2); });
  test("detects canonical frontmatter", async () => { const asset=await detectCurriculumAsset(VALID_CURRICULUM_CONTENT); assert.ok(asset); assert.equal(asset.id,"RED-L1-099"); });
  test("parses CONTENT ID combined format", async () => { const source=["CONTENT ID: WHITE-L1-001","TRACK: WHITE","OFFICIAL TRACK NAME: Paper Assets","LEVEL: 1","LESSON NUMBER: 001","LESSON TITLE: Intro","","# Intro","## Learning Objectives","Learn","## Core Content","Body"].join("\n"); const lessons=await detectBundledCurriculumLessons(source); assert.equal(lessons.length,1); assert.equal(lessons[0].asset.id,"WHITE-L1-001"); });
  test("parses Claude master headings at Level 2", async () => { const source=["# RED Level 2","","## RED-L2-001","### Executive Summary","First summary.","### Learning Objectives","Learn one.","### Core Content","First body.","","## RED-L2-002","### Executive Summary","Second summary.","### Learning Objectives","Learn two.","### Core Content","Second body."].join("\n"); const lessons=await detectBundledCurriculumLessons(source); assert.equal(lessons.length,2); assert.equal(lessons[0].asset.id,"RED-L2-001"); assert.equal(lessons[1].asset.id,"RED-L2-002"); assert.equal(lessons[1].asset.canonicalPath,"content/curriculum/RED/L2/RED-L2-002.md"); });
  test("supports Levels 3, 4 and 5 without a 50-lesson ceiling", async () => { for (const level of [3,4,5]) { const source=[`## BLUE-L${level}-050`,`### Core Content`,`Fifty.`,`## BLUE-L${level}-051`,`### Core Content`,`Fifty one.`].join("\n"); const lessons=await detectBundledCurriculumLessons(source); assert.equal(lessons.length,2); assert.equal(lessons[1].asset.id,`BLUE-L${level}-051`); } });
  test("fails closed on gaps in master IDs", async () => { const source=["## GOLD-L4-001","### Core Content","One","## GOLD-L4-003","### Core Content","Three"].join("\n"); await assert.rejects(() => detectBundledCurriculumLessons(source),/non-sequential lesson ID/); });
  test("fails closed when a master mixes levels", async () => { const source=["## PURPLE-L3-001","### Core Content","One","## PURPLE-L4-002","### Core Content","Two"].join("\n"); await assert.rejects(() => detectBundledCurriculumLessons(source),/mixes track\/level identities/); });
  test("builds registry entries", async () => { const asset=await detectCurriculumAsset(VALID_CURRICULUM_CONTENT); assert.ok(asset); const entry=buildRegistryEntry(asset,Buffer.from(VALID_CURRICULUM_CONTENT),"ingestion","2026-01-01T00:00:00.000Z"); assert.equal(entry.id,"RED-L1-099"); assert.equal(entry.status,"active"); });
});
