import { extractLocalizedLessonTranslation } from "@/lib/admin-content/localized-batch-repair";
import type { PackageIdentity } from "@/lib/admin-content/package-upload-config";
import type { UploadBatch } from "@/lib/admin-content/types";
import { invalidateAtomicPublishedCache } from "@/lib/curriculum/atomic-published-store";
import { invalidateRegistryCache } from "@/lib/curriculum/reader";
import { invalidateNeonLearnerCache } from "@/lib/curriculum/neon-learner-resolver";
import { getRuntimePublishedLesson, getRuntimePublishedTrack } from "@/lib/curriculum/runtime-localization";
import { invalidateTranslationPackageCache } from "@/lib/curriculum/translation-package-store";

export type LearnerReadback = { learnerVisible:boolean; detail:string; checkedLessons:number; checkedAt:string; failures:string[] };
const CANONICAL_ENGLISH=new Set(["en","en-us"]);
const LESSON_ID=/([A-Z]+-L\d+-\d{3})/u;
function stripFrontMatter(text:string){const trimmed=text.replace(/^﻿/u,"").trim();if(!trimmed.startsWith("---"))return trimmed;const end=trimmed.indexOf("\n---",3);return end===-1?trimmed:trimmed.slice(end+4).trim();}
export function normalizeForComparison(text:string):string{return stripFrontMatter(text).replace(/^#\s[^\n]*\n/u,"").normalize("NFC").replace(/[#*_`>|~\\]+/gu,"").replace(/\s+/gu," ").trim().toLowerCase();}
export function expectedBodies(batch:UploadBatch,identity:PackageIdentity):Map<string,string>{const expected=new Map<string,string>();const localized=!CANONICAL_ENGLISH.has(identity.language.toLowerCase());const archiveByUpload=new Map(batch.uploads.map(upload=>[upload.id,upload.originalFilename]));for(const file of batch.files){if(file.reviewStatus!=="approved"||file.extension!==".md")continue;if(localized){const translation=extractLocalizedLessonTranslation(file,archiveByUpload.get(file.uploadId));if(translation)expected.set(translation.lessonId,translation.body);continue;}const lessonId=(file.originalFilename.toUpperCase().match(LESSON_ID)??file.archivePath?.toUpperCase().match(LESSON_ID))?.[1];if(lessonId)expected.set(lessonId,Buffer.from(file.encodedContent,"base64").toString("utf8"));}return expected;}
function matches(returnedBody:string|undefined,uploadedBody:string):boolean{if(!returnedBody)return false;const returned=normalizeForComparison(returnedBody),uploaded=normalizeForComparison(uploadedBody);if(!uploaded)return false;if(returned===uploaded)return true;const probe=uploaded.slice(0,400);return probe.length>=40&&returned.includes(probe);}
export async function verifyLearnerVisibility(batch:UploadBatch,identity:PackageIdentity):Promise<LearnerReadback>{const checkedAt=new Date().toISOString(),expected=expectedBodies(batch,identity);if(expected.size===0)return{learnerVisible:false,detail:"No publishable lessons were extracted from the package; nothing to verify.",checkedLessons:0,checkedAt,failures:["no-lessons"]};invalidateAtomicPublishedCache();invalidateTranslationPackageCache();invalidateRegistryCache();invalidateNeonLearnerCache();const levelNumber=Number(identity.level.replace("level-",""));const track=await getRuntimePublishedTrack(identity.track.toUpperCase(),identity.language);const lessons=new Map((track?.levels.find(level=>level.level===levelNumber)?.lessons??[]).map(lesson=>[lesson.id.toUpperCase(),lesson]));const failures:string[]=[];for(const[lessonId,uploadedBody]of expected){const served=lessons.get(lessonId);if(!served)failures.push(`${lessonId}: not served on the learner level page`);else if(served.status!=="active")failures.push(`${lessonId}: not active`);else if(!matches(served.body,uploadedBody))failures.push(`${lessonId}: learner receives different content (fallback, older translation, or stale row)`);}const ids=[...expected.keys()].sort();for(const lessonId of [ids[0],ids[ids.length-1]]){if(!lessonId)continue;const page=await getRuntimePublishedLesson(lessonId,identity.language);if(!page||!matches(page.body,expected.get(lessonId)!))failures.push(`${lessonId}: lesson page does not serve the uploaded content`);}const checkedLessons=expected.size,passed=checkedLessons-new Set(failures.map(failure=>failure.split(":")[0])).size;return failures.length===0?{learnerVisible:true,detail:`Learner read-back: ${checkedLessons}/${checkedLessons} lessons served as uploaded for ${identity.track}/${identity.level}/${identity.language}.`,checkedLessons,checkedAt,failures}:{learnerVisible:false,detail:`Learner read-back failed: ${passed}/${checkedLessons} lessons verified. ${failures.slice(0,5).join("; ")}${failures.length>5?` (+${failures.length-5} more)`:""}`,checkedLessons,checkedAt,failures};}
