"use client";

import Link from "next/link";
import { useInternationalPreferences } from "@/components/international/InternationalPreferencesProvider";
import { normalizeLanguageCode } from "@/lib/international/languages";

const copy = {
  en: { label:"OUR STORY", title:"Why Edunancial Exists", intro:"Edunancial begins with financial literacy, builds financial competency, and works toward financial intelligence.", methods:"We use structured learning, practical exercises, guided reflection, and technology-supported tools to help members improve judgment and decision-making.", son:"It Started With My Son", sonP:["When my son was 11 years old, I had just finished working on a file when my phone alerted me that a client payment had arrived.","He walked into the room at that exact moment and asked: “Dad, how did you do that?”","I answered: “Because I work with my head.” Then I asked whether he would like to work with his head someday.","He answered: “Yes... but I don't know how.” That was the moment Edunancial was born."], ntege:"Then Came Ntege", ntegeP:["Thousands of miles away, a young entrepreneur in Uganda faced a completely different set of challenges.","Together we focused on costs, pricing, inventory, gross profit, cash flow, hiring, customer demand, and expansion.","The goal was never simply to learn business vocabulary. The goal was making better business decisions every day.","Knowledge became action. Action became competency. Competency created opportunity."], conclusion:"Different Countries. Same Principles.", cP:["One story began with a father teaching his son. Another began with a determined young entrepreneur in Uganda.","Different backgrounds. Different opportunities. Different economies.","Financial literacy provided the foundation. Financial competency changed the outcome."], assess:"Take the Assessment", learn:"Start Learning" },
  es: { label:"NUESTRA HISTORIA", title:"Por qué existe Edunancial", intro:"Edunancial comienza con alfabetización financiera, desarrolla competencia financiera y avanza hacia la inteligencia financiera.", methods:"Utilizamos aprendizaje estructurado, ejercicios prácticos, reflexión guiada y herramientas apoyadas por tecnología para mejorar el criterio y la toma de decisiones.", son:"Comenzó con mi hijo", sonP:["Cuando mi hijo tenía 11 años, acababa de terminar de trabajar en un expediente cuando mi teléfono me avisó que había llegado el pago de un cliente.","Entró en la habitación justo en ese momento y preguntó: “Papá, ¿cómo hiciste eso?”","Le respondí: “Porque trabajo con la cabeza.” Luego le pregunté si algún día le gustaría trabajar con la cabeza.","Contestó: “Sí... pero no sé cómo.” Ese fue el momento en que nació Edunancial."], ntege:"Luego llegó Ntege", ntegeP:["A miles de kilómetros de distancia, un joven emprendedor en Uganda enfrentaba un conjunto completamente distinto de desafíos.","Juntos nos concentramos en costos, precios, inventario, ganancia bruta, flujo de efectivo, contratación, demanda de clientes y expansión.","La meta nunca fue simplemente aprender vocabulario empresarial. La meta era tomar mejores decisiones de negocio cada día.","El conocimiento se convirtió en acción. La acción en competencia. La competencia creó oportunidades."], conclusion:"Países diferentes. Principios iguales.", cP:["Una historia comenzó con un padre enseñando a su hijo. Otra comenzó con un joven emprendedor decidido en Uganda.","Distintos orígenes. Distintas oportunidades. Distintas economías.","La alfabetización financiera proporcionó la base. La competencia financiera cambió el resultado."], assess:"Realizar la evaluación", learn:"Comenzar a aprender" },
  fr: { label:"NOTRE HISTOIRE", title:"Pourquoi Edunancial existe", intro:"Edunancial commence par la littératie financière, développe la compétence financière et progresse vers l’intelligence financière.", methods:"Nous utilisons un apprentissage structuré, des exercices pratiques, une réflexion guidée et des outils technologiques pour améliorer le jugement et la prise de décision.", son:"Tout a commencé avec mon fils", sonP:["Lorsque mon fils avait 11 ans, je venais de terminer un dossier quand mon téléphone m’a signalé qu’un paiement client était arrivé.","Il est entré dans la pièce à ce moment précis et a demandé : « Papa, comment as-tu fait ça ? »","J’ai répondu : « Parce que je travaille avec ma tête. » Puis je lui ai demandé s’il aimerait faire de même un jour.","Il a répondu : « Oui... mais je ne sais pas comment. » C’est à ce moment qu’Edunancial est né."], ntege:"Puis Ntege est arrivé", ntegeP:["À des milliers de kilomètres, un jeune entrepreneur en Ouganda faisait face à des défis complètement différents.","Ensemble, nous nous sommes concentrés sur les coûts, les prix, les stocks, la marge brute, les flux de trésorerie, l’embauche, la demande et l’expansion.","Le but n’était jamais simplement d’apprendre le vocabulaire des affaires. Le but était de prendre de meilleures décisions chaque jour.","La connaissance est devenue action. L’action est devenue compétence. La compétence a créé des possibilités."], conclusion:"Des pays différents. Les mêmes principes.", cP:["Une histoire a commencé avec un père enseignant à son fils. Une autre avec un jeune entrepreneur déterminé en Ouganda.","Des parcours différents. Des possibilités différentes. Des économies différentes.","La littératie financière a fourni la base. La compétence financière a changé le résultat."], assess:"Faire l’évaluation", learn:"Commencer à apprendre" },
  pt: { label:"NOSSA HISTÓRIA", title:"Por que a Edunancial existe", intro:"A Edunancial começa com educação financeira, desenvolve competência financeira e avança em direção à inteligência financeira.", methods:"Usamos aprendizagem estruturada, exercícios práticos, reflexão orientada e ferramentas apoiadas por tecnologia para melhorar o julgamento e a tomada de decisões.", son:"Tudo começou com meu filho", sonP:["Quando meu filho tinha 11 anos, eu acabara de terminar um trabalho quando meu telefone avisou que o pagamento de um cliente havia chegado.","Ele entrou na sala exatamente naquele momento e perguntou: “Pai, como você fez isso?”","Respondi: “Porque eu trabalho com a cabeça.” Depois perguntei se algum dia ele gostaria de trabalhar com a cabeça.","Ele respondeu: “Sim... mas eu não sei como.” Foi nesse momento que nasceu a Edunancial."], ntege:"Depois veio Ntege", ntegeP:["A milhares de quilômetros de distância, um jovem empreendedor em Uganda enfrentava desafios completamente diferentes.","Juntos, focamos em custos, preços, estoque, lucro bruto, fluxo de caixa, contratação, demanda de clientes e expansão.","O objetivo nunca foi simplesmente aprender vocabulário empresarial. O objetivo era tomar melhores decisões de negócio todos os dias.","Conhecimento virou ação. Ação virou competência. Competência criou oportunidade."], conclusion:"Países diferentes. Os mesmos princípios.", cP:["Uma história começou com um pai ensinando seu filho. Outra começou com um jovem empreendedor determinado em Uganda.","Origens diferentes. Oportunidades diferentes. Economias diferentes.","A educação financeira forneceu a base. A competência financeira mudou o resultado."], assess:"Fazer a avaliação", learn:"Começar a aprender" },
  de: { label:"UNSERE GESCHICHTE", title:"Warum Edunancial existiert", intro:"Edunancial beginnt mit Finanzbildung, baut Finanzkompetenz auf und entwickelt sich in Richtung finanzieller Intelligenz.", methods:"Wir nutzen strukturiertes Lernen, praktische Übungen, geführte Reflexion und technologiegestützte Werkzeuge, um Urteilsvermögen und Entscheidungsfähigkeit zu verbessern.", son:"Es begann mit meinem Sohn", sonP:["Als mein Sohn 11 Jahre alt war, hatte ich gerade eine Akte abgeschlossen, als mein Telefon meldete, dass eine Kundenzahlung eingegangen war.","Er kam genau in diesem Moment ins Zimmer und fragte: „Papa, wie hast du das gemacht?“","Ich antwortete: „Weil ich mit meinem Kopf arbeite.“ Dann fragte ich ihn, ob er eines Tages auch mit seinem Kopf arbeiten möchte.","Er antwortete: „Ja... aber ich weiß nicht wie.“ In diesem Moment entstand Edunancial."], ntege:"Dann kam Ntege", ntegeP:["Tausende Kilometer entfernt stand ein junger Unternehmer in Uganda vor ganz anderen Herausforderungen.","Gemeinsam konzentrierten wir uns auf Kosten, Preise, Bestand, Bruttogewinn, Cashflow, Einstellungen, Kundennachfrage und Expansion.","Das Ziel war nie, nur Geschäftsvokabular zu lernen. Das Ziel war, jeden Tag bessere Geschäftsentscheidungen zu treffen.","Wissen wurde zu Handlung. Handlung wurde zu Kompetenz. Kompetenz schuf Chancen."], conclusion:"Unterschiedliche Länder. Gleiche Prinzipien.", cP:["Eine Geschichte begann mit einem Vater, der seinen Sohn unterrichtete. Eine andere mit einem entschlossenen jungen Unternehmer in Uganda.","Unterschiedliche Hintergründe. Unterschiedliche Chancen. Unterschiedliche Volkswirtschaften.","Finanzbildung schuf die Grundlage. Finanzkompetenz veränderte das Ergebnis."], assess:"Assessment durchführen", learn:"Lernen beginnen" },
  it: { label:"LA NOSTRA STORIA", title:"Perché esiste Edunancial", intro:"Edunancial parte dall’alfabetizzazione finanziaria, sviluppa competenza finanziaria e procede verso l’intelligenza finanziaria.", methods:"Usiamo apprendimento strutturato, esercizi pratici, riflessione guidata e strumenti supportati dalla tecnologia per migliorare giudizio e capacità decisionale.", son:"È iniziato con mio figlio", sonP:["Quando mio figlio aveva 11 anni, avevo appena finito di lavorare su un fascicolo quando il telefono mi avvisò che era arrivato il pagamento di un cliente.","Entrò nella stanza proprio in quel momento e chiese: “Papà, come hai fatto?”","Risposi: “Perché lavoro con la testa.” Poi gli chiesi se un giorno avrebbe voluto fare lo stesso.","Rispose: “Sì... ma non so come.” Fu in quel momento che nacque Edunancial."], ntege:"Poi arrivò Ntege", ntegeP:["A migliaia di chilometri di distanza, un giovane imprenditore in Uganda affrontava sfide completamente diverse.","Insieme ci siamo concentrati su costi, prezzi, inventario, profitto lordo, flusso di cassa, assunzioni, domanda dei clienti ed espansione.","L’obiettivo non era mai semplicemente imparare il vocabolario aziendale. Era prendere decisioni migliori ogni giorno.","La conoscenza divenne azione. L’azione divenne competenza. La competenza creò opportunità."], conclusion:"Paesi diversi. Stessi principi.", cP:["Una storia iniziò con un padre che insegnava a suo figlio. Un’altra con un giovane imprenditore determinato in Uganda.","Contesti diversi. Opportunità diverse. Economie diverse.","L’alfabetizzazione finanziaria fornì la base. La competenza finanziaria cambiò il risultato."], assess:"Fai la valutazione", learn:"Inizia a imparare" },
  nl: { label:"ONS VERHAAL", title:"Waarom Edunancial bestaat", intro:"Edunancial begint met financiële geletterdheid, bouwt financiële competentie op en werkt toe naar financiële intelligentie.", methods:"We gebruiken gestructureerd leren, praktische oefeningen, begeleide reflectie en technologieondersteunde hulpmiddelen om oordeel en besluitvorming te verbeteren.", son:"Het begon met mijn zoon", sonP:["Toen mijn zoon 11 jaar oud was, had ik net een dossier afgerond toen mijn telefoon meldde dat een klantbetaling was binnengekomen.","Hij kwam precies op dat moment de kamer binnen en vroeg: “Papa, hoe deed je dat?”","Ik antwoordde: “Omdat ik met mijn hoofd werk.” Daarna vroeg ik of hij later ook met zijn hoofd wilde werken.","Hij antwoordde: “Ja... maar ik weet niet hoe.” Dat was het moment waarop Edunancial ontstond."], ntege:"Toen kwam Ntege", ntegeP:["Duizenden kilometers verderop stond een jonge ondernemer in Oeganda voor totaal andere uitdagingen.","Samen richtten we ons op kosten, prijzen, voorraad, brutowinst, cashflow, personeel, klantvraag en uitbreiding.","Het doel was nooit alleen zakelijke woorden leren. Het doel was elke dag betere zakelijke beslissingen nemen.","Kennis werd actie. Actie werd competentie. Competentie creëerde kansen."], conclusion:"Verschillende landen. Dezelfde principes.", cP:["Het ene verhaal begon met een vader die zijn zoon lesgaf. Het andere met een vastberaden jonge ondernemer in Oeganda.","Verschillende achtergronden. Verschillende kansen. Verschillende economieën.","Financiële geletterdheid vormde de basis. Financiële competentie veranderde de uitkomst."], assess:"Doe de test", learn:"Begin met leren" }
} as const;

function getCopy(locale: string) {
  const l = normalizeLanguageCode(locale);
  if (l.startsWith("es")) return copy.es;
  if (l.startsWith("fr")) return copy.fr;
  if (l.startsWith("pt")) return copy.pt;
  if (l === "de") return copy.de;
  if (l === "it") return copy.it;
  if (l === "nl") return copy.nl;
  return copy.en;
}

export default function OurStoryClient() {
  const { effectiveLanguage } = useInternationalPreferences();
  const c = getCopy(effectiveLanguage);
  return <main className="min-h-screen bg-[#08101f] text-white">
    <section className="mx-auto max-w-7xl px-6 py-24 text-center"><p className="font-bold uppercase tracking-[0.45em] text-yellow-400">{c.label}</p><h1 className="mt-8 text-5xl font-black md:text-7xl">{c.title}</h1><p className="mx-auto mt-10 max-w-5xl text-2xl leading-10 text-slate-300">{c.intro}</p><p className="mx-auto mt-6 max-w-5xl text-lg leading-9 text-slate-400">{c.methods}</p></section>
    <section className="mx-auto max-w-6xl px-6 py-20"><h2 className="text-4xl font-black text-blue-400 md:text-5xl">{c.son}</h2>{c.sonP.map(p=><p key={p} className="mt-8 text-xl leading-10 text-slate-300 sm:text-2xl">{p}</p>)}</section>
    <section className="bg-[#111827]"><div className="mx-auto max-w-6xl px-6 py-20"><h2 className="text-4xl font-black text-green-400 md:text-5xl">{c.ntege}</h2>{c.ntegeP.map(p=><p key={p} className="mt-8 text-xl leading-10 text-slate-300">{p}</p>)}</div></section>
    <section className="mx-auto max-w-6xl px-6 py-24"><h2 className="text-4xl font-black md:text-5xl">{c.conclusion}</h2>{c.cP.map(p=><p key={p} className="mt-7 text-xl leading-10 text-slate-300 sm:text-2xl">{p}</p>)}<div className="mt-12 flex flex-wrap gap-6"><Link href="/assessment" className="rounded-xl bg-blue-600 px-8 py-5 text-xl font-bold hover:bg-blue-700">{c.assess}</Link><Link href="/courses" className="rounded-xl border border-white px-8 py-5 text-xl font-bold hover:bg-white hover:text-black">{c.learn}</Link></div></section>
  </main>;
}
