import { Buffer } from "node:buffer";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

import type { ExtractedFile, UploadBatch } from "@/lib/admin-content/types";
import { detectCurriculumAsset, detectCurriculumSourceLessons, isCanonicalEnglishCurriculumPath } from "@/lib/admin-content/curriculum";
import { getAdminContentStorage } from "@/lib/admin-content/storage";
import { ACADEMIES, ACADEMY_MAP } from "@/lib/curriculum/academies";
import { getLocalizedLessonDescription, getLocalizedLessonTitle, getLocalizedTrackCopy, resolveCurriculumLocale, type CurriculumLocale } from "@/lib/curriculum/localization";
import { getLessonContent, readRegistry, type RegistryAsset } from "@/lib/curriculum/reader";
import { readAtomicPublishedLessons, removeAtomicPublishedBatch, removeAtomicPublishedLesson, upsertAtomicPublishedLessons, upsertAtomicPublishedTranslation } from "@/lib/curriculum/atomic-published-store";

const PUBLISHED_STATE_PATH="published/curriculum-state.json";
const SEEDS_DIR=join(process.cwd(),"curriculum","seeds","translations");
const COURSE_CONTENT_DIR=join(process.cwd(),"content","courses");
export interface PublishedLessonTranslation{title?:string;summary?:string;body?:string}
export interface PublishedLessonRecord{id:string;track:string;trackName:string;level:number;lessonNumber:number;title:string;summary:string;author:string;date:string;version:string;status:"active";importedAt:string;metadata:Record<string,string>;path:string;body:string;frontMatter:Record<string,string>;translations?:Record<string,PublishedLessonTranslation>}
export interface PublishedCurriculumState{schemaVersion:"1.0";initialized:boolean;updatedAt:string;lessons:Record<string,PublishedLessonRecord>;batchLessonIds:Record<string,string[]>}
export interface PublishedLevelSummary{level:number;lessonCount:number;lessons:PublishedLessonRecord[]}
export interface PublishedTrackSummary{code:string;name:string;description:string;levelCount:number;lessonCount:number;levels:PublishedLevelSummary[]}
export interface PublishedCourse{id:string;code:string;title:string;subtitle:string;description:string;category:string;difficulty:"Beginner"|"Intermediate"|"Advanced";color:string;isFree:boolean;isFeatured:boolean;lessons:PublishedLessonRecord[]}
export interface PublishedLessonTranslationImportRecord{lessonId:string;locale:string;title?:string;summary?:string;body?:string}
export interface PublishedLessonTranslationImportResult{updatedRecords:number;updatedLessonIds:string[];missingLessonIds:string[]}
export interface PublishedLessonTranslationExportRecord{id:string;title:string;summary:string;body:string}
export interface PublishedLessonTranslationExportOptions{prefixes?:string[];lessonIds?:string[]}
function empty():PublishedCurriculumState{return{schemaVersion:"1.0",initialized:true,updatedAt:new Date().toISOString(),lessons:{},batchLessonIds:{}}}
async function readLegacy(){const b=await getAdminContentStorage().readBinary(PUBLISHED_STATE_PATH);if(!b)return empty();try{const p=JSON.parse(b.toString("utf8")) as Partial<PublishedCurriculumState>;return{schemaVersion:"1.0" as const,initialized:Boolean(p.initialized),updatedAt:typeof p.updatedAt==="string"?p.updatedAt:new Date().toISOString(),lessons:p.lessons&&typeof p.lessons==="object"?p.lessons:{},batchLessonIds:p.batchLessonIds&&typeof p.batchLessonIds==="object"?p.batchLessonIds:{}}}catch{return empty()}}
async function readPublishedState(){const rows=await readAtomicPublishedLessons();if(rows!==null&&rows.length){const s=empty();for(const r of rows)s.lessons[r.id]=r;return s}return readLegacy()}
async function writeLegacy(s:PublishedCurriculumState){await getAdminContentStorage().saveBinary(PUBLISHED_STATE_PATH,Buffer.from(`${JSON.stringify(s,null,2)}\n`),"application/json")}
function parseFM(raw:string){if(!raw.startsWith("---"))return{frontMatter:{} as Record<string,string>,body:raw.trim()};const p=raw.split("---");if(p.length<3)return{frontMatter:{} as Record<string,string>,body:raw.trim()};const f:Record<string,string>={};for(const line of(p[1]??"").split(/\r?\n/u)){const i=line.indexOf(":");if(i>=0){const k=line.slice(0,i).trim();if(k)f[k]=line.slice(i+1).trim()}}return{frontMatter:f,body:p.slice(2).join("---").trim()}}
function trackName(t:string,f:string){return getLocalizedTrackCopy(t,"en")?.name||f||ACADEMY_MAP.get(t)?.name||t}
function fromRegistry(a:RegistryAsset):PublishedLessonRecord|null{if(a.type!=="lesson"||a.status!=="active"||typeof a.lessonNumber!=="number")return null;const c=getLessonContent(a.id,"en");return c?{id:a.id,track:a.track,trackName:trackName(a.track,a.trackName),level:a.level,lessonNumber:a.lessonNumber,title:c.meta.title,summary:c.meta.summary,author:c.meta.author,date:c.meta.date,version:c.meta.version,status:"active",importedAt:c.meta.importedAt,metadata:a.metadata??{},path:a.path,body:c.body,frontMatter:c.frontMatter}:{id:a.id,track:a.track,trackName:trackName(a.track,a.trackName),level:a.level,lessonNumber:a.lessonNumber,title:a.title,summary:a.metadata?.summary??"",author:a.author,date:a.date,version:a.version,status:"active",importedAt:a.importedAt,metadata:a.metadata??{},path:a.path,body:"",frontMatter:{}}}
let seedCache:Map<string,PublishedLessonTranslation>|null=null;
function put(m:Map<string,PublishedLessonTranslation>,id:string,locale:string,t:PublishedLessonTranslation){const k=`${id.trim().toUpperCase()}::${locale.trim()}`,e=m.get(k);m.set(k,e?{title:t.title||e.title,summary:t.summary||e.summary,body:t.body||e.body}:t)}
function normalizeT(raw:unknown):PublishedLessonTranslation|null{if(!raw||typeof raw!=="object")return null;const r=raw as Record<string,unknown>,title=typeof r.title==="string"?r.title.trim():undefined,summary=(typeof r.summary==="string"?r.summary:typeof r.exec_summary==="string"?r.exec_summary:undefined)?.trim(),body=typeof r.body==="string"?r.body.trim():undefined;return title||summary||body?{...(title?{title}:{}),...(summary?{summary}:{}),...(body?{body}:{})}:null}
function scanTranslations(dir:string,m:Map<string,PublishedLessonTranslation>){if(!existsSync(dir))return;for(const e of readdirSync(dir,{withFileTypes:true})){const p=join(dir,e.name);if(e.isDirectory()){scanTranslations(p,m);continue}if(!e.name.endsWith(".json"))continue;try{const x=JSON.parse(readFileSync(p,"utf8")) as unknown,rs=Array.isArray(x)?x:x&&typeof x==="object"&&Array.isArray((x as {records?:unknown[]}).records)?(x as {records:unknown[]}).records:[x];for(const raw of rs){if(!raw||typeof raw!=="object"||Array.isArray(raw))continue;const r=raw as Record<string,unknown>,id=typeof r.id==="string"?r.id:typeof r.lesson_id==="string"?r.lesson_id:typeof r.lessonId==="string"?r.lessonId:"";if(!id||!r.translations||typeof r.translations!=="object"||Array.isArray(r.translations))continue;for(const[locale,v]of Object.entries(r.translations as Record<string,unknown>)){const t=normalizeT(v);if(t)put(m,id,locale,t)}}}catch{}}}
function seeds(){if(seedCache)return seedCache;const m=new Map<string,PublishedLessonTranslation>();if(existsSync(SEEDS_DIR))for(const file of readdirSync(SEEDS_DIR)){if(!file.endsWith(".json"))continue;try{const rs=JSON.parse(readFileSync(join(SEEDS_DIR,file),"utf8")) as PublishedLessonTranslationImportRecord[];if(Array.isArray(rs))for(const r of rs)if(typeof r.lessonId==="string"&&typeof r.locale==="string")put(m,r.lessonId,r.locale,{title:r.title,summary:r.summary,body:r.body})}catch{}}scanTranslations(COURSE_CONTENT_DIR,m);seedCache=m;return m}
function resolveMap(m:Record<string,PublishedLessonTranslation>|undefined,locale:CurriculumLocale){if(!m)return;const base=locale.split("-")[0];return m[locale]||(base?m[base]:undefined)||(base?m[Object.keys(m).find(k=>k.split("-")[0]===base)??""]:undefined)}
function seed(id:string,locale:CurriculumLocale){const m=seeds(),n=id.toUpperCase(),base=locale.split("-")[0];return m.get(`${n}::${locale}`)||(base?m.get(`${n}::${base}`):undefined)||(base?[...m].find(([k])=>k.startsWith(`${n}::`)&&k.split("::")[1]?.split("-")[0]===base)?.[1]:undefined)}
function localize(l:PublishedLessonRecord,locale:CurriculumLocale){const c=getLessonContent(l.id,locale),local=c&&c.localization.resolution!=="canonical-en"?{title:c.meta.title,summary:c.meta.summary,body:c.body}:undefined,stored=resolveMap(l.translations,locale),s=seed(l.id,locale);return{...l,title:stored?.title??local?.title??s?.title??getLocalizedLessonTitle(l.id,locale,l.title),summary:stored?.summary??local?.summary??s?.summary??getLocalizedLessonDescription(l.id,locale,l.summary),body:stored?.body??local?.body??s?.body??l.body}}
function sort(ls:PublishedLessonRecord[]){return[...ls].sort((a,b)=>a.track.localeCompare(b.track)||a.level-b.level||a.lessonNumber-b.lessonNumber||a.id.localeCompare(b.id))}
async function effective(){const s=await readPublishedState(),registry=readRegistry(),remember=(lesson:PublishedLessonRecord|null)=>{if(lesson&&!s.lessons[lesson.id])s.lessons[lesson.id]=lesson};async function scan(dir:string){if(!existsSync(dir))return;for(const e of readdirSync(dir,{withFileTypes:true})){const p=join(dir,e.name);if(e.isDirectory()){await scan(p);continue}if(!e.name.endsWith(".md")||!isCanonicalEnglishCurriculumPath(p))continue;try{for(const {asset,content} of await detectCurriculumSourceLessons(readFileSync(p,"utf8"),e.name))remember(detected(asset,content))}catch{}}}await scan(COURSE_CONTENT_DIR);for(const t of Object.values(registry.tracks))for(const level of Object.values(t.levels))for(const a of Object.values(level.assets)){if(s.lessons[a.id])continue;remember(fromRegistry(a))}return s}
function detected(a:Awaited<ReturnType<typeof detectCurriculumAsset>>,raw:string):PublishedLessonRecord|null{if(!a||a.type!=="lesson"||!a.id||!a.track||!a.level||!a.number)return null;const p=parseFM(raw),fm=Object.keys(p.frontMatter).length?p.frontMatter:a.frontMatter;return{id:a.id,track:a.track,trackName:trackName(a.track,a.trackName),level:a.level,lessonNumber:a.number,title:fm.title??a.id,summary:fm.summary??"",author:fm.author??"Edunancial Faculty",date:fm.date??new Date().toISOString().slice(0,10),version:fm.version??"1.0",status:"active",importedAt:new Date().toISOString(),metadata:{officialTrackName:fm.officialTrackName??a.trackName},path:a.canonicalPath,body:p.body,frontMatter:fm}}
async function extract(f:ExtractedFile){if(f.extension!==".md")return[];return(await detectCurriculumSourceLessons(Buffer.from(f.encodedContent,"base64").toString("utf8"),f.originalFilename)).map(({asset,content})=>detected(asset,content)).filter((x):x is PublishedLessonRecord=>Boolean(x))}
export async function upsertPublishedLessonsFromBatch(batch:UploadBatch){const files=batch.files.filter(f=>f.reviewStatus==="approved");if(!files.length)return{upserted:0};const lessons=(await Promise.all(files.map(extract))).flat();if(!lessons.length)return{upserted:0};if(await upsertAtomicPublishedLessons(batch.id,lessons))return{upserted:new Set(lessons.map(l=>l.id)).size};const s=await readLegacy(),ids=new Set<string>();for(const l of lessons){for(const[bid,list]of Object.entries(s.batchLessonIds))if(list.includes(l.id))s.batchLessonIds[bid]=list.filter(id=>id!==l.id);const t=s.lessons[l.id]?.translations;s.lessons[l.id]={...l,...(t?{translations:t}:{}),importedAt:new Date().toISOString()};ids.add(l.id)}s.batchLessonIds[batch.id]=sort(lessons).map(l=>l.id);s.updatedAt=new Date().toISOString();await writeLegacy(s);return{upserted:ids.size}}
export async function importPublishedLessonTranslations(records:PublishedLessonTranslationImportRecord[]):Promise<PublishedLessonTranslationImportResult>{if(!records.length)return{updatedRecords:0,updatedLessonIds:[],missingLessonIds:[]};const s=await readPublishedState(),missingLessonIds=[...new Set(records.map(r=>r.lessonId.trim().toUpperCase()).filter(id=>!s.lessons[id]))],missing=new Set(missingLessonIds),updated=new Set<string>();let count=0,atomic=true;for(const r of records){const id=r.lessonId.trim().toUpperCase();if(missing.has(id))continue;const locale=r.locale.trim(),current=s.lessons[id].translations?.[locale]??{},next={...current};if(typeof r.title==="string")next.title=r.title;if(typeof r.summary==="string")next.summary=r.summary;if(typeof r.body==="string")next.body=r.body;const result=await upsertAtomicPublishedTranslation(id,locale,next);if(result===null)atomic=false;else if(!result){missing.add(id);continue}updated.add(id);count++;if(!atomic){const l=s.lessons[id],translations=l.translations??{};s.lessons[id]={...l,translations:{...translations,[locale]:next}}}}if(!atomic&&count){s.updatedAt=new Date().toISOString();await writeLegacy(s)}return{updatedRecords:count,updatedLessonIds:[...updated].sort(),missingLessonIds:[...new Set([...missingLessonIds,...missing])].sort()}}
export async function exportPublishedLessonTranslations(o:PublishedLessonTranslationExportOptions={}){const ps=o.prefixes?.map(p=>p.trim().toUpperCase()).filter(Boolean),ids=o.lessonIds?.map(i=>i.trim().toUpperCase()).filter(Boolean),requested=ids?.length?new Set(ids):null,s=await effective(),match=(id:string)=>!ps?.length||ps.some(p=>/^L[1-9]\d*$/u.test(p)?id.split("-")[1]===p:id.startsWith(`${p}-`)),found=sort(Object.values(s.lessons).filter(l=>l.status==="active"&&(!requested||requested.has(l.id))&&match(l.id))).map(l=>({id:l.id,title:l.title,summary:l.summary,body:l.body}));if(!requested)return found;const have=new Set(found.map(x=>x.id));return[...found,...[...requested].filter(id=>!have.has(id)).map(id=>({id,title:null,summary:null,body:null}))]}
export async function removePublishedLessonsForBatch(batch:UploadBatch){const atomic=await removeAtomicPublishedBatch(batch.id);const s=await readLegacy();let ids=[...(s.batchLessonIds[batch.id]??[])];if(!ids.length)ids=[...new Set((await Promise.all(batch.files.map(extract))).flat().map(l=>l.id))];if(atomic)return{removed:ids.length,trackedLessonIds:ids};for(const id of ids)delete s.lessons[id];delete s.batchLessonIds[batch.id];s.updatedAt=new Date().toISOString();await writeLegacy(s);return{removed:ids.length,trackedLessonIds:ids}}
export async function getPublishedTracks(languageOrLocale:string){const locale=resolveCurriculumLocale(languageOrLocale),s=await effective(),m=new Map<string,Map<number,PublishedLessonRecord[]>>();for(const l of Object.values(s.lessons)){if(l.status!=="active")continue;const levels=m.get(l.track)??new Map<number,PublishedLessonRecord[]>(),list=levels.get(l.level)??[];list.push(l);levels.set(l.level,list);m.set(l.track,levels)}return ACADEMIES.map(a=>{const lc=getLocalizedTrackCopy(a.code,locale),levels=Array.from({length:a.levelCount},(_,i)=>i+1).map(level=>{const lessons=m.get(a.code)?.get(level)??[];return{level,lessonCount:lessons.length,lessons:sort(lessons).map(l=>({...localize(l,locale),trackName:lc?.name??l.trackName}))}});return{code:a.code,name:lc?.name??a.name,description:lc?.description??a.description,levelCount:a.levelCount,lessonCount:levels.reduce((n,l)=>n+l.lessonCount,0),levels}})}
export async function getPublishedTrack(code:string,locale:string){return(await getPublishedTracks(locale)).find(t=>t.code===code.toUpperCase())??null}
export async function getPublishedLesson(id:string,localeString:string){const locale=resolveCurriculumLocale(localeString),l=(await effective()).lessons[id.toUpperCase()];return!l||l.status!=="active"?null:localize(l,locale)}
export async function removePublishedLesson(id:string){const n=id.toUpperCase(),atomic=await removeAtomicPublishedLesson(n);if(atomic!==null)return atomic;const s=await readLegacy();if(!s.lessons[n])return false;delete s.lessons[n];for(const[bid,ids]of Object.entries(s.batchLessonIds))s.batchLessonIds[bid]=ids.filter(x=>x!==n);s.updatedAt=new Date().toISOString();await writeLegacy(s);return true}
export async function upsertPublishedLessonFromRegistry(id:string){const n=id.toUpperCase(),registry=readRegistry();let a:RegistryAsset|null=null;for(const t of Object.values(registry.tracks)){for(const level of Object.values(t.levels)){const c=level.assets[n];if(c?.type==="lesson"){a=c;break}}if(a)break}if(!a)return false;const next=fromRegistry(a);if(!next)return false;if(await upsertAtomicPublishedLessons(`registry:${n}`,[next]))return true;const s=await readLegacy(),t=s.lessons[n]?.translations;s.lessons[n]={...next,...(t?{translations:t}:{}),importedAt:new Date().toISOString()};s.updatedAt=new Date().toISOString();await writeLegacy(s);return true}
export async function getPublishedCourses(locale:string){const tracks=await getPublishedTracks(locale),colors:Record<string,string>={RED:"bg-red-700",WHITE:"bg-slate-200",BLUE:"bg-blue-700",GREEN:"bg-green-700",GOLD:"bg-yellow-600",PURPLE:"bg-purple-700",ORANGE:"bg-orange-700",BLACK:"bg-slate-700"};return tracks.map(t=>({id:t.code.toLowerCase(),code:t.code,title:`${t.code}: ${t.name}`,subtitle:t.description,description:t.description,category:t.name,difficulty:"Intermediate" as const,color:colors[t.code]??"bg-slate-700",isFree:false,isFeatured:false,lessons:t.levels.flatMap(l=>l.lessons)}))}

export async function diagnosticResolveLesson(input:{trackCode:string;level:number;lessonId?:string}){
 const state=await effective();
 const trackCode=input.trackCode.toUpperCase();
 const levelDir=join(COURSE_CONTENT_DIR,trackCode.toLowerCase(),`level-${input.level}`,"en_us");
 const trackLessons=Object.entries(state.lessons??{}).filter(([id])=>id.startsWith(`${trackCode}-L${input.level}-`));
 return{
  courseContentDirResolved:COURSE_CONTENT_DIR,
  courseContentDirExists:existsSync(COURSE_CONTENT_DIR),
  levelDirExists:existsSync(levelDir),
  filesInLevelDir:existsSync(levelDir)?readdirSync(levelDir):[],
  matchedLessonsInEffectiveState:trackLessons.map(([id,record])=>({id,record})),
  specificLessonRequested:input.lessonId?state.lessons?.[input.lessonId.toUpperCase()]??null:null,
  publishedTrackResult:await getPublishedTrack(trackCode,"en-US"),
 };
}
