import { Buffer } from "node:buffer";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

import type { ExtractedFile, UploadBatch } from "@/lib/admin-content/types";
import { detectBundledCurriculumLessons, detectCurriculumAsset } from "@/lib/admin-content/curriculum";
import { getAdminContentStorage } from "@/lib/admin-content/storage";
import { ACADEMIES, ACADEMY_MAP } from "@/lib/curriculum/academies";
import {
  getLocalizedLessonDescription,
  getLocalizedLessonTitle,
  getLocalizedTrackCopy,
  resolveCurriculumLocale,
  type CurriculumLocale,
} from "@/lib/curriculum/localization";
import { getLessonContent, readRegistry, type RegistryAsset } from "@/lib/curriculum/reader";

const PUBLISHED_STATE_PATH = "published/curriculum-state.json";
const SEEDS_DIR = join(process.cwd(), "curriculum", "seeds", "translations");
const COURSE_CONTENT_DIR = join(process.cwd(), "content", "courses");

export interface PublishedLessonTranslation { title?: string; summary?: string; body?: string; }
export interface PublishedLessonRecord {
  id: string; track: string; trackName: string; level: number; lessonNumber: number; title: string; summary: string;
  author: string; date: string; version: string; status: "active"; importedAt: string; metadata: Record<string,string>;
  path: string; body: string; frontMatter: Record<string,string>; translations?: Record<string,PublishedLessonTranslation>;
}
export interface PublishedCurriculumState { schemaVersion:"1.0"; initialized:boolean; updatedAt:string; lessons:Record<string,PublishedLessonRecord>; batchLessonIds:Record<string,string[]>; }
export interface PublishedLevelSummary { level:number; lessonCount:number; lessons:PublishedLessonRecord[]; }
export interface PublishedTrackSummary { code:string; name:string; description:string; levelCount:number; lessonCount:number; levels:PublishedLevelSummary[]; }
export interface PublishedCourse { id:string; code:string; title:string; subtitle:string; description:string; category:string; difficulty:"Beginner"|"Intermediate"|"Advanced"; color:string; isFree:boolean; isFeatured:boolean; lessons:PublishedLessonRecord[]; }
export interface PublishedLessonTranslationImportRecord { lessonId:string; locale:string; title?:string; summary?:string; body?:string; }
export interface PublishedLessonTranslationImportResult { updatedRecords:number; updatedLessonIds:string[]; missingLessonIds:string[]; }
export interface PublishedLessonTranslationExportRecord { id:string; title:string; summary:string; body:string; }
export interface PublishedLessonTranslationExportOptions { prefixes?:string[]; lessonIds?:string[]; }

function createEmptyState():PublishedCurriculumState { return {schemaVersion:"1.0",initialized:true,updatedAt:new Date().toISOString(),lessons:{},batchLessonIds:{}}; }
async function readPublishedState():Promise<PublishedCurriculumState>{
 const storage=getAdminContentStorage(); const buffer=await storage.readBinary(PUBLISHED_STATE_PATH); if(!buffer)return createEmptyState();
 try{const parsed=JSON.parse(buffer.toString("utf8")) as Partial<PublishedCurriculumState>;return{schemaVersion:"1.0",initialized:Boolean(parsed.initialized),updatedAt:typeof parsed.updatedAt==="string"?parsed.updatedAt:new Date().toISOString(),lessons:parsed.lessons&&typeof parsed.lessons==="object"?parsed.lessons:{},batchLessonIds:parsed.batchLessonIds&&typeof parsed.batchLessonIds==="object"?parsed.batchLessonIds:{}};}catch{return createEmptyState();}
}
async function writePublishedState(state:PublishedCurriculumState):Promise<void>{const payload=Buffer.from(`${JSON.stringify(state,null,2)}\n`,"utf8");await getAdminContentStorage().saveBinary(PUBLISHED_STATE_PATH,payload,"application/json");}
function parseFrontMatter(raw:string){if(!raw.startsWith("---"))return{frontMatter:{},body:raw.trim()};const parts=raw.split("---");if(parts.length<3)return{frontMatter:{},body:raw.trim()};const frontMatter:Record<string,string>={};for(const line of (parts[1]??"").split(/\r?\n/u)){const idx=line.indexOf(":");if(idx<0)continue;const key=line.slice(0,idx).trim();if(key)frontMatter[key]=line.slice(idx+1).trim();}return{frontMatter,body:parts.slice(2).join("---").trim()};}
function normalizeTrackName(track:string,fallback:string){return getLocalizedTrackCopy(track,"en")?.name||fallback||ACADEMY_MAP.get(track)?.name||track;}
function entryFromRegistryAsset(asset:RegistryAsset):PublishedLessonRecord|null{if(asset.type!=="lesson"||asset.status!=="active"||typeof asset.lessonNumber!=="number")return null;const content=getLessonContent(asset.id,"en");if(content)return{id:asset.id,track:asset.track,trackName:normalizeTrackName(asset.track,asset.trackName),level:asset.level,lessonNumber:asset.lessonNumber,title:content.meta.title,summary:content.meta.summary,author:content.meta.author,date:content.meta.date,version:content.meta.version,status:"active",importedAt:content.meta.importedAt,metadata:asset.metadata??{},path:asset.path,body:content.body,frontMatter:content.frontMatter};return{id:asset.id,track:asset.track,trackName:normalizeTrackName(asset.track,asset.trackName),level:asset.level,lessonNumber:asset.lessonNumber,title:asset.title,summary:asset.metadata?.summary??"",author:asset.author,date:asset.date,version:asset.version,status:"active",importedAt:asset.importedAt,metadata:asset.metadata??{},path:asset.path,body:"",frontMatter:{}};}
let _seedTranslationCache:Map<string,PublishedLessonTranslation>|null=null;
function addTranslationToMap(map:Map<string,PublishedLessonTranslation>,lessonId:string,locale:string,translation:PublishedLessonTranslation){const key=`${lessonId.trim().toUpperCase()}::${locale.trim()}`;const existing=map.get(key);map.set(key,existing?{title:translation.title||existing.title,summary:translation.summary||existing.summary,body:translation.body||existing.body}:translation);}
const LEGACY_TRANSLATION_SECTION_TITLES:Record<string,string>={objectives:"Objetivos de aprendizaje",topics:"Contenido principal",definitions:"Definiciones",examples:"Ejemplos prácticos",mistakes:"Errores comunes",faq:"Preguntas frecuentes",takeaways:"Puntos clave",exercise:"Ejercicio"};
function formatLegacyKey(key:string){return key.replace(/[_-]+/gu," ").replace(/\b\w/gu,l=>l.toUpperCase());}
function renderLegacyValue(value:unknown,depth=3):string{if(typeof value==="string")return value.trim();if(typeof value==="number"||typeof value==="boolean")return String(value);if(Array.isArray(value))return value.map(i=>typeof i==="string"||typeof i==="number"||typeof i==="boolean"?`- ${String(i).trim()}`:renderLegacyValue(i,depth)).filter(Boolean).join("\n\n");if(!value||typeof value!=="object")return"";const d=Math.min(Math.max(depth,1),6);return Object.entries(value as Record<string,unknown>).map(([k,v])=>{const r=renderLegacyValue(v,d+1);if(!r)return"";return typeof v==="string"||typeof v==="number"||typeof v==="boolean"?`**${formatLegacyKey(k)}:** ${r}`:`${"#".repeat(d)} ${formatLegacyKey(k)}\n\n${r}`;}).filter(Boolean).join("\n\n");}
function renderLegacyStructuredBody(record:Record<string,unknown>){const s=Object.entries(LEGACY_TRANSLATION_SECTION_TITLES).map(([k,t])=>{const r=renderLegacyValue(record[k]);return r?`## ${t}\n\n${r}`:"";}).filter(Boolean);return s.length?s.join("\n\n"):undefined;}
function normalizeBundledTranslation(raw:unknown):PublishedLessonTranslation|null{if(!raw||typeof raw!=="object")return null;const r=raw as Record<string,unknown>;const title=typeof r.title==="string"?r.title.trim():undefined;const sv=typeof r.summary==="string"?r.summary:typeof r.exec_summary==="string"?r.exec_summary:undefined;const summary=sv?.trim();const body=(typeof r.body==="string"?r.body.trim():undefined)||renderLegacyStructuredBody(r);return title||summary||body?{...(title?{title}:{}),...(summary?{summary}:{}),...(body?{body}:{})}:null;}
function loadBundledTranslationRecord(raw:unknown,map:Map<string,PublishedLessonTranslation>){if(!raw||typeof raw!=="object"||Array.isArray(raw))return;const r=raw as Record<string,unknown>;const id=typeof r.id==="string"?r.id:typeof r.lesson_id==="string"?r.lesson_id:typeof r.lessonId==="string"?r.lessonId:"";if(!id||!r.translations||typeof r.translations!=="object"||Array.isArray(r.translations))return;for(const [locale,v] of Object.entries(r.translations as Record<string,unknown>)){const t=normalizeBundledTranslation(v);if(t)addTranslationToMap(map,id,locale,t);}}
function loadBundledTranslationFiles(dir:string,map:Map<string,PublishedLessonTranslation>){if(!existsSync(dir))return;for(const e of readdirSync(dir,{withFileTypes:true})){const p=join(dir,e.name);if(e.isDirectory()){loadBundledTranslationFiles(p,map);continue;}if(!e.name.endsWith(".json"))continue;try{const parsed=JSON.parse(readFileSync(p,"utf8")) as unknown;const records=Array.isArray(parsed)?parsed:parsed&&typeof parsed==="object"&&Array.isArray((parsed as Record<string,unknown>).records)?(parsed as {records:unknown[]}).records:[parsed];for(const c of records)loadBundledTranslationRecord(c,map);}catch{}}}
function loadSeedTranslations(){if(_seedTranslationCache)return _seedTranslationCache;const map=new Map<string,PublishedLessonTranslation>();if(existsSync(SEEDS_DIR))for(const file of readdirSync(SEEDS_DIR)){if(!file.endsWith(".json"))continue;try{const records=JSON.parse(readFileSync(join(SEEDS_DIR,file),"utf8")) as PublishedLessonTranslationImportRecord[];if(Array.isArray(records))for(const r of records)if(typeof r.lessonId==="string"&&typeof r.locale==="string")addTranslationToMap(map,r.lessonId,r.locale,{...(typeof r.title==="string"?{title:r.title}:{}),...(typeof r.summary==="string"?{summary:r.summary}:{}),...(typeof r.body==="string"?{body:r.body}:{})});}catch{}}loadBundledTranslationFiles(COURSE_CONTENT_DIR,map);_seedTranslationCache=map;return map;}
function resolveSeedTranslation(id:string,locale:CurriculumLocale){const s=loadSeedTranslations(),n=id.toUpperCase();const exact=s.get(`${n}::${locale}`);if(exact)return exact;const base=locale.split("-")[0];if(base){const b=s.get(`${n}::${base}`);if(b)return b;for(const[k,t]of s)if(k.startsWith(`${n}::`)&&k.slice(k.indexOf("::")+2).split("-")[0]===base)return t;}return undefined;}
function resolveTranslation(ts:Record<string,PublishedLessonTranslation>|undefined,locale:CurriculumLocale){if(!ts)return; if(ts[locale])return ts[locale];const base=locale.split("-")[0];if(base&&ts[base])return ts[base];const k=base?Object.keys(ts).find(c=>c.split("-")[0]===base):undefined;return k?ts[k]:undefined;}
function resolvePublishedLessonForLocale(lesson:PublishedLessonRecord,locale:CurriculumLocale){const localized=getLessonContent(lesson.id,locale);const local=localized&&localized.localization.resolution!=="canonical-en"?{title:localized.meta.title,summary:localized.meta.summary,body:localized.body}:undefined;const stored=resolveTranslation(lesson.translations,locale);const seed=resolveSeedTranslation(lesson.id,locale);return{...lesson,title:stored?.title??local?.title??seed?.title??getLocalizedLessonTitle(lesson.id,locale,lesson.title),summary:stored?.summary??local?.summary??seed?.summary??getLocalizedLessonDescription(lesson.id,locale,lesson.summary),body:stored?.body??local?.body??seed?.body??lesson.body};}
function sortLessons(ls:PublishedLessonRecord[]){return[...ls].sort((a,b)=>a.track.localeCompare(b.track)||a.level-b.level||a.lessonNumber-b.lessonNumber||a.id.localeCompare(b.id));}
async function getEffectiveState(){const state=await readPublishedState();const registry=readRegistry();const allow=process.env.EDUNANCIAL_ENABLE_LEGACY_CURRICULUM_REGISTRY_FALLBACK==="true";for(const track of Object.values(registry.tracks))for(const level of Object.values(track.levels))for(const asset of Object.values(level.assets)){if(state.lessons[asset.id]||!allow)continue;const r=entryFromRegistryAsset(asset);if(r)state.lessons[r.id]=r;}return state;}
function lessonFromDetectedAsset(asset:Awaited<ReturnType<typeof detectCurriculumAsset>>,raw:string):PublishedLessonRecord|null{if(!asset||asset.type!=="lesson"||!asset.id||!asset.track||!asset.level||!asset.number)return null;const p=parseFrontMatter(raw);return{id:asset.id,track:asset.track,trackName:normalizeTrackName(asset.track,asset.trackName),level:asset.level,lessonNumber:asset.number,title:p.frontMatter.title??asset.id,summary:p.frontMatter.summary??"",author:p.frontMatter.author??"Edunancial Faculty",date:p.frontMatter.date??new Date().toISOString().slice(0,10),version:p.frontMatter.version??"1.0",status:"active",importedAt:new Date().toISOString(),metadata:{officialTrackName:p.frontMatter.officialTrackName??asset.trackName},path:asset.canonicalPath,body:p.body,frontMatter:p.frontMatter};}
async function extractLessonsFromFile(file:ExtractedFile){if(file.extension!==".md")return[];const raw=Buffer.from(file.encodedContent,"base64").toString("utf8");const direct=await detectCurriculumAsset(raw,file.originalFilename);if(direct&&!direct.locale){const l=lessonFromDetectedAsset(direct,raw);return l?[l]:[];}return(await detectBundledCurriculumLessons(raw)).map(({asset,content})=>lessonFromDetectedAsset(asset,content)).filter((e):e is PublishedLessonRecord=>Boolean(e));}
export async function upsertPublishedLessonsFromBatch(batch:UploadBatch){const files=batch.files.filter(f=>f.reviewStatus==="approved");if(!files.length)return{upserted:0};const lessons=(await Promise.all(files.map(extractLessonsFromFile))).flat();if(!lessons.length)return{upserted:0};const state=await readPublishedState();const ids=new Set<string>();for(const lesson of lessons){for(const[bid,bids]of Object.entries(state.batchLessonIds))if(bids.includes(lesson.id))state.batchLessonIds[bid]=bids.filter(id=>id!==lesson.id);const t=state.lessons[lesson.id]?.translations;state.lessons[lesson.id]={...lesson,...(t?{translations:t}:{}),importedAt:new Date().toISOString()};ids.add(lesson.id);}state.batchLessonIds[batch.id]=sortLessons(lessons).map(l=>l.id);state.updatedAt=new Date().toISOString();await writePublishedState(state);return{upserted:ids.size};}
export async function importPublishedLessonTranslations(records:PublishedLessonTranslationImportRecord[]):Promise<PublishedLessonTranslationImportResult>{if(!records.length)return{updatedRecords:0,updatedLessonIds:[],missingLessonIds:[]};const state=await readPublishedState();const missingLessonIds=[...new Set(records.map(r=>r.lessonId.trim().toUpperCase()).filter(id=>!state.lessons[id]))];const missing=new Set(missingLessonIds),updated=new Set<string>();let count=0;for(const r of records){const id=r.lessonId.trim().toUpperCase();if(missing.has(id))continue;const locale=r.locale.trim(),lesson=state.lessons[id],translations=lesson.translations??{},next={...(translations[locale]??{})};if(typeof r.title==="string")next.title=r.title;if(typeof r.summary==="string")next.summary=r.summary;if(typeof r.body==="string")next.body=r.body;state.lessons[id]={...lesson,translations:{...translations,[locale]:next}};updated.add(id);count++;}if(count){state.updatedAt=new Date().toISOString();await writePublishedState(state);}return{updatedRecords:count,updatedLessonIds:[...updated].sort(),missingLessonIds};}
export async function exportPublishedLessonTranslations(options:PublishedLessonTranslationExportOptions={}){const prefixes=options.prefixes?.map(p=>p.trim().toUpperCase()).filter(Boolean),ids=options.lessonIds?.map(i=>i.trim().toUpperCase()).filter(Boolean),requested=ids?.length?new Set(ids):null,state=await getEffectiveState();const matches=(id:string)=>!prefixes?.length||prefixes.some(p=>/^L[1-9]\d*$/u.test(p)?id.split("-")[1]===p:id.startsWith(`${p}-`));const matched=sortLessons(Object.values(state.lessons).filter(l=>l.status==="active"&&(!requested||requested.has(l.id))&&matches(l.id))).map(l=>({id:l.id,title:l.title,summary:l.summary,body:l.body}));if(requested){const found=new Set(matched.map(r=>r.id));return[...matched,...[...requested].filter(id=>!found.has(id)).map(id=>({id,title:null,summary:null,body:null}))];}return matched;}
export async function removePublishedLessonsForBatch(batch:UploadBatch){const state=await readPublishedState();let ids=[...(state.batchLessonIds[batch.id]??[])];if(!ids.length)ids=[...new Set((await Promise.all(batch.files.map(extractLessonsFromFile))).flat().map(l=>l.id))];for(const id of ids)delete state.lessons[id];delete state.batchLessonIds[batch.id];state.updatedAt=new Date().toISOString();await writePublishedState(state);return{removed:ids.length,trackedLessonIds:ids};}
export async function getPublishedTracks(languageOrLocale:string){const locale=resolveCurriculumLocale(languageOrLocale),state=await getEffectiveState(),map=new Map<string,Map<number,PublishedLessonRecord[]>>();for(const l of Object.values(state.lessons)){if(l.status!=="active")continue;const levels=map.get(l.track)??new Map<number,PublishedLessonRecord[]>(),list=levels.get(l.level)??[];list.push(l);levels.set(l.level,list);map.set(l.track,levels);}return ACADEMIES.map(a=>{const local=getLocalizedTrackCopy(a.code,locale),levels=Array.from({length:a.levelCount},(_,i)=>i+1).map(level=>{const lessons=map.get(a.code)?.get(level)??[];return{level,lessonCount:lessons.length,lessons:sortLessons(lessons).map(l=>({...resolvePublishedLessonForLocale(l,locale),trackName:local?.name??l.trackName}))};});return{code:a.code,name:local?.name??a.name,description:local?.description??a.description,levelCount:a.levelCount,lessonCount:levels.reduce((s,l)=>s+l.lessonCount,0),levels};});}
export async function getPublishedTrack(code:string,locale:string){return(await getPublishedTracks(locale)).find(t=>t.code===code.toUpperCase())??null;}
export async function getPublishedLesson(id:string,localeString:string){const locale=resolveCurriculumLocale(localeString),lesson=(await getEffectiveState()).lessons[id.toUpperCase()];return !lesson||lesson.status!=="active"?null:resolvePublishedLessonForLocale(lesson,locale);}
export async function removePublishedLesson(id:string){const n=id.toUpperCase(),state=await readPublishedState();if(!state.lessons[n])return false;delete state.lessons[n];for(const[bid,ids]of Object.entries(state.batchLessonIds))state.batchLessonIds[bid]=ids.filter(x=>x!==n);state.updatedAt=new Date().toISOString();await writePublishedState(state);return true;}
export async function upsertPublishedLessonFromRegistry(id:string){const n=id.toUpperCase(),registry=readRegistry();let asset:RegistryAsset|null=null;for(const track of Object.values(registry.tracks)){for(const level of Object.values(track.levels)){const c=level.assets[n];if(c?.type==="lesson"){asset=c;break;}}if(asset)break;}if(!asset)return false;const next=entryFromRegistryAsset(asset);if(!next)return false;const state=await readPublishedState(),t=state.lessons[n]?.translations;state.lessons[n]={...next,...(t?{translations:t}:{}),importedAt:new Date().toISOString()};state.updatedAt=new Date().toISOString();await writePublishedState(state);return true;}
export async function getPublishedCourses(locale:string){const tracks=await getPublishedTracks(locale),colors:Record<string,string>={RED:"bg-red-700",WHITE:"bg-slate-200",BLUE:"bg-blue-700",GREEN:"bg-green-700",GOLD:"bg-yellow-600",PURPLE:"bg-purple-700",ORANGE:"bg-orange-700",BLACK:"bg-slate-700"};return tracks.map(t=>({id:t.code.toLowerCase(),code:t.code,title:`${t.code}: ${t.name}`,subtitle:t.description,description:t.description,category:t.name,difficulty:"Intermediate" as const,color:colors[t.code]??"bg-slate-700",isFree:false,isFeatured:false,lessons:t.levels.flatMap(l=>l.lessons)}));}
