import { normalizeLanguageCode } from "@/lib/international/languages";

/**
 * CurriculumLocale is now an open string type matching the app's language codes.
 * Use `resolveCurriculumLocale()` to normalise any incoming code.
 * Internally, TRACK_COPY keys use the same codes as LANGUAGE_CATALOG.
 * All lookups fall back through: exact code → base code → "en".
 */
export type CurriculumLocale = string;
export type LaunchTrackCode = "RED" | "WHITE" | "BLUE" | "GREEN" | "GOLD" | "PURPLE" | "ORANGE" | "BLACK";

export const PUBLIC_CURRICULUM_TRACK_CODES = [
  "RED",
  "WHITE",
  "BLUE",
  "GREEN",
  "GOLD",
  "PURPLE",
  "ORANGE",
  "BLACK",
] as const satisfies readonly LaunchTrackCode[];

export function isPublicCurriculumTrack(trackCode: string): trackCode is LaunchTrackCode {
  return PUBLIC_CURRICULUM_TRACK_CODES.includes(trackCode.toUpperCase() as LaunchTrackCode);
}

/**
 * Resolve any incoming language code to the most specific curriculum locale
 * available in TRACK_COPY.  Falls back through:
 *   1. exact normalised code (e.g. "fr-CA")
 *   2. base language code (e.g. "fr")
 *   3. "en"
 */
export function resolveCurriculumLocale(languageCode: string): CurriculumLocale {
  return normalizeLanguageCode(languageCode) || "en";
}

/**
 * Resolve a LocalizedValue to a string for the given locale.
 * Tries: exact locale → base language (strip region/script) → "en" → first available value.
 */
function resolveLocalizedValue(
  value: Partial<Record<string, string>>,
  locale: CurriculumLocale,
): string {
  if (value[locale]) return value[locale]!;
  // Strip region/script suffix (e.g. "fr-CA" → "fr", "zh-Hans" → "zh")
  const base = locale.split("-")[0];
  if (base && value[base]) return value[base]!;
  // Universal English fallback
  if (value["en"]) return value["en"]!;
  // Last resort: first defined value
  const first = Object.values(value).find(Boolean);
  return first ?? "";
}

/** A multilingual string keyed by language code. "en" is always required. */
type LocalizedValue = { en: string } & Partial<Record<string, string>>;

type TrackCopy = {
  name: LocalizedValue;
  description: LocalizedValue;
  category: LocalizedValue;
  subtitle: LocalizedValue;
};

/**
 * Canonical multilingual copy for every curriculum academy.
 *
 * Every academy MUST use the same shape.  To add a new language, add the
 * language code key to each LocalizedValue object here — no other file needs
 * to change.  Missing language codes fall back to "en" automatically via
 * resolveLocalizedValue().
 *
 * Language codes match LANGUAGE_CATALOG in src/lib/international/languages.ts.
 */
const TRACK_COPY: Record<LaunchTrackCode, TrackCopy> = {
  // ─── RED — Real Estate ───────────────────────────────────────────────────────
  RED: {
    name: {
      en: "Real Estate",
      es: "Bienes raíces",
      fr: "Immobilier",
      pt: "Imóveis",
      de: "Immobilien",
      it: "Immobiliare",
      nl: "Onroerend goed",
      pl: "Nieruchomości",
      cs: "Nemovitosti",
      sk: "Nehnuteľnosti",
      ro: "Imobiliare",
      bg: "Недвижими имоти",
      ru: "Недвижимость",
      uk: "Нерухомість",
      ar: "العقارات",
      he: "נדל\"ן",
      fa: "املاک",
      hi: "रियल एस्टेट",
      bn: "রিয়েল এস্টেট",
      ur: "رئیل اسٹیٹ",
      ta: "ரியல் எஸ்டேட்",
      zh: "房地产",
      "zh-Hans": "房地产",
      "zh-Hant": "房地產",
      ja: "不動産",
      ko: "부동산",
      th: "อสังหาริมทรัพย์",
      vi: "Bất động sản",
      id: "Properti",
      ms: "Hartanah",
      fil: "Real Estate",
      sw: "Mali Isiyohamia",
      am: "ሪል ኤስቴት",
      ht: "Imobilye",
    },
    description: {
      en: "Master real estate as an asset class — residential, commercial, income generation, financing, and long-term wealth building.",
      es: "Domina los bienes raíces como clase de activo: vivienda, propiedades comerciales, generación de ingresos, financiamiento y creación de patrimonio a largo plazo.",
      fr: "Maîtrisez l'immobilier en tant que classe d'actifs — résidentiel, commercial, génération de revenus, financement et création de patrimoine à long terme.",
      pt: "Domine o mercado imobiliário como classe de ativos — residencial, comercial, geração de renda, financiamento e construção de riqueza a longo prazo.",
      de: "Meistern Sie Immobilien als Anlageklasse — Wohnimmobilien, Gewerbeimmobilien, Einkommensgenerierung, Finanzierung und langfristigen Vermögensaufbau.",
      it: "Padroneggia il mercato immobiliare come classe di attivi — residenziale, commerciale, generazione di reddito, finanziamento e costruzione di ricchezza a lungo termine.",
      nl: "Beheers vastgoed als beleggingscategorie — residentieel, commercieel, inkomensgeneratie, financiering en langetermijnvermogensopbouw.",
      pl: "Opanuj nieruchomości jako klasę aktywów — mieszkaniowe, komercyjne, generowanie dochodu, finansowanie i długoterminowe budowanie majątku.",
      ru: "Освойте недвижимость как класс активов — жилую, коммерческую, генерацию дохода, финансирование и долгосрочное построение благосостояния.",
      ar: "أتقن العقارات كفئة أصول — السكنية والتجارية وتوليد الدخل والتمويل وبناء الثروة على المدى البعيد.",
      hi: "रियल एस्टेट को एक परिसंपत्ति वर्ग के रूप में समझें — आवासीय, वाणिज्यिक, आय सृजन, वित्तपोषण और दीर्घकालिक धन निर्माण।",
      "zh-Hans": "掌握房地产作为一种资产类别——住宅、商业、创收、融资和长期财富积累。",
      "zh-Hant": "掌握房地產作為一種資產類別——住宅、商業、創收、融資和長期財富積累。",
      ja: "不動産を資産クラスとして習得する — 住宅、商業、収益創出、融資、長期的な富の構築。",
      ko: "부동산을 자산 클래스로 마스터하세요 — 주거용, 상업용, 소득 창출, 금융, 장기 자산 형성.",
      vi: "Nắm vững bất động sản như một loại tài sản — nhà ở, thương mại, tạo thu nhập, tài chính và xây dựng tài sản lâu dài.",
      id: "Kuasai properti sebagai kelas aset — residensial, komersial, penghasilan, pembiayaan, dan pembangunan kekayaan jangka panjang.",
      sw: "Jifunze mali isiyohamia kama darasa la mali — makazi, biashara, uzalishaji wa mapato, ufadhili na ujenzi wa utajiri wa muda mrefu.",
    },
    category: {
      en: "Real Estate",
      es: "Bienes raíces",
      fr: "Immobilier",
      pt: "Imóveis",
      de: "Immobilien",
      it: "Immobiliare",
      nl: "Onroerend goed",
      pl: "Nieruchomości",
      ru: "Недвижимость",
      ar: "العقارات",
      hi: "रियल एस्टेट",
      "zh-Hans": "房地产",
      "zh-Hant": "房地產",
      ja: "不動産",
      ko: "부동산",
      vi: "Bất động sản",
      id: "Properti",
      sw: "Mali Isiyohamia",
    },
    subtitle: {
      en: "Real estate investing strategies: rentals, tax liens, tax deeds, and creative financing.",
      es: "Estrategias de inversión inmobiliaria: alquileres, gravámenes fiscales, escrituras fiscales y financiamiento creativo.",
      fr: "Stratégies d'investissement immobilier : locations, privilèges fiscaux, actes fiscaux et financement créatif.",
      pt: "Estratégias de investimento imobiliário: aluguéis, penhoras fiscais, escrituras fiscais e financiamento criativo.",
      de: "Immobilieninvestitionsstrategien: Vermietungen, Steuerpfandrechte, Steuerschuldverschreibungen und kreative Finanzierungen.",
      it: "Strategie di investimento immobiliare: affitti, privilegi fiscali, atti fiscali e finanziamento creativo.",
      nl: "Vastgoedbeleggingsstrategieën: verhuur, belastingpandrechten, belastingakten en creatieve financiering.",
      pl: "Strategie inwestowania w nieruchomości: wynajem, zastawy podatkowe, akty podatkowe i kreatywne finansowanie.",
      ru: "Стратегии инвестирования в недвижимость: аренда, налоговые залоги, налоговые акты и творческое финансирование.",
      ar: "استراتيجيات الاستثمار العقاري: الإيجارات ورهون الضرائب وصكوك الضرائب والتمويل الإبداعي.",
      hi: "रियल एस्टेट निवेश रणनीतियाँ: किराया, टैक्स लाइन, टैक्स डीड और रचनात्मक वित्तपोषण।",
      "zh-Hans": "房地产投资策略：租赁、税务留置权、税务契约和创意融资。",
      "zh-Hant": "房地產投資策略：租賃、稅務留置權、稅務契約和創意融資。",
      ja: "不動産投資戦略：賃貸、税務先取特権、税務証書、クリエイティブ融資。",
      ko: "부동산 투자 전략: 임대, 세금 유치권, 세금 증서 및 창의적 금융.",
      vi: "Chiến lược đầu tư bất động sản: cho thuê, quyền giữ lại thuế, chứng thư thuế và tài chính sáng tạo.",
      id: "Strategi investasi properti: sewa, hak tanggungan pajak, akta pajak, dan pembiayaan kreatif.",
      sw: "Mikakati ya uwekezaji wa mali isiyohamia: upangaji, dhamana za ushuru, hati za ushuru na ufadhili wa ubunifu.",
    },
  },

  // ─── WHITE — Paper Assets ────────────────────────────────────────────────────
  WHITE: {
    name: {
      en: "Paper Assets",
      es: "Activos financieros",
      fr: "Actifs financiers",
      pt: "Ativos financeiros",
      de: "Finanzielle Vermögenswerte",
      it: "Attività finanziarie",
      nl: "Financiële activa",
      pl: "Aktywa papierowe",
      cs: "Papírová aktiva",
      sk: "Papierové aktíva",
      ro: "Active financiare",
      bg: "Финансови активи",
      ru: "Бумажные активы",
      uk: "Паперові активи",
      ar: "الأصول الورقية",
      he: "נכסים פיננסיים",
      fa: "دارایی‌های کاغذی",
      hi: "पेपर संपत्ति",
      bn: "কাগজ সম্পদ",
      "zh-Hans": "金融资产",
      "zh-Hant": "金融資產",
      ja: "金融資産",
      ko: "금융 자산",
      th: "สินทรัพย์ทางการเงิน",
      vi: "Tài sản tài chính",
      id: "Aset Keuangan",
      ms: "Aset Kewangan",
      fil: "Mga Papel na Asset",
      sw: "Mali za Karatasi",
      am: "የፋይናንሺያል ሀብቶች",
      ht: "Aktif Finansye",
    },
    description: {
      en: "Understand stocks, bonds, funds, and other financial instruments — how they work, how they generate returns, and how to evaluate them.",
      es: "Comprende acciones, bonos, fondos y otros instrumentos financieros: cómo funcionan, cómo generan rendimiento y cómo evaluarlos.",
      fr: "Comprendre les actions, les obligations, les fonds et autres instruments financiers — comment ils fonctionnent, comment ils génèrent des rendements et comment les évaluer.",
      pt: "Entenda ações, títulos, fundos e outros instrumentos financeiros — como funcionam, como geram retornos e como avaliá-los.",
      de: "Verstehen Sie Aktien, Anleihen, Fonds und andere Finanzinstrumente — wie sie funktionieren, wie sie Renditen erzielen und wie man sie bewertet.",
      it: "Comprendi azioni, obbligazioni, fondi e altri strumenti finanziari — come funzionano, come generano rendimenti e come valutarli.",
      nl: "Begrijp aandelen, obligaties, fondsen en andere financiële instrumenten — hoe ze werken, hoe ze rendement genereren en hoe ze te evalueren.",
      pl: "Zrozum akcje, obligacje, fundusze i inne instrumenty finansowe — jak działają, jak generują zwroty i jak je oceniać.",
      ru: "Понять акции, облигации, фонды и другие финансовые инструменты — как они работают, как они генерируют доход и как их оценивать.",
      ar: "فهم الأسهم والسندات والصناديق وغيرها من الأدوات المالية — كيف تعمل وكيف تولد العوائد وكيف يتم تقييمها.",
      hi: "स्टॉक, बॉन्ड, फंड और अन्य वित्तीय साधनों को समझें — वे कैसे काम करते हैं, कैसे रिटर्न देते हैं और उनका मूल्यांकन कैसे करें।",
      "zh-Hans": "了解股票、债券、基金和其他金融工具——它们如何运作、如何产生回报以及如何评估它们。",
      "zh-Hant": "了解股票、債券、基金和其他金融工具——它們如何運作、如何產生回報以及如何評估它們。",
      ja: "株式、債券、ファンド、その他の金融商品を理解する — それらの仕組み、収益の生み方、評価方法。",
      ko: "주식, 채권, 펀드 및 기타 금융 상품 이해 — 작동 방식, 수익 창출 방식 및 평가 방법.",
      vi: "Hiểu về cổ phiếu, trái phiếu, quỹ và các công cụ tài chính khác — cách hoạt động, cách tạo ra lợi nhuận và cách đánh giá chúng.",
      id: "Memahami saham, obligasi, reksa dana, dan instrumen keuangan lainnya — cara kerjanya, cara menghasilkan imbal hasil, dan cara mengevaluasinya.",
      sw: "Elewa hisa, dhamana, mifuko na vyombo vingine vya fedha — jinsi unavyofanya kazi, jinsi unavyozalisha faida na jinsi ya kutathmini.",
    },
    category: {
      en: "Paper Assets",
      es: "Activos financieros",
      fr: "Actifs financiers",
      pt: "Ativos financeiros",
      de: "Finanzielle Vermögenswerte",
      it: "Attività finanziarie",
      nl: "Financiële activa",
      pl: "Aktywa papierowe",
      ru: "Бумажные активы",
      ar: "الأصول الورقية",
      hi: "पेपर संपत्ति",
      "zh-Hans": "金融资产",
      "zh-Hant": "金融資產",
      ja: "金融資産",
      ko: "금융 자산",
      vi: "Tài sản tài chính",
      id: "Aset Keuangan",
      sw: "Mali za Karatasi",
    },
    subtitle: {
      en: "Paper asset investing: stocks, bonds, ETFs, and retirement accounts.",
      es: "Inversión en activos financieros: acciones, bonos, ETF y cuentas para el retiro.",
      fr: "Investissement en actifs financiers : actions, obligations, ETF et comptes de retraite.",
      pt: "Investimento em ativos financeiros: ações, títulos, ETFs e contas de aposentadoria.",
      de: "Investitionen in finanzielle Vermögenswerte: Aktien, Anleihen, ETFs und Rentenkonten.",
      it: "Investimento in attività finanziarie: azioni, obbligazioni, ETF e conti pensionistici.",
      nl: "Beleggen in financiële activa: aandelen, obligaties, ETF's en pensioenrekeningen.",
      pl: "Inwestowanie w aktywa papierowe: akcje, obligacje, ETF i konta emerytalne.",
      ru: "Инвестирование в бумажные активы: акции, облигации, ETF и пенсионные счета.",
      ar: "الاستثمار في الأصول الورقية: الأسهم والسندات وصناديق الاستثمار المتداولة وحسابات التقاعد.",
      hi: "पेपर संपत्ति निवेश: स्टॉक, बॉन्ड, ETF और सेवानिवृत्ति खाते।",
      "zh-Hans": "金融资产投资：股票、债券、ETF和退休账户。",
      "zh-Hant": "金融資產投資：股票、債券、ETF和退休賬戶。",
      ja: "金融資産投資：株式、債券、ETF、退職口座。",
      ko: "금융 자산 투자: 주식, 채권, ETF 및 퇴직 계좌.",
      vi: "Đầu tư tài sản tài chính: cổ phiếu, trái phiếu, ETF và tài khoản hưu trí.",
      id: "Investasi aset keuangan: saham, obligasi, ETF, dan rekening pensiun.",
      sw: "Uwekezaji wa mali za karatasi: hisa, dhamana, ETF na akaunti za kustaafu.",
    },
  },

  // ─── BLUE — Business ─────────────────────────────────────────────────────────
  BLUE: {
    name: {
      en: "Business",
      es: "Negocios",
      fr: "Entreprise",
      pt: "Negócios",
      de: "Unternehmen",
      it: "Impresa",
      nl: "Bedrijf",
      pl: "Biznes",
      cs: "Podnikání",
      sk: "Podnikanie",
      ro: "Afaceri",
      bg: "Бизнес",
      ru: "Бизнес",
      uk: "Бізнес",
      ar: "الأعمال",
      he: "עסקים",
      fa: "کسب‌وکار",
      hi: "व्यापार",
      bn: "ব্যবসা",
      "zh-Hans": "商业",
      "zh-Hant": "商業",
      ja: "ビジネス",
      ko: "비즈니스",
      th: "ธุรกิจ",
      vi: "Kinh doanh",
      id: "Bisnis",
      ms: "Perniagaan",
      fil: "Negosyo",
      sw: "Biashara",
      am: "ንግድ",
      ht: "Biznis",
    },
    description: {
      en: "Build business competency — business models, cash flow, operations, growth strategies, and the financial mechanics of entrepreneurship.",
      es: "Desarrolla competencia empresarial: modelos de negocio, flujo de efectivo, operaciones, estrategias de crecimiento y la mecánica financiera del emprendimiento.",
      fr: "Développez votre compétence en affaires — modèles économiques, flux de trésorerie, opérations, stratégies de croissance et mécanique financière de l'entrepreneuriat.",
      pt: "Desenvolva competência empresarial — modelos de negócios, fluxo de caixa, operações, estratégias de crescimento e a mecânica financeira do empreendedorismo.",
      de: "Entwickeln Sie unternehmerische Kompetenz — Geschäftsmodelle, Cashflow, Betrieb, Wachstumsstrategien und die finanzielle Mechanik des Unternehmertums.",
      it: "Sviluppa la competenza imprenditoriale — modelli di business, flusso di cassa, operazioni, strategie di crescita e la meccanica finanziaria dell'imprenditorialità.",
      nl: "Ontwikkel zakelijke competentie — bedrijfsmodellen, cashflow, operaties, groeistrateg ieën en de financiële mechanica van het ondernemerschap.",
      pl: "Rozwijaj kompetencje biznesowe — modele biznesowe, przepływy pieniężne, operacje, strategie wzrostu i finansową mechanikę przedsiębiorczości.",
      ru: "Развивайте деловую компетентность — бизнес-модели, денежный поток, операции, стратегии роста и финансовую механику предпринимательства.",
      ar: "بناء الكفاءة في الأعمال — نماذج الأعمال والتدفق النقدي والعمليات واستراتيجيات النمو والميكانيكا المالية لريادة الأعمال.",
      hi: "व्यापार दक्षता बनाएं — व्यापार मॉडल, नकदी प्रवाह, संचालन, विकास रणनीतियाँ और उद्यमिता की वित्तीय यांत्रिकी।",
      "zh-Hans": "建立商业能力——商业模式、现金流、运营、增长战略以及创业的财务机制。",
      "zh-Hant": "建立商業能力——商業模式、現金流、運營、增長戰略以及創業的財務機制。",
      ja: "ビジネス能力を構築する — ビジネスモデル、キャッシュフロー、オペレーション、成長戦略、起業家精神の財務メカニズム。",
      ko: "비즈니스 역량 구축 — 비즈니스 모델, 현금 흐름, 운영, 성장 전략 및 기업가 정신의 재무 메커니즘.",
      vi: "Xây dựng năng lực kinh doanh — mô hình kinh doanh, dòng tiền, vận hành, chiến lược tăng trưởng và cơ chế tài chính của khởi nghiệp.",
      id: "Bangun kompetensi bisnis — model bisnis, arus kas, operasi, strategi pertumbuhan, dan mekanika keuangan kewirausahaan.",
      sw: "Jenga uwezo wa biashara — mifano ya biashara, mtiririko wa pesa, uendeshaji, mikakati ya ukuaji na mechanics ya fedha za ujasiriamali.",
    },
    category: {
      en: "Business",
      es: "Negocios",
      fr: "Entreprise",
      pt: "Negócios",
      de: "Unternehmen",
      it: "Impresa",
      nl: "Bedrijf",
      pl: "Biznes",
      ru: "Бизнес",
      ar: "الأعمال",
      hi: "व्यापार",
      "zh-Hans": "商业",
      "zh-Hant": "商業",
      ja: "ビジネス",
      ko: "비즈니스",
      vi: "Kinh doanh",
      id: "Bisnis",
      sw: "Biashara",
    },
    subtitle: {
      en: "Business competency: starting, growing, and managing a business.",
      es: "Competencia empresarial: iniciar, hacer crecer y administrar un negocio.",
      fr: "Compétence en affaires : démarrer, développer et gérer une entreprise.",
      pt: "Competência empresarial: iniciar, crescer e gerenciar um negócio.",
      de: "Unternehmerische Kompetenz: Starten, Wachsen und Verwalten eines Unternehmens.",
      it: "Competenza imprenditoriale: avviare, far crescere e gestire un'impresa.",
      nl: "Zakelijke competentie: starten, laten groeien en beheren van een bedrijf.",
      pl: "Kompetencje biznesowe: zakładanie, rozwijanie i zarządzanie firmą.",
      ru: "Деловая компетентность: запуск, развитие и управление бизнесом.",
      ar: "الكفاءة في الأعمال: البدء والنمو وإدارة الأعمال.",
      hi: "व्यापार दक्षता: व्यापार शुरू करना, बढ़ाना और प्रबंधित करना।",
      "zh-Hans": "商业能力：创办、发展和管理企业。",
      "zh-Hant": "商業能力：創辦、發展和管理企業。",
      ja: "ビジネス能力：ビジネスの開始、成長、管理。",
      ko: "비즈니스 역량: 비즈니스 시작, 성장 및 관리.",
      vi: "Năng lực kinh doanh: bắt đầu, phát triển và quản lý doanh nghiệp.",
      id: "Kompetensi bisnis: memulai, mengembangkan, dan mengelola bisnis.",
      sw: "Uwezo wa biashara: kuanza, kukua na kusimamia biashara.",
    },
  },

  // ─── GREEN — Taxes ───────────────────────────────────────────────────────────
  GREEN: {
    name: {
      en: "Taxes",
      es: "Impuestos",
      fr: "Impôts",
      pt: "Impostos",
      de: "Steuern",
      it: "Tasse",
      nl: "Belastingen",
      pl: "Podatki",
      cs: "Daně",
      sk: "Dane",
      ro: "Impozite",
      bg: "Данъци",
      ru: "Налоги",
      uk: "Податки",
      ar: "الضرائب",
      he: "מיסים",
      fa: "مالیات",
      hi: "कर",
      bn: "কর",
      "zh-Hans": "税务",
      "zh-Hant": "稅務",
      ja: "税金",
      ko: "세금",
      th: "ภาษี",
      vi: "Thuế",
      id: "Pajak",
      ms: "Cukai",
      fil: "Buwis",
      sw: "Ushuru",
      am: "ግብር",
      ht: "Taks",
    },
    description: {
      en: "Understand how taxation works, how to minimize your tax burden legally, and how to use the tax code as a financial tool.",
      es: "Comprende cómo funcionan los impuestos, cómo reducir legalmente tu carga fiscal y cómo usar el código tributario como herramienta financiera.",
      fr: "Comprendre le fonctionnement de la fiscalité, comment minimiser légalement votre charge fiscale et comment utiliser le code des impôts comme outil financier.",
      pt: "Entenda como a tributação funciona, como minimizar legalmente sua carga tributária e como usar o código tributário como ferramenta financeira.",
      de: "Verstehen Sie, wie Besteuerung funktioniert, wie Sie Ihre Steuerlast legal minimieren und wie Sie das Steuerrecht als Finanzwerkzeug nutzen können.",
      it: "Capire come funziona la tassazione, come ridurre legalmente il carico fiscale e come utilizzare il codice fiscale come strumento finanziario.",
      nl: "Begrijp hoe belastingheffing werkt, hoe u uw belastingdruk legaal kunt minimaliseren en hoe u de belastingwetgeving als financieel instrument kunt gebruiken.",
      pl: "Zrozum, jak działa opodatkowanie, jak legalnie minimalizować obciążenia podatkowe i jak używać prawa podatkowego jako narzędzia finansowego.",
      ru: "Понять, как работает налогообложение, как законно минимизировать налоговое бремя и как использовать налоговый кодекс в качестве финансового инструмента.",
      ar: "فهم كيفية عمل الضرائب وكيفية تقليل العبء الضريبي بشكل قانوني وكيفية استخدام قانون الضرائب كأداة مالية.",
      hi: "समझें कि कराधान कैसे काम करता है, कानूनी रूप से अपने कर बोझ को कैसे कम करें और वित्तीय उपकरण के रूप में कर संहिता का उपयोग कैसे करें।",
      "zh-Hans": "了解税收如何运作，如何合法减少税务负担，以及如何将税法作为金融工具使用。",
      "zh-Hant": "了解稅收如何運作，如何合法減少稅務負擔，以及如何將稅法作為金融工具使用。",
      ja: "課税の仕組み、合法的に税負担を最小化する方法、税法を金融ツールとして活用する方法を理解する。",
      ko: "세금이 어떻게 작동하는지, 합법적으로 세금 부담을 최소화하는 방법, 세법을 금융 도구로 사용하는 방법을 이해하세요.",
      vi: "Hiểu cách hệ thống thuế hoạt động, cách giảm thiểu gánh nặng thuế hợp pháp và cách sử dụng luật thuế như một công cụ tài chính.",
      id: "Pahami bagaimana perpajakan bekerja, cara meminimalkan beban pajak secara legal, dan cara menggunakan kode pajak sebagai alat keuangan.",
      sw: "Elewa jinsi ushuru unavyofanya kazi, jinsi ya kupunguza mzigo wa ushuru kisheria na jinsi ya kutumia kanuni ya ushuru kama chombo cha fedha.",
    },
    category: {
      en: "Taxes",
      es: "Impuestos",
      fr: "Impôts",
      pt: "Impostos",
      de: "Steuern",
      it: "Tasse",
      nl: "Belastingen",
      pl: "Podatki",
      ru: "Налоги",
      ar: "الضرائب",
      hi: "कर",
      "zh-Hans": "税务",
      "zh-Hant": "稅務",
      ja: "税金",
      ko: "세금",
      vi: "Thuế",
      id: "Pajak",
      sw: "Ushuru",
    },
    subtitle: {
      en: "Tax strategy: legal minimization, deductions, entities, and tax-advantaged wealth building.",
      es: "Estrategia fiscal: minimización legal, deducciones, entidades y creación de patrimonio con ventajas fiscales.",
      fr: "Stratégie fiscale : minimisation légale, déductions, entités et constitution de patrimoine fiscalement avantageux.",
      pt: "Estratégia tributária: minimização legal, deduções, entidades e construção de riqueza com vantagens fiscais.",
      de: "Steuerstrategie: legale Minimierung, Abzüge, Entitäten und steuerlich begünstigter Vermögensaufbau.",
      it: "Strategia fiscale: minimizzazione legale, detrazioni, entità e costruzione della ricchezza con vantaggi fiscali.",
      nl: "Belastingstrategie: legale minimalisatie, aftrekposten, entiteiten en fiscaal voordelig vermogensopbouw.",
      pl: "Strategia podatkowa: legalna minimalizacja, odliczenia, podmioty i budowanie majątku z korzyściami podatkowymi.",
      ru: "Налоговая стратегия: законная минимизация, вычеты, субъекты и накопление богатства с налоговыми льготами.",
      ar: "الاستراتيجية الضريبية: التقليل القانوني والخصومات والكيانات وبناء الثروة الميسر ضريبياً.",
      hi: "कर रणनीति: कानूनी न्यूनीकरण, कटौती, संस्थाएं और कर-लाभप्रद धन निर्माण।",
      "zh-Hans": "税务策略：合法减税、扣除、实体和税务优惠的财富积累。",
      "zh-Hant": "稅務策略：合法減稅、扣除、實體和稅務優惠的財富積累。",
      ja: "税務戦略：合法的な最小化、控除、エンティティ、税制優遇による富の構築。",
      ko: "세금 전략: 합법적 최소화, 공제, 법인 및 세금 우대 자산 형성.",
      vi: "Chiến lược thuế: giảm thiểu hợp pháp, khấu trừ, thực thể và xây dựng tài sản có lợi thế thuế.",
      id: "Strategi pajak: minimisasi legal, pengurangan, entitas, dan pembangunan kekayaan berbasis keuntungan pajak.",
      sw: "Mkakati wa ushuru: kupunguza kisheria, makato, vyombo na ujenzi wa utajiri wenye faida za ushuru.",
    },
  },

  // ─── GOLD — Investing & Wealth Building ─────────────────────────────────────
  GOLD: {
    name: {
      en: "Investing & Wealth Building",
      es: "Inversión y creación de patrimonio",
      fr: "Investissement et création de patrimoine",
      pt: "Investimento e construção de riqueza",
      de: "Investieren und Vermögensaufbau",
      it: "Investimento e creazione di ricchezza",
      nl: "Beleggen en vermogensopbouw",
      pl: "Inwestowanie i budowanie majątku",
      cs: "Investování a budování bohatství",
      sk: "Investovanie a budovanie bohatstva",
      ro: "Investiții și construirea bogăției",
      bg: "Инвестиране и изграждане на богатство",
      ru: "Инвестирование и создание богатства",
      uk: "Інвестування та накопичення багатства",
      ar: "الاستثمار وبناء الثروة",
      he: "השקעות ובניית עושר",
      fa: "سرمایه‌گذاری و ثروت‌سازی",
      hi: "निवेश और धन निर्माण",
      bn: "বিনিয়োগ ও সম্পদ নির্মাণ",
      "zh-Hans": "投资与财富积累",
      "zh-Hant": "投資與財富積累",
      ja: "投資と資産形成",
      ko: "투자 및 자산 형성",
      th: "การลงทุนและการสร้างความมั่งคั่ง",
      vi: "Đầu tư và xây dựng tài sản",
      id: "Investasi & Pembangunan Kekayaan",
      ms: "Pelaburan & Pembinaan Kekayaan",
      fil: "Pamumuhunan at Pagtatayo ng Kayamanan",
      sw: "Uwekezaji na Ujenzi wa Utajiri",
      am: "ኢንቨስትመንት እና ሀብት ግንባታ",
      ht: "Envèstisman ak Konstwi Richès",
    },
    description: {
      en: "Master investment principles, portfolio construction, asset allocation, and long-term wealth building strategies across all asset classes.",
      es: "Domina los principios de inversión, la construcción de carteras, la asignación de activos y las estrategias de creación de patrimonio a largo plazo en todas las clases de activos.",
      fr: "Maîtrisez les principes d'investissement, la construction de portefeuille, l'allocation d'actifs et les stratégies de création de patrimoine à long terme dans toutes les classes d'actifs.",
      pt: "Domine os princípios de investimento, construção de portfólio, alocação de ativos e estratégias de criação de riqueza a longo prazo em todas as classes de ativos.",
      de: "Meistern Sie Investitionsprinzipien, Portfolioaufbau, Asset Allocation und langfristige Vermögensaufbaustrategien für alle Anlageklassen.",
      it: "Padroneggia i principi di investimento, la costruzione di portafoglio, l'allocazione degli attivi e le strategie di creazione di ricchezza a lungo termine in tutte le classi di attivi.",
      nl: "Beheers beleggingsbeginselen, portefeuilleconstructie, activaspreiding en langetermijnstrategieën voor vermogensopbouw in alle activaklassen.",
      pl: "Opanuj zasady inwestowania, budowanie portfela, alokację aktywów i długoterminowe strategie budowania majątku we wszystkich klasach aktywów.",
      ru: "Освойте принципы инвестирования, построение портфеля, распределение активов и долгосрочные стратегии накопления богатства во всех классах активов.",
      ar: "إتقان مبادئ الاستثمار وبناء المحافظ وتخصيص الأصول واستراتيجيات بناء الثروة على المدى البعيد عبر جميع فئات الأصول.",
      hi: "निवेश सिद्धांतों, पोर्टफोलियो निर्माण, संपत्ति आवंटन और सभी संपत्ति वर्गों में दीर्घकालिक धन निर्माण रणनीतियों में महारत हासिल करें।",
      "zh-Hans": "掌握投资原则、投资组合构建、资产配置以及跨所有资产类别的长期财富积累策略。",
      "zh-Hant": "掌握投資原則、投資組合構建、資產配置以及跨所有資產類別的長期財富積累策略。",
      ja: "すべての資産クラスにわたる投資原則、ポートフォリオ構築、資産配分、長期資産形成戦略を習得する。",
      ko: "모든 자산 클래스에 걸친 투자 원칙, 포트폴리오 구성, 자산 배분 및 장기 자산 형성 전략을 마스터하세요.",
      vi: "Nắm vững các nguyên tắc đầu tư, xây dựng danh mục đầu tư, phân bổ tài sản và chiến lược xây dựng tài sản dài hạn trên tất cả các loại tài sản.",
      id: "Kuasai prinsip investasi, konstruksi portofolio, alokasi aset, dan strategi pembangunan kekayaan jangka panjang di semua kelas aset.",
      sw: "Jifunze kanuni za uwekezaji, ujenzi wa mkoba, ugawaji wa mali na mikakati ya ujenzi wa utajiri wa muda mrefu katika madarasa yote ya mali.",
    },
    category: {
      en: "Investing & Wealth Building",
      es: "Inversión y creación de patrimonio",
      fr: "Investissement et création de patrimoine",
      pt: "Investimento e construção de riqueza",
      de: "Investieren und Vermögensaufbau",
      it: "Investimento e creazione di ricchezza",
      nl: "Beleggen en vermogensopbouw",
      pl: "Inwestowanie i budowanie majątku",
      ru: "Инвестирование и создание богатства",
      ar: "الاستثمار وبناء الثروة",
      hi: "निवेश और धन निर्माण",
      "zh-Hans": "投资与财富积累",
      "zh-Hant": "投資與財富積累",
      ja: "投資と資産形成",
      ko: "투자 및 자산 형성",
      vi: "Đầu tư và xây dựng tài sản",
      id: "Investasi & Pembangunan Kekayaan",
      sw: "Uwekezaji na Ujenzi wa Utajiri",
    },
    subtitle: {
      en: "Wealth building: investment fundamentals, portfolio strategy, and financial independence.",
      es: "Creación de patrimonio: fundamentos de inversión, estrategia de cartera e independencia financiera.",
      fr: "Construction de patrimoine : fondamentaux de l'investissement, stratégie de portefeuille et indépendance financière.",
      pt: "Construção de riqueza: fundamentos de investimento, estratégia de portfólio e independência financeira.",
      de: "Vermögensaufbau: Investitionsgrundlagen, Portfoliostrategie und finanzielle Unabhängigkeit.",
      it: "Costruzione della ricchezza: fondamenti di investimento, strategia di portafoglio e indipendenza finanziaria.",
      nl: "Vermogensopbouw: beleggingsbeginselen, portefeuillesstrategie en financiële onafhankelijkheid.",
      pl: "Budowanie majątku: podstawy inwestowania, strategia portfela i niezależność finansowa.",
      ru: "Накопление богатства: основы инвестирования, стратегия портфеля и финансовая независимость.",
      ar: "بناء الثروة: أساسيات الاستثمار واستراتيجية المحفظة والاستقلال المالي.",
      hi: "धन निर्माण: निवेश की मूल बातें, पोर्टफोलियो रणनीति और वित्तीय स्वतंत्रता।",
      "zh-Hans": "财富积累：投资基础、投资组合策略和财务独立。",
      "zh-Hant": "財富積累：投資基礎、投資組合策略和財務獨立。",
      ja: "資産形成：投資の基礎、ポートフォリオ戦略、経済的自立。",
      ko: "자산 형성: 투자 기초, 포트폴리오 전략 및 재정적 독립.",
      vi: "Xây dựng tài sản: nguyên tắc cơ bản về đầu tư, chiến lược danh mục và độc lập tài chính.",
      id: "Pembangunan kekayaan: dasar-dasar investasi, strategi portofolio, dan kebebasan finansial.",
      sw: "Ujenzi wa utajiri: misingi ya uwekezaji, mkakati wa mkoba na uhuru wa kifedha.",
    },
  },

  // ─── PURPLE — Law ────────────────────────────────────────────────────────────
  PURPLE: {
    name: {
      en: "Law",
      es: "Derecho",
      fr: "Droit",
      pt: "Direito",
      de: "Recht",
      it: "Diritto",
      nl: "Recht",
      pl: "Prawo",
      cs: "Právo",
      sk: "Právo",
      ro: "Drept",
      bg: "Право",
      ru: "Право",
      uk: "Право",
      ar: "القانون",
      he: "משפט",
      fa: "حقوق",
      hi: "कानून",
      bn: "আইন",
      "zh-Hans": "法律",
      "zh-Hant": "法律",
      ja: "法律",
      ko: "법률",
      th: "กฎหมาย",
      vi: "Pháp luật",
      id: "Hukum",
      ms: "Undang-undang",
      fil: "Batas",
      sw: "Sheria",
      am: "ህግ",
      ht: "Lwa",
    },
    description: {
      en: "Learn how legal structures, contracts, entities, and asset protection strategies work — and how to use them to protect and grow your wealth.",
      es: "Aprende cómo funcionan las estructuras legales, contratos, entidades y estrategias de protección de activos, y cómo usarlos para proteger y hacer crecer tu patrimonio.",
      fr: "Apprenez comment fonctionnent les structures juridiques, les contrats, les entités et les stratégies de protection des actifs — et comment les utiliser pour protéger et faire croître votre patrimoine.",
      pt: "Aprenda como funcionam as estruturas legais, contratos, entidades e estratégias de proteção de ativos — e como usá-los para proteger e crescer seu patrimônio.",
      de: "Erfahren Sie, wie rechtliche Strukturen, Verträge, Entitäten und Vermögensschutzstrategien funktionieren — und wie man sie einsetzt, um Ihr Vermögen zu schützen und zu vergrößern.",
      it: "Scopri come funzionano le strutture legali, i contratti, le entità e le strategie di protezione degli attivi — e come usarli per proteggere e far crescere la tua ricchezza.",
      nl: "Leer hoe juridische structuren, contracten, entiteiten en vermogensbeschermingsstrategieën werken — en hoe u ze kunt gebruiken om uw vermogen te beschermen en te laten groeien.",
      pl: "Dowiedz się, jak działają struktury prawne, umowy, podmioty i strategie ochrony aktywów — i jak je wykorzystać do ochrony i powiększania swojego majątku.",
      ru: "Узнайте, как работают правовые структуры, контракты, субъекты и стратегии защиты активов — и как их использовать для защиты и приумножения богатства.",
      ar: "تعرف على كيفية عمل الهياكل القانونية والعقود والكيانات واستراتيجيات حماية الأصول — وكيفية استخدامها لحماية ثروتك وتنميتها.",
      hi: "जानें कि कानूनी संरचनाएं, अनुबंध, संस्थाएं और संपत्ति संरक्षण रणनीतियाँ कैसे काम करती हैं — और अपनी संपत्ति की रक्षा और बढ़ाने के लिए उनका उपयोग कैसे करें।",
      "zh-Hans": "了解法律结构、合同、实体和资产保护策略如何运作——以及如何使用它们来保护和增长您的财富。",
      "zh-Hant": "了解法律結構、合同、實體和資產保護策略如何運作——以及如何使用它們來保護和增長您的財富。",
      ja: "法的構造、契約、エンティティ、資産保護戦略の仕組みを学び、それらを使って富を守り、成長させる方法を学ぶ。",
      ko: "법적 구조, 계약, 법인 및 자산 보호 전략이 어떻게 작동하는지, 그리고 이를 활용하여 자산을 보호하고 성장시키는 방법을 배우세요.",
      vi: "Tìm hiểu cách các cấu trúc pháp lý, hợp đồng, thực thể và chiến lược bảo vệ tài sản hoạt động — và cách sử dụng chúng để bảo vệ và phát triển tài sản của bạn.",
      id: "Pelajari cara kerja struktur hukum, kontrak, entitas, dan strategi perlindungan aset — serta cara menggunakannya untuk melindungi dan menumbuhkan kekayaan Anda.",
      sw: "Jifunze jinsi miundo ya kisheria, mikataba, vyombo na mikakati ya ulinzi wa mali inavyofanya kazi — na jinsi ya kuitumia kulinda na kukuza utajiri wako.",
    },
    category: {
      en: "Law",
      es: "Derecho",
      fr: "Droit",
      pt: "Direito",
      de: "Recht",
      it: "Diritto",
      nl: "Recht",
      pl: "Prawo",
      ru: "Право",
      ar: "القانون",
      hi: "कानून",
      "zh-Hans": "法律",
      "zh-Hant": "法律",
      ja: "法律",
      ko: "법률",
      vi: "Pháp luật",
      id: "Hukum",
      sw: "Sheria",
    },
    subtitle: {
      en: "Legal foundations: contracts, entities, asset protection, and financial law.",
      es: "Fundamentos legales: contratos, entidades, protección de activos y derecho financiero.",
      fr: "Fondements juridiques : contrats, entités, protection des actifs et droit financier.",
      pt: "Fundamentos legais: contratos, entidades, proteção de ativos e direito financeiro.",
      de: "Rechtliche Grundlagen: Verträge, Entitäten, Vermögensschutz und Finanzrecht.",
      it: "Fondamenti legali: contratti, entità, protezione degli attivi e diritto finanziario.",
      nl: "Juridische grondslagen: contracten, entiteiten, vermogensbescherming en financieel recht.",
      pl: "Podstawy prawne: umowy, podmioty, ochrona aktywów i prawo finansowe.",
      ru: "Правовые основы: контракты, субъекты, защита активов и финансовое право.",
      ar: "الأسس القانونية: العقود والكيانات وحماية الأصول والقانون المالي.",
      hi: "कानूनी नींव: अनुबंध, संस्थाएं, संपत्ति संरक्षण और वित्तीय कानून।",
      "zh-Hans": "法律基础：合同、实体、资产保护和金融法。",
      "zh-Hant": "法律基礎：合同、實體、資產保護和金融法。",
      ja: "法的基礎：契約、エンティティ、資産保護、金融法。",
      ko: "법적 기초: 계약, 법인, 자산 보호 및 금융법.",
      vi: "Nền tảng pháp lý: hợp đồng, thực thể, bảo vệ tài sản và luật tài chính.",
      id: "Dasar-dasar hukum: kontrak, entitas, perlindungan aset, dan hukum keuangan.",
      sw: "Misingi ya kisheria: mikataba, vyombo, ulinzi wa mali na sheria ya fedha.",
    },
  },

  // ─── ORANGE — Sales & Marketing ─────────────────────────────────────────────
  ORANGE: {
    name: {
      en: "Sales & Marketing",
      es: "Ventas y marketing",
      fr: "Vente et marketing",
      pt: "Vendas e marketing",
      de: "Vertrieb und Marketing",
      it: "Vendite e marketing",
      nl: "Verkoop en marketing",
      pl: "Sprzedaż i marketing",
      cs: "Prodej a marketing",
      sk: "Predaj a marketing",
      ro: "Vânzări și marketing",
      bg: "Продажби и маркетинг",
      ru: "Продажи и маркетинг",
      uk: "Продажі та маркетинг",
      ar: "المبيعات والتسويق",
      he: "מכירות ושיווק",
      fa: "فروش و بازاریابی",
      hi: "बिक्री और विपणन",
      bn: "বিক্রয় ও বিপণন",
      "zh-Hans": "销售与营销",
      "zh-Hant": "銷售與營銷",
      ja: "セールスとマーケティング",
      ko: "영업 및 마케팅",
      th: "การขายและการตลาด",
      vi: "Bán hàng và tiếp thị",
      id: "Penjualan & Pemasaran",
      ms: "Jualan & Pemasaran",
      fil: "Benta at Marketing",
      sw: "Mauzo na Masoko",
      am: "ሽያጭ እና ግብይት",
      ht: "Vant ak Maketing",
    },
    description: {
      en: "Develop competency in sales, marketing, customer acquisition, and persuasion — the skills that drive revenue in any business or career.",
      es: "Desarrolla competencia en ventas, marketing, adquisición de clientes y persuasión: las habilidades que impulsan los ingresos en cualquier negocio o carrera.",
      fr: "Développez des compétences en vente, marketing, acquisition de clients et persuasion — les compétences qui stimulent les revenus dans n'importe quelle entreprise ou carrière.",
      pt: "Desenvolva competência em vendas, marketing, aquisição de clientes e persuasão — as habilidades que impulsionam a receita em qualquer negócio ou carreira.",
      de: "Entwickeln Sie Kompetenz in Vertrieb, Marketing, Kundenakquise und Überzeugungsarbeit — die Fähigkeiten, die Umsatz in jedem Unternehmen oder jeder Karriere vorantreiben.",
      it: "Sviluppa competenza in vendite, marketing, acquisizione clienti e persuasione — le competenze che guidano le entrate in qualsiasi attività o carriera.",
      nl: "Ontwikkel competentie in verkoop, marketing, klantenwerving en overtuiging — de vaardigheden die inkomsten genereren in elk bedrijf of elke carrière.",
      pl: "Rozwijaj kompetencje w zakresie sprzedaży, marketingu, pozyskiwania klientów i perswazji — umiejętności, które napędzają przychody w każdym biznesie lub karierze.",
      ru: "Развивайте компетентность в продажах, маркетинге, привлечении клиентов и убеждении — навыки, которые обеспечивают доход в любом бизнесе или карьере.",
      ar: "تطوير الكفاءة في المبيعات والتسويق واكتساب العملاء والإقناع — المهارات التي تدفع الإيرادات في أي عمل أو مسيرة مهنية.",
      hi: "बिक्री, विपणन, ग्राहक अधिग्रहण और अनुनय में दक्षता विकसित करें — वे कौशल जो किसी भी व्यवसाय या करियर में राजस्व चलाते हैं।",
      "zh-Hans": "发展销售、营销、客户获取和说服力方面的能力——在任何业务或职业中推动收入的技能。",
      "zh-Hant": "發展銷售、營銷、客戶獲取和說服力方面的能力——在任何業務或職業中推動收入的技能。",
      ja: "セールス、マーケティング、顧客獲得、説得力の能力を開発する — どんなビジネスやキャリアでも収益を生み出すスキル。",
      ko: "영업, 마케팅, 고객 확보 및 설득력에 대한 역량 개발 — 모든 비즈니스나 직업에서 수익을 창출하는 기술.",
      vi: "Phát triển năng lực trong bán hàng, tiếp thị, thu hút khách hàng và thuyết phục — những kỹ năng thúc đẩy doanh thu trong bất kỳ doanh nghiệp hay sự nghiệp nào.",
      id: "Kembangkan kompetensi dalam penjualan, pemasaran, akuisisi pelanggan, dan persuasi — keterampilan yang mendorong pendapatan dalam bisnis atau karier apa pun.",
      sw: "Endeleza uwezo katika mauzo, masoko, upatikanaji wa wateja na ushawishi — ujuzi unaosukuma mapato katika biashara au kazi yoyote.",
    },
    category: {
      en: "Sales & Marketing",
      es: "Ventas y marketing",
      fr: "Vente et marketing",
      pt: "Vendas e marketing",
      de: "Vertrieb und Marketing",
      it: "Vendite e marketing",
      nl: "Verkoop en marketing",
      pl: "Sprzedaż i marketing",
      ru: "Продажи и маркетинг",
      ar: "المبيعات والتسويق",
      hi: "बिक्री और विपणन",
      "zh-Hans": "销售与营销",
      "zh-Hant": "銷售與營銷",
      ja: "セールスとマーケティング",
      ko: "영업 및 마케팅",
      vi: "Bán hàng và tiếp thị",
      id: "Penjualan & Pemasaran",
      sw: "Mauzo na Masoko",
    },
    subtitle: {
      en: "Sales and marketing competency: persuasion, customer acquisition, and revenue growth.",
      es: "Competencia en ventas y marketing: persuasión, adquisición de clientes y crecimiento de ingresos.",
      fr: "Compétence en vente et marketing : persuasion, acquisition de clients et croissance des revenus.",
      pt: "Competência em vendas e marketing: persuasão, aquisição de clientes e crescimento de receita.",
      de: "Vertriebs- und Marketingkompetenz: Überzeugung, Kundenakquise und Umsatzwachstum.",
      it: "Competenza in vendite e marketing: persuasione, acquisizione clienti e crescita dei ricavi.",
      nl: "Verkoop- en marketingcompetentie: overtuiging, klantenwerving en omzetgroei.",
      pl: "Kompetencje w zakresie sprzedaży i marketingu: perswazja, pozyskiwanie klientów i wzrost przychodów.",
      ru: "Компетентность в продажах и маркетинге: убеждение, привлечение клиентов и рост доходов.",
      ar: "الكفاءة في المبيعات والتسويق: الإقناع واكتساب العملاء ونمو الإيرادات.",
      hi: "बिक्री और विपणन दक्षता: अनुनय, ग्राहक अधिग्रहण और राजस्व वृद्धि।",
      "zh-Hans": "销售和营销能力：说服力、客户获取和收入增长。",
      "zh-Hant": "銷售和營銷能力：說服力、客戶獲取和收入增長。",
      ja: "セールスとマーケティングの能力：説得、顧客獲得、収益成長。",
      ko: "영업 및 마케팅 역량: 설득력, 고객 확보 및 수익 성장.",
      vi: "Năng lực bán hàng và tiếp thị: thuyết phục, thu hút khách hàng và tăng trưởng doanh thu.",
      id: "Kompetensi penjualan dan pemasaran: persuasi, akuisisi pelanggan, dan pertumbuhan pendapatan.",
      sw: "Uwezo wa mauzo na masoko: ushawishi, upatikanaji wa wateja na ukuaji wa mapato.",
    },
  },

  // ─── BLACK — Leadership & Executive Management ───────────────────────────────
  BLACK: {
    name: {
      en: "Leadership & Executive Management",
      es: "Liderazgo y gestión ejecutiva",
      fr: "Leadership et gestion de direction",
      pt: "Liderança e gestão executiva",
      de: "Führung und Unternehmensmanagement",
      it: "Leadership e gestione esecutiva",
      nl: "Leiderschap en uitvoerend management",
      pl: "Przywództwo i zarządzanie wykonawcze",
      cs: "Vedení a výkonný management",
      sk: "Vedenie a výkonný manažment",
      ro: "Leadership și management executiv",
      bg: "Лидерство и изпълнителско управление",
      ru: "Лидерство и исполнительное управление",
      uk: "Лідерство та виконавче управління",
      ar: "القيادة والإدارة التنفيذية",
      he: "מנהיגות וניהול בכיר",
      fa: "رهبری و مدیریت اجرایی",
      hi: "नेतृत्व और कार्यकारी प्रबंधन",
      bn: "নেতৃত্ব ও নির্বাহী ব্যবস্থাপনা",
      "zh-Hans": "领导力与高管管理",
      "zh-Hant": "領導力與高管管理",
      ja: "リーダーシップと経営管理",
      ko: "리더십 및 경영 관리",
      th: "ความเป็นผู้นำและการจัดการเชิงบริหาร",
      vi: "Lãnh đạo và quản lý điều hành",
      id: "Kepemimpinan & Manajemen Eksekutif",
      ms: "Kepimpinan & Pengurusan Eksekutif",
      fil: "Pamumuno at Pamamahala ng Ehekutibo",
      sw: "Uongozi na Usimamizi wa Watendaji",
      am: "አመራር እና ሥራ አስኪያጅ አስተዳደር",
      ht: "Lidèchip ak Jesyon Egzekitif",
    },
    description: {
      en: "Build leadership competency — executive decision-making, team building, organizational management, and the financial acumen required at the highest levels.",
      es: "Desarrolla competencia en liderazgo: toma de decisiones ejecutivas, formación de equipos, gestión organizacional y el criterio financiero requerido en los niveles más altos.",
      fr: "Développez la compétence en leadership — prise de décision de direction, constitution d'équipes, gestion organisationnelle et le sens financier requis aux plus hauts niveaux.",
      pt: "Desenvolva competência em liderança — tomada de decisões executivas, formação de equipes, gestão organizacional e o senso financeiro exigido nos níveis mais altos.",
      de: "Entwickeln Sie Führungskompetenz — Entscheidungsfindung auf Führungsebene, Teambildung, Organisationsmanagement und die auf höchster Ebene erforderliche finanzielle Kompetenz.",
      it: "Sviluppa la competenza di leadership — decision-making esecutivo, team building, gestione organizzativa e l'acume finanziario richiesto ai livelli più alti.",
      nl: "Ontwikkel leiderschapscompetentie — besluitvorming op directieniveau, teamopbouw, organisatiemanagement en het financieel inzicht dat op de hoogste niveaus vereist is.",
      pl: "Rozwijaj kompetencje przywódcze — decyzje kierownicze, budowanie zespołu, zarządzanie organizacyjne i wiedza finansowa wymagana na najwyższych szczeblach.",
      ru: "Развивайте лидерскую компетентность — исполнительное принятие решений, построение команды, организационное управление и финансовая проницательность, необходимая на высшем уровне.",
      ar: "بناء الكفاءة في القيادة — صنع القرار التنفيذي وبناء الفريق والإدارة التنظيمية والفطنة المالية المطلوبة على أعلى المستويات.",
      hi: "नेतृत्व दक्षता बनाएं — कार्यकारी निर्णय लेना, टीम निर्माण, संगठनात्मक प्रबंधन और उच्चतम स्तरों पर आवश्यक वित्तीय कुशाग्रता।",
      "zh-Hans": "建立领导力——高管决策、团队建设、组织管理以及最高层次所需的财务洞察力。",
      "zh-Hant": "建立領導力——高管決策、團隊建設、組織管理以及最高層次所需的財務洞察力。",
      ja: "リーダーシップ能力を構築する — エグゼクティブの意思決定、チームビルディング、組織管理、最高レベルで必要な財務的洞察力。",
      ko: "리더십 역량 구축 — 경영진 의사결정, 팀 빌딩, 조직 관리 및 최고 수준에서 요구되는 재무 통찰력.",
      vi: "Xây dựng năng lực lãnh đạo — ra quyết định điều hành, xây dựng đội nhóm, quản lý tổ chức và khả năng nhạy bén về tài chính cần thiết ở các cấp cao nhất.",
      id: "Bangun kompetensi kepemimpinan — pengambilan keputusan eksekutif, pembangunan tim, manajemen organisasi, dan kecerdasan finansial yang diperlukan di tingkat tertinggi.",
      sw: "Jenga uwezo wa uongozi — maamuzi ya watendaji, ujenzi wa timu, usimamizi wa shirika na akili ya kifedha inayohitajika katika viwango vya juu.",
    },
    category: {
      en: "Leadership & Executive Management",
      es: "Liderazgo y gestión ejecutiva",
      fr: "Leadership et gestion de direction",
      pt: "Liderança e gestão executiva",
      de: "Führung und Unternehmensmanagement",
      it: "Leadership e gestione esecutiva",
      nl: "Leiderschap en uitvoerend management",
      pl: "Przywództwo i zarządzanie wykonawcze",
      ru: "Лидерство и исполнительное управление",
      ar: "القيادة والإدارة التنفيذية",
      hi: "नेतृत्व और कार्यकारी प्रबंधन",
      "zh-Hans": "领导力与高管管理",
      "zh-Hant": "領導力與高管管理",
      ja: "リーダーシップと経営管理",
      ko: "리더십 및 경영 관리",
      vi: "Lãnh đạo và quản lý điều hành",
      id: "Kepemimpinan & Manajemen Eksekutif",
      sw: "Uongozi na Usimamizi wa Watendaji",
    },
    subtitle: {
      en: "Leadership and executive management: decision-making, teams, and organizational financial acumen.",
      es: "Liderazgo y gestión ejecutiva: toma de decisiones, equipos y criterio financiero organizacional.",
      fr: "Leadership et gestion de direction : prise de décision, équipes et sens financier organisationnel.",
      pt: "Liderança e gestão executiva: tomada de decisões, equipes e senso financeiro organizacional.",
      de: "Führung und Unternehmensmanagement: Entscheidungsfindung, Teams und organisatorischer Finanzsinn.",
      it: "Leadership e gestione esecutiva: decision-making, team e acume finanziario organizzativo.",
      nl: "Leiderschap en uitvoerend management: besluitvorming, teams en organisatorisch financieel inzicht.",
      pl: "Przywództwo i zarządzanie wykonawcze: podejmowanie decyzji, zespoły i organizacyjna wiedza finansowa.",
      ru: "Лидерство и исполнительное управление: принятие решений, команды и организационная финансовая проницательность.",
      ar: "القيادة والإدارة التنفيذية: صنع القرار والفرق والفطنة المالية التنظيمية.",
      hi: "नेतृत्व और कार्यकारी प्रबंधन: निर्णय लेना, टीमें और संगठनात्मक वित्तीय कुशाग्रता।",
      "zh-Hans": "领导力与高管管理：决策、团队和组织财务洞察力。",
      "zh-Hant": "領導力與高管管理：決策、團隊和組織財務洞察力。",
      ja: "リーダーシップと経営管理：意思決定、チーム、組織の財務的洞察力。",
      ko: "리더십 및 경영 관리: 의사결정, 팀 및 조직적 재무 통찰력.",
      vi: "Lãnh đạo và quản lý điều hành: ra quyết định, đội nhóm và khả năng nhạy bén tài chính của tổ chức.",
      id: "Kepemimpinan dan manajemen eksekutif: pengambilan keputusan, tim, dan kecerdasan finansial organisasi.",
      sw: "Uongozi na usimamizi wa watendaji: kufanya maamuzi, timu na akili ya fedha ya shirika.",
    },
  },
};

const LESSON_TITLE_COPY: Partial<Record<string, Partial<Record<string, string>>>> = {
  "RED-L1-001": { en: "Understanding Real Estate as an Asset Class", es: "Comprender los bienes raíces como clase de activo" },
  "RED-L1-002": { en: "Types of Real Estate — Residential, Commercial, and Land", es: "Tipos de bienes raíces: residencial, comercial y terreno" },
  "RED-L1-003": { en: "How Real Estate Generates Income", es: "Cómo los bienes raíces generan ingresos" },
  "RED-L1-004": { en: "The Real Estate Market Cycle", es: "El ciclo del mercado inmobiliario" },
  "RED-L1-005": { en: "Key Real Estate Financial Metrics", es: "Métricas financieras clave de bienes raíces" },
  "RED-L1-006": { en: "Understanding Property Values and Appraisals", es: "Comprender el valor de las propiedades y las tasaciones" },
  "RED-L1-007": { en: "Financing Real Estate — Mortgages, Loans, and Leverage", es: "Financiamiento inmobiliario: hipotecas, préstamos y apalancamiento" },
  "RED-L1-008": { en: "Cash Flow Analysis for Rental Properties", es: "Análisis de flujo de efectivo para propiedades de alquiler" },
  "RED-L1-009": { en: "Real Estate Risk and Due Diligence", es: "Riesgo inmobiliario y debida diligencia" },
  "RED-L1-010": { en: "Building Your Real Estate Investment Strategy", es: "Construir tu estrategia de inversión inmobiliaria" },
  "RED-L1-011": { en: "Financing Your First Investment Property", es: "Financiar tu primera propiedad de inversión" },
  "RED-L1-012": { en: "Evaluating Real Estate Markets", es: "Evaluar mercados inmobiliarios" },
  "RED-L1-013": { en: "Due Diligence — What to Inspect Before You Buy", es: "Debida diligencia: qué inspeccionar antes de comprar" },
  "RED-L1-014": { en: "Cash Flow Analysis and the 1% Rule", es: "Análisis de flujo de efectivo y la regla del 1 %" },
  "RED-L1-015": { en: "Property Management Fundamentals", es: "Fundamentos de la administración de propiedades" },
  "RED-L1-016": { en: "Real Estate Investment Entities and Structures", es: "Entidades y estructuras para invertir en bienes raíces" },
  "RED-L1-017": { en: "Depreciation and Tax Benefits of Real Estate", es: "Depreciación y beneficios fiscales de los bienes raíces" },
  "RED-L1-018": { en: "Short-Term Rentals vs. Long-Term Rentals", es: "Alquileres a corto plazo vs. alquileres a largo plazo" },
  "RED-L1-019": { en: "Wholesaling and Fix-and-Flip Strategies", es: "Estrategias de wholesaling y fix-and-flip" },
  "RED-L1-020": { en: "Syndications and Real Estate Partnerships", es: "Sindicación y alianzas inmobiliarias" },
  "RED-L1-021": { en: "Commercial Real Estate Fundamentals", es: "Fundamentos de los bienes raíces comerciales" },
  "RED-L1-022": { en: "Real Estate Risk Management", es: "Gestión del riesgo inmobiliario" },
  "RED-L1-023": { en: "Building a Real Estate Portfolio", es: "Construir una cartera inmobiliaria" },
  "RED-L1-024": { en: "Real Estate in Your Retirement Strategy", es: "Los bienes raíces en tu estrategia de jubilación" },
  "RED-L1-025": { en: "From First Property to Financial Independence", es: "De la primera propiedad a la independencia financiera" },
  "WHITE-L1-001": { en: "Understanding Paper Assets as an Asset Class", es: "Comprender los activos financieros como clase de activo" },
  "WHITE-L1-002": { en: "Stocks — Ownership, Price, and Return", es: "Acciones: propiedad, precio y rendimiento" },
  "WHITE-L1-003": { en: "Bonds — Fixed Income and Lending Returns", es: "Bonos: renta fija y rendimientos por préstamo" },
  "WHITE-L1-004": { en: "Funds — ETFs, Index Funds, and Mutual Funds", es: "Fondos: ETF, fondos indexados y fondos mutuos" },
  "WHITE-L1-005": { en: "Tax-Advantaged Accounts — 401(k), IRA, and Roth IRA", es: "Cuentas con ventajas fiscales: 401(k), IRA y Roth IRA" },
  "WHITE-L1-006": { en: "Asset Allocation and Portfolio Construction", es: "Asignación de activos y construcción de cartera" },
  "WHITE-L1-007": { en: "How the Stock Market Works — Exchanges, Orders, and Market Mechanics", es: "Cómo funciona el mercado bursátil: bolsas, órdenes y mecánica del mercado" },
  "WHITE-L1-008": { en: "Reading Financial Statements for Investors", es: "Leer estados financieros para inversionistas" },
  "WHITE-L1-009": { en: "Investment Risk — Types, Measurement, and Management", es: "Riesgo de inversión: tipos, medición y gestión" },
  "WHITE-L1-010": { en: "Building Your Paper Asset Investment Strategy", es: "Construir tu estrategia de inversión en activos financieros" },
  "WHITE-L1-011": { en: "Introduction to Options Contracts", es: "Introducción a los contratos de opciones" },
  "WHITE-L1-012": { en: "Understanding Exchange-Traded Funds", es: "Comprender los fondos cotizados en bolsa" },
  "WHITE-L1-013": { en: "Reading Financial Statements", es: "Leer estados financieros" },
  "WHITE-L1-014": { en: "Evaluating Stocks — Fundamental Analysis", es: "Evaluar acciones: análisis fundamental" },
  "WHITE-L1-015": { en: "Bonds — How They Work and Why They Matter", es: "Bonos: cómo funcionan y por qué importan" },
  "WHITE-L1-016": { en: "Dividend Investing Strategies", es: "Estrategias de inversión en dividendos" },
  "WHITE-L1-017": { en: "Retirement Accounts — 401(k), IRA, and Roth Strategies", es: "Cuentas de retiro: estrategias 401(k), IRA y Roth" },
  "WHITE-L1-018": { en: "Dollar-Cost Averaging and Systematic Investing", es: "Promedio del costo en dólares e inversión sistemática" },
  "WHITE-L1-019": { en: "Understanding Market Cycles", es: "Comprender los ciclos del mercado" },
  "WHITE-L1-020": { en: "Portfolio Construction and Asset Allocation", es: "Construcción de cartera y asignación de activos" },
  "WHITE-L1-021": { en: "Tax-Efficient Investing", es: "Inversión fiscalmente eficiente" },
  "WHITE-L1-022": { en: "Alternative Investments — REITs, Commodities, and More", es: "Inversiones alternativas: REIT, materias primas y más" },
  "WHITE-L1-023": { en: "Behavioral Finance — Why Investors Make Bad Decisions", es: "Finanzas conductuales: por qué los inversionistas toman malas decisiones" },
  "WHITE-L1-024": { en: "Building Wealth Through Compounding", es: "Construir patrimonio mediante el interés compuesto" },
  "WHITE-L1-025": { en: "From First Investment to Financial Independence", es: "De la primera inversión a la independencia financiera" },
  "BLUE-L1-001": { en: "Understanding Business as an Asset Class", es: "Comprender el negocio como clase de activo" },
  "BLUE-L1-002": { en: "Business Models — How Businesses Generate Revenue", es: "Modelos de negocio: cómo los negocios generan ingresos" },
  "BLUE-L1-003": { en: "Cash Flow in Business — Reading the Numbers", es: "Flujo de efectivo en los negocios: leer los números" },
  "BLUE-L1-004": { en: "Profit Margins — Revenue, Costs, and What's Left", es: "Márgenes de ganancia: ingresos, costos y lo que queda" },
  "BLUE-L1-005": { en: "Key Performance Indicators — Measuring What Matters", es: "Indicadores clave de desempeño: medir lo que importa" },
  "BLUE-L1-006": { en: "Pricing Strategy — Setting Prices for Profit", es: "Estrategia de precios: fijar precios para obtener ganancias" },
  "BLUE-L1-007": { en: "Customer Acquisition — The Economics of Growth", es: "Adquisición de clientes: la economía del crecimiento" },
  "BLUE-L1-008": { en: "Operations — Systems, Processes, and Efficiency", es: "Operaciones: sistemas, procesos y eficiencia" },
  "BLUE-L1-009": { en: "Business Risk and Financial Resilience", es: "Riesgo empresarial y resiliencia financiera" },
  "BLUE-L1-010": { en: "Building Your Business Competency Foundation", es: "Construir tu base de competencia empresarial" },
  "BLUE-L1-011": { en: "Business Structures and Entity Formation", es: "Estructuras empresariales y formación de entidades" },
  "BLUE-L1-012": { en: "Reading a Business's Financial Health", es: "Leer la salud financiera de un negocio" },
  "BLUE-L1-013": { en: "Pricing Strategy and Profit Margins", es: "Estrategia de precios y márgenes de ganancia" },
  "BLUE-L1-014": { en: "Customer Acquisition and the Revenue Engine", es: "Adquisición de clientes y motor de ingresos" },
  "BLUE-L1-015": { en: "Business Cash Flow Management", es: "Gestión del flujo de efectivo empresarial" },
  "BLUE-L1-016": { en: "Operations and Systems Thinking", es: "Operaciones y pensamiento sistémico" },
  "BLUE-L1-017": { en: "Hiring, Compensation, and Building a Team", es: "Contratación, compensación y construcción de equipo" },
  "BLUE-L1-018": { en: "Business Credit and Commercial Financing", es: "Crédito empresarial y financiamiento comercial" },
  "BLUE-L1-019": { en: "Scaling a Business — Growth Levers and Capital Allocation", es: "Escalar un negocio: palancas de crecimiento y asignación de capital" },
  "BLUE-L1-020": { en: "Intellectual Property for Business Owners", es: "Propiedad intelectual para dueños de negocios" },
  "BLUE-L1-021": { en: "Exit Strategies — How Business Owners Create Liquidity", es: "Estrategias de salida: cómo los dueños de negocios crean liquidez" },
  "BLUE-L1-022": { en: "Franchising — Buying and Building", es: "Franquicias: comprar y construir" },
  "BLUE-L1-023": { en: "E-Commerce and Digital Business Models", es: "Comercio electrónico y modelos de negocio digitales" },
  "BLUE-L1-024": { en: "Business Insurance and Risk Management", es: "Seguros empresariales y gestión de riesgos" },
  "BLUE-L1-025": { en: "From First Business to Financial Independence", es: "Del primer negocio a la independencia financiera" },
};

/**
 * Returns true when the resolved locale maps to English (base code "en").
 * Handles both "en" and "en-US" (the canonical LANGUAGE_CATALOG English code).
 */
export function isEnglishLocale(locale: CurriculumLocale): boolean {
  return locale === "en" || locale.startsWith("en-");
}

export function getLocalizedTrackCopy(trackCode: string, locale: CurriculumLocale) {
  const copy = TRACK_COPY[trackCode.toUpperCase() as LaunchTrackCode];
  if (!copy) return null;
  return {
    name: resolveLocalizedValue(copy.name, locale),
    description: resolveLocalizedValue(copy.description, locale),
    category: resolveLocalizedValue(copy.category, locale),
    subtitle: resolveLocalizedValue(copy.subtitle, locale),
  };
}

export function getLocalizedLessonTitle(lessonId: string, locale: CurriculumLocale, fallbackTitle: string) {
  const entry = LESSON_TITLE_COPY[lessonId];
  if (!entry) return fallbackTitle;
  return resolveLocalizedValue({ en: fallbackTitle, ...entry }, locale);
}

/**
 * Translations for lesson descriptions, keyed by stable lesson ID.
 * "en" is derived from the canonical registry metadata at runtime (fallbackDescription).
 * Add translated entries here as translations become available.
 */
const LESSON_DESCRIPTION_COPY: Record<string, Partial<Record<string, string>>> = {};

/**
 * Resolve a lesson description for the given locale.
 * Falls back through: exact locale → base language → English (fallbackDescription).
 * Never returns blank when a canonical English description exists.
 */
export function getLocalizedLessonDescription(
  lessonId: string,
  locale: CurriculumLocale,
  fallbackDescription: string,
): string {
  const entry = LESSON_DESCRIPTION_COPY[lessonId];
  if (!entry) return fallbackDescription;
  return resolveLocalizedValue({ en: fallbackDescription, ...entry }, locale);
}
