import { CountryConfiguration } from "@/types/country-config";

export const countries: CountryConfiguration[] = [

  // ── North America ──────────────────────────────────────────────────────────

  {
    isoCode: "US",
    country: "United States",
    continent: "North America",
    enabled: true,
    status: "live",
    membershipEnabled: true,
    marketplaceEnabled: true,
    paymentsEnabled: true,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: true,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "USD",
    language: "English",
  },

  {
    isoCode: "CA",
    country: "Canada",
    continent: "North America",
    enabled: true,
    status: "development",
    membershipEnabled: true,
    marketplaceEnabled: true,
    paymentsEnabled: true,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: true,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "CAD",
    language: "English",
  },

  // ── Caribbean ──────────────────────────────────────────────────────────────

  {
    isoCode: "CU",
    country: "Cuba",
    continent: "Caribbean",
    enabled: false,
    status: "disabled",
    membershipEnabled: false,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: false,
    assessmentsEnabled: false,
    hiringEnabled: false,
    aiEnabled: false,
    operatingEntity: "",
    currency: "CUP",
    language: "Spanish",
  },

  // ── Africa Phase One ───────────────────────────────────────────────────────

  {
    isoCode: "UG",
    country: "Uganda",
    continent: "Africa",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: true,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: true,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "UGX",
    language: "English",
  },

  {
    isoCode: "NG",
    country: "Nigeria",
    continent: "Africa",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: true,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: true,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "NGN",
    language: "English",
  },

  {
    isoCode: "KE",
    country: "Kenya",
    continent: "Africa",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: true,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: true,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "KES",
    language: "English",
  },

  {
    isoCode: "TZ",
    country: "Tanzania",
    continent: "Africa",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "TZS",
    language: "English",
  },

  {
    isoCode: "GH",
    country: "Ghana",
    continent: "Africa",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "GHS",
    language: "English",
  },

  {
    isoCode: "ZA",
    country: "South Africa",
    continent: "Africa",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: true,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: true,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "ZAR",
    language: "English",
  },

  {
    isoCode: "RW",
    country: "Rwanda",
    continent: "Africa",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "RWF",
    language: "English",
  },

  // ── Asia ───────────────────────────────────────────────────────────────────

  {
    isoCode: "JP",
    country: "Japan",
    continent: "Asia",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: true,
    paymentsEnabled: true,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "JPY",
    language: "Japanese",
  },

  {
    isoCode: "KR",
    country: "South Korea",
    continent: "Asia",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: true,
    paymentsEnabled: true,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "KRW",
    language: "Korean",
  },

  {
    isoCode: "PH",
    country: "Philippines",
    continent: "Asia",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "PHP",
    language: "Filipino",
  },

  {
    isoCode: "VN",
    country: "Vietnam",
    continent: "Asia",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "VND",
    language: "Vietnamese",
  },

  {
    isoCode: "MY",
    country: "Malaysia",
    continent: "Asia",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "MYR",
    language: "Malay",
  },

  {
    isoCode: "SG",
    country: "Singapore",
    continent: "Asia",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: true,
    paymentsEnabled: true,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "SGD",
    language: "English",
  },

  {
    isoCode: "TH",
    country: "Thailand",
    continent: "Asia",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "THB",
    language: "Thai",
  },

  {
    isoCode: "ID",
    country: "Indonesia",
    continent: "Asia",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "IDR",
    language: "Indonesian",
  },

  {
    isoCode: "IN",
    country: "India",
    continent: "Asia",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: true,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "INR",
    language: "Hindi",
  },

  {
    isoCode: "PK",
    country: "Pakistan",
    continent: "Asia",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "PKR",
    language: "Urdu",
  },

  {
    isoCode: "BD",
    country: "Bangladesh",
    continent: "Asia",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "BDT",
    language: "Bengali",
  },

  {
    isoCode: "LK",
    country: "Sri Lanka",
    continent: "Asia",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "LKR",
    language: "Tamil",
  },

  {
    isoCode: "CN",
    country: "China",
    continent: "Asia",
    enabled: false,
    status: "disabled",
    membershipEnabled: false,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: false,
    assessmentsEnabled: false,
    hiringEnabled: false,
    aiEnabled: false,
    operatingEntity: "",
    currency: "CNY",
    language: "Chinese (Simplified)",
  },

  // ── Middle East ────────────────────────────────────────────────────────────

  {
    isoCode: "SA",
    country: "Saudi Arabia",
    continent: "Middle East",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "SAR",
    language: "Arabic",
  },

  {
    isoCode: "AE",
    country: "United Arab Emirates",
    continent: "Middle East",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "AED",
    language: "Arabic",
  },

  {
    isoCode: "QA",
    country: "Qatar",
    continent: "Middle East",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "QAR",
    language: "Arabic",
  },

  {
    isoCode: "KW",
    country: "Kuwait",
    continent: "Middle East",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "KWD",
    language: "Arabic",
  },

  {
    isoCode: "BH",
    country: "Bahrain",
    continent: "Middle East",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "BHD",
    language: "Arabic",
  },

  {
    isoCode: "OM",
    country: "Oman",
    continent: "Middle East",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "OMR",
    language: "Arabic",
  },

  {
    isoCode: "JO",
    country: "Jordan",
    continent: "Middle East",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "JOD",
    language: "Arabic",
  },

  {
    isoCode: "IL",
    country: "Israel",
    continent: "Middle East",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "ILS",
    language: "Hebrew",
  },

  {
    isoCode: "LB",
    country: "Lebanon",
    continent: "Middle East",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "LBP",
    language: "Arabic",
  },

  {
    isoCode: "IQ",
    country: "Iraq",
    continent: "Middle East",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "IQD",
    language: "Arabic",
  },

  {
    isoCode: "IR",
    country: "Iran",
    continent: "Middle East",
    enabled: false,
    status: "disabled",
    membershipEnabled: false,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: false,
    assessmentsEnabled: false,
    hiringEnabled: false,
    aiEnabled: false,
    operatingEntity: "",
    currency: "IRR",
    language: "Farsi",
  },

  {
    isoCode: "AF",
    country: "Afghanistan",
    continent: "Middle East",
    enabled: false,
    status: "disabled",
    membershipEnabled: false,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: false,
    assessmentsEnabled: false,
    hiringEnabled: false,
    aiEnabled: false,
    operatingEntity: "",
    currency: "AFN",
    language: "Dari",
  },

  // ── Eastern Europe ─────────────────────────────────────────────────────────

  {
    isoCode: "PL",
    country: "Poland",
    continent: "Europe",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "PLN",
    language: "Polish",
  },

  {
    isoCode: "CZ",
    country: "Czech Republic",
    continent: "Europe",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "CZK",
    language: "Czech",
  },

  {
    isoCode: "SK",
    country: "Slovakia",
    continent: "Europe",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "EUR",
    language: "Slovak",
  },

  {
    isoCode: "RO",
    country: "Romania",
    continent: "Europe",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "RON",
    language: "Romanian",
  },

  {
    isoCode: "BG",
    country: "Bulgaria",
    continent: "Europe",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "BGN",
    language: "Bulgarian",
  },

  {
    isoCode: "LT",
    country: "Lithuania",
    continent: "Europe",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "EUR",
    language: "Lithuanian",
  },

  {
    isoCode: "LV",
    country: "Latvia",
    continent: "Europe",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "EUR",
    language: "Latvian",
  },

  {
    isoCode: "EE",
    country: "Estonia",
    continent: "Europe",
    enabled: true,
    status: "planning",
    membershipEnabled: true,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: true,
    assessmentsEnabled: true,
    hiringEnabled: false,
    aiEnabled: true,
    operatingEntity: "Edge Financial USA",
    currency: "EUR",
    language: "Estonian",
  },

  {
    isoCode: "RU",
    country: "Russia",
    continent: "Europe",
    enabled: false,
    status: "disabled",
    membershipEnabled: false,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: false,
    assessmentsEnabled: false,
    hiringEnabled: false,
    aiEnabled: false,
    operatingEntity: "",
    currency: "RUB",
    language: "Russian",
  },

  {
    isoCode: "BY",
    country: "Belarus",
    continent: "Europe",
    enabled: false,
    status: "disabled",
    membershipEnabled: false,
    marketplaceEnabled: false,
    paymentsEnabled: false,
    coursesEnabled: false,
    assessmentsEnabled: false,
    hiringEnabled: false,
    aiEnabled: false,
    operatingEntity: "",
    currency: "BYN",
    language: "Belarusian",
  },

];

// ── Utility helpers ──────────────────────────────────────────────────────────

export function getCountry(isoCode: string): CountryConfiguration | undefined {
  return countries.find((c) => c.isoCode.toUpperCase() === isoCode.toUpperCase());
}

export function isCountryInstalled(isoCode: string): boolean {
  return Boolean(getCountry(isoCode));
}

export function isCountryEnabled(isoCode: string): boolean {
  return getCountry(isoCode)?.enabled === true;
}

export function getEnabledCountries(): CountryConfiguration[] {
  return countries.filter((c) => c.enabled);
}

export function getDisabledCountries(): CountryConfiguration[] {
  return countries.filter((c) => !c.enabled);
}
