/**
 * Country Activation Registry
 *
 * Defines the canonical activation model for every country in the Edunancial
 * global platform. Language choice remains independent from country activation.
 *
 * Fields:
 *   enabled              – site is accessible from this country
 *   beta                 – accessible to beta users only (requires enabled:true)
 *   publicLaunch         – fully launched to the public
 *   marketingEnabled     – marketing pages/campaigns targeting this country
 *   registrationEnabled  – new user registration allowed
 *   paymentsEnabled      – payment processing allowed
 *   marketplaceEnabled   – marketplace features available
 *   aiFeaturesEnabled    – AI-powered features available
 *   complianceReviewRequired – legal/compliance team must review before enabling
 *   sanctionsRestricted  – country is subject to international trade sanctions
 */

export type PrivacyProfile =
  | "gdpr"
  | "ccpa"
  | "pipeda"
  | "pdpa"
  | "pdp-india"
  | "pdp-brazil"
  | "pdp-africa"
  | "pdp-mena"
  | "minimal"
  | "restricted";

export type TaxProfile =
  | "vat-eu"
  | "vat-mena"
  | "vat-africa"
  | "vat-apac"
  | "gst-apac"
  | "gst-au"
  | "gst-nz"
  | "gst-in"
  | "gst-sg"
  | "gst-my"
  | "sales-tax-us"
  | "sales-tax-ca"
  | "none"
  | "placeholder";

export type LegalNoticeProfile =
  | "us-standard"
  | "canada-pipeda"
  | "eu-gdpr"
  | "uk-uk-gdpr"
  | "apac-standard"
  | "mena-standard"
  | "africa-standard"
  | "restricted";

export type PaymentProviderRef =
  | "square"
  | "stripe"
  | "paypal"
  | "flutterwave"
  | "paystack"
  | "mobile-money"
  | "local-eu-methods"
  | "local-apac-methods"
  | "local-latam-gateway";

export interface CountryAgeRestrictions {
  minimumAge: number;
  requiresParentalConsent: boolean;
  consentAge?: number;
}

export interface CountryActivationRecord {
  isoCode: string;
  name: string;
  region: string;

  // Activation flags
  enabled: boolean;
  beta: boolean;
  publicLaunch: boolean;
  marketingEnabled: boolean;
  registrationEnabled: boolean;
  paymentsEnabled: boolean;
  marketplaceEnabled: boolean;
  aiFeaturesEnabled: boolean;

  // Language & locale
  supportedLanguages: string[];
  defaultLanguage: string;

  // Currency & payments
  supportedCurrencies: string[];
  defaultCurrency: string;
  paymentProviders: PaymentProviderRef[];

  // Compliance
  complianceReviewRequired: boolean;
  sanctionsRestricted: boolean;
  privacyProfile: PrivacyProfile;
  taxProfile: TaxProfile;
  legalNoticeProfile: LegalNoticeProfile;

  // Access rules
  ageRestrictions: CountryAgeRestrictions;

  // Feature flags (country-level overrides)
  featureFlags: {
    hreflangEnabled: boolean;
    sitemapIncluded: boolean;
    betaAccessGate: boolean;
    paymentGate: boolean;
    registrationGate: boolean;
  };
}

const DEFAULT_AGE_RESTRICTIONS: CountryAgeRestrictions = {
  minimumAge: 18,
  requiresParentalConsent: false,
};

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export const COUNTRY_ACTIVATION_REGISTRY: readonly CountryActivationRecord[] = [

  // =========================================================================
  // NORTH AMERICA
  // =========================================================================
  {
    isoCode: "US",
    name: "United States",
    region: "north-america",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: true,
    aiFeaturesEnabled: true,
    supportedLanguages: ["en", "es"],
    defaultLanguage: "en",
    supportedCurrencies: ["USD"],
    defaultCurrency: "USD",
    paymentProviders: ["square", "stripe", "paypal"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "ccpa",
    taxProfile: "sales-tax-us",
    legalNoticeProfile: "us-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "CA",
    name: "Canada",
    region: "north-america",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: true,
    aiFeaturesEnabled: true,
    supportedLanguages: ["en", "fr", "fr-CA"],
    defaultLanguage: "en",
    supportedCurrencies: ["CAD", "USD"],
    defaultCurrency: "CAD",
    paymentProviders: ["stripe", "paypal"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pipeda",
    taxProfile: "sales-tax-ca",
    legalNoticeProfile: "canada-pipeda",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },

  // =========================================================================
  // ASIA-PACIFIC
  // =========================================================================
  {
    isoCode: "JP",
    name: "Japan",
    region: "asia-pacific",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: true,
    aiFeaturesEnabled: true,
    supportedLanguages: ["ja", "en"],
    defaultLanguage: "ja",
    supportedCurrencies: ["JPY", "USD"],
    defaultCurrency: "JPY",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "vat-apac",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "KR",
    name: "South Korea",
    region: "asia-pacific",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: true,
    aiFeaturesEnabled: true,
    supportedLanguages: ["ko", "en"],
    defaultLanguage: "ko",
    supportedCurrencies: ["KRW", "USD"],
    defaultCurrency: "KRW",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "vat-apac",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "CN",
    name: "China (Mainland)",
    region: "asia-pacific",
    enabled: false,
    beta: false,
    publicLaunch: false,
    marketingEnabled: false,
    registrationEnabled: false,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["zh-Hans"],
    defaultLanguage: "zh-Hans",
    supportedCurrencies: ["CNY"],
    defaultCurrency: "CNY",
    paymentProviders: [],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "restricted",
    taxProfile: "vat-apac",
    legalNoticeProfile: "restricted",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: false,
      sitemapIncluded: false,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: true,
    },
  },
  {
    isoCode: "TW",
    name: "Taiwan",
    region: "asia-pacific",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: true,
    aiFeaturesEnabled: true,
    supportedLanguages: ["zh-Hant", "yue-Hant", "en"],
    defaultLanguage: "zh-Hant",
    supportedCurrencies: ["TWD", "USD"],
    defaultCurrency: "TWD",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "vat-apac",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "HK",
    name: "Hong Kong",
    region: "asia-pacific",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: true,
    aiFeaturesEnabled: true,
    supportedLanguages: ["zh-Hant", "yue-Hant", "en"],
    defaultLanguage: "zh-Hant",
    supportedCurrencies: ["HKD", "USD"],
    defaultCurrency: "HKD",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "none",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "SG",
    name: "Singapore",
    region: "asia-pacific",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: true,
    aiFeaturesEnabled: true,
    supportedLanguages: ["en", "zh-Hans", "ms", "ta"],
    defaultLanguage: "en",
    supportedCurrencies: ["SGD", "USD"],
    defaultCurrency: "SGD",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "gst-sg",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "PH",
    name: "Philippines",
    region: "asia-pacific",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: true,
    aiFeaturesEnabled: true,
    supportedLanguages: ["en", "fil"],
    defaultLanguage: "en",
    supportedCurrencies: ["PHP", "USD"],
    defaultCurrency: "PHP",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "vat-apac",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "VN",
    name: "Vietnam",
    region: "asia-pacific",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["vi", "en"],
    defaultLanguage: "vi",
    supportedCurrencies: ["VND", "USD"],
    defaultCurrency: "VND",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "vat-apac",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "MY",
    name: "Malaysia",
    region: "asia-pacific",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: true,
    aiFeaturesEnabled: false,
    supportedLanguages: ["en", "ms"],
    defaultLanguage: "en",
    supportedCurrencies: ["MYR", "USD"],
    defaultCurrency: "MYR",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "gst-my",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "TH",
    name: "Thailand",
    region: "asia-pacific",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["th", "en"],
    defaultLanguage: "th",
    supportedCurrencies: ["THB", "USD"],
    defaultCurrency: "THB",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "vat-apac",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "ID",
    name: "Indonesia",
    region: "asia-pacific",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["id", "en"],
    defaultLanguage: "id",
    supportedCurrencies: ["IDR", "USD"],
    defaultCurrency: "IDR",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "vat-apac",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "IN",
    name: "India",
    region: "asia-pacific",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: true,
    aiFeaturesEnabled: true,
    supportedLanguages: ["hi", "en", "bn", "ta"],
    defaultLanguage: "en",
    supportedCurrencies: ["INR", "USD"],
    defaultCurrency: "INR",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdp-india",
    taxProfile: "gst-in",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "PK",
    name: "Pakistan",
    region: "asia-pacific",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ur", "en"],
    defaultLanguage: "ur",
    supportedCurrencies: ["PKR", "USD"],
    defaultCurrency: "PKR",
    paymentProviders: ["stripe"],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "vat-apac",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: false,
    },
  },
  {
    isoCode: "BD",
    name: "Bangladesh",
    region: "asia-pacific",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["bn", "en"],
    defaultLanguage: "bn",
    supportedCurrencies: ["BDT", "USD"],
    defaultCurrency: "BDT",
    paymentProviders: ["stripe"],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "vat-apac",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: false,
    },
  },
  {
    isoCode: "LK",
    name: "Sri Lanka",
    region: "asia-pacific",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["en", "ta"],
    defaultLanguage: "en",
    supportedCurrencies: ["LKR", "USD"],
    defaultCurrency: "LKR",
    paymentProviders: ["stripe"],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "vat-apac",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: false,
    },
  },
  {
    isoCode: "AU",
    name: "Australia",
    region: "asia-pacific",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: true,
    aiFeaturesEnabled: true,
    supportedLanguages: ["en"],
    defaultLanguage: "en",
    supportedCurrencies: ["AUD", "USD"],
    defaultCurrency: "AUD",
    paymentProviders: ["stripe"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "gst-au",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "NZ",
    name: "New Zealand",
    region: "asia-pacific",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: true,
    supportedLanguages: ["en"],
    defaultLanguage: "en",
    supportedCurrencies: ["NZD", "USD"],
    defaultCurrency: "NZD",
    paymentProviders: ["stripe"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdpa",
    taxProfile: "gst-nz",
    legalNoticeProfile: "apac-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },

  // =========================================================================
  // MIDDLE EAST
  // =========================================================================
  {
    isoCode: "SA",
    name: "Saudi Arabia",
    region: "middle-east",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ar", "en"],
    defaultLanguage: "ar",
    supportedCurrencies: ["SAR", "USD"],
    defaultCurrency: "SAR",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "pdp-mena",
    taxProfile: "vat-mena",
    legalNoticeProfile: "mena-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "AE",
    name: "United Arab Emirates",
    region: "middle-east",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ar", "en"],
    defaultLanguage: "ar",
    supportedCurrencies: ["AED", "USD"],
    defaultCurrency: "AED",
    paymentProviders: ["stripe", "local-apac-methods"],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "pdp-mena",
    taxProfile: "vat-mena",
    legalNoticeProfile: "mena-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "QA",
    name: "Qatar",
    region: "middle-east",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ar", "en"],
    defaultLanguage: "ar",
    supportedCurrencies: ["QAR", "USD"],
    defaultCurrency: "QAR",
    paymentProviders: ["stripe"],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "pdp-mena",
    taxProfile: "vat-mena",
    legalNoticeProfile: "mena-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "KW",
    name: "Kuwait",
    region: "middle-east",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ar", "en"],
    defaultLanguage: "ar",
    supportedCurrencies: ["KWD", "USD"],
    defaultCurrency: "KWD",
    paymentProviders: ["stripe"],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "pdp-mena",
    taxProfile: "vat-mena",
    legalNoticeProfile: "mena-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "BH",
    name: "Bahrain",
    region: "middle-east",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ar", "en"],
    defaultLanguage: "ar",
    supportedCurrencies: ["BHD", "USD"],
    defaultCurrency: "BHD",
    paymentProviders: ["stripe"],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "pdp-mena",
    taxProfile: "vat-mena",
    legalNoticeProfile: "mena-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "OM",
    name: "Oman",
    region: "middle-east",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ar", "en"],
    defaultLanguage: "ar",
    supportedCurrencies: ["OMR", "USD"],
    defaultCurrency: "OMR",
    paymentProviders: ["stripe"],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "pdp-mena",
    taxProfile: "vat-mena",
    legalNoticeProfile: "mena-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "JO",
    name: "Jordan",
    region: "middle-east",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ar", "en"],
    defaultLanguage: "ar",
    supportedCurrencies: ["JOD", "USD"],
    defaultCurrency: "JOD",
    paymentProviders: ["stripe"],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "pdp-mena",
    taxProfile: "vat-mena",
    legalNoticeProfile: "mena-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "IL",
    name: "Israel",
    region: "middle-east",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["he", "ar", "en"],
    defaultLanguage: "he",
    supportedCurrencies: ["ILS", "USD"],
    defaultCurrency: "ILS",
    paymentProviders: ["stripe"],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "gdpr",
    taxProfile: "vat-mena",
    legalNoticeProfile: "mena-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "IQ",
    name: "Iraq",
    region: "middle-east",
    enabled: false,
    beta: false,
    publicLaunch: false,
    marketingEnabled: false,
    registrationEnabled: false,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ar", "en"],
    defaultLanguage: "ar",
    supportedCurrencies: ["IQD", "USD"],
    defaultCurrency: "IQD",
    paymentProviders: [],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "pdp-mena",
    taxProfile: "placeholder",
    legalNoticeProfile: "mena-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: false,
      sitemapIncluded: false,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: true,
    },
  },
  {
    isoCode: "LB",
    name: "Lebanon",
    region: "middle-east",
    enabled: false,
    beta: false,
    publicLaunch: false,
    marketingEnabled: false,
    registrationEnabled: false,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ar", "fr", "en"],
    defaultLanguage: "ar",
    supportedCurrencies: ["LBP", "USD"],
    defaultCurrency: "USD",
    paymentProviders: [],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "pdp-mena",
    taxProfile: "placeholder",
    legalNoticeProfile: "mena-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: false,
      sitemapIncluded: false,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: true,
    },
  },
  {
    isoCode: "IR",
    name: "Iran",
    region: "middle-east",
    enabled: false,
    beta: false,
    publicLaunch: false,
    marketingEnabled: false,
    registrationEnabled: false,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["fa"],
    defaultLanguage: "fa",
    supportedCurrencies: ["IRR"],
    defaultCurrency: "IRR",
    paymentProviders: [],
    complianceReviewRequired: true,
    sanctionsRestricted: true,
    privacyProfile: "restricted",
    taxProfile: "placeholder",
    legalNoticeProfile: "restricted",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: false,
      sitemapIncluded: false,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: true,
    },
  },
  {
    isoCode: "AF",
    name: "Afghanistan",
    region: "middle-east",
    enabled: false,
    beta: false,
    publicLaunch: false,
    marketingEnabled: false,
    registrationEnabled: false,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ps", "fa"],
    defaultLanguage: "ps",
    supportedCurrencies: ["AFN"],
    defaultCurrency: "AFN",
    paymentProviders: [],
    complianceReviewRequired: true,
    sanctionsRestricted: false,
    privacyProfile: "restricted",
    taxProfile: "placeholder",
    legalNoticeProfile: "restricted",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: false,
      sitemapIncluded: false,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: true,
    },
  },

  // =========================================================================
  // EUROPE
  // =========================================================================
  {
    isoCode: "PL",
    name: "Poland",
    region: "europe",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["pl", "en"],
    defaultLanguage: "pl",
    supportedCurrencies: ["PLN", "EUR"],
    defaultCurrency: "PLN",
    paymentProviders: ["stripe", "paypal", "local-eu-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "gdpr",
    taxProfile: "vat-eu",
    legalNoticeProfile: "eu-gdpr",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "CZ",
    name: "Czech Republic",
    region: "europe",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["cs", "en"],
    defaultLanguage: "cs",
    supportedCurrencies: ["CZK", "EUR"],
    defaultCurrency: "CZK",
    paymentProviders: ["stripe", "paypal", "local-eu-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "gdpr",
    taxProfile: "vat-eu",
    legalNoticeProfile: "eu-gdpr",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "SK",
    name: "Slovakia",
    region: "europe",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["sk", "en"],
    defaultLanguage: "sk",
    supportedCurrencies: ["EUR"],
    defaultCurrency: "EUR",
    paymentProviders: ["stripe", "paypal", "local-eu-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "gdpr",
    taxProfile: "vat-eu",
    legalNoticeProfile: "eu-gdpr",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "RO",
    name: "Romania",
    region: "europe",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ro", "en"],
    defaultLanguage: "ro",
    supportedCurrencies: ["RON", "EUR"],
    defaultCurrency: "RON",
    paymentProviders: ["stripe", "paypal", "local-eu-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "gdpr",
    taxProfile: "vat-eu",
    legalNoticeProfile: "eu-gdpr",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "BG",
    name: "Bulgaria",
    region: "europe",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["bg", "en"],
    defaultLanguage: "bg",
    supportedCurrencies: ["BGN", "EUR"],
    defaultCurrency: "BGN",
    paymentProviders: ["stripe", "paypal", "local-eu-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "gdpr",
    taxProfile: "vat-eu",
    legalNoticeProfile: "eu-gdpr",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "LT",
    name: "Lithuania",
    region: "europe",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["lt", "en"],
    defaultLanguage: "lt",
    supportedCurrencies: ["EUR"],
    defaultCurrency: "EUR",
    paymentProviders: ["stripe", "paypal", "local-eu-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "gdpr",
    taxProfile: "vat-eu",
    legalNoticeProfile: "eu-gdpr",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "LV",
    name: "Latvia",
    region: "europe",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["lv", "en"],
    defaultLanguage: "lv",
    supportedCurrencies: ["EUR"],
    defaultCurrency: "EUR",
    paymentProviders: ["stripe", "paypal", "local-eu-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "gdpr",
    taxProfile: "vat-eu",
    legalNoticeProfile: "eu-gdpr",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "EE",
    name: "Estonia",
    region: "europe",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["et", "en"],
    defaultLanguage: "et",
    supportedCurrencies: ["EUR"],
    defaultCurrency: "EUR",
    paymentProviders: ["stripe", "paypal", "local-eu-methods"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "gdpr",
    taxProfile: "vat-eu",
    legalNoticeProfile: "eu-gdpr",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "RU",
    name: "Russia",
    region: "europe",
    enabled: false,
    beta: false,
    publicLaunch: false,
    marketingEnabled: false,
    registrationEnabled: false,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ru"],
    defaultLanguage: "ru",
    supportedCurrencies: ["RUB"],
    defaultCurrency: "RUB",
    paymentProviders: [],
    complianceReviewRequired: true,
    sanctionsRestricted: true,
    privacyProfile: "restricted",
    taxProfile: "placeholder",
    legalNoticeProfile: "restricted",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: false,
      sitemapIncluded: false,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: true,
    },
  },
  {
    isoCode: "BY",
    name: "Belarus",
    region: "europe",
    enabled: false,
    beta: false,
    publicLaunch: false,
    marketingEnabled: false,
    registrationEnabled: false,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["be", "ru"],
    defaultLanguage: "be",
    supportedCurrencies: ["BYN"],
    defaultCurrency: "BYN",
    paymentProviders: [],
    complianceReviewRequired: true,
    sanctionsRestricted: true,
    privacyProfile: "restricted",
    taxProfile: "placeholder",
    legalNoticeProfile: "restricted",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: false,
      sitemapIncluded: false,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: true,
    },
  },

  // =========================================================================
  // AFRICA PHASE ONE
  // =========================================================================
  {
    isoCode: "UG",
    name: "Uganda",
    region: "africa",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["en", "lg", "sw"],
    defaultLanguage: "en",
    supportedCurrencies: ["UGX", "USD"],
    defaultCurrency: "UGX",
    paymentProviders: ["mobile-money", "flutterwave"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdp-africa",
    taxProfile: "vat-africa",
    legalNoticeProfile: "africa-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: false,
    },
  },
  {
    isoCode: "NG",
    name: "Nigeria",
    region: "africa",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["en", "ha", "yo", "ig"],
    defaultLanguage: "en",
    supportedCurrencies: ["NGN", "USD"],
    defaultCurrency: "NGN",
    paymentProviders: ["paystack", "flutterwave", "stripe"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdp-africa",
    taxProfile: "vat-africa",
    legalNoticeProfile: "africa-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "KE",
    name: "Kenya",
    region: "africa",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["en", "sw"],
    defaultLanguage: "en",
    supportedCurrencies: ["KES", "USD"],
    defaultCurrency: "KES",
    paymentProviders: ["mobile-money", "flutterwave", "stripe"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdp-africa",
    taxProfile: "vat-africa",
    legalNoticeProfile: "africa-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "TZ",
    name: "Tanzania",
    region: "africa",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["sw", "en"],
    defaultLanguage: "sw",
    supportedCurrencies: ["TZS", "USD"],
    defaultCurrency: "TZS",
    paymentProviders: ["mobile-money", "flutterwave"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdp-africa",
    taxProfile: "vat-africa",
    legalNoticeProfile: "africa-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "GH",
    name: "Ghana",
    region: "africa",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["en"],
    defaultLanguage: "en",
    supportedCurrencies: ["GHS", "USD"],
    defaultCurrency: "GHS",
    paymentProviders: ["paystack", "flutterwave", "mobile-money"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdp-africa",
    taxProfile: "vat-africa",
    legalNoticeProfile: "africa-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "ZA",
    name: "South Africa",
    region: "africa",
    enabled: true,
    beta: false,
    publicLaunch: true,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: true,
    marketplaceEnabled: true,
    aiFeaturesEnabled: false,
    supportedLanguages: ["en"],
    defaultLanguage: "en",
    supportedCurrencies: ["ZAR", "USD"],
    defaultCurrency: "ZAR",
    paymentProviders: ["stripe", "paystack", "flutterwave"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdp-africa",
    taxProfile: "vat-africa",
    legalNoticeProfile: "africa-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: false,
      paymentGate: false,
      registrationGate: false,
    },
  },
  {
    isoCode: "RW",
    name: "Rwanda",
    region: "africa",
    enabled: true,
    beta: true,
    publicLaunch: false,
    marketingEnabled: true,
    registrationEnabled: true,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["en", "fr", "sw"],
    defaultLanguage: "en",
    supportedCurrencies: ["RWF", "USD"],
    defaultCurrency: "RWF",
    paymentProviders: ["mobile-money"],
    complianceReviewRequired: false,
    sanctionsRestricted: false,
    privacyProfile: "pdp-africa",
    taxProfile: "vat-africa",
    legalNoticeProfile: "africa-standard",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: true,
      sitemapIncluded: true,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: false,
    },
  },

  // =========================================================================
  // RESTRICTED / SANCTIONED (architecture-only, never enabled)
  // =========================================================================
  {
    isoCode: "KP",
    name: "North Korea",
    region: "asia-pacific",
    enabled: false,
    beta: false,
    publicLaunch: false,
    marketingEnabled: false,
    registrationEnabled: false,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ko"],
    defaultLanguage: "ko",
    supportedCurrencies: ["KPW"],
    defaultCurrency: "KPW",
    paymentProviders: [],
    complianceReviewRequired: true,
    sanctionsRestricted: true,
    privacyProfile: "restricted",
    taxProfile: "placeholder",
    legalNoticeProfile: "restricted",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: false,
      sitemapIncluded: false,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: true,
    },
  },
  {
    isoCode: "CU",
    name: "Cuba",
    region: "caribbean",
    enabled: false,
    beta: false,
    publicLaunch: false,
    marketingEnabled: false,
    registrationEnabled: false,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["es"],
    defaultLanguage: "es",
    supportedCurrencies: ["CUP"],
    defaultCurrency: "CUP",
    paymentProviders: [],
    complianceReviewRequired: true,
    sanctionsRestricted: true,
    privacyProfile: "restricted",
    taxProfile: "placeholder",
    legalNoticeProfile: "restricted",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: false,
      sitemapIncluded: false,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: true,
    },
  },
  {
    isoCode: "SY",
    name: "Syria",
    region: "middle-east",
    enabled: false,
    beta: false,
    publicLaunch: false,
    marketingEnabled: false,
    registrationEnabled: false,
    paymentsEnabled: false,
    marketplaceEnabled: false,
    aiFeaturesEnabled: false,
    supportedLanguages: ["ar"],
    defaultLanguage: "ar",
    supportedCurrencies: ["SYP"],
    defaultCurrency: "SYP",
    paymentProviders: [],
    complianceReviewRequired: true,
    sanctionsRestricted: true,
    privacyProfile: "restricted",
    taxProfile: "placeholder",
    legalNoticeProfile: "restricted",
    ageRestrictions: DEFAULT_AGE_RESTRICTIONS,
    featureFlags: {
      hreflangEnabled: false,
      sitemapIncluded: false,
      betaAccessGate: true,
      paymentGate: true,
      registrationGate: true,
    },
  },
];

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

export function getCountryActivation(
  isoCode: string
): CountryActivationRecord | undefined {
  return COUNTRY_ACTIVATION_REGISTRY.find(
    (c) => c.isoCode.toUpperCase() === isoCode.toUpperCase()
  );
}

export function isCountryEnabled(isoCode: string): boolean {
  return getCountryActivation(isoCode)?.enabled ?? false;
}

export function isCountryBeta(isoCode: string): boolean {
  const record = getCountryActivation(isoCode);
  return (record?.enabled ?? false) && (record?.beta ?? false);
}

export function isCountrySanctioned(isoCode: string): boolean {
  return getCountryActivation(isoCode)?.sanctionsRestricted ?? false;
}

export function canInitiatePayment(isoCode: string): boolean {
  const record = getCountryActivation(isoCode);
  if (!record) return false;
  return record.enabled && record.paymentsEnabled && !record.sanctionsRestricted;
}

export function canRegister(isoCode: string): boolean {
  const record = getCountryActivation(isoCode);
  if (!record) return false;
  return record.enabled && record.registrationEnabled && !record.sanctionsRestricted;
}

export function getEnabledCountries(): CountryActivationRecord[] {
  return COUNTRY_ACTIVATION_REGISTRY.filter((c) => c.enabled);
}

export function getBetaCountries(): CountryActivationRecord[] {
  return COUNTRY_ACTIVATION_REGISTRY.filter((c) => c.enabled && c.beta);
}

export function getSanctionedCountries(): CountryActivationRecord[] {
  return COUNTRY_ACTIVATION_REGISTRY.filter((c) => c.sanctionsRestricted);
}

export function getDisabledCountries(): CountryActivationRecord[] {
  return COUNTRY_ACTIVATION_REGISTRY.filter((c) => !c.enabled);
}
