type Catalog = Record<string, string>;

const pt: Catalog = {
  "branding.identity": "Na Edunancial, começamos pela literacia financeira, desenvolvemos competência financeira e trabalhamos rumo à inteligência financeira.",
  "footer.identity": "Na Edunancial, começamos pela literacia financeira, desenvolvemos competência financeira e trabalhamos rumo à inteligência financeira.",
  "footer.subtitle": "Literacia financeira → Competência financeira → Inteligência financeira.",
  "footer.col.learn": "Aprender",
  "footer.col.competency": "Competência",
  "footer.col.company": "Empresa",
  "footer.col.community": "Comunidade",
  "footer.col.trustLegal": "Confiança e aspetos legais",
  "contact.label": "Contacto",
  "contact.heading": "Contactar a Edunancial",
  "contact.intro": "Para manter o apoio ao lançamento fiável, a Edunancial publica apenas as caixas de correio que são atualmente monitorizadas. Utilize o endereço que melhor corresponde ao que precisa e, sempre que possível, inclua o email associado à sua adesão.",
  "contact.card1.title": "Informações gerais",
  "contact.card1.description": "Questões sobre adesões, disponibilidade, acesso de organizações ou a experiência Edunancial em geral.",
  "contact.card2.title": "Apoio ao cliente",
  "contact.card2.description": "Precisa de ajuda com início de sessão, checkout, acesso, certificados, progresso nos cursos ou problemas técnicos? Comece aqui.",
  "pricingPage.label": "Preços",
  "pricingPage.title": "Preços de adesão para pessoas e organizações aprovadas.",
  "pricingPage.intro": "Na Edunancial, começamos pela literacia financeira, desenvolvemos competência financeira e trabalhamos rumo à inteligência financeira. As três primeiras lições do Nível 1 de cada cor curricular são gratuitas; depois pode escolher o plano pago adequado ao nível de acesso pretendido.",
  "pricingPage.freePlan.name": "ACESSO GRATUITO AO NÍVEL 1",
  "pricingPage.freePlan.priceDisplay": "$0",
  "pricingPage.freePlan.billingLabel": "sem cartão de crédito para as lições gratuitas",
  "pricingPage.freePlan.description": "Crie uma conta Edunancial gratuita e aceda às três primeiras lições do Nível 1 de cada cor curricular sem qualquer custo.",
  "pricingPage.freePlan.ctaLabel": "Começar lições gratuitas",
  "pricingPage.enterprisePlan.name": "Empresarial",
  "pricingPage.enterprisePlan.priceDisplay": "Orçamento personalizado",
  "pricingPage.enterprisePlan.billingLabel": "contacte-nos para preços",
  "pricingPage.enterprisePlan.description": "Para grandes organizações, entidades governamentais e parceiros empresariais que necessitem de acordos personalizados, apoio dedicado ou preços por volume.",
  "pricingPage.enterprisePlan.ctaLabel": "Contactar sobre preços empresariais",
  "pricingPage.primaryLabel": "Ver detalhes da adesão",
  "pricingPage.secondaryLabel": "Contactar vendas e apoio",
  "pricingTable.feature": "Funcionalidade",
  "pricingTable.contactUs": "Contacte-nos",
  "pricingTable.select": "Selecionar",
  "membershipCopy.plan.basic.name": "Adesão Basic",
  "membershipCopy.plan.basic.description": "Recursos estruturados, sessões orientadas, exercícios práticos e ferramentas para desenvolver literacia e competência financeira.",
  "membershipCopy.plan.basic.billingLabel": "por mês",
  "membershipCopy.plan.basic.ctaLabel": "Escolher adesão Basic",
  "membershipCopy.plan.pro.name": "Adesão Pro",
  "membershipCopy.plan.pro.description": "Benefícios ampliados com acesso de aprendizagem mais profundo, downloads e apoio do Coach Financeiro com IA.",
  "membershipCopy.plan.pro.billingLabel": "por mês",
  "membershipCopy.plan.pro.ctaLabel": "Escolher adesão Pro",
  "membershipCopy.plan.gold.name": "Adesão Gold",
  "membershipCopy.plan.gold.description": "Acesso completo para aprendizagem avançada, com apoio prioritário e ferramentas premium.",
  "membershipCopy.plan.gold.billingLabel": "por mês",
  "membershipCopy.plan.gold.ctaLabel": "Escolher adesão Gold",
  "membershipCopy.feature.assessmentIncluded": "Avaliação de competência",
  "membershipCopy.feature.marketplaceIncluded": "Acesso ao Marketplace",
  "membershipCopy.feature.aiCoachIncluded": "Coach com IA",
  "membershipCopy.feature.downloadableCourses": "Recursos de aprendizagem descarregáveis",
  "membershipCopy.feature.prioritySupport": "Apoio prioritário",
  "membershipCopy.feature.maxCertificates": "Certificados de conclusão"
};

const de: Catalog = {
  "branding.identity": "Bei Edunancial beginnen wir mit Finanzbildung, bauen finanzielle Kompetenz auf und arbeiten auf finanzielle Intelligenz hin.",
  "footer.identity": "Bei Edunancial beginnen wir mit Finanzbildung, bauen finanzielle Kompetenz auf und arbeiten auf finanzielle Intelligenz hin.",
  "footer.subtitle": "Finanzbildung → Finanzkompetenz → Finanzielle Intelligenz.",
  "contact.label": "Kontakt",
  "contact.heading": "Edunancial kontaktieren",
  "contact.card1.title": "Allgemeine Informationen",
  "contact.card1.description": "Fragen zu Mitgliedschaften, Verfügbarkeit, Organisationszugang oder zur Edunancial-Erfahrung insgesamt.",
  "contact.card2.title": "Kundensupport",
  "contact.card2.description": "Hilfe bei Anmeldung, Checkout, Zugang, Zertifikaten, Kursfortschritt oder technischen Problemen? Beginnen Sie hier.",
  "pricingPage.label": "Preise",
  "pricingPage.title": "Mitgliedschaftspreise für Einzelpersonen und zugelassene Organisationen.",
  "pricingPage.intro": "Bei Edunancial beginnen wir mit Finanzbildung, bauen finanzielle Kompetenz auf und arbeiten auf finanzielle Intelligenz hin. Die ersten drei Lektionen von Level 1 jeder Curriculum-Farbe sind kostenlos.",
  "pricingPage.freePlan.name": "KOSTENLOSER LEVEL-1-ZUGANG",
  "pricingPage.freePlan.billingLabel": "für die kostenlosen Lektionen keine Kreditkarte erforderlich",
  "pricingPage.freePlan.description": "Erstellen Sie ein kostenloses Edunancial-Konto und nutzen Sie die ersten drei Lektionen von Level 1 jeder Curriculum-Farbe kostenlos.",
  "pricingPage.freePlan.ctaLabel": "Kostenlose Lektionen starten",
  "pricingTable.feature": "Leistung",
  "pricingTable.contactUs": "Kontakt",
  "pricingTable.select": "Auswählen",
  "membershipCopy.plan.basic.name": "Basic-Mitgliedschaft",
  "membershipCopy.plan.basic.description": "Strukturierte Lernressourcen, geführte Einheiten, praktische Übungen und Mitgliedertools zum Aufbau von Finanzbildung und Finanzkompetenz.",
  "membershipCopy.plan.basic.billingLabel": "pro Monat",
  "membershipCopy.plan.basic.ctaLabel": "Basic wählen",
  "membershipCopy.plan.pro.name": "Pro-Mitgliedschaft",
  "membershipCopy.plan.pro.description": "Erweiterte Vorteile mit vertieftem Lernzugang, Downloads und Unterstützung durch den KI-Finanzcoach.",
  "membershipCopy.plan.pro.billingLabel": "pro Monat",
  "membershipCopy.plan.pro.ctaLabel": "Pro wählen",
  "membershipCopy.plan.gold.name": "Gold-Mitgliedschaft",
  "membershipCopy.plan.gold.description": "Voller Mitgliedszugang für fortgeschrittene Lernende mit priorisiertem Support und Premium-Tools.",
  "membershipCopy.plan.gold.billingLabel": "pro Monat",
  "membershipCopy.plan.gold.ctaLabel": "Gold wählen"
};

const it: Catalog = {
  "branding.identity": "In Edunancial partiamo dall'alfabetizzazione finanziaria, sviluppiamo la competenza finanziaria e lavoriamo verso l'intelligenza finanziaria.",
  "footer.identity": "In Edunancial partiamo dall'alfabetizzazione finanziaria, sviluppiamo la competenza finanziaria e lavoriamo verso l'intelligenza finanziaria.",
  "footer.subtitle": "Alfabetizzazione finanziaria → Competenza finanziaria → Intelligenza finanziaria.",
  "contact.label": "Contatti",
  "contact.heading": "Contatta Edunancial",
  "contact.card1.title": "Informazioni generali",
  "contact.card1.description": "Domande su iscrizioni, disponibilità, accesso per organizzazioni o sull'esperienza Edunancial in generale.",
  "contact.card2.title": "Assistenza clienti",
  "contact.card2.description": "Hai bisogno di aiuto con accesso, checkout, certificati, avanzamento dei corsi o problemi tecnici? Inizia qui.",
  "pricingPage.label": "Prezzi",
  "pricingPage.title": "Prezzi di iscrizione per individui e organizzazioni approvate.",
  "pricingPage.intro": "In Edunancial partiamo dall'alfabetizzazione finanziaria, sviluppiamo la competenza finanziaria e lavoriamo verso l'intelligenza finanziaria. Le prime tre lezioni del Livello 1 di ogni colore curricolare sono gratuite.",
  "pricingPage.freePlan.name": "ACCESSO GRATUITO AL LIVELLO 1",
  "pricingPage.freePlan.billingLabel": "nessuna carta di credito richiesta per le lezioni gratuite",
  "pricingPage.freePlan.description": "Crea un account Edunancial gratuito e accedi senza costi alle prime tre lezioni del Livello 1 di ogni colore curricolare.",
  "pricingPage.freePlan.ctaLabel": "Inizia le lezioni gratuite",
  "pricingTable.feature": "Funzionalità",
  "pricingTable.contactUs": "Contattaci",
  "pricingTable.select": "Seleziona",
  "membershipCopy.plan.basic.name": "Iscrizione Basic",
  "membershipCopy.plan.basic.description": "Risorse strutturate, sessioni guidate, esercizi pratici e strumenti per sviluppare alfabetizzazione e competenza finanziaria.",
  "membershipCopy.plan.basic.billingLabel": "al mese",
  "membershipCopy.plan.basic.ctaLabel": "Scegli Basic",
  "membershipCopy.plan.pro.name": "Iscrizione Pro",
  "membershipCopy.plan.pro.description": "Vantaggi ampliati con accesso formativo più approfondito, download e supporto del Coach finanziario AI.",
  "membershipCopy.plan.pro.billingLabel": "al mese",
  "membershipCopy.plan.pro.ctaLabel": "Scegli Pro",
  "membershipCopy.plan.gold.name": "Iscrizione Gold",
  "membershipCopy.plan.gold.description": "Accesso completo per utenti avanzati con supporto prioritario e strumenti premium.",
  "membershipCopy.plan.gold.billingLabel": "al mese",
  "membershipCopy.plan.gold.ctaLabel": "Scegli Gold"
};

const nl: Catalog = {
  "branding.identity": "Bij Edunancial beginnen we met financiële geletterdheid, bouwen we financiële competentie op en werken we toe naar financiële intelligentie.",
  "footer.identity": "Bij Edunancial beginnen we met financiële geletterdheid, bouwen we financiële competentie op en werken we toe naar financiële intelligentie.",
  "footer.subtitle": "Financiële geletterdheid → Financiële competentie → Financiële intelligentie.",
  "contact.label": "Contact",
  "contact.heading": "Contact opnemen met Edunancial",
  "contact.card1.title": "Algemene informatie",
  "contact.card1.description": "Vragen over lidmaatschappen, beschikbaarheid, toegang voor organisaties of de Edunancial-ervaring in het algemeen.",
  "contact.card2.title": "Klantenservice",
  "contact.card2.description": "Hulp nodig met inloggen, checkout, toegang, certificaten, cursusvoortgang of technische problemen? Begin hier.",
  "pricingPage.label": "Prijzen",
  "pricingPage.title": "Lidmaatschapsprijzen voor particulieren en goedgekeurde organisaties.",
  "pricingPage.intro": "Bij Edunancial beginnen we met financiële geletterdheid, bouwen we financiële competentie op en werken we toe naar financiële intelligentie. De eerste drie lessen van niveau 1 van elke curriculumkleur zijn gratis.",
  "pricingPage.freePlan.name": "GRATIS TOEGANG TOT NIVEAU 1",
  "pricingPage.freePlan.billingLabel": "geen creditcard nodig voor de gratis lessen",
  "pricingPage.freePlan.description": "Maak een gratis Edunancial-account aan en krijg kosteloos toegang tot de eerste drie lessen van niveau 1 van elke curriculumkleur.",
  "pricingPage.freePlan.ctaLabel": "Start gratis lessen",
  "pricingTable.feature": "Functie",
  "pricingTable.contactUs": "Contact opnemen",
  "pricingTable.select": "Selecteren",
  "membershipCopy.plan.basic.name": "Basic-lidmaatschap",
  "membershipCopy.plan.basic.description": "Gestructureerde leermiddelen, begeleide sessies, praktische oefeningen en hulpmiddelen om financiële geletterdheid en competentie op te bouwen.",
  "membershipCopy.plan.basic.billingLabel": "per maand",
  "membershipCopy.plan.basic.ctaLabel": "Kies Basic",
  "membershipCopy.plan.pro.name": "Pro-lidmaatschap",
  "membershipCopy.plan.pro.description": "Uitgebreide voordelen met diepere leertoegang, downloads en ondersteuning van de AI-financiële coach.",
  "membershipCopy.plan.pro.billingLabel": "per maand",
  "membershipCopy.plan.pro.ctaLabel": "Kies Pro",
  "membershipCopy.plan.gold.name": "Gold-lidmaatschap",
  "membershipCopy.plan.gold.description": "Volledige toegang voor gevorderde deelnemers met prioriteitsondersteuning en premiumtools.",
  "membershipCopy.plan.gold.billingLabel": "per maand",
  "membershipCopy.plan.gold.ctaLabel": "Kies Gold"
};

const overrides: Record<string, Catalog> = {
  pt, "pt-BR": pt, "pt-PT": pt, de, it, nl,
};

export function getPublicPageOverride(language: string, key: string): string | undefined {
  return overrides[language]?.[key];
}

export const REQUIRED_PUBLIC_TRANSLATION_KEYS = [
  "branding.identity",
  "footer.identity",
  "footer.subtitle",
  "contact.heading",
  "contact.card1.title",
  "contact.card2.title",
  "pricingPage.title",
  "pricingPage.intro",
  "pricingPage.freePlan.name",
  "pricingPage.freePlan.description",
  "membershipCopy.plan.basic.name",
  "membershipCopy.plan.basic.description",
  "membershipCopy.plan.pro.name",
  "membershipCopy.plan.pro.description",
  "membershipCopy.plan.gold.name",
  "membershipCopy.plan.gold.description"
] as const;
