import { normalizeLanguageCode } from "./languages";

type PathwayCopy = { label: string; title: string; steps: readonly string[] };
type SelfDirectedCopy = { label: string; principle: string; body: string; close: string };
type RecentPositioningCopy = { pathway: PathwayCopy; selfDirected: SelfDirectedCopy };

const copy: Record<string, RecentPositioningCopy> = {
  "en-US": { pathway: { label: "THE EDUNANCIAL PATH™", title: "Eight subjects. Five levels. One goal: financial intelligence.", steps: ["Financial literacy", "Financial competency", "Applied decision-making", "Strategic integration", "Financial intelligence"] }, selfDirected: { label: "Your Goals. Your Path. Your Progress.", principle: "No GPA. No rankings. No one-size-fits-all definition of financial success.", body: "Your financial goals are personal. Edunancial gives you information, concepts, tools and practical frameworks across real estate, financial assets, business and the subjects that support them. You decide what applies to your goals, dreams and aspirations—and how deeply you want to learn.", close: "We don't define success for you. We help you become better informed to pursue the success you define for yourself." } },
  "en-GB": { pathway: { label: "THE EDUNANCIAL PATH™", title: "Eight subjects. Five levels. One goal: financial intelligence.", steps: ["Financial literacy", "Financial competency", "Applied decision-making", "Strategic integration", "Financial intelligence"] }, selfDirected: { label: "Your Goals. Your Path. Your Progress.", principle: "No GPA. No rankings. No one-size-fits-all definition of financial success.", body: "Your financial goals are personal. Edunancial gives you information, concepts, tools and practical frameworks across property, financial assets, business and the subjects that support them. You decide what applies to your goals, dreams and aspirations—and how deeply you want to learn.", close: "We don't define success for you. We help you become better informed to pursue the success you define for yourself." } },
  "es-Caribbean": { pathway: { label: "LA RUTA EDUNANCIAL™", title: "Ocho temas. Cinco niveles. Una meta: inteligencia financiera.", steps: ["Alfabetización financiera", "Competencia financiera", "Toma de decisiones aplicada", "Integración estratégica", "Inteligencia financiera"] }, selfDirected: { label: "Tus metas. Tu ruta. Tu progreso.", principle: "Sin GPA. Sin rankings. Sin una definición única del éxito financiero.", body: "Tus metas financieras son personales. Edunancial te ofrece información, conceptos, herramientas y marcos prácticos sobre bienes raíces, activos financieros, negocios y los temas que los apoyan. Tú decides qué aplica a tus metas, sueños y aspiraciones, y hasta dónde quieres aprender.", close: "Nosotros no definimos el éxito por ti. Te ayudamos a estar mejor informado para perseguir el éxito que tú defines." } },
  "es-ES": { pathway: { label: "LA RUTA EDUNANCIAL™", title: "Ocho temas. Cinco niveles. Una meta: inteligencia financiera.", steps: ["Alfabetización financiera", "Competencia financiera", "Toma de decisiones aplicada", "Integración estratégica", "Inteligencia financiera"] }, selfDirected: { label: "Tus objetivos. Tu ruta. Tu progreso.", principle: "Sin GPA. Sin clasificaciones. Sin una definición única del éxito financiero.", body: "Tus objetivos financieros son personales. Edunancial te ofrece información, conceptos, herramientas y marcos prácticos sobre bienes inmuebles, activos financieros, empresa y los temas que los respaldan. Tú decides qué se aplica a tus objetivos, sueños y aspiraciones, y hasta qué punto quieres aprender.", close: "No definimos el éxito por ti. Te ayudamos a estar mejor informado para perseguir el éxito que tú mismo defines." } },
  "fr-CA": { pathway: { label: "LE PARCOURS EDUNANCIAL™", title: "Huit sujets. Cinq niveaux. Un objectif : l’intelligence financière.", steps: ["Littératie financière", "Compétence financière", "Prise de décision appliquée", "Intégration stratégique", "Intelligence financière"] }, selfDirected: { label: "Vos objectifs. Votre parcours. Vos progrès.", principle: "Aucune moyenne générale. Aucun classement. Aucune définition universelle de la réussite financière.", body: "Vos objectifs financiers sont personnels. Edunancial vous offre de l’information, des concepts, des outils et des cadres pratiques sur l’immobilier, les actifs financiers, les affaires et les sujets qui les soutiennent. Vous décidez de ce qui s’applique à vos objectifs, rêves et aspirations, et jusqu’où vous souhaitez apprendre.", close: "Nous ne définissons pas la réussite à votre place. Nous vous aidons à être mieux informé pour poursuivre la réussite que vous définissez vous-même." } },
  "fr-FR": { pathway: { label: "LE PARCOURS EDUNANCIAL™", title: "Huit sujets. Cinq niveaux. Un objectif : l’intelligence financière.", steps: ["Culture financière", "Compétence financière", "Prise de décision appliquée", "Intégration stratégique", "Intelligence financière"] }, selfDirected: { label: "Vos objectifs. Votre parcours. Vos progrès.", principle: "Pas de moyenne générale. Pas de classement. Pas de définition unique de la réussite financière.", body: "Vos objectifs financiers sont personnels. Edunancial vous apporte des informations, des concepts, des outils et des cadres pratiques sur l’immobilier, les actifs financiers, l’entreprise et les sujets qui les accompagnent. Vous décidez de ce qui correspond à vos objectifs, rêves et aspirations, et jusqu’où vous souhaitez approfondir vos connaissances.", close: "Nous ne définissons pas la réussite à votre place. Nous vous aidons à être mieux informé pour poursuivre la réussite que vous définissez vous-même." } },
  "pt-BR": { pathway: { label: "A JORNADA EDUNANCIAL™", title: "Oito temas. Cinco níveis. Um objetivo: inteligência financeira.", steps: ["Educação financeira", "Competência financeira", "Tomada de decisão aplicada", "Integração estratégica", "Inteligência financeira"] }, selfDirected: { label: "Seus objetivos. Sua jornada. Seu progresso.", principle: "Sem GPA. Sem rankings. Sem uma definição única de sucesso financeiro.", body: "Seus objetivos financeiros são pessoais. A Edunancial oferece informações, conceitos, ferramentas e estruturas práticas sobre imóveis, ativos financeiros, negócios e os temas que os apoiam. Você decide o que se aplica aos seus objetivos, sonhos e aspirações e até onde deseja aprender.", close: "Nós não definimos sucesso por você. Ajudamos você a se informar melhor para buscar o sucesso que você mesmo define." } },
  "pt-PT": { pathway: { label: "O PERCURSO EDUNANCIAL™", title: "Oito temas. Cinco níveis. Um objetivo: inteligência financeira.", steps: ["Literacia financeira", "Competência financeira", "Tomada de decisão aplicada", "Integração estratégica", "Inteligência financeira"] }, selfDirected: { label: "Os seus objetivos. O seu percurso. O seu progresso.", principle: "Sem média geral. Sem classificações. Sem uma definição única de sucesso financeiro.", body: "Os seus objetivos financeiros são pessoais. A Edunancial oferece informação, conceitos, ferramentas e estruturas práticas sobre imobiliário, ativos financeiros, negócios e os temas que os apoiam. Decide o que se aplica aos seus objetivos, sonhos e aspirações e até onde pretende aprender.", close: "Não definimos o sucesso por si. Ajudamo-lo a estar mais bem informado para procurar o sucesso que define para si próprio." } },
  de: { pathway: { label: "DER EDUNANCIAL-WEG™", title: "Acht Themen. Fünf Stufen. Ein Ziel: finanzielle Intelligenz.", steps: ["Finanzbildung", "Finanzkompetenz", "Angewandte Entscheidungsfindung", "Strategische Integration", "Finanzielle Intelligenz"] }, selfDirected: { label: "Ihre Ziele. Ihr Weg. Ihr Fortschritt.", principle: "Keine Notendurchschnitte. Keine Ranglisten. Keine allgemeingültige Definition von finanziellem Erfolg.", body: "Ihre finanziellen Ziele sind persönlich. Edunancial bietet Informationen, Konzepte, Werkzeuge und praktische Rahmenmodelle zu Immobilien, Finanzanlagen, Unternehmen und den unterstützenden Themen. Sie entscheiden, was zu Ihren Zielen, Träumen und Vorstellungen passt und wie tief Sie lernen möchten.", close: "Wir definieren Erfolg nicht für Sie. Wir helfen Ihnen, besser informiert den Erfolg anzustreben, den Sie selbst definieren." } },
  it: { pathway: { label: "IL PERCORSO EDUNANCIAL™", title: "Otto argomenti. Cinque livelli. Un obiettivo: intelligenza finanziaria.", steps: ["Alfabetizzazione finanziaria", "Competenza finanziaria", "Processo decisionale applicato", "Integrazione strategica", "Intelligenza finanziaria"] }, selfDirected: { label: "I tuoi obiettivi. Il tuo percorso. I tuoi progressi.", principle: "Niente media scolastica. Niente classifiche. Nessuna definizione universale di successo finanziario.", body: "I tuoi obiettivi finanziari sono personali. Edunancial offre informazioni, concetti, strumenti e modelli pratici su immobili, attività finanziarie, impresa e gli argomenti che li supportano. Sei tu a decidere cosa si applica ai tuoi obiettivi, sogni e aspirazioni e quanto vuoi approfondire.", close: "Non definiamo il successo al posto tuo. Ti aiutiamo a essere più informato per perseguire il successo che definisci tu stesso." } },
  nl: { pathway: { label: "HET EDUNANCIAL-PAD™", title: "Acht onderwerpen. Vijf niveaus. Eén doel: financiële intelligentie.", steps: ["Financiële geletterdheid", "Financiële competentie", "Toegepaste besluitvorming", "Strategische integratie", "Financiële intelligentie"] }, selfDirected: { label: "Jouw doelen. Jouw pad. Jouw vooruitgang.", principle: "Geen GPA. Geen ranglijsten. Geen universele definitie van financieel succes.", body: "Jouw financiële doelen zijn persoonlijk. Edunancial biedt informatie, concepten, hulpmiddelen en praktische kaders over vastgoed, financiële activa, ondernemen en de ondersteunende onderwerpen. Jij bepaalt wat bij jouw doelen, dromen en ambities past en hoe diep je wilt leren.", close: "Wij bepalen niet wat succes voor jou is. Wij helpen je beter geïnformeerd het succes na te streven dat jij zelf definieert." } },
};

export function getRecentPositioningCopy(languageCode: string): RecentPositioningCopy {
  const locale = normalizeLanguageCode(languageCode);
  return copy[locale] ?? copy["en-US"];
}
