"use client";
import Link from "next/link";
import type { ExecutiveOperationsSnapshot,LiveValue } from "@/lib/admin/operations-snapshot";
const QUICK_LINKS=[["Video Studio","/admin/video-studio","🎬"],["Content Upload Portal","/admin/content/upload","📦"],["Analytics & KPIs","/admin/kpi","📊"],["Revenue & Profit","/admin/profit-dashboard","💰"],["Customer Management","/admin/customers","👥"],["Membership Management","/admin/memberships","🏆"],["Curriculum Manager","/admin/curriculum","📖"],["Country Launch Controls","/admin/regions","🌎"]] as const;
const money=(m:LiveValue)=>m.status==="LIVE"&&m.value!==null?m.value.toLocaleString(undefined,{style:"currency",currency:"USD"}):"Unavailable"; const count=(m:LiveValue)=>m.status==="LIVE"&&m.value!==null?m.value.toLocaleString():"Unavailable"; const pct=(m:LiveValue)=>m.status==="LIVE"&&m.value!==null?`${m.value.toFixed(1)}%`:"Unavailable";
export default function AdminDashboardClient({snapshot}:{snapshot:ExecutiveOperationsSnapshot}){
 const primary=[["Gross Revenue",money(snapshot.grossRevenue),"Verified completed payment records"],["Net Revenue",money(snapshot.netRevenue),"Revenue less recorded refunds"],["MRR",money(snapshot.mrr),"Active recurring membership run-rate"],["ARR",money(snapshot.arr),"Annualized recurring run-rate"],["Active Members",count(snapshot.activeMembers),"Production member records"],["New Members · 30D",count(snapshot.newMembers30d),"Acquisition velocity"],["Active Subscriptions",count(snapshot.activeSubscriptions),"Current recurring subscriptions"],["Refunds",money(snapshot.refunds),"Recorded refunded payments"]] as const;
 const members=[["Basic",snapshot.basicMembers],["Pro",snapshot.proMembers],["Gold",snapshot.goldMembers]] as const; const videos=[["Projects",count(snapshot.video.projects)],["Masters Ready",count(snapshot.video.mastersReady)],["Queued",count(snapshot.video.queuedJobs)],["Processing",count(snapshot.video.processingJobs)],["Renders · 30D",count(snapshot.video.renders30d)],["Failed Renders",count(snapshot.video.failedRenders)],["Render Success",pct(snapshot.video.successRate)]] as const; const tax=[["Sales Tax Collected",money(snapshot.salesTaxCollected)],["Sales Tax Remitted",money(snapshot.salesTaxRemitted)],["Sales Tax Due",money(snapshot.salesTaxDue)],["Total Business Tax Due",money(snapshot.totalBusinessTaxDue)],["Jurisdictions With Tax Due",count(snapshot.taxJurisdictionsDue)]] as const;
 return <main className="min-h-screen bg-[#08101f] text-white"><div className="mx-auto max-w-7xl px-6 py-10">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[0.4em] text-yellow-400">Owner · Live Operations</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Executive KPI Command Center</h1><p className="mt-2 max-w-3xl text-slate-400">Day-one production metrics for operating decisions and investor reporting. Unavailable sources are labeled instead of replaced with fabricated zeros.</p></div><div className="flex flex-wrap gap-3"><Link href="/admin/video-studio" className="rounded-lg bg-purple-700 px-4 py-2 text-sm font-bold">Video Studio</Link><Link href="/admin/content/upload" className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold">Upload Content</Link><Link href="/executive/dashboard" className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold">Investor Analytics</Link></div></div>
  <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{primary.map(([l,v,d])=><article key={l} className="rounded-2xl border border-white/10 bg-[#101a2f] p-6"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{l}</p><p className="mt-3 text-3xl font-black">{v}</p><p className="mt-3 text-xs text-slate-500">{d}</p></article>)}</section>
  <section className="mt-8 grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-[#101a2f] p-6"><h2 className="text-xl font-bold">Membership Mix</h2><div className="mt-5 grid grid-cols-3 gap-3">{members.map(([l,m])=><div key={l} className="rounded-xl bg-slate-950/30 p-4"><p className="text-xs text-slate-400">{l}</p><p className="mt-2 text-2xl font-black">{count(m)}</p></div>)}</div><p className="mt-4 text-xs text-slate-500">Tier mix is read from active member records and begins accumulating immediately.</p></article><article className="rounded-2xl border border-white/10 bg-[#101a2f] p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Video Production</h2><Link href="/admin/video-studio" className="text-sm font-bold text-purple-400">Open Studio →</Link></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{videos.map(([l,v])=><div key={l} className="rounded-xl bg-slate-950/30 p-4"><p className="text-xs text-slate-400">{l}</p><p className="mt-2 text-xl font-black">{v}</p></div>)}</div></article></section>
  <section className="mt-8 grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-[#101a2f] p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Content Pipeline Health</h2><span className={snapshot.upload.status==="READY"?"font-bold text-emerald-400":"font-bold text-red-400"}>{snapshot.upload.status}</span></div><div className="mt-4 space-y-2 text-sm text-slate-300"><p>Signed upload: {snapshot.upload.signedUploadConfigured?"Configured":"Not configured"}</p><p>GitHub publication: {snapshot.upload.githubPublishingConfigured?"Configured":"Not configured"}</p>{snapshot.upload.problems.map(p=><p key={p} className="text-red-300">• {p}</p>)}</div></article><article className="rounded-2xl border border-white/10 bg-[#101a2f] p-6"><h2 className="text-xl font-bold">Payment Operations</h2><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-950/30 p-4"><p className="text-xs text-slate-400">Failed Payments</p><p className="mt-2 text-2xl font-black">{count(snapshot.failedPayments)}</p></div><div className="rounded-xl bg-slate-950/30 p-4"><p className="text-xs text-slate-400">Square Verification</p><p className="mt-2 text-lg font-black text-yellow-300">Pending external verification</p></div></div></article></section>
  <section className="mt-8"><h2 className="text-xl font-bold">Tax Liability</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{tax.map(([l,v])=><div key={l} className="rounded-xl border border-white/10 bg-[#101a2f] p-5"><p className="text-xs text-slate-400">{l}</p><p className="mt-2 text-2xl font-black">{v}</p></div>)}</div></section>
  <section className="mt-8"><h2 className="text-xl font-bold">Owner Modules</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{QUICK_LINKS.map(([t,h,i])=><Link key={t} href={h} className="flex items-center gap-3 rounded-xl border border-white/10 bg-[#101a2f] p-5 hover:border-blue-500"><span className="text-xl">{i}</span><span className="font-semibold">{t}</span></Link>)}</div><p className="mt-5 text-xs text-slate-500">As of {new Date(snapshot.asOf).toLocaleString()}</p></section>
 </div></main>;
}
