"use client";
import Link from "next/link";
import type { ExecutiveOperationsSnapshot, LiveValue, SystemHealthStatus } from "@/lib/admin/operations-snapshot";

const QUICK_LINKS = [["Investor Intelligence","/executive/dashboard","📈"],["Video Studio","/admin/video-studio","🎬"],["Content Upload Portal","/admin/content/upload","📦"],["Analytics & KPIs","/admin/kpi","📊"],["Revenue & Profit","/admin/profit-dashboard","💰"],["Customer Management","/admin/customers","👥"],["Membership Management","/admin/memberships","🏆"],["Curriculum Manager","/admin/curriculum","📖"],["Country Launch Controls","/admin/regions","🌎"],["Tax Operations","/admin/tax","🧾"]] as const;
const money = (m: LiveValue) => m.status === "LIVE" && m.value !== null ? m.value.toLocaleString(undefined, { style: "currency", currency: "USD" }) : "Unavailable";
const count = (m: LiveValue) => m.status === "LIVE" && m.value !== null ? m.value.toLocaleString() : "Unavailable";
const pct = (m: LiveValue) => m.status === "LIVE" && m.value !== null ? `${m.value.toFixed(1)}%` : "Unavailable";
const healthClass = (status: SystemHealthStatus) => status === "READY" ? "text-emerald-400" : status === "DEGRADED" ? "text-yellow-300" : "text-red-400";

export default function AdminDashboardClient({ snapshot }: { snapshot: ExecutiveOperationsSnapshot }) {
  const primary = [["Gross Revenue",money(snapshot.grossRevenue),"Verified completed payment records"],["Net Revenue",money(snapshot.netRevenue),"Revenue less recorded refunds"],["MRR",money(snapshot.mrr),"Active recurring membership run-rate"],["ARR",money(snapshot.arr),"Annualized recurring run-rate"],["Active Members",count(snapshot.activeMembers),"Production member records"],["New Members · 30D",count(snapshot.newMembers30d),"Acquisition velocity"],["Active Subscriptions",count(snapshot.activeSubscriptions),"Current recurring subscriptions"],["Refunds",money(snapshot.refunds),"Recorded refunded payments"]] as const;
  const members = [["Basic",snapshot.basicMembers],["Pro",snapshot.proMembers],["Gold",snapshot.goldMembers]] as const;
  const videos = [["Projects",count(snapshot.video.projects)],["Masters Ready",count(snapshot.video.mastersReady)],["Queued",count(snapshot.video.queuedJobs)],["Processing",count(snapshot.video.processingJobs)],["Renders · 30D",count(snapshot.video.renders30d)],["Successful Renders",count(snapshot.video.successfulRenders)],["Failed Renders",count(snapshot.video.failedRenders)],["Render Success",pct(snapshot.video.successRate)]] as const;
  const tax = [["Sales Tax Collected",money(snapshot.salesTaxCollected)],["Sales Tax Remitted",money(snapshot.salesTaxRemitted)],["Sales Tax Due",money(snapshot.salesTaxDue)],["Total Business Tax Due",money(snapshot.totalBusinessTaxDue)],["Jurisdictions With Tax Due",count(snapshot.taxJurisdictionsDue)]] as const;
  const health = [
    { label: "Payments", status: snapshot.payment.status, detail: `Square ${snapshot.payment.squareConfigured ? "configured" : "not configured"} · persistence ${snapshot.payment.persistenceConfigured ? "configured" : "not configured"}`, problems: snapshot.payment.problems },
    { label: "Video Production", status: snapshot.video.status, detail: `Worker ${snapshot.video.workerConfigured ? "configured" : "not configured"} · TTS ${snapshot.video.ttsConfigured ? "configured" : "not configured"}`, problems: snapshot.video.problems },
    { label: "Bulk Content", status: snapshot.upload.status, detail: `Failures 24h: ${snapshot.upload.failures24h ?? "unavailable"} · fallbacks: ${snapshot.upload.fallbacks24h ?? "unavailable"}`, problems: snapshot.upload.problems },
    { label: "Global Commerce", status: snapshot.globalCommerce.status, detail: `${snapshot.globalCommerce.enabledCountries ?? "?"}/${snapshot.globalCommerce.canonicalCountries} countries enabled · ${snapshot.globalCommerce.pricedCountries} priced`, problems: snapshot.globalCommerce.problems },
  ] as const;

  return <main className="min-h-screen bg-[#08101f] text-white"><div className="mx-auto max-w-7xl px-6 py-10">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[0.4em] text-yellow-400">Owner · Live Operations</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Executive KPI Command Center</h1><p className="mt-2 max-w-3xl text-slate-400">Day-one production metrics for operating decisions, growth allocation and investor diligence. Unavailable sources are labeled instead of replaced with fabricated zeros.</p></div><div className="flex flex-wrap gap-3"><Link href="/executive/dashboard" className="rounded-lg bg-yellow-500 px-4 py-2 text-sm font-black text-slate-950">Investor Intelligence</Link><Link href="/admin/video-studio" className="rounded-lg bg-purple-700 px-4 py-2 text-sm font-bold">Video Studio</Link><Link href="/admin/content/upload" className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold">Upload Content</Link></div></div>

    <section className="mt-8 rounded-2xl border border-white/10 bg-[#101a2f] p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-300">Launch-Critical Systems</p><h2 className="mt-2 text-2xl font-black">Production Health</h2></div><p className="text-xs text-slate-500">Configuration and production records only; unknown systems fail closed.</p></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{health.map((item)=><article key={item.label} className="rounded-xl bg-slate-950/30 p-4"><div className="flex items-center justify-between gap-3"><p className="font-bold">{item.label}</p><span className={`text-xs font-black ${healthClass(item.status)}`}>{item.status}</span></div><p className="mt-2 text-xs text-slate-400">{item.detail}</p>{item.problems.slice(0,2).map((problem)=><p key={problem} className="mt-2 text-xs text-red-300">• {problem}</p>)}</article>)}</div></section>

    <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{primary.map(([l,v,d])=><article key={l} className="rounded-2xl border border-white/10 bg-[#101a2f] p-6"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{l}</p><p className="mt-3 text-3xl font-black">{v}</p><p className="mt-3 text-xs text-slate-500">{d}</p></article>)}</section>
    <section className="mt-8 grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-[#101a2f] p-6"><h2 className="text-xl font-bold">Membership Mix</h2><div className="mt-5 grid grid-cols-3 gap-3">{members.map(([l,m])=><div key={l} className="rounded-xl bg-slate-950/30 p-4"><p className="text-xs text-slate-400">{l}</p><p className="mt-2 text-2xl font-black">{count(m)}</p></div>)}</div><p className="mt-4 text-xs text-slate-500">Tier mix is read from active member records and begins accumulating immediately.</p></article><article className="rounded-2xl border border-white/10 bg-[#101a2f] p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Video Production</h2><Link href="/admin/video-studio" className="text-sm font-bold text-purple-400">Open Studio →</Link></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{videos.map(([l,v])=><div key={l} className="rounded-xl bg-slate-950/30 p-4"><p className="text-xs text-slate-400">{l}</p><p className="mt-2 text-xl font-black">{v}</p></div>)}</div><p className="mt-4 text-xs text-slate-500">Production throughput and render reliability are tracked as operating-scale and diligence metrics.</p></article></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-[#101a2f] p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Content Pipeline Health</h2><span className={`font-bold ${healthClass(snapshot.upload.status)}`}>{snapshot.upload.status}</span></div><div className="mt-4 space-y-2 text-sm text-slate-300"><p>Signed upload: {snapshot.upload.signedUploadConfigured?"Configured":"Not configured"}</p><p>GitHub publication: {snapshot.upload.githubPublishingConfigured?"Configured":"Not configured"}</p><p>Failures in last 24h: {snapshot.upload.failures24h ?? "Unavailable"}</p>{snapshot.upload.lastFailure?<p className="text-red-300">Last failure: {snapshot.upload.lastFailure}</p>:null}{snapshot.upload.problems.map(p=><p key={p} className="text-red-300">• {p}</p>)}</div></article><article className="rounded-2xl border border-white/10 bg-[#101a2f] p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Payment Operations</h2><span className={`font-bold ${healthClass(snapshot.payment.status)}`}>{snapshot.payment.status}</span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-950/30 p-4"><p className="text-xs text-slate-400">Failed Payments</p><p className="mt-2 text-2xl font-black">{count(snapshot.failedPayments)}</p></div><div className="rounded-xl bg-slate-950/30 p-4"><p className="text-xs text-slate-400">Square Checkout</p><p className={`mt-2 text-lg font-black ${healthClass(snapshot.payment.status)}`}>{snapshot.payment.status}</p><p className="mt-1 text-xs text-slate-500">Webhook: {snapshot.payment.webhookVerificationConfigured?"configured":"not configured"}</p></div></div>{snapshot.payment.problems.map(p=><p key={p} className="mt-2 text-xs text-red-300">• {p}</p>)}</article></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-[#101a2f] p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold">Global Commerce Readiness</h2><p className="mt-1 text-xs text-slate-500">Country controls and approved pricing must agree before paid access is considered ready.</p></div><span className={`font-bold ${healthClass(snapshot.globalCommerce.status)}`}>{snapshot.globalCommerce.status}</span></div><div className="mt-5 grid grid-cols-3 gap-3"><div className="rounded-xl bg-slate-950/30 p-4"><p className="text-xs text-slate-400">Canonical</p><p className="mt-2 text-2xl font-black">{snapshot.globalCommerce.canonicalCountries}</p></div><div className="rounded-xl bg-slate-950/30 p-4"><p className="text-xs text-slate-400">Enabled</p><p className="mt-2 text-2xl font-black">{snapshot.globalCommerce.enabledCountries ?? "Unavailable"}</p></div><div className="rounded-xl bg-slate-950/30 p-4"><p className="text-xs text-slate-400">Priced</p><p className="mt-2 text-2xl font-black">{snapshot.globalCommerce.pricedCountries}</p></div></div>{snapshot.globalCommerce.enabledWithoutPricing.length?<p className="mt-4 text-sm text-yellow-300">Enabled without approved pricing: {snapshot.globalCommerce.enabledWithoutPricing.join(", ")}</p>:null}{snapshot.globalCommerce.problems.map(p=><p key={p} className="mt-2 text-xs text-red-300">• {p}</p>)}</article><article className="rounded-2xl border border-white/10 bg-[#101a2f] p-6"><h2 className="text-xl font-bold">Video Runtime Health</h2><div className="mt-4 space-y-2 text-sm text-slate-300"><p>Worker: {snapshot.video.workerConfigured?"Configured":"Not configured"}</p><p>Multilingual TTS: {snapshot.video.ttsConfigured?"Configured":"Not configured"}</p><p>Queued: {count(snapshot.video.queuedJobs)} · Processing: {count(snapshot.video.processingJobs)} · Failed: {count(snapshot.video.failedRenders)}</p>{snapshot.video.problems.map(p=><p key={p} className="text-red-300">• {p}</p>)}</div></article></section>
    <section className="mt-8"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Tax Liability</h2><p className="mt-1 text-xs text-slate-500">Collected, remitted and outstanding tax is preserved by jurisdiction for compliance and diligence.</p></div><Link href="/admin/tax" className="text-sm font-bold text-yellow-300">Tax Operations →</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{tax.map(([l,v])=><div key={l} className="rounded-xl border border-white/10 bg-[#101a2f] p-5"><p className="text-xs text-slate-400">{l}</p><p className="mt-2 text-2xl font-black">{v}</p></div>)}</div></section>
    <section className="mt-8 rounded-2xl border border-yellow-500/20 bg-yellow-500/5 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-yellow-400">Enterprise Value Intelligence</p><h2 className="mt-2 text-2xl font-black">VC / PE / Strategic Diligence</h2><p className="mt-2 max-w-3xl text-sm text-slate-400">Open the investor command center for customer economics, acquisition efficiency, retention, product engagement, geography, revenue quality, forecasts and valuation-grade KPI history.</p></div><Link href="/executive/dashboard" className="rounded-lg bg-yellow-500 px-5 py-3 text-sm font-black text-slate-950">Open Investor Dashboard →</Link></div></section>
    <section className="mt-8"><h2 className="text-xl font-bold">Owner Modules</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{QUICK_LINKS.map(([t,h,i])=><Link key={t} href={h} className="flex items-center gap-3 rounded-xl border border-white/10 bg-[#101a2f] p-5 hover:border-blue-500"><span className="text-xl">{i}</span><span className="font-semibold">{t}</span></Link>)}</div><p className="mt-5 text-xs text-slate-500">As of {new Date(snapshot.asOf).toLocaleString()}</p></section>
  </div></main>;
}
