import { RegionContentMap } from './types';

export const regionContent: RegionContentMap = {
  us: {
    en: {
      title: 'United States Curriculum',
      description: 'Foundational financial literacy for the U.S. market.',
      curriculum: [
        'Personal finance basics',
        'Credit and debt management',
        'Investing fundamentals',
        'Business formation in the U.S.',
      ],
      pricing: {
        currency: 'USD',
        monthly: 29,
        annual: 299,
        quarterly: 79,
        lifetime: 999,
      },
    },
    es: {
      title: 'Programa de Estados Unidos',
      description: 'Educación financiera para el mercado estadounidense.',
      curriculum: [
        'Finanzas personales',
        'Crédito y deudas',
        'Fundamentos de inversión',
        'Formación de empresas en EE.UU.',
      ],
      pricing: {
        currency: 'USD',
        monthly: 29,
        annual: 299,
        quarterly: 79,
        lifetime: 999,
      },
    },
    fr: {} as any,
    de: {} as any,
    pt: {} as any,
    ar: {} as any,
    zh: {} as any,
    ja: {} as any,
    ko: {} as any,
  },

  africa: {
    en: {
      title: 'Africa Curriculum',
      description: 'Entrepreneurship and finance adapted for African markets.',
      curriculum: [
        'Micro-enterprise finance',
        'Mobile banking & fintech',
        'Trade and logistics basics',
        'Cross-border investing',
      ],
      pricing: {
        currency: 'USD',
        monthly: 15,
        annual: 149,
        quarterly: 39,
        lifetime: 499,
      },
    },
    es: {} as any,
    fr: {} as any,
    de: {} as any,
    pt: {} as any,
    ar: {} as any,
    zh: {} as any,
    ja: {} as any,
    ko: {} as any,
  },

  europe: {
    en: {
      title: 'Europe Curriculum',
      description: 'Multi-jurisdiction finance and business education.',
      curriculum: [
        'EU financial systems',
        'Multi-currency investing',
        'Cross-border compliance',
        'Business structures in Europe',
      ],
      pricing: {
        currency: 'EUR',
        monthly: 25,
        annual: 249,
        quarterly: 69,
        lifetime: 899,
      },
    },
    es: {} as any,
    fr: {} as any,
    de: {} as any,
    pt: {} as any,
    ar: {} as any,
    zh: {} as any,
    ja: {} as any,
    ko: {} as any,
  },

  asia: {
    en: {
      title: 'Asia Curriculum',
      description: 'Finance and growth strategies for Asia.',
      curriculum: [
        'Regional capital markets',
        'Manufacturing finance',
        'Technology startups',
        'Cross-border trade',
      ],
      pricing: {
        currency: 'USD',
        monthly: 19,
        annual: 189,
        quarterly: 49,
        lifetime: 699,
      },
    },
    es: {} as any,
    fr: {} as any,
    de: {} as any,
    pt: {} as any,
    ar: {} as any,
    zh: {} as any,
    ja: {} as any,
    ko: {} as any,
  },

  'asia-emerging': {
    en: {
      title: 'Asia Emerging Markets',
      description: 'High-growth, early-stage economies.',
      curriculum: [
        'Startup finance',
        'SME scaling',
        'Foreign investment basics',
        'Risk management',
      ],
      pricing: {
        currency: 'USD',
        monthly: 12,
        annual: 119,
        quarterly: 35,
        lifetime: 399,
      },
    },
    es: {} as any,
    fr: {} as any,
    de: {} as any,
    pt: {} as any,
    ar: {} as any,
    zh: {} as any,
    ja: {} as any,
    ko: {} as any,
  },

  'asia-pacific': {
    en: {
      title: 'Asia-Pacific Curriculum',
      description: 'Advanced trade and investment across the Pacific.',
      curriculum: [
        'International trade finance',
        'Supply chain economics',
        'Currency risk',
        'Regional compliance',
      ],
      pricing: {
        currency: 'USD',
        monthly: 22,
        annual: 219,
        quarterly: 59,
        lifetime: 799,
      },
    },
    es: {} as any,
    fr: {} as any,
    de: {} as any,
    pt: {} as any,
    ar: {} as any,
    zh: {} as any,
    ja: {} as any,
    ko: {} as any,
  },

  mena: {
    en: {
      title: 'MENA Curriculum',
      description: 'Finance and business for Middle East & North Africa.',
      curriculum: [
        'Islamic finance basics',
        'Energy economics',
        'Regional trade',
        'Family office structures',
      ],
      pricing: {
        currency: 'USD',
        monthly: 20,
        annual: 199,
        quarterly: 55,
        lifetime: 749,
      },
    },
    es: {} as any,
    fr: {} as any,
    de: {} as any,
    pt: {} as any,
    ar: {} as any,
    zh: {} as any,
    ja: {} as any,
    ko: {} as any,
  },
};
