/**
 * LATAM Country Configuration
 *
 * All countries in Latin America and the Caribbean.
 * Structured using the shared CountryConfig interface from the global framework.
 *
 * Launch status defaults to "PRIVATE" for every country unless explicitly overridden.
 * Countries can be individually promoted via the launchControl.countryOverrides
 * in the LATAM region config.
 *
 * Sub-regions:
 *  - central-america  (Mexico + Central American Isthmus)
 *  - south-america    (South American continent + Guianas)
 *  - caribbean        (Island nations and territories)
 */

import type { CountryConfig } from "@/lib/global/regional-framework";

// ─────────────────────────────────────────────
// Central America
// ─────────────────────────────────────────────

export const CENTRAL_AMERICA_COUNTRIES: CountryConfig[] = [
  {
    code: "mx",
    name: "Mexico",
    nativeName: "México",
    iso2: "MX",
    currency: "MXN",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Mexico_City",
    subRegion: "central-america",
  },
  {
    code: "gt",
    name: "Guatemala",
    nativeName: "Guatemala",
    iso2: "GT",
    currency: "GTQ",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Guatemala",
    subRegion: "central-america",
  },
  {
    code: "bz",
    name: "Belize",
    nativeName: "Belize",
    iso2: "BZ",
    currency: "BZD",
    defaultLanguage: "en",
    languages: ["en", "es"],
    timezone: "America/Belize",
    subRegion: "central-america",
  },
  {
    code: "sv",
    name: "El Salvador",
    nativeName: "El Salvador",
    iso2: "SV",
    currency: "USD",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/El_Salvador",
    subRegion: "central-america",
  },
  {
    code: "hn",
    name: "Honduras",
    nativeName: "Honduras",
    iso2: "HN",
    currency: "HNL",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Tegucigalpa",
    subRegion: "central-america",
  },
  {
    code: "ni",
    name: "Nicaragua",
    nativeName: "Nicaragua",
    iso2: "NI",
    currency: "NIO",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Managua",
    subRegion: "central-america",
  },
  {
    code: "cr",
    name: "Costa Rica",
    nativeName: "Costa Rica",
    iso2: "CR",
    currency: "CRC",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Costa_Rica",
    subRegion: "central-america",
  },
  {
    code: "pa",
    name: "Panama",
    nativeName: "Panamá",
    iso2: "PA",
    currency: "USD",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Panama",
    subRegion: "central-america",
  },
];

// ─────────────────────────────────────────────
// South America
// ─────────────────────────────────────────────

export const SOUTH_AMERICA_COUNTRIES: CountryConfig[] = [
  {
    code: "co",
    name: "Colombia",
    nativeName: "Colombia",
    iso2: "CO",
    currency: "COP",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Bogota",
    subRegion: "south-america",
  },
  {
    code: "ve",
    name: "Venezuela",
    nativeName: "Venezuela",
    iso2: "VE",
    currency: "VES",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Caracas",
    subRegion: "south-america",
  },
  {
    code: "ec",
    name: "Ecuador",
    nativeName: "Ecuador",
    iso2: "EC",
    currency: "USD",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Guayaquil",
    subRegion: "south-america",
  },
  {
    code: "pe",
    name: "Peru",
    nativeName: "Perú",
    iso2: "PE",
    currency: "PEN",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Lima",
    subRegion: "south-america",
  },
  {
    code: "bo",
    name: "Bolivia",
    nativeName: "Bolivia",
    iso2: "BO",
    currency: "BOB",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/La_Paz",
    subRegion: "south-america",
  },
  {
    code: "cl",
    name: "Chile",
    nativeName: "Chile",
    iso2: "CL",
    currency: "CLP",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Santiago",
    subRegion: "south-america",
  },
  {
    code: "ar",
    name: "Argentina",
    nativeName: "Argentina",
    iso2: "AR",
    currency: "ARS",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Argentina/Buenos_Aires",
    subRegion: "south-america",
  },
  {
    code: "uy",
    name: "Uruguay",
    nativeName: "Uruguay",
    iso2: "UY",
    currency: "UYU",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Montevideo",
    subRegion: "south-america",
  },
  {
    code: "py",
    name: "Paraguay",
    nativeName: "Paraguay",
    iso2: "PY",
    currency: "PYG",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Asuncion",
    subRegion: "south-america",
  },
  {
    code: "br",
    name: "Brazil",
    nativeName: "Brasil",
    iso2: "BR",
    currency: "BRL",
    defaultLanguage: "pt",
    languages: ["pt"],
    timezone: "America/Sao_Paulo",
    subRegion: "south-america",
  },
  {
    code: "gy",
    name: "Guyana",
    nativeName: "Guyana",
    iso2: "GY",
    currency: "GYD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/Guyana",
    subRegion: "south-america",
  },
  {
    code: "sr",
    name: "Suriname",
    nativeName: "Suriname",
    iso2: "SR",
    currency: "SRD",
    defaultLanguage: "nl",
    languages: ["nl", "en"],
    timezone: "America/Paramaribo",
    subRegion: "south-america",
  },
  {
    code: "gf",
    name: "French Guiana",
    nativeName: "Guyane française",
    iso2: "GF",
    currency: "EUR",
    defaultLanguage: "fr",
    languages: ["fr"],
    timezone: "America/Cayenne",
    subRegion: "south-america",
  },
];

// ─────────────────────────────────────────────
// Caribbean
// ─────────────────────────────────────────────

export const CARIBBEAN_COUNTRIES: CountryConfig[] = [
  {
    code: "do",
    name: "Dominican Republic",
    nativeName: "República Dominicana",
    iso2: "DO",
    currency: "DOP",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Santo_Domingo",
    subRegion: "caribbean",
  },
  {
    code: "pr",
    name: "Puerto Rico",
    nativeName: "Puerto Rico",
    iso2: "PR",
    currency: "USD",
    defaultLanguage: "es",
    languages: ["es", "en"],
    timezone: "America/Puerto_Rico",
    subRegion: "caribbean",
  },
  {
    code: "cu",
    name: "Cuba",
    nativeName: "Cuba",
    iso2: "CU",
    currency: "CUP",
    defaultLanguage: "es",
    languages: ["es"],
    timezone: "America/Havana",
    subRegion: "caribbean",
  },
  {
    code: "jm",
    name: "Jamaica",
    nativeName: "Jamaica",
    iso2: "JM",
    currency: "JMD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/Jamaica",
    subRegion: "caribbean",
  },
  {
    code: "ht",
    name: "Haiti",
    nativeName: "Haïti",
    iso2: "HT",
    currency: "HTG",
    defaultLanguage: "fr",
    languages: ["fr"],
    timezone: "America/Port-au-Prince",
    subRegion: "caribbean",
  },
  {
    code: "tt",
    name: "Trinidad and Tobago",
    nativeName: "Trinidad and Tobago",
    iso2: "TT",
    currency: "TTD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/Port_of_Spain",
    subRegion: "caribbean",
  },
  // ── Remaining Caribbean jurisdictions ─────
  // Full data pending — structure is complete and extensible
  {
    code: "bb",
    name: "Barbados",
    nativeName: "Barbados",
    iso2: "BB",
    currency: "USD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/Barbados",
    subRegion: "caribbean",
  },
  {
    code: "bs",
    name: "Bahamas",
    nativeName: "Bahamas",
    iso2: "BS",
    currency: "USD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/Nassau",
    subRegion: "caribbean",
  },
  {
    code: "ag",
    name: "Antigua and Barbuda",
    nativeName: "Antigua and Barbuda",
    iso2: "AG",
    currency: "USD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/Antigua",
    subRegion: "caribbean",
  },
  {
    code: "dm",
    name: "Dominica",
    nativeName: "Dominica",
    iso2: "DM",
    currency: "USD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/Dominica",
    subRegion: "caribbean",
  },
  {
    code: "gd",
    name: "Grenada",
    nativeName: "Grenada",
    iso2: "GD",
    currency: "USD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/Grenada",
    subRegion: "caribbean",
  },
  {
    code: "kn",
    name: "Saint Kitts and Nevis",
    nativeName: "Saint Kitts and Nevis",
    iso2: "KN",
    currency: "USD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/St_Kitts",
    subRegion: "caribbean",
  },
  {
    code: "lc",
    name: "Saint Lucia",
    nativeName: "Saint Lucia",
    iso2: "LC",
    currency: "USD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/St_Lucia",
    subRegion: "caribbean",
  },
  {
    code: "vc",
    name: "Saint Vincent and the Grenadines",
    nativeName: "Saint Vincent and the Grenadines",
    iso2: "VC",
    currency: "USD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/St_Vincent",
    subRegion: "caribbean",
  },
  {
    code: "aw",
    name: "Aruba",
    nativeName: "Aruba",
    iso2: "AW",
    currency: "USD",
    defaultLanguage: "nl",
    languages: ["nl", "en"],
    timezone: "America/Aruba",
    subRegion: "caribbean",
  },
  {
    code: "cw",
    name: "Curaçao",
    nativeName: "Curaçao",
    iso2: "CW",
    currency: "USD",
    defaultLanguage: "nl",
    languages: ["nl", "en"],
    timezone: "America/Curacao",
    subRegion: "caribbean",
  },
  {
    code: "sx",
    name: "Sint Maarten",
    nativeName: "Sint Maarten",
    iso2: "SX",
    currency: "USD",
    defaultLanguage: "nl",
    languages: ["nl", "en"],
    timezone: "America/Lower_Princes",
    subRegion: "caribbean",
  },
  {
    code: "bq",
    name: "Caribbean Netherlands",
    nativeName: "Caribisch Nederland",
    iso2: "BQ",
    currency: "USD",
    defaultLanguage: "nl",
    languages: ["nl", "en"],
    timezone: "America/Kralendijk",
    subRegion: "caribbean",
  },
  {
    code: "tc",
    name: "Turks and Caicos Islands",
    nativeName: "Turks and Caicos Islands",
    iso2: "TC",
    currency: "USD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/Grand_Turk",
    subRegion: "caribbean",
  },
  {
    code: "ky",
    name: "Cayman Islands",
    nativeName: "Cayman Islands",
    iso2: "KY",
    currency: "USD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/Cayman",
    subRegion: "caribbean",
  },
  {
    code: "vg",
    name: "British Virgin Islands",
    nativeName: "British Virgin Islands",
    iso2: "VG",
    currency: "USD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/Tortola",
    subRegion: "caribbean",
  },
  {
    code: "vi",
    name: "US Virgin Islands",
    nativeName: "US Virgin Islands",
    iso2: "VI",
    currency: "USD",
    defaultLanguage: "en",
    languages: ["en"],
    timezone: "America/St_Thomas",
    subRegion: "caribbean",
  },
  {
    code: "mq",
    name: "Martinique",
    nativeName: "Martinique",
    iso2: "MQ",
    currency: "EUR",
    defaultLanguage: "fr",
    languages: ["fr"],
    timezone: "America/Martinique",
    subRegion: "caribbean",
  },
  {
    code: "gp",
    name: "Guadeloupe",
    nativeName: "Guadeloupe",
    iso2: "GP",
    currency: "EUR",
    defaultLanguage: "fr",
    languages: ["fr"],
    timezone: "America/Guadeloupe",
    subRegion: "caribbean",
  },
];

// ─────────────────────────────────────────────
// Combined
// ─────────────────────────────────────────────

export const ALL_LATAM_COUNTRIES: CountryConfig[] = [
  ...CENTRAL_AMERICA_COUNTRIES,
  ...SOUTH_AMERICA_COUNTRIES,
  ...CARIBBEAN_COUNTRIES,
];

export const ALL_LATAM_COUNTRY_CODES = ALL_LATAM_COUNTRIES.map((c) => c.code);
