const copy = {
 en: { tools:"Interactive Tools", eyebrow:"Business Skills Lab", title:"Financial Statements Toolkit", intro:"Learn how the income statement, balance sheet, and cash flow statement work together to describe a business.", sample:"Annotated example", samplePeriod:"Illustrative business — year ended December 31", incomeStatement:{title:"Income Statement",description:"Shows revenue, expenses, and whether the business generated a profit."}, balanceSheet:{title:"Balance Sheet",description:"Shows what the business owns, owes, and the owners' remaining equity."}, cashFlowStatement:{title:"Cash Flow Statement",description:"Explains where cash came from, where it went, and why profit is not the same as cash."}, line:{revenue:"Revenue",cogs:"Cost of Goods Sold",grossProfit:"Gross Profit",operatingExpenses:"Operating Expenses",operatingIncome:"Operating Income",interest:"Interest",taxes:"Taxes",netIncome:"Net Income"}, explain:{revenue:"20,000 transactions × $50 average sale = $1,000,000.",cogs:"Direct costs associated with producing the goods or services sold.",grossProfit:"Revenue minus cost of goods sold.",operatingExpenses:"Costs of running the business beyond direct production costs.",operatingIncome:"Gross profit minus operating expenses.",interest:"Cost of borrowed money during the period.",taxes:"Illustrative taxes attributed to the period.",netIncome:"What remains after the illustrated expenses, interest, and taxes."}, ownerQuestion:{title:"Think like the owner",body:"The company reports $100,000 of net income. Does that mean it has $100,000 in the bank? Examine cash flow before deciding."}, disclaimer:"Educational illustration only. Actual accounting treatment varies by business, jurisdiction, accounting method, and circumstances." },
 es: { tools:"Herramientas interactivas", eyebrow:"Laboratorio de habilidades empresariales", title:"Kit de estados financieros", intro:"Aprende cómo el estado de resultados, el balance general y el estado de flujo de efectivo trabajan juntos para describir un negocio.", sample:"Ejemplo explicado", samplePeriod:"Negocio ilustrativo — año terminado el 31 de diciembre", incomeStatement:{title:"Estado de resultados",description:"Muestra ingresos, gastos y si el negocio generó ganancias."}, balanceSheet:{title:"Balance general",description:"Muestra lo que el negocio posee, lo que debe y el patrimonio restante de los propietarios."}, cashFlowStatement:{title:"Estado de flujo de efectivo",description:"Explica de dónde vino el efectivo, adónde fue y por qué la ganancia no equivale al efectivo."}, line:{revenue:"Ingresos",cogs:"Costo de los bienes vendidos",grossProfit:"Ganancia bruta",operatingExpenses:"Gastos operativos",operatingIncome:"Ingreso operativo",interest:"Intereses",taxes:"Impuestos",netIncome:"Ingreso neto"}, explain:{revenue:"20,000 transacciones × $50 de venta promedio = $1,000,000.",cogs:"Costos directos asociados con producir los bienes o servicios vendidos.",grossProfit:"Ingresos menos el costo de los bienes vendidos.",operatingExpenses:"Costos de operar el negocio aparte de los costos directos de producción.",operatingIncome:"Ganancia bruta menos gastos operativos.",interest:"Costo del dinero prestado durante el período.",taxes:"Impuestos ilustrativos atribuidos al período.",netIncome:"Lo que queda después de los gastos, intereses e impuestos ilustrados."}, ownerQuestion:{title:"Piensa como propietario",body:"La empresa reporta $100,000 de ingreso neto. ¿Significa que tiene $100,000 en el banco? Examina el flujo de efectivo antes de decidir."}, disclaimer:"Ejemplo educativo solamente. El tratamiento contable real varía según el negocio, la jurisdicción, el método contable y las circunstancias." },
} as const;

type Deep = any;
export function financialToolkitText(language: string, path: string): string {
 const locale = language.toLowerCase().startsWith("es") ? "es" : "en";
 const get = (obj: Deep) => path.split(".").reduce((value, key) => value?.[key], obj);
 return get(copy[locale]) ?? get(copy.en) ?? path;
}
