import type {Metadata} from "next";import Link from "next/link";import{notFound}from"next/navigation";import{isPublicCurriculumTrack}from"@/lib/curriculum/localization";import{getPublishedTrack}from"@/lib/curriculum/public-safe";import{getServerLanguage}from"@/lib/international/server";
export const dynamic="force-dynamic";interface Props{params:Promise<{track:string}>}
const LEVELS=["Financial Literacy","Financial Competency","Applied Reasoning","Strategic Integration","Financial Intelligence"];
const DESC:Record<string,string>={RED:"Learn how property works as an investment, a business, and a wealth-building asset.",WHITE:"Understand stocks, bonds, funds, retirement accounts, and financial markets.",BLUE:"Understand how businesses create value, operate, compete, and grow.",GREEN:"Build practical skills for personal finance, taxes, credit, and planning.",GOLD:"Understand investing principles, terminology, analysis, and risk.",PURPLE:"Understand legal concepts affecting money, property, business, and agreements.",ORANGE:"Build practical sales, customer, marketing, and communication knowledge.",BLACK:"Develop leadership, management, accountability, and decision-making skills."};
const ACCENT:Record<string,string>={RED:"from-red-950 via-red-900 to-slate-950",WHITE:"from-slate-900 via-slate-800 to-slate-950",BLUE:"from-blue-950 via-blue-900 to-slate-950",GREEN:"from-emerald-950 via-emerald-900 to-slate-950",GOLD:"from-amber-950 via-amber-900 to-slate-950",PURPLE:"from-purple-950 via-purple-900 to-slate-950",ORANGE:"from-orange-950 via-orange-900 to-slate-950",BLACK:"from-slate-950 via-slate-900 to-black"};
export async function generateMetadata({params}:Props):Promise<Metadata>{const{track:raw}=await params;const language=await getServerLanguage();const track=await getPublishedTrack(raw.toUpperCase(),language);return{title:track?`${track.name} (${track.code}) | Edunancial`:"Track Not Found | Edunancial"}}
export default async function TrackPage({params}:Props){const{track:raw}=await params;const code=raw.toUpperCase();if(!isPublicCurriculumTrack(code))notFound();const language=await getServerLanguage();const track=await getPublishedTrack(code,language);if(!track)notFound();return <main className="min-h-screen bg-[#f7f8fb] text-slate-950">
<section className={`bg-gradient-to-r ${ACCENT[code]??ACCENT.BLACK} text-white`}><div className="mx-auto max-w-7xl px-6 py-12 md:py-16"><Link href="/curriculum" className="text-sm text-white/70">Curriculum</Link><p className="mt-8 text-sm font-black tracking-[.3em] text-red-200">{code} TRACK</p><h1 className="mt-3 text-5xl font-black md:text-6xl">{track.name}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/80">{DESC[code]}</p><p className="mt-5 font-bold text-yellow-300">{track.lessonCount} lessons currently available</p></div></section>
<div className="border-b bg-white"><div className="mx-auto flex max-w-7xl gap-7 overflow-x-auto px-6 py-5 text-sm font-bold"><span className="text-blue-700">Overview</span><span>Lessons</span><span>Case Studies</span><span>Resources</span><span>Flashcards</span></div></div>
<section className="mx-auto max-w-7xl px-6 py-10"><div className="grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><div><h2 className="text-3xl font-black">What You’ll Learn</h2><p className="mt-3 max-w-3xl leading-7 text-slate-600">Build knowledge across five structured levels, then apply it to increasingly realistic financial decisions. Your membership determines the levels available to you, while earlier levels remain available for review.</p></div><aside className="rounded-xl border border-blue-100 bg-blue-50 p-5"><p className="text-sm font-black uppercase tracking-[.2em] text-blue-700">Real-World Focus</p><p className="mt-3 leading-7 text-slate-700">Learn concepts in context and practice applying them to decisions—not promises, predictions, or personalized investment advice.</p></aside></div>
<div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[1,2,3,4,5].map(n=>{const found=track.levels.find(l=>l.level===n);const count=found?.lessonCount??0;return <Link key={n} href={`/curriculum/${raw}/l${n}`} className="group rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-md"><p className="text-xs font-black uppercase tracking-wider text-blue-700">Level {n}</p><h3 className="mt-2 text-lg font-black">{LEVELS[n-1]}</h3><p className="mt-3 text-sm text-slate-500">{count>0?`${count} lessons available`:"Curriculum in development"}</p>{count>0&&<p className="mt-4 text-sm font-bold text-blue-700">{n===1?"Preview / open lessons →":"Open level →"}</p>}</Link>})}</div>
</section></main>}
