"use client";

import Link from "next/link";
import { useInternationalPreferences } from "@/components/international/InternationalPreferencesProvider";
import { getHomeMarketingCopy } from "@/lib/international/home-marketing-copy";
import { getHomeUiCopy } from "@/lib/international/home-ui-copy";

const featureIcons=["◈","▱","◎","▥"] as const;
const goals=["business","realEstate","retirement","finances","career","family"] as const;
const trackVisuals=["🏠","📄","🏢","🌱","🪙","⚖️","📣","♟️"];
const goalVisuals=["💻","🏡","🌅","💳","💼","👨‍👩‍👧‍👦"];

export default function HomePageClient(){
 const {effectiveLanguage}=useInternationalPreferences(); const copy=getHomeMarketingCopy(effectiveLanguage); const ui=getHomeUiCopy(effectiveLanguage);
 return <main className="bg-white text-[#071426]">
  <section className="relative isolate h-[350px] overflow-hidden bg-[#08213a] text-white sm:h-[390px]"><img src="/approved-home-hero.svg" alt="" className="absolute inset-0 h-full w-full object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-[#071426]/95 via-[#071426]/55 to-transparent"/><div className="relative mx-auto flex h-full max-w-[1440px] items-center px-5 sm:px-8 lg:px-16"><div className="max-w-[590px]"><h1 className="text-[36px] font-black leading-[.98] tracking-[-.035em] sm:text-[50px]">{copy.heroTitle}</h1><p className="mt-3 max-w-[530px] text-[15px] leading-6 sm:text-base">{copy.heroBody}</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/curriculum" className="rounded-md bg-yellow-300 px-7 py-3 text-[13px] font-black text-slate-950">{copy.startFree}</Link><Link href="/assessment" className="rounded-md border border-white/90 bg-[#071426]/45 px-7 py-3 text-[13px] font-bold">{copy.takeAssessment}</Link></div></div></div></section>
  <section className="border-b border-slate-200"><div className="mx-auto grid max-w-[1440px] grid-cols-2 md:grid-cols-4">{ui.features.map(([title,body],i)=><div key={title} className="flex min-h-[72px] items-center gap-3 border-r border-slate-200 px-4"><span aria-hidden className="text-2xl text-sky-500">{featureIcons[i]}</span><div><h2 className="text-[13px] font-black">{title}</h2><p className="text-[11px] text-slate-600">{body}</p></div></div>)}</div></section>
  <section className="mx-auto max-w-[1440px] px-5 py-5 sm:px-8 lg:px-16"><div className="flex items-end justify-between"><div><h2 className="text-[25px] font-black">{copy.colorTitle}</h2><p className="text-[13px] text-slate-600">{copy.colorLabel}</p></div><Link href="/curriculum" className="text-[13px] font-bold text-sky-600">{copy.explorePathway} →</Link></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-8">{copy.tracks.map((track,i)=><Link href={track.href} key={track.code} className={`overflow-hidden rounded-md border shadow-sm transition hover:-translate-y-0.5 ${track.className}`}><div className="flex h-[72px] items-center justify-center bg-white/90 text-4xl" aria-hidden>{trackVisuals[i]}</div><div className="min-h-[68px] p-2"><h3 className="text-[13px] font-black leading-4">{track.title}</h3></div></Link>)}</div></section>
  <section className="bg-gradient-to-b from-sky-50 to-white"><div className="mx-auto max-w-[1440px] px-5 py-4 sm:px-8 lg:px-16"><div className="text-center"><h2 className="text-[25px] font-black">{ui.goalsTitle}</h2><p className="text-[13px] text-slate-600">{ui.goalsBody}</p></div><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-3 lg:grid-cols-6">{goals.map((goal,i)=>{const [title,body]=ui.goals[goal];return <Link href={`/assessment?goal=${goal}`} key={goal} className="overflow-hidden rounded-md border border-slate-200 bg-white shadow-sm"><div className="flex h-[66px] items-center justify-center bg-slate-100 text-3xl" aria-hidden>{goalVisuals[i]}</div><div className="p-3"><div className="flex justify-between gap-1"><h3 className="text-[12px] font-black leading-4">{title}</h3><span>→</span></div><p className="mt-1 text-[11px] leading-[14px] text-slate-600">{body}</p></div></Link>})}</div><div className="mt-3 flex items-center justify-between gap-3 rounded-md bg-sky-100 px-5 py-3"><div><h3 className="text-[14px] font-black">{copy.assessmentLabel}</h3><p className="text-[12px] text-slate-600">{copy.assessmentBody}</p></div><Link href="/assessment" className="shrink-0 rounded-md bg-blue-600 px-7 py-3 text-[12px] font-bold text-white">{copy.assessmentCta}</Link></div></div></section>
 </main>;
}
