"use client";

import Link from "next/link";
import { useInternationalPreferences } from "@/components/international/InternationalPreferencesProvider";
import { getHomeMarketingCopy } from "@/lib/international/home-marketing-copy";
import { getRecentPositioningCopy } from "@/lib/international/recent-positioning-copy";

export default function HomePageClient() {
  const { effectiveLanguage, t } = useInternationalPreferences();
  const copy = getHomeMarketingCopy(effectiveLanguage);
  const positioning = getRecentPositioningCopy(effectiveLanguage);
  const { label: pathwayLabel, title: pathwayTitle, steps: journeySteps } = positioning.pathway;

  return (
    <main className="min-h-screen bg-[#08101f] text-white">
      <section aria-labelledby="homepage-hero-heading" className="border-b border-white/10 bg-gradient-to-b from-[#08101f] via-[#0d1730] to-[#08101f]">
        <div className="mx-auto max-w-7xl px-6 py-20 md:py-28"><div className="mx-auto max-w-5xl text-center">
          <p className="text-xs font-black uppercase tracking-[0.45em] text-yellow-300 md:text-sm">{copy.heroEyebrow}</p><h1 id="homepage-hero-heading" className="mt-6 text-5xl font-black leading-tight sm:text-6xl md:text-7xl">{copy.heroTitle}</h1><p className="mx-auto mt-7 max-w-4xl text-xl leading-9 text-slate-200">{copy.heroBody}</p>
          <div className="mt-10 flex flex-col justify-center gap-4 sm:flex-row"><Link href="/curriculum" className="inline-flex items-center justify-center rounded-xl bg-yellow-400 px-8 py-4 text-lg font-black text-black transition hover:bg-yellow-300">{copy.startFree}</Link><Link href="/assessment" className="inline-flex items-center justify-center rounded-xl bg-blue-600 px-8 py-4 text-lg font-bold text-white transition hover:bg-blue-700">{copy.takeAssessment}</Link></div><p className="mx-auto mt-6 max-w-3xl text-sm leading-7 text-slate-400">{copy.freeAccessNote}</p>
        </div></div>
      </section>
      <section aria-labelledby="problem-heading" className="mx-auto max-w-7xl px-6 py-16 md:py-20"><div className="mx-auto max-w-5xl text-center"><p className="text-sm font-bold uppercase tracking-[0.4em] text-yellow-400">{copy.whyLabel}</p><h2 id="problem-heading" className="mt-4 text-4xl font-black md:text-5xl">{copy.whyTitle}</h2><p className="mx-auto mt-6 max-w-4xl text-lg leading-8 text-slate-300">{copy.whyBody}</p></div><div className="mt-10 grid gap-6 md:grid-cols-3">{copy.barriers.map(([title, body]) => <div key={title} className="rounded-2xl border border-white/10 bg-white/5 p-7"><h3 className="text-2xl font-black text-yellow-300">{title}</h3><p className="mt-4 leading-7 text-slate-300">{body}</p></div>)}</div></section>
      <section aria-labelledby="pathways-heading" className="border-y border-white/10 bg-slate-950/60"><div className="mx-auto max-w-7xl px-6 py-16 md:py-20"><p className="text-sm font-bold uppercase tracking-[0.4em] text-yellow-400">{pathwayLabel}</p><h2 id="pathways-heading" className="mt-4 text-4xl font-black md:text-5xl">{pathwayTitle}</h2><p className="mt-5 max-w-4xl text-lg leading-8 text-slate-300">{copy.colorBody}</p><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{copy.tracks.map((track) => <Link key={track.code} href={track.href} className={`rounded-2xl border p-6 transition hover:-translate-y-1 ${track.className}`}><p className="text-xs font-black tracking-[0.35em] text-slate-300">{track.code}</p><h3 className="mt-3 text-2xl font-black">{track.title}</h3><p className="mt-3 text-sm leading-7 text-slate-300">{track.body}</p><p className="mt-5 text-sm font-bold text-yellow-300">{copy.explorePathway}</p></Link>)}</div></div></section>
      <section aria-labelledby="journey-heading" className="mx-auto max-w-7xl px-6 py-16 md:py-20"><div className="rounded-3xl border border-blue-400/20 bg-blue-500/10 p-8 md:p-10"><p className="text-sm font-bold uppercase tracking-[0.4em] text-blue-300">{copy.journeyLabel}</p><h2 id="journey-heading" className="mt-4 text-4xl font-black md:text-5xl">{copy.journeyTitle}</h2><p className="mt-6 max-w-4xl text-lg leading-8 text-slate-200">{copy.journeyBody}</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{journeySteps.map((step, index) => <div key={step} className="rounded-xl border border-white/10 bg-slate-950/40 p-5"><p className="text-xs font-black text-blue-300">{copy.levelLabel} {index + 1}+</p><p className="mt-2 font-black">{step}</p></div>)}</div></div></section>
      <section aria-labelledby="assessment-heading" className="mx-auto max-w-7xl px-6 pb-16 md:pb-20"><div className="grid gap-8 rounded-3xl border border-yellow-400/30 bg-yellow-400/10 p-8 md:p-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.4em] text-yellow-300">{copy.assessmentLabel}</p><h2 id="assessment-heading" className="mt-4 text-3xl font-black sm:text-4xl">{copy.assessmentTitle}</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-200">{copy.assessmentBody}</p></div><Link href="/assessment" className="inline-flex items-center justify-center rounded-xl bg-yellow-400 px-7 py-4 text-center font-black text-black transition hover:bg-yellow-300">{copy.assessmentCta}</Link></div></section>
      <section aria-labelledby="trust-heading" className="border-y border-white/10 bg-slate-950/60"><div className="mx-auto max-w-7xl px-6 py-16 md:py-20"><div className="grid gap-10 lg:grid-cols-2 lg:items-start"><div><p className="text-sm font-bold uppercase tracking-[0.4em] text-yellow-400">{copy.trustLabel}</p><h2 id="trust-heading" className="mt-4 text-4xl font-black">{copy.trustTitle}</h2><p className="mt-6 text-lg leading-8 text-slate-300">{copy.trustBody}</p><div className="mt-7 flex flex-wrap gap-4"><Link href="/our-story" className="font-bold text-blue-300 hover:text-blue-200">{copy.storyLink}</Link><Link href="/mission" className="font-bold text-blue-300 hover:text-blue-200">{copy.missionLink}</Link></div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-7"><h3 className="text-2xl font-black">{copy.noticeTitle}</h3><p className="mt-4 leading-7 text-slate-300">{copy.noticeBody}</p><p className="mt-4 text-sm leading-7 text-slate-400">{t("branding.methodsClarification")}</p></div></div></div></section>
      <section aria-labelledby="membership-heading" className="mx-auto max-w-7xl px-6 py-16 md:py-20"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[0.4em] text-yellow-400">{copy.membershipLabel}</p><h2 id="membership-heading" className="mt-4 text-4xl font-black md:text-5xl">{copy.membershipTitle}</h2></div><div className="mt-10 grid gap-6 md:grid-cols-3">{copy.plans.map(([plan, title, levels, body]) => <div key={plan} className="rounded-2xl border border-white/10 bg-white/5 p-7"><p className="text-sm font-black tracking-[0.3em] text-yellow-300">{plan}</p><h3 className="mt-3 text-2xl font-black">{title}</h3><p className="mt-2 font-bold text-blue-300">{levels}</p><p className="mt-4 leading-7 text-slate-300">{body}</p></div>)}</div><div className="mt-8 text-center"><Link href="/membership" className="inline-flex items-center justify-center rounded-xl bg-blue-600 px-8 py-4 text-lg font-bold hover:bg-blue-700">{copy.comparePlans}</Link></div></section>
      <section aria-labelledby="final-heading" className="mx-auto max-w-7xl px-6 pb-20"><div className="rounded-3xl border border-blue-500/30 bg-blue-500/10 p-8 text-center md:p-12"><p className="text-sm font-bold uppercase tracking-[0.4em] text-blue-300">{copy.finalLabel}</p><h2 id="final-heading" className="mt-4 text-4xl font-black md:text-5xl">{copy.finalTitle}</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-slate-200">{copy.finalBody}</p><div className="mt-8 flex flex-col justify-center gap-4 sm:flex-row"><Link href="/curriculum" className="rounded-xl bg-yellow-400 px-8 py-4 font-black text-black hover:bg-yellow-300">{copy.startFree}</Link><Link href="/assessment" className="rounded-xl border border-white/40 px-8 py-4 font-bold hover:bg-white hover:text-slate-950">{copy.assessmentCta}</Link></div></div></section>
    </main>
  );
}
