import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import type { AdminContentStorage } from "@/lib/admin-content/storage/types";
import type { AuditEvent, BatchSummary, ExportPackage, UploadBatch } from "@/lib/admin-content/types";

function localRoot() { return process.env.EDUNANCIAL_CONTENT_STORE_ROOT?.trim() || join(process.cwd(), ".admin-content-store"); }
const INDEX_FILE = "index.json";
const AUDIT_FILE = "audit.json";
const STORAGE_BRANCH = "admin-content-storage";
const STORAGE_ROOT = ".edunancial-admin-content";

function ensureLocalRoot() { mkdirSync(localRoot(), { recursive: true }); }
function localPath(...parts: string[]) { ensureLocalRoot(); return join(localRoot(), ...parts); }
function readJsonFile<T>(path: string, fallback: T): T { return existsSync(path) ? JSON.parse(readFileSync(path, "utf8")) as T : fallback; }
function writeJsonFile(path: string, data: unknown) { const parent = dirname(path); if (parent) mkdirSync(parent, { recursive: true }); writeFileSync(path, JSON.stringify(data, null, 2)); }
function summarizeBatch(batch: UploadBatch): BatchSummary { return { id: batch.id, name: batch.name, slug: batch.slug, source: batch.source, status: batch.status, createdAt: batch.createdAt, updatedAt: batch.updatedAt, totalUploads: batch.uploads.length, totalFiles: batch.files.length, approvedFiles: batch.files.filter((f) => f.reviewStatus === "approved").length, rejectedFiles: batch.files.filter((f) => f.reviewStatus === "rejected").length, pendingFiles: batch.files.filter((f) => f.reviewStatus === "pending").length, conflicts: batch.files.filter((f) => f.conflictStatus !== "none").length }; }
function listLocalWorkspaceEntries() { if (!existsSync(localRoot())) return [] as string[]; return readdirSync(localRoot(), { recursive: true }).map(String).filter((entry) => { try { return statSync(join(localRoot(), entry)).isFile(); } catch { return false; } }).map((entry) => entry.replaceAll("\\", "/")); }

class LocalAdminContentStorage implements AdminContentStorage {
 async createBatch(batch: UploadBatch) { await this.updateBatch(batch); return batch; }
 async updateBatch(batch: UploadBatch) { writeJsonFile(localPath("batches", `${batch.id}.json`), batch); const current=readJsonFile<BatchSummary[]>(localPath(INDEX_FILE),[]); const next=current.filter(e=>e.id!==batch.id); next.unshift(summarizeBatch(batch)); writeJsonFile(localPath(INDEX_FILE),next); return batch; }
 async removeBatch(batchId:string){await this.deleteBinary(`batches/${batchId}.json`);} async updateBatchIndex(s:BatchSummary[]){writeJsonFile(localPath(INDEX_FILE),s);} async listBatches(){return readJsonFile<BatchSummary[]>(localPath(INDEX_FILE),[]);} async getBatch(id:string){return readJsonFile<UploadBatch|null>(localPath("batches",`${id}.json`),null);}
 async saveBinary(path:string,content:Buffer,_type:string){const target=localPath(path);mkdirSync(dirname(target),{recursive:true});writeFileSync(target,content);} async deleteBinary(path:string){rmSync(localPath(path),{force:true});} async readBinary(path:string){const target=localPath(path);return existsSync(target)?readFileSync(target):null;}
 async appendAuditEvent(event:AuditEvent){const current=readJsonFile<AuditEvent[]>(localPath(AUDIT_FILE),[]);current.unshift(event);writeJsonFile(localPath(AUDIT_FILE),current.slice(0,1000));} async listAuditHistory(batchId?:string){const all=readJsonFile<AuditEvent[]>(localPath(AUDIT_FILE),[]);return batchId?all.filter(e=>e.batchId===batchId):all;}
 async createExport(p:ExportPackage,a:Buffer){await this.saveBinary(p.storagePath,a,"application/zip");writeJsonFile(localPath("exports",`${p.id}.json`),p);return p;} async getSignedUploadUrl(_path:string):Promise<string|null>{return null;} async listWorkspaceEntries(){return listLocalWorkspaceEntries();}
}

class GithubAdminContentStorage implements AdminContentStorage {
 private readonly token=process.env.EDUNANCIAL_GITHUB_TOKEN?.trim()||""; private readonly owner=process.env.EDUNANCIAL_GITHUB_OWNER?.trim()||""; private readonly repo=process.env.EDUNANCIAL_GITHUB_REPO?.trim()||""; private branchReady=false;
 private headers(){if(!this.token||!this.owner||!this.repo)throw new Error("GitHub upload storage is not configured.");return{Accept:"application/vnd.github+json",Authorization:`Bearer ${this.token}`,"X-GitHub-Api-Version":"2022-11-28"};}
 private api(path:string){return `https://api.github.com/repos/${this.owner}/${this.repo}${path}`;}
 private key(path:string){return `${STORAGE_ROOT}/${path.replace(/^\/+/,"")}`;}
 private async ensureBranch(){if(this.branchReady)return;const h=this.headers();let r=await fetch(this.api(`/branches/${encodeURIComponent(STORAGE_BRANCH)}`),{headers:h,cache:"no-store"});if(r.status===404){const base=await fetch(this.api("/git/ref/heads/main"),{headers:h,cache:"no-store"});if(!base.ok)throw new Error(`Unable to read main for upload storage (HTTP ${base.status}).`);const b=await base.json() as {object:{sha:string}};r=await fetch(this.api("/git/refs"),{method:"POST",headers:{...h,"content-type":"application/json"},body:JSON.stringify({ref:`refs/heads/${STORAGE_BRANCH}`,sha:b.object.sha}),cache:"no-store"});if(!r.ok&&r.status!==422)throw new Error(`Unable to create upload storage branch (HTTP ${r.status}).`);}else if(!r.ok)throw new Error(`Unable to access upload storage branch (HTTP ${r.status}).`);this.branchReady=true;}
 private async getObject(path:string):Promise<{sha:string;content:string}|null>{await this.ensureBranch();const r=await fetch(this.api(`/contents/${this.key(path).split("/").map(encodeURIComponent).join("/")}?ref=${encodeURIComponent(STORAGE_BRANCH)}`),{headers:this.headers(),cache:"no-store"});if(r.status===404)return null;if(!r.ok)throw new Error(`GitHub upload storage read failed (HTTP ${r.status}).`);const d=await r.json() as {sha:string;content:string};return d;}
 private async put(path:string,content:Buffer,message:string){await this.ensureBranch();const existing=await this.getObject(path);const body:Record<string,string>={message,content:content.toString("base64"),branch:STORAGE_BRANCH};if(existing?.sha)body.sha=existing.sha;const r=await fetch(this.api(`/contents/${this.key(path).split("/").map(encodeURIComponent).join("/")}`),{method:"PUT",headers:{...this.headers(),"content-type":"application/json"},body:JSON.stringify(body),cache:"no-store"});if(!r.ok)throw new Error(`GitHub upload storage write failed (HTTP ${r.status}): ${await r.text().catch(()=>"")}`);}
 private async readJson<T>(path:string,fallback:T):Promise<T>{const o=await this.getObject(path);return o?JSON.parse(Buffer.from(o.content.replace(/\s/g,""),"base64").toString("utf8")) as T:fallback;} private async writeJson(path:string,value:unknown){await this.put(path,Buffer.from(JSON.stringify(value,null,2),"utf8"),`Persist admin upload state: ${path}`);}
 async createBatch(batch:UploadBatch){await this.updateBatch(batch);return batch;} async updateBatch(batch:UploadBatch){await this.writeJson(`batches/${batch.id}.json`,batch);const current=await this.readJson<BatchSummary[]>(INDEX_FILE,[]);const next=current.filter(e=>e.id!==batch.id);next.unshift(summarizeBatch(batch));await this.writeJson(INDEX_FILE,next);return batch;}
 async removeBatch(batchId:string){await this.deleteBinary(`batches/${batchId}.json`);} async updateBatchIndex(s:BatchSummary[]){await this.writeJson(INDEX_FILE,s);} async listBatches(){return this.readJson<BatchSummary[]>(INDEX_FILE,[]);} async getBatch(id:string){return this.readJson<UploadBatch|null>(`batches/${id}.json`,null);}
 async saveBinary(path:string,content:Buffer,_type:string){await this.put(path,content,`Stage admin upload: ${path.split("/").pop()??"file"}`);} async readBinary(path:string){const o=await this.getObject(path);return o?Buffer.from(o.content.replace(/\s/g,""),"base64"):null;}
 async deleteBinary(path:string){const o=await this.getObject(path);if(!o)return;const r=await fetch(this.api(`/contents/${this.key(path).split("/").map(encodeURIComponent).join("/")}`),{method:"DELETE",headers:{...this.headers(),"content-type":"application/json"},body:JSON.stringify({message:`Remove admin upload state: ${path}`,sha:o.sha,branch:STORAGE_BRANCH}),cache:"no-store"});if(!r.ok&&r.status!==404)throw new Error(`GitHub upload storage delete failed (HTTP ${r.status}).`);}
 async appendAuditEvent(event:AuditEvent){const current=await this.readJson<AuditEvent[]>(AUDIT_FILE,[]);current.unshift(event);await this.writeJson(AUDIT_FILE,current.slice(0,1000));} async listAuditHistory(batchId?:string){const all=await this.readJson<AuditEvent[]>(AUDIT_FILE,[]);return batchId?all.filter(e=>e.batchId===batchId):all;}
 async createExport(p:ExportPackage,a:Buffer){await this.saveBinary(p.storagePath,a,"application/zip");await this.writeJson(`exports/${p.id}.json`,p);return p;} async getSignedUploadUrl(_path:string):Promise<string|null>{return null;}
 async listWorkspaceEntries(){await this.ensureBranch();const ref=await fetch(this.api(`/git/ref/heads/${encodeURIComponent(STORAGE_BRANCH)}`),{headers:this.headers(),cache:"no-store"});if(!ref.ok)return[];const d=await ref.json() as {object:{sha:string}};const tree=await fetch(this.api(`/git/trees/${d.object.sha}?recursive=1`),{headers:this.headers(),cache:"no-store"});if(!tree.ok)return[];const t=await tree.json() as {tree:Array<{path:string;type:string}>};const prefix=`${STORAGE_ROOT}/`;return t.tree.filter(e=>e.type==="blob"&&e.path.startsWith(prefix)).map(e=>e.path.slice(prefix.length));}
}

let cachedStorage:AdminContentStorage|null=null;
export function getAdminContentStorage():AdminContentStorage{if(cachedStorage)return cachedStorage;cachedStorage=process.env.NODE_ENV==="production"?new GithubAdminContentStorage():new LocalAdminContentStorage();return cachedStorage;}
export function getLocalAdminStorageFiles(){return existsSync(localRoot())?readdirSync(localRoot(),{recursive:true}):[];} export function resetAdminContentStorage(){cachedStorage=null;rmSync(localRoot(),{recursive:true,force:true});}
