import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, relative } from "node:path";
import { classifyTranslationQuality } from "./lib/quality.mjs";

const ROOT=process.cwd(), OUT=join(ROOT,"content","generated","curriculum-index");
const TRACKS=["RED","WHITE","BLUE","GREEN","GOLD","PURPLE","ORANGE","BLACK"], LEVELS=[1,2,3,4,5];
const registry=JSON.parse(readFileSync(join(ROOT,"content","registries","locales.json"),"utf8"));
const LOCALES=[...new Set(["en-US",...registry.locales.filter(x=>x.status==="active").map(x=>x.locale)])];
function walk(d,o=[]){if(!existsSync(d))return o;for(const e of readdirSync(d,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){const p=join(d,e.name);if(e.isDirectory())walk(p,o);else o.push(p)}return o}
function norm(v){const x=String(v??"").replaceAll("_","-").toLowerCase();return({"en":"en-US","en-us":"en-US","en-gb":"en-GB","es-es":"es-ES","es-caribbean":"es-Caribbean","fr-fr":"fr-FR","fr-ca":"fr-CA","pt-pt":"pt-PT","pt-br":"pt-BR","it-it":"it"}[x]??x)}
function idOf(v){return String(v??"").toUpperCase().match(/(?:RED|WHITE|BLUE|GREEN|GOLD|PURPLE|ORANGE|BLACK)-L[1-5]-\d{3}/u)?.[0]}
function md(raw){let body=raw.trim(),meta={};if(body.startsWith("---")){const p=body.split("---");if(p.length>=3){for(const l of (p[1]??"").split(/\r?\n/u)){const i=l.indexOf(":");if(i>0)meta[l.slice(0,i).trim()]=l.slice(i+1).trim().replace(/^["']|["']$/g,"")}body=p.slice(2).join("---").trim()}}else{const lines=body.split(/\r?\n/u),labels={"Filename":"filename","Folder":"folder","Title":"title","Meta Description":"summary","SEO Keywords":"seoKeywords","Slug":"slug"};let i=0,h=0;while(i<lines.length){const line=lines[i];if(!line.trim()){if(h){i++;continue}break}const c=line.indexOf(":");if(c<0)break;const k=labels[line.slice(0,c).trim()];if(!k)break;meta[k]=line.slice(c+1).trim();h++;i++}if(h>=3)body=lines.slice(i).join("\n").trim()}return{body,meta}}
const byId=new Map();
function put(id,locale,row){const k=id+"|"+norm(locale),a=byId.get(k)??[];a.push(row);byId.set(k,a)}
for(const path of walk(join(ROOT,"content"))){if(path.includes("/generated/"))continue;if(path.endsWith(".md")){const raw=readFileSync(path,"utf8"),id=idOf(path+"\n"+raw);if(!id)continue;const parsed=md(raw),side=path.match(/\.([A-Za-z]{2}(?:-[A-Za-z0-9]+)?)\.md$/u)?.[1],seg=relative(ROOT,path).replaceAll("\\","/").split("/").find(x=>/^(en(?:[_-](?:us|gb))?|es(?:[_-](?:es|caribbean))?|fr(?:[_-](?:fr|ca))?|pt(?:[_-](?:pt|br))?|de|it|nl)$/iu.test(x));put(id,side??seg??"en-US",{...parsed,path:relative(ROOT,path)})}else if(path.endsWith(".json")){let x;try{x=JSON.parse(readFileSync(path,"utf8"))}catch{continue}const id=idOf(x.id??x.lesson_id??x.lessonId??path);if(!id)continue;if(x.translations)for(const [locale,v] of Object.entries(x.translations))if(v&&typeof v==="object")put(id,locale,{body:v.body??"",meta:{title:v.title??"",summary:v.summary??""},path:relative(ROOT,path),explicitStatus:v.status});if(x.locale)put(id,x.locale,{body:x.body??"",meta:{title:x.title??"",summary:x.summary??""},path:relative(ROOT,path),explicitStatus:x.status})}}
mkdirSync(OUT,{recursive:true});let total=0;
for(const track of TRACKS)for(const level of LEVELS)for(const locale of LOCALES){const rows=[];for(let lesson=1;lesson<=50;lesson++){const id=`${track}-L${level}-${String(lesson).padStart(3,"0")}`,base=(byId.get(id+"|en-US")??[])[0],candidates=byId.get(id+"|"+locale)??[];let source=locale==="en-US"?base:candidates[0],status=locale==="en-US"?(base?"canonical":"missing"):classifyTranslationQuality({body:source?.body,canonicalBody:base?.body,explicitStatus:source?.explicitStatus});if(!source&&status==="missing")continue;const body=source?.body??"";rows.push({id,track,level,lesson,locale,title:source?.meta?.title??"",summary:source?.meta?.summary??"",body,status,sourceHash:createHash("sha256").update(body).digest("hex"),origin:source?.path??""})}if(rows.length){const path=join(OUT,track,`L${level}`,`${locale}.json`);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(rows)+"\n");total+=rows.length}}
console.log(`[curriculum-index] compiled ${total} normalized lesson records`);
