from pathlib import Path
p=Path('src/lib/curriculum/authoritative-published.ts')
s=p.read_text()
old='async function effective(){const s=await readPublishedState(),registry=readRegistry(),all=process.env.EDUNANCIAL_ENABLE_LEGACY_CURRICULUM_REGISTRY_FALLBACK==="true";for(const t of Object.values(registry.tracks))for(const level of Object.values(t.levels))for(const a of Object.values(level.assets)){if(s.lessons[a.id])continue;if(!all&&a.level!==2)continue;const r=fromRegistry(a);if(r)s.lessons[r.id]=r}return s}'
new='async function effective(){const s=await readPublishedState(),registry=readRegistry(),all=process.env.EDUNANCIAL_ENABLE_LEGACY_CURRICULUM_REGISTRY_FALLBACK==="true";for(const t of Object.values(registry.tracks))for(const level of Object.values(t.levels))for(const a of Object.values(level.assets)){if(s.lessons[a.id])continue;if(!all&&a.level!==2)continue;const r=fromRegistry(a);if(r)s.lessons[r.id]=r}async function scan(dir:string){if(!existsSync(dir))return;for(const e of readdirSync(dir,{withFileTypes:true})){const p=join(dir,e.name);if(e.isDirectory()){await scan(p);continue}if(!e.name.endsWith(".md")||!p.includes(`${join("", "en_us")}`))continue;try{const raw=readFileSync(p,"utf8"),a=await detectCurriculumAsset(raw,e.name),r=detected(a,raw);if(r&&!s.lessons[r.id])s.lessons[r.id]=r}catch{}}}await scan(COURSE_CONTENT_DIR);return s}'
if old not in s: raise SystemExit('effective() contract not found')
s=s.replace(old,new)
old2='function detected(a:Awaited<ReturnType<typeof detectCurriculumAsset>>,raw:string):PublishedLessonRecord|null{if(!a||a.type!=="lesson"||!a.id||!a.track||!a.level||!a.number)return null;const p=parseFM(raw);return{id:a.id,track:a.track,trackName:trackName(a.track,a.trackName),level:a.level,lessonNumber:a.number,title:p.frontMatter.title??a.id,summary:p.frontMatter.summary??"",author:p.frontMatter.author??"Edunancial Faculty",date:p.frontMatter.date??new Date().toISOString().slice(0,10),version:p.frontMatter.version??"1.0",status:"active",importedAt:new Date().toISOString(),metadata:{officialTrackName:p.frontMatter.officialTrackName??a.trackName},path:a.canonicalPath,body:p.body,frontMatter:p.frontMatter}}'
new2='function detected(a:Awaited<ReturnType<typeof detectCurriculumAsset>>,raw:string):PublishedLessonRecord|null{if(!a||a.type!=="lesson"||!a.id||!a.track||!a.level||!a.number)return null;const p=parseFM(raw),fm=Object.keys(p.frontMatter).length?p.frontMatter:a.frontMatter;return{id:a.id,track:a.track,trackName:trackName(a.track,a.trackName),level:a.level,lessonNumber:a.number,title:fm.title??a.id,summary:fm.summary??"",author:fm.author??"Edunancial Faculty",date:fm.date??new Date().toISOString().slice(0,10),version:fm.version??"1.0",status:"active",importedAt:new Date().toISOString(),metadata:{officialTrackName:fm.officialTrackName??a.trackName},path:a.canonicalPath,body:p.body,frontMatter:fm}}'
if old2 not in s: raise SystemExit('detected() contract not found')
s=s.replace(old2,new2)
p.write_text(s)
