import type { GlobalRolloutConfig, ReadinessStatus } from "@/types/global-rollout";

const disabledReadiness: ReadinessStatus = {
  translationsReady: false,
  legalReviewReady: false,
  paymentReady: false,
  taxReady: false,
  privacyReady: false,
  contentReady: false,
  marketingReady: false,
  supportReady: false,
};

export const globalRolloutConfig: GlobalRolloutConfig = {
  continents: [
    { code: "north-america", name: "North America", enabled: true },
    { code: "caribbean", name: "Caribbean", enabled: false },
    { code: "latin-america", name: "Latin America", enabled: false },
    { code: "europe", name: "Europe", enabled: false },
    { code: "asia-pacific", name: "Asia-Pacific", enabled: false },
    { code: "africa", name: "Africa", enabled: false },
  ],
  regions: [
    {
      code: "north-america",
      continentCode: "north-america",
      name: "North America",
      enabled: true,
    },
    {
      code: "quebec",
      continentCode: "north-america",
      name: "Quebec",
      enabled: true,
    },
    {
      code: "caribbean",
      continentCode: "caribbean",
      name: "Caribbean",
      enabled: false,
    },
    {
      code: "latin-america",
      continentCode: "latin-america",
      name: "Latin America",
      enabled: false,
    },
    {
      code: "europe",
      continentCode: "europe",
      name: "Europe",
      enabled: false,
    },
    {
      code: "asia-pacific",
      continentCode: "asia-pacific",
      name: "Asia-Pacific",
      enabled: false,
    },
    {
      code: "africa",
      continentCode: "africa",
      name: "Africa",
      enabled: false,
    },
  ],
  languages: [
    { code: "en", name: "English", nativeName: "English", enabled: true },
    { code: "es", name: "Spanish", nativeName: "Español", enabled: true },
    { code: "fr", name: "French", nativeName: "Français", enabled: true },
    { code: "pt", name: "Portuguese", nativeName: "Português", enabled: false },
    { code: "ar", name: "Arabic", nativeName: "العربية", enabled: false },
    { code: "ja", name: "Japanese", nativeName: "日本語", enabled: false },
    { code: "ko", name: "Korean", nativeName: "한국어", enabled: false },
  ],
  currencies: [
    { code: "USD", name: "US Dollar", symbol: "$", enabled: true },
    { code: "CAD", name: "Canadian Dollar", symbol: "$", enabled: true },
    { code: "MXN", name: "Mexican Peso", symbol: "$", enabled: false },
    { code: "DOP", name: "Dominican Peso", symbol: "$", enabled: false },
    { code: "EUR", name: "Euro", symbol: "€", enabled: false },
    { code: "BRL", name: "Brazilian Real", symbol: "R$", enabled: false },
    { code: "UGX", name: "Ugandan Shilling", symbol: "USh", enabled: false },
    { code: "KES", name: "Kenyan Shilling", symbol: "KSh", enabled: false },
    { code: "ZAR", name: "South African Rand", symbol: "R", enabled: false },
    { code: "JPY", name: "Japanese Yen", symbol: "¥", enabled: false },
  ],
  taxProfiles: [
    {
      id: "us-sales-tax",
      name: "United States Sales Tax",
      description: "Supports state-based nexus and sales tax handling.",
    },
    {
      id: "canada-gst-hst",
      name: "Canada GST/HST",
      description: "Supports GST/HST calculation for Canadian provinces.",
    },
    {
      id: "quebec-gst-qst",
      name: "Quebec GST/QST",
      description: "Supports Quebec-specific GST/QST requirements.",
    },
    {
      id: "eu-vat",
      name: "European Union VAT",
      description: "GDPR-aligned VAT placeholder for future EU rollout.",
    },
    {
      id: "latam-placeholder",
      name: "Latin America Placeholder",
      description: "Reserved for future localized LATAM tax modeling.",
    },
    {
      id: "caribbean-placeholder",
      name: "Caribbean Placeholder",
      description: "Reserved for future Caribbean tax requirements.",
    },
    {
      id: "apac-placeholder",
      name: "Asia-Pacific Placeholder",
      description: "Reserved for future APAC tax requirements.",
    },
    {
      id: "africa-placeholder",
      name: "Africa Placeholder",
      description: "Reserved for future Africa tax requirements.",
    },
  ],
  complianceProfiles: [
    {
      id: "united-states",
      name: "United States",
      description: "Baseline privacy and consent model for United States launches.",
      privacyModel: "State privacy laws and sector-specific disclosures.",
      requirements: ["privacy notice", "cookie disclosure", "consumer support contacts"],
    },
    {
      id: "canada",
      name: "Canada",
      description: "Canadian compliance profile with bilingual support expectations.",
      privacyModel: "PIPEDA-aligned privacy program.",
      requirements: ["privacy notice", "consent controls", "bilingual support review"],
    },
    {
      id: "quebec",
      name: "Quebec",
      description: "Quebec-specific privacy and language obligations.",
      privacyModel: "Quebec privacy amendments with French-language readiness.",
      requirements: ["french legal review", "consent log", "quebec tax validation"],
    },
    {
      id: "eu-gdpr",
      name: "European Union (GDPR-ready)",
      description: "Configurable placeholder for GDPR-ready expansion.",
      privacyModel: "GDPR data minimization and rights management.",
      requirements: ["lawful basis", "DPA review", "cross-border transfer controls"],
    },
    {
      id: "latin-america-ready",
      name: "Latin America-ready",
      description: "Placeholder profile for Latin America expansion planning.",
      privacyModel: "Country-specific privacy law mapping pending activation.",
      requirements: ["local counsel review", "tax model", "payments validation"],
    },
    {
      id: "caribbean-ready",
      name: "Caribbean-ready",
      description: "Placeholder profile for Caribbean expansion planning.",
      privacyModel: "Island-specific privacy and payments review pending activation.",
      requirements: ["payments review", "support workflow", "terms localization"],
    },
    {
      id: "asia-pacific-ready",
      name: "Asia-Pacific-ready",
      description: "Placeholder profile for Asia-Pacific market planning.",
      privacyModel: "Regional privacy baseline with local-country overlays.",
      requirements: ["content localization", "payments review", "regulatory counsel"],
    },
    {
      id: "africa-ready",
      name: "Africa-ready",
      description: "Placeholder profile for Africa market planning.",
      privacyModel: "Country-by-country privacy and data localization review.",
      requirements: ["mobile money review", "tax validation", "support readiness"],
    },
  ],
  products: [
    { id: "wealth-building-red-white-blue", label: "Wealth Building the RED, WHITE & BLUE Way" },
    { id: "business-is-about-making-profit", label: "Business Is About Making Profit" },
    { id: "economic-self-defense", label: "Economic Self Defense" },
    { id: "financial-competency", label: "Financial Competency" },
  ],
  courses: [
    { id: "real-estate-competency", label: "Real Estate Competency" },
    { id: "financial-asset-competency", label: "Financial Asset Competency" },
    { id: "business-competency", label: "Business Competency" },
  ],
  membershipPlans: [
    { id: "core", label: "Core Membership" },
    { id: "family", label: "Family Membership" },
    { id: "business", label: "Business Membership" },
  ],
  aiFeatures: [
    { id: "ai-coach", label: "AI Coach" },
    { id: "financial-passport", label: "Financial Passport" },
  ],
  marketingCampaigns: [
    { id: "north-america-launch", label: "North America Launch" },
    { id: "canada-growth", label: "Canada Growth" },
    { id: "latam-readiness", label: "LATAM Readiness" },
    { id: "eu-readiness", label: "EU Readiness" },
    { id: "africa-readiness", label: "Africa Readiness" },
    { id: "apac-readiness", label: "APAC Readiness" },
  ],
  countries: [
    {
      code: "US",
      name: "United States",
      continentCode: "north-america",
      regionCode: "north-america",
      enabled: true,
      defaultLanguage: "en",
      defaultCurrency: "USD",
      timeZones: ["America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles"],
      taxProfileId: "us-sales-tax",
      complianceProfileId: "united-states",
      supportedLanguages: ["en", "es"],
      supportedCurrencies: ["USD"],
      paymentProviders: ["square", "bank-transfer"],
      products: [
        "wealth-building-red-white-blue",
        "business-is-about-making-profit",
        "economic-self-defense",
        "financial-competency",
      ],
      courses: [
        "real-estate-competency",
        "financial-asset-competency",
        "business-competency",
      ],
      membershipPlans: ["core", "family", "business"],
      aiFeatures: ["ai-coach", "financial-passport"],
      marketingCampaigns: ["north-america-launch"],
      featureAvailability: {
        marketplace: true,
        aiCoach: true,
        familyLearning: true,
        financialPassport: true,
        memberships: true,
      },
      readiness: {
        translationsReady: true,
        legalReviewReady: true,
        paymentReady: true,
        taxReady: true,
        privacyReady: true,
        contentReady: true,
        marketingReady: true,
        supportReady: true,
      },
    },
    {
      code: "CA",
      name: "Canada",
      continentCode: "north-america",
      regionCode: "north-america",
      enabled: true,
      defaultLanguage: "en",
      defaultCurrency: "CAD",
      timeZones: ["America/Toronto", "America/Vancouver"],
      taxProfileId: "canada-gst-hst",
      complianceProfileId: "canada",
      supportedLanguages: ["en", "fr"],
      supportedCurrencies: ["CAD", "USD"],
      paymentProviders: ["square", "bank-transfer"],
      products: [
        "wealth-building-red-white-blue",
        "business-is-about-making-profit",
        "economic-self-defense",
        "financial-competency",
      ],
      courses: [
        "real-estate-competency",
        "financial-asset-competency",
        "business-competency",
      ],
      membershipPlans: ["core", "family", "business"],
      aiFeatures: ["ai-coach", "financial-passport"],
      marketingCampaigns: ["north-america-launch", "canada-growth"],
      featureAvailability: {
        marketplace: true,
        aiCoach: true,
        familyLearning: true,
        financialPassport: true,
        memberships: true,
      },
      readiness: {
        translationsReady: true,
        legalReviewReady: true,
        paymentReady: true,
        taxReady: true,
        privacyReady: true,
        contentReady: true,
        marketingReady: true,
        supportReady: true,
      },
      subdivisionComplianceOverrides: {
        QC: "quebec",
      },
    },
    {
      code: "DO",
      name: "Dominican Republic",
      continentCode: "caribbean",
      regionCode: "caribbean",
      enabled: false,
      defaultLanguage: "es",
      defaultCurrency: "DOP",
      timeZones: ["America/Santo_Domingo"],
      taxProfileId: "caribbean-placeholder",
      complianceProfileId: "caribbean-ready",
      supportedLanguages: ["es", "en"],
      supportedCurrencies: ["DOP", "USD"],
      paymentProviders: ["paypal", "bank-transfer"],
      products: ["financial-competency"],
      courses: ["financial-asset-competency"],
      membershipPlans: ["core"],
      aiFeatures: [],
      marketingCampaigns: ["latam-readiness"],
      featureAvailability: {
        marketplace: false,
        aiCoach: false,
        familyLearning: false,
        financialPassport: false,
        memberships: false,
      },
      readiness: {
        ...disabledReadiness,
        translationsReady: true,
        contentReady: true,
      },
    },
    {
      code: "MX",
      name: "Mexico",
      continentCode: "latin-america",
      regionCode: "latin-america",
      enabled: false,
      defaultLanguage: "es",
      defaultCurrency: "MXN",
      timeZones: ["America/Mexico_City"],
      taxProfileId: "latam-placeholder",
      complianceProfileId: "latin-america-ready",
      supportedLanguages: ["es", "en"],
      supportedCurrencies: ["MXN", "USD"],
      paymentProviders: ["paypal", "bank-transfer"],
      products: ["financial-competency"],
      courses: ["financial-asset-competency"],
      membershipPlans: ["core"],
      aiFeatures: [],
      marketingCampaigns: ["latam-readiness"],
      featureAvailability: {
        marketplace: false,
        aiCoach: false,
        familyLearning: false,
        financialPassport: false,
        memberships: false,
      },
      readiness: {
        ...disabledReadiness,
        translationsReady: true,
        contentReady: true,
      },
    },
    {
      code: "ES",
      name: "Spain",
      continentCode: "europe",
      regionCode: "europe",
      enabled: false,
      defaultLanguage: "es",
      defaultCurrency: "EUR",
      timeZones: ["Europe/Madrid"],
      taxProfileId: "eu-vat",
      complianceProfileId: "eu-gdpr",
      supportedLanguages: ["es", "en"],
      supportedCurrencies: ["EUR"],
      paymentProviders: ["stripe", "paypal", "bank-transfer"],
      products: ["financial-competency"],
      courses: ["financial-asset-competency"],
      membershipPlans: ["core"],
      aiFeatures: [],
      marketingCampaigns: ["eu-readiness"],
      featureAvailability: {
        marketplace: false,
        aiCoach: false,
        familyLearning: false,
        financialPassport: false,
        memberships: false,
      },
      readiness: {
        ...disabledReadiness,
        legalReviewReady: true,
        privacyReady: true,
      },
    },
    {
      code: "UG",
      name: "Uganda",
      continentCode: "africa",
      regionCode: "africa",
      enabled: false,
      defaultLanguage: "en",
      defaultCurrency: "UGX",
      timeZones: ["Africa/Kampala"],
      taxProfileId: "africa-placeholder",
      complianceProfileId: "africa-ready",
      supportedLanguages: ["en"],
      supportedCurrencies: ["UGX", "USD"],
      paymentProviders: ["mtn-mobile-money", "airtel-money", "flutterwave", "bank-transfer"],
      products: ["financial-competency"],
      courses: ["business-competency"],
      membershipPlans: ["core"],
      aiFeatures: [],
      marketingCampaigns: ["africa-readiness"],
      featureAvailability: {
        marketplace: false,
        aiCoach: false,
        familyLearning: false,
        financialPassport: false,
        memberships: false,
      },
      readiness: {
        ...disabledReadiness,
        contentReady: true,
        supportReady: true,
      },
    },
    {
      code: "KE",
      name: "Kenya",
      continentCode: "africa",
      regionCode: "africa",
      enabled: false,
      defaultLanguage: "en",
      defaultCurrency: "KES",
      timeZones: ["Africa/Nairobi"],
      taxProfileId: "africa-placeholder",
      complianceProfileId: "africa-ready",
      supportedLanguages: ["en"],
      supportedCurrencies: ["KES", "USD"],
      paymentProviders: ["mpesa", "flutterwave", "bank-transfer"],
      products: ["financial-competency"],
      courses: ["business-competency"],
      membershipPlans: ["core"],
      aiFeatures: [],
      marketingCampaigns: ["africa-readiness"],
      featureAvailability: {
        marketplace: false,
        aiCoach: false,
        familyLearning: false,
        financialPassport: false,
        memberships: false,
      },
      readiness: {
        ...disabledReadiness,
        supportReady: true,
      },
    },
    {
      code: "JP",
      name: "Japan",
      continentCode: "asia-pacific",
      regionCode: "asia-pacific",
      enabled: false,
      defaultLanguage: "ja",
      defaultCurrency: "JPY",
      timeZones: ["Asia/Tokyo"],
      taxProfileId: "apac-placeholder",
      complianceProfileId: "asia-pacific-ready",
      supportedLanguages: ["ja", "en"],
      supportedCurrencies: ["JPY"],
      paymentProviders: ["stripe", "bank-transfer"],
      products: ["financial-competency"],
      courses: ["financial-asset-competency"],
      membershipPlans: ["core"],
      aiFeatures: [],
      marketingCampaigns: ["apac-readiness"],
      featureAvailability: {
        marketplace: false,
        aiCoach: false,
        familyLearning: false,
        financialPassport: false,
        memberships: false,
      },
      readiness: {
        ...disabledReadiness,
        contentReady: true,
      },
    },
  ],
};

export const defaultCountryCode = "US";
