import type { Metadata } from "next";
import AICoachLayout from "@/components/ai-coach/AICoachLayout";
import DailyRecommendations from "@/components/ai-coach/DailyRecommendations";
import { generateRecommendations } from "@/lib/ai-coach/recommendation-engine";
import { DEMO_SCORES } from "@/lib/ai-coach/coach-data-service";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Recommendations | AI Coach | Edunancial",
  description:
    "Personalized course, book, article, video, and marketplace recommendations from your Edunancial AI Coach — with explanations and confidence scores.",
};

export default function RecommendationsPage() {
  const allRecs = generateRecommendations(
    {
      competencyScores: DEMO_SCORES,
      goalCategories: ["savings", "debt", "investment"],
      assessmentCompleted: true,
      membershipLevel: "Premium",
    },
    { limit: 20 }
  );

  const courses = allRecs.filter((r) => r.type === "course");
  const books = allRecs.filter((r) => r.type === "book");
  const articles = allRecs.filter((r) => r.type === "article");
  const videos = allRecs.filter((r) => r.type === "video");
  const marketplace = allRecs.filter((r) => r.type === "marketplaceProduct");
  const actions = allRecs.filter((r) => r.type === "action" || r.type === "assessment");

  const sections = [
    { label: "📚 Courses", recs: courses },
    { label: "📖 Books", recs: books },
    { label: "📄 Articles", recs: articles },
    { label: "🎬 Videos", recs: videos },
    { label: "🛒 Marketplace", recs: marketplace },
    { label: "⚡ Actions", recs: actions },
  ].filter((s) => s.recs.length > 0);

  return (
    <AICoachLayout activeHref="/ai-coach/recommendations">
      {/* Header */}
      <section aria-labelledby="recommendations-page-heading">
        <p className="text-sm font-bold uppercase tracking-widest text-yellow-400">
          Personalized Recommendations
        </p>
        <h1 id="recommendations-page-heading" className="mt-3 text-5xl font-black">
          Your Learning Path
        </h1>
        <p className="mt-4 max-w-2xl text-lg text-slate-300">
          Every recommendation below is generated by Edunancial&apos;s rule-based AI engine based on your competency scores, goals, and learning history. Each recommendation includes the exact reason it was chosen and a confidence score.
        </p>
      </section>

      {/* How it works */}
      <div className="mt-8 rounded-2xl bg-slate-800 p-6">
        <h2 className="text-lg font-black">How Recommendations Are Made</h2>
        <div className="mt-4 grid gap-4 sm:grid-cols-3">
          <div className="rounded-xl bg-slate-900 p-4">
            <p className="text-2xl" aria-hidden="true">📊</p>
            <h3 className="mt-2 font-bold">Competency Analysis</h3>
            <p className="mt-1 text-sm text-slate-400">
              Your 6-area score breakdown determines which topics need attention most.
            </p>
          </div>
          <div className="rounded-xl bg-slate-900 p-4">
            <p className="text-2xl" aria-hidden="true">🎯</p>
            <h3 className="mt-2 font-bold">Goal Alignment</h3>
            <p className="mt-1 text-sm text-slate-400">
              Active financial goals match you with directly relevant content and tools.
            </p>
          </div>
          <div className="rounded-xl bg-slate-900 p-4">
            <p className="text-2xl" aria-hidden="true">🤖</p>
            <h3 className="mt-2 font-bold">AI-Ready Architecture</h3>
            <p className="mt-1 text-sm text-slate-400">
              Built to integrate with LLM-based scoring. Future: personalized narrative explanations.
            </p>
          </div>
        </div>
      </div>

      {/* All recommendations */}
      <div className="mt-8 space-y-12">
        {sections.map((section) => (
          <div key={section.label}>
            <h2 className="mb-5 text-2xl font-black">{section.label}</h2>
            <DailyRecommendations recommendations={section.recs} />
          </div>
        ))}
      </div>

      <div className="mt-8 text-center">
        <Link
          href="/ai-coach"
          className="rounded-xl border border-slate-600 px-6 py-3 font-bold text-slate-300 hover:border-white hover:text-white"
        >
          ← Back to Dashboard
        </Link>
      </div>
    </AICoachLayout>
  );
}
