"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ADMIN_CONTENT_LANGUAGES, ADMIN_CONTENT_LANGUAGE_LABELS, type AdminContentLanguage } from "@/lib/admin-content/languages";
import { MEMBERSHIP_ACCESS } from "@/lib/admin-content/constants";
import { runSequentialFinalization } from "@/lib/admin-content/finalize-queue";
import { runParallelUploads } from "@/lib/admin-content/parallel-upload";

const COURSE_LEVELS = ["level-1", "level-2", "level-3", "level-4", "level-5"] as const;
const MARKETPLACE_CATEGORIES = ["books","ebooks","pdf-guides","templates","worksheets","forms","downloads","zip-packages","audio","videos","images","software","digital-products","calculators","presentations","spreadsheets","future-products"] as const;
type Track = "red"|"white"|"blue"|"green"|"gold"|"purple"|"orange"|"black";
type MembershipAccess = (typeof MEMBERSHIP_ACCESS)[number];
const TRACKS:Array<{value:Track;label:string}>=[{value:"red",label:"🔴 Red — Real Estate"},{value:"white",label:"⚪ White — Paper Assets"},{value:"blue",label:"🔵 Blue — Business"},{value:"green",label:"🟢 Green — Taxes"},{value:"gold",label:"🟡 Gold — Investing"},{value:"purple",label:"🟣 Purple — Law"},{value:"orange",label:"🟠 Orange — Sales & Marketing"},{value:"black",label:"⚫ Black — Leadership & Executive Management"}];
const TRACK_VALUES=new Set(TRACKS.map(t=>t.value));
const HUMAN_LOCALES:Array<[string,AdminContentLanguage]>=[["spanish-latin-america-caribbean","es-Caribbean"],["spanish-caribbean","es-Caribbean"],["portuguese-brazil","pt-BR"],["brazilian-portuguese","pt-BR"],["portuguese-portugal","pt-PT"],["french-canadian","fr-CA"],["canadian-french","fr-CA"],["french-france","fr-FR"],["spanish-spain","es-ES"],["english-uk","en-GB"],["english-united-kingdom","en-GB"],["english-us","en-US"],["english-united-states","en-US"],["german-germany","de"],["italian-italy","it"],["dutch-netherlands","nl"]];
const CANONICAL_LOCALES=["es-Caribbean","en-US","en-GB","es-ES","fr-CA","fr-FR","pt-BR","pt-PT","de","it","nl","es","fr","pt","en"] as const;
function stem(filename:string){return filename.replace(/\.[^.]+$/u,"");}
function normalized(filename:string){return `-${stem(filename).toLowerCase().replaceAll("_","-").replaceAll(".","-")}-`;}
function tokens(filename:string){return stem(filename).toLowerCase().split(/[^a-z0-9]+/u).filter(Boolean);}
function inferLanguage(filename:string):AdminContentLanguage|null{const n=normalized(filename);for(const [alias,locale] of HUMAN_LOCALES)if(n.includes(`-${alias}-`))return locale;for(const locale of CANONICAL_LOCALES)if(n.includes(`-${locale.toLowerCase()}-`))return locale as AdminContentLanguage;return null;}
function inferTrack(filename:string):Track|null{for(const token of tokens(filename))if(TRACK_VALUES.has(token as Track))return token as Track;return null;}
function inferLevel(filename:string):(typeof COURSE_LEVELS)[number]|null{const t=tokens(filename);for(let i=0;i<t.length;i++){const m=t[i].match(/^l([1-5])$/u)??t[i].match(/^level([1-5])$/u);if(m)return `level-${m[1]}` as (typeof COURSE_LEVELS)[number];if(t[i]==="level"&&/^[1-5]$/u.test(t[i+1]??""))return `level-${t[i+1]}` as (typeof COURSE_LEVELS)[number];}return null;}
function inspect(file:File,defaultLanguage:AdminContentLanguage){const track=inferTrack(file.name),level=inferLevel(file.name),explicitLanguage=inferLanguage(file.name);return{track,level,explicitLanguage,language:explicitLanguage??defaultLanguage,ready:Boolean(track&&level)};}
function languageLabel(locale:string){return ADMIN_CONTENT_LANGUAGE_LABELS[locale as AdminContentLanguage]??locale;}
function packageTitle(track:Track,level:(typeof COURSE_LEVELS)[number]){const label=TRACKS.find(t=>t.value===track)?.label.replace(/^[^A-Za-z]+/u,"")??track.toUpperCase();return `${label} — ${level.replace("level-","Level ")}`;}
type Presigned={batchId:string;uploads:Array<{uploadId:string;storagePath:string;safeName:string;signedUrl:string|null;directUpload:{url:string;headers:Record<string,string>}|null}>};
type StoredUpload={uploadId:string;originalFilename:string;mimeType:string;sizeBytes:number;storagePath:string};
type FinalizePayload={batch?:{id:string}|null;batches?:Array<{id:string}>;failures?:Array<{filename:string;error:string}>};

export default function ResilientUploadClient(){
 const router=useRouter(),fileInputRef=useRef<HTMLInputElement|null>(null),xhrRefs=useRef<Set<XMLHttpRequest>>(new Set());
 const [files,setFiles]=useState<File[]>([]),[destination,setDestination]=useState<""|"courses"|"marketplace">(""),[batchName,setBatchName]=useState(""),[source,setSource]=useState("Admin dashboard"),[notes,setNotes]=useState("");
 const [category,setCategory]=useState<(typeof MARKETPLACE_CATEGORIES)[number]>("books"),[language,setLanguage]=useState<AdminContentLanguage>("en-US"),[membership,setMembership]=useState<MembershipAccess>("basic"),[publication,setPublication]=useState<"draft"|"review"|"published"|"archived">("draft");
 const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[associatedTrack,setAssociatedTrack]=useState<""|Track>(""),[associatedLevel,setAssociatedLevel]=useState<""|(typeof COURSE_LEVELS)[number]>("");
 const [csrf,setCsrf]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState(""),[uploading,setUploading]=useState(false),[progress,setProgress]=useState(0),[phase,setPhase]=useState("");
 useEffect(()=>{void(async()=>{const r=await fetch("/api/admin/auth/session",{cache:"no-store"});const p=await r.json();setCsrf(p.csrfToken??"");})();},[]);
 function appendFiles(list:FileList|null){if(!list)return;setFiles(current=>{const seen=new Set(current.map(f=>`${f.name}:${f.size}:${f.lastModified}`)),next=[...current];for(const f of Array.from(list)){const k=`${f.name}:${f.size}:${f.lastModified}`;if(!seen.has(k)){seen.add(k);next.push(f);}}return next;});setError("");}
 function cancel(){for(const xhr of xhrRefs.current)xhr.abort();xhrRefs.current.clear();}
 function validate(){if(!destination)return"Choose CONTENT DESTINATION first.";if(destination==="marketplace"&&!title.trim())return"Title is required for Marketplace uploads.";if(destination==="marketplace"&&!description.trim())return"Description is required for Marketplace uploads.";if(!files.length)return"Select at least one file or ZIP package.";if(destination==="courses"){const bad=files.filter(f=>!inspect(f,language).ready);if(bad.length)return`Cannot safely classify: ${bad.map(f=>f.name).join(", ")}. Every curriculum filename must include COLOR and LEVEL.`;}return"";}
 function uploadDirect(file:File,url:string,method:string,headers:Record<string,string>,report:(n:number)=>void){return new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhrRefs.current.add(xhr);const done=()=>xhrRefs.current.delete(xhr);xhr.upload.onprogress=e=>{if(e.lengthComputable)report(e.loaded);};xhr.onload=()=>{done();xhr.status>=200&&xhr.status<300?resolve():reject(new Error(`Direct upload failed (HTTP ${xhr.status}).`));};xhr.onerror=()=>{done();reject(new Error("Network error during file upload."));};xhr.onabort=()=>{done();reject(new Error("Upload canceled."));};xhr.open(method,url);Object.entries(headers).forEach(([k,v])=>xhr.setRequestHeader(k,v));xhr.send(file);});}
 async function submit(event:React.FormEvent<HTMLFormElement>){
  event.preventDefault();const problem=validate();if(problem){setError(problem);return;}setUploading(true);setError("");setSuccess("");setProgress(0);setPhase("Preparing secure storage uploads…");
  const first=destination==="courses"?inspect(files[0],language):null;const effectiveTitle=destination==="courses"&&first?.track&&first.level?packageTitle(first.track,first.level):title.trim();
  const config:Record<string,string>={batchName:batchName||`Content Upload ${new Date().toISOString().slice(0,10)}`,source,notes,contentDestination:destination,membershipAccess:membership,publicationStatus:publication,title:effectiveTitle,description:destination==="courses"?(description.trim()||"Bulk curriculum package upload; each package is classified and finalized independently."):description.trim(),thumbnailUrl:"",previewUrl:""};
  if(destination==="courses"&&first?.track&&first.level){config.courseTrack=first.track;config.courseLevel=first.level;config.language=language;}else if(destination==="marketplace"){config.language=language;config.marketplaceCategory=category;config.associatedTrack=associatedTrack;config.associatedLevel=associatedLevel;}
  try{
   const pre=await fetch("/api/admin/content/upload/presign",{method:"POST",headers:{"Content-Type":"application/json","x-csrf-token":csrf},body:JSON.stringify({...config,files:files.map(f=>({name:f.name,size:f.size,type:f.type}))})});
   if(!pre.ok){const p=await pre.json().catch(()=>({}));throw new Error(p.error??`Failed to prepare upload (HTTP ${pre.status}).`);}const presigned=await pre.json() as Presigned;
   if(!presigned.uploads.every(u=>u.signedUrl||u.directUpload))throw new Error("Direct storage upload is unavailable for one or more packages.");
   setPhase(`Uploading ${files.length} package${files.length===1?"":"s"} to storage…`);
   await runParallelUploads(files,async(file,i,report)=>{const spec=presigned.uploads[i];if(spec.signedUrl)await uploadDirect(file,spec.signedUrl,"PUT",{"Content-Type":file.type||"application/octet-stream"},report);else if(spec.directUpload)await uploadDirect(file,spec.directUpload.url,"POST",{...spec.directUpload.headers,"Content-Type":file.type||"application/octet-stream"},report);},{sizeOf:f=>f.size,onProgress:({percent})=>setProgress(Math.round(percent*0.9))});
   const stored:StoredUpload[]=files.map((file,i)=>({uploadId:presigned.uploads[i].uploadId,originalFilename:file.name,mimeType:file.type||"application/octet-stream",sizeBytes:file.size,storagePath:presigned.uploads[i].storagePath}));
   const completedBatchIds:string[]=[];
   await runSequentialFinalization(stored,async(upload,index)=>{
    setPhase(`Processing package ${index+1} of ${stored.length}: ${upload.originalFilename}`);
    const r=await fetch("/api/admin/content/upload/finalize",{method:"POST",headers:{"Content-Type":"application/json","x-csrf-token":csrf},body:JSON.stringify({...config,batchId:presigned.batchId,uploads:[upload]})});
    if(!r.ok){const p=await r.json().catch(()=>({}));const detail=p.detail??p.message??p.error;throw new Error(`${upload.originalFilename} failed during finalization (HTTP ${r.status})${detail?`: ${detail}`:""}. ${completedBatchIds.length} package${completedBatchIds.length===1?"":"s"} already finalized successfully and will not be discarded.`);}
    const payload=await r.json() as FinalizePayload;const id=payload.batch?.id??payload.batches?.[0]?.id;if(!id)throw new Error(`${upload.originalFilename} returned no review batch after finalization.`);completedBatchIds.push(id);return id;
   },({completed,total})=>setProgress(90+Math.round((completed/total)*10)));
   setProgress(100);setSuccess(`${completedBatchIds.length} package${completedBatchIds.length===1?"":"s"} uploaded and finalized independently. Opening the first review batch.`);setUploading(false);setPhase("");router.push(`/admin/content/batches/${completedBatchIds[0]}`);router.refresh();
  }catch(err){cancel();setUploading(false);setPhase("");setError((err as Error).message);}
 }
 return <form onSubmit={submit} className="mx-auto max-w-5xl space-y-7">
  <label className="grid gap-2 text-sm font-bold text-slate-200">CONTENT DESTINATION *<select value={destination} onChange={e=>{setDestination(e.target.value as typeof destination);setFiles([]);setError("");}} className="rounded-xl border border-white/10 bg-[#101a2f] px-4 py-3 text-white"><option value="">Select destination</option><option value="courses">COURSES / CURRICULUM</option><option value="marketplace">MARKETPLACE</option></select></label>
  {!destination?null:<><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Batch name<input value={batchName} onChange={e=>setBatchName(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3" placeholder="Mixed curriculum upload"/></label><label className="grid gap-2 text-sm font-semibold">Source<input value={source} onChange={e=>setSource(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3"/></label></div>
  {destination==="courses"?<div className="rounded-2xl border border-blue-500/20 bg-blue-500/5 p-5"><p className="font-black text-blue-200">Automatic per-package curriculum classification</p><p className="mt-2 text-sm text-slate-300">Color, level, and descriptive language names are detected independently for every ZIP. Each ZIP is finalized in its own request so a large batch does not depend on one long-running finalization request.</p><label className="mt-4 grid gap-2 text-sm font-semibold">Default language for untagged files *<select value={language} onChange={e=>setLanguage(e.target.value as AdminContentLanguage)} className="rounded-xl bg-[#101a2f] px-4 py-3 text-white">{ADMIN_CONTENT_LANGUAGES.map(l=><option key={l} value={l}>{ADMIN_CONTENT_LANGUAGE_LABELS[l]}</option>)}</select></label></div>:<><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Marketplace title *<input value={title} onChange={e=>setTitle(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3"/></label><label className="grid gap-2 text-sm font-semibold">Language *<select value={language} onChange={e=>setLanguage(e.target.value as AdminContentLanguage)} className="rounded-xl bg-[#101a2f] px-4 py-3">{ADMIN_CONTENT_LANGUAGES.map(l=><option key={l} value={l}>{ADMIN_CONTENT_LANGUAGE_LABELS[l]}</option>)}</select></label></div><label className="grid gap-2 text-sm font-semibold">Description *<textarea value={description} onChange={e=>setDescription(e.target.value)} className="min-h-28 rounded-xl bg-[#101a2f] px-4 py-3"/></label><div className="grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-sm font-semibold">Category<select value={category} onChange={e=>setCategory(e.target.value as typeof category)} className="rounded-xl bg-[#101a2f] px-4 py-3">{MARKETPLACE_CATEGORIES.map(c=><option key={c} value={c}>{c}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Associated color<select value={associatedTrack} onChange={e=>setAssociatedTrack(e.target.value as typeof associatedTrack)} className="rounded-xl bg-[#101a2f] px-4 py-3"><option value="">None</option>{TRACKS.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Associated level<select value={associatedLevel} onChange={e=>setAssociatedLevel(e.target.value as typeof associatedLevel)} className="rounded-xl bg-[#101a2f] px-4 py-3"><option value="">None</option>{COURSE_LEVELS.map(l=><option key={l} value={l}>{l.replace("level-","Level ")}</option>)}</select></label></div></>}
  <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Membership Access *<select value={membership} onChange={e=>setMembership(e.target.value as MembershipAccess)} className="rounded-xl bg-[#101a2f] px-4 py-3">{MEMBERSHIP_ACCESS.map(t=><option key={t} value={t}>{t.charAt(0).toUpperCase()+t.slice(1)}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Publication Status *<select value={publication} onChange={e=>setPublication(e.target.value as typeof publication)} className="rounded-xl bg-[#101a2f] px-4 py-3"><option value="draft">Draft</option><option value="review">Review</option><option value="published">Published</option><option value="archived">Archived</option></select></label></div>
  <label className="grid gap-2 text-sm font-semibold">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="min-h-24 rounded-xl bg-[#101a2f] px-4 py-3"/></label>
  <div className="rounded-2xl border border-dashed border-white/20 bg-white/5 p-6"><input ref={fileInputRef} type="file" multiple className="hidden" onChange={e=>appendFiles(e.target.files)}/><button type="button" onClick={()=>fileInputRef.current?.click()} className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Choose files / ZIP packages</button><p className="mt-3 text-sm text-slate-400">Curriculum filenames must identify color and level. Recognized language names override the selected default.</p>{files.length?<div className="mt-4 space-y-2">{files.map((file,index)=>{const identity=destination==="courses"?inspect(file,language):null;return <div key={`${file.name}:${file.lastModified}`} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-black/20 px-3 py-2 text-sm"><span>{file.name}</span>{identity?<span className={identity.ready?"text-emerald-300":"text-amber-300"}>{identity.track??"?"} / {identity.level?.replace("level-","L")??"?"} / {languageLabel(identity.language)}{identity.explicitLanguage?" (filename)":" (default)"}</span>:null}<button type="button" onClick={()=>setFiles(current=>current.filter((_,i)=>i!==index))} className="text-red-300">Remove</button></div>;})}</div>:null}</div>
  {uploading?<div><div className="h-2 overflow-hidden rounded bg-white/10"><div className="h-full bg-blue-500" style={{width:`${progress}%`}}/></div><p className="mt-2 text-sm">{phase||"Uploading…"} {progress}%</p><button type="button" onClick={cancel} className="mt-2 text-sm text-red-300">Cancel upload</button></div>:null}{error?<p className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{error}</p>:null}{success?<p className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-200">{success}</p>:null}<button type="submit" disabled={uploading||!destination} className="rounded-xl bg-emerald-600 px-6 py-3 font-black text-white disabled:opacity-50">{uploading?"Uploading…":"Upload content"}</button></>}
 </form>;
}
