"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ADMIN_CONTENT_LANGUAGES, ADMIN_CONTENT_LANGUAGE_LABELS, type AdminContentLanguage } from "@/lib/admin-content/languages";
import { MEMBERSHIP_ACCESS } from "@/lib/admin-content/constants";

const COURSE_LEVELS = ["level-1", "level-2", "level-3", "level-4", "level-5"] as const;
const MARKETPLACE_CATEGORIES = ["books","ebooks","pdf-guides","templates","worksheets","forms","downloads","zip-packages","audio","videos","images","software","digital-products","calculators","presentations","spreadsheets","future-products"] as const;
type Track = "red" | "white" | "blue" | "green" | "gold" | "purple" | "orange" | "black";
type MembershipAccess = (typeof MEMBERSHIP_ACCESS)[number];
const TRACKS: Array<{value:Track;label:string}> = [
  {value:"red",label:"🔴 Red — Real Estate"},{value:"white",label:"⚪ White — Paper Assets"},{value:"blue",label:"🔵 Blue — Business"},{value:"green",label:"🟢 Green — Taxes"},{value:"gold",label:"🟡 Gold — Investing"},{value:"purple",label:"🟣 Purple — Law"},{value:"orange",label:"🟠 Orange — Sales & Marketing"},{value:"black",label:"⚫ Black — Leadership & Executive Management"},
];
const TRACK_VALUES = new Set(TRACKS.map((track)=>track.value));
const FILENAME_LOCALES = ["es-Caribbean","en-US","en-GB","es-ES","fr-CA","fr-FR","pt-BR","pt-PT","de","it","nl","es","fr","pt","en"] as const;

function stemOf(filename:string){return filename.replace(/\.[^.]+$/u,"");}
function filenameTokens(filename:string){return stemOf(filename).toLowerCase().split(/[^a-z0-9]+/u).filter(Boolean);}
function inferLanguage(filename:string){const normalized=`-${stemOf(filename).toLowerCase().replaceAll("_","-").replaceAll(".","-")}-`;return FILENAME_LOCALES.find(locale=>normalized.includes(`-${locale.toLowerCase()}-`))??null;}
function inferTrack(filename:string):Track|null{for(const token of filenameTokens(filename)){if(TRACK_VALUES.has(token as Track))return token as Track;}return null;}
function inferLevel(filename:string):(typeof COURSE_LEVELS)[number]|null{const tokens=filenameTokens(filename);for(let i=0;i<tokens.length;i++){const token=tokens[i];const compact=token.match(/^l([1-5])$/u)??token.match(/^level([1-5])$/u);if(compact)return `level-${compact[1]}` as (typeof COURSE_LEVELS)[number];if(token==="level"&&/^[1-5]$/u.test(tokens[i+1]??""))return `level-${tokens[i+1]}` as (typeof COURSE_LEVELS)[number];}return null;}
function inferTitle(filename:string){const localeTokens=new Set(FILENAME_LOCALES.flatMap(locale=>locale.toLowerCase().split("-")));const metadata=new Set(["complete","combined","package","curriculum",...TRACKS.map(track=>track.value)]);const tokens=stemOf(filename).split(/[-_.\s]+/u).filter(Boolean).filter(token=>{const lower=token.toLowerCase();return !metadata.has(lower)&&!localeTokens.has(lower)&&!/^l[1-5]$/iu.test(token)&&!/^level[1-5]$/iu.test(token)&&!/^[1-5]$/u.test(token);});return tokens.length?tokens.join(" "):null;}
function languageLabel(locale:string){return ADMIN_CONTENT_LANGUAGE_LABELS[locale as AdminContentLanguage]??locale;}

export default function UploadClient() {
  const router=useRouter(), fileInputRef=useRef<HTMLInputElement|null>(null), xhrRef=useRef<XMLHttpRequest|null>(null);
  const [files,setFiles]=useState<File[]>([]), [contentDestination,setContentDestination]=useState<""|"courses"|"marketplace">(""), [batchName,setBatchName]=useState(""), [source,setSource]=useState("Admin dashboard"), [notes,setNotes]=useState("");
  const [courseTrack,setCourseTrack]=useState<Track>("red"), [courseLevel,setCourseLevel]=useState<(typeof COURSE_LEVELS)[number]>("level-1"), [marketplaceCategory,setMarketplaceCategory]=useState<(typeof MARKETPLACE_CATEGORIES)[number]>("books");
  const [language,setLanguage]=useState<AdminContentLanguage>("en-US"), [membershipAccess,setMembershipAccess]=useState<MembershipAccess>("basic"), [publicationStatus,setPublicationStatus]=useState<"draft"|"review"|"published"|"archived">("draft");
  const [title,setTitle]=useState(""), [description,setDescription]=useState(""), [thumbnailUrl,setThumbnailUrl]=useState(""), [previewUrl,setPreviewUrl]=useState(""), [associatedTrack,setAssociatedTrack]=useState<""|Track>(""), [associatedLevel,setAssociatedLevel]=useState<""|(typeof COURSE_LEVELS)[number]>("");
  const [csrfToken,setCsrfToken]=useState(""), [error,setError]=useState(""), [success,setSuccess]=useState(""), [uploading,setUploading]=useState(false), [progress,setProgress]=useState(0);
  useEffect(()=>{void(async()=>{const response=await fetch("/api/admin/auth/session",{cache:"no-store"});const payload=await response.json();setCsrfToken(payload.csrfToken??"");})();},[]);
  function appendFiles(list:FileList|null){if(!list)return;setFiles(current=>{const seen=new Set(current.map(f=>`${f.name}:${f.size}:${f.lastModified}`)),next=[...current];for(const file of Array.from(list)){const key=`${file.name}:${file.size}:${file.lastModified}`;if(!seen.has(key)){seen.add(key);next.push(file);}}return next;});setError("");}
  function validateBeforeUpload(){if(!contentDestination)return"Choose CONTENT DESTINATION first.";if(contentDestination==="marketplace"&&!title.trim())return"Title is required for Marketplace uploads.";if(contentDestination==="marketplace"&&!description.trim())return"Description is required for Marketplace uploads.";if(files.length===0)return"Select at least one file or ZIP package.";return"";}
  function uploadFileDirect(file:File,url:string,method:string,headers:Record<string,string>,onProgress:(pct:number)=>void):Promise<void>{return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhrRef.current=xhr;xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(Math.round(e.loaded/e.total*100));};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error(`Direct upload failed (HTTP ${xhr.status}): ${xhr.responseText}`));xhr.onerror=()=>reject(new Error("Network error during file upload."));xhr.onabort=()=>reject(new Error("Upload canceled."));xhr.open(method,url);Object.entries(headers).forEach(([k,v])=>xhr.setRequestHeader(k,v));xhr.send(file);});}
  async function handleSubmit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const validation=validateBeforeUpload();if(validation){setError(validation);return;}setUploading(true);setError("");setSuccess("");setProgress(0);
    const effectiveTitle=title.trim()||(contentDestination==="courses"?"Mixed curriculum upload":"");const effectiveDescription=description.trim()||(contentDestination==="courses"?"Bulk curriculum package upload; package metadata is inferred from each filename when available.":"");
    const sharedConfig:Record<string,string>={batchName:batchName||`Content Upload ${new Date().toISOString().slice(0,10)}`,source,notes,contentDestination,language,membershipAccess,publicationStatus,title:effectiveTitle,description:effectiveDescription,thumbnailUrl,previewUrl};if(contentDestination==="courses"){sharedConfig.courseTrack=courseTrack;sharedConfig.courseLevel=courseLevel;}else{sharedConfig.marketplaceCategory=marketplaceCategory;sharedConfig.associatedTrack=associatedTrack;sharedConfig.associatedLevel=associatedLevel;}
    let presignResult:{batchId:string;uploads:Array<{uploadId:string;storagePath:string;safeName:string;signedUrl:string|null;directUpload:{url:string;headers:Record<string,string>}|null}>}|null=null;
    try{const response=await fetch("/api/admin/content/upload/presign",{method:"POST",headers:{"Content-Type":"application/json","x-csrf-token":csrfToken},body:JSON.stringify({...sharedConfig,files:files.map(f=>({name:f.name,size:f.size,type:f.type}))})});if(!response.ok){const parsed=await response.json().catch(()=>({}));throw new Error(parsed.error??"Failed to prepare upload.");}presignResult=await response.json();}catch(err){if(err instanceof Error&&err.message!=="Failed to fetch"){setUploading(false);setError(err.message);return;}}
    const allDirect=presignResult&&presignResult.uploads.every(u=>u.signedUrl||u.directUpload);if(presignResult&&allDirect){try{for(let i=0;i<files.length;i++){const file=files[i],spec=presignResult.uploads[i],base=Math.round(i/files.length*85);if(spec.signedUrl)await uploadFileDirect(file,spec.signedUrl,"PUT",{"Content-Type":file.type||"application/octet-stream"},pct=>setProgress(base+Math.round(pct/100*(85/files.length))));else if(spec.directUpload)await uploadFileDirect(file,spec.directUpload.url,"POST",{...spec.directUpload.headers,"Content-Type":file.type||"application/octet-stream"},pct=>setProgress(base+Math.round(pct/100*(85/files.length))));}setProgress(90);const response=await fetch("/api/admin/content/upload/finalize",{method:"POST",headers:{"Content-Type":"application/json","x-csrf-token":csrfToken},body:JSON.stringify({...sharedConfig,batchId:presignResult.batchId,uploads:files.map((file,i)=>({uploadId:presignResult!.uploads[i].uploadId,originalFilename:file.name,mimeType:file.type||"application/octet-stream",sizeBytes:file.size,storagePath:presignResult!.uploads[i].storagePath}))})});if(!response.ok){const parsed=await response.json().catch(()=>({}));const detail=parsed.detail??parsed.message??parsed.error;throw new Error(detail?`Upload processing failed: ${detail}`:"Upload processing failed during finalization.");}const payload=await response.json();setProgress(100);setSuccess("Upload complete. Opening batch review.");router.push(`/admin/content/batches/${payload.batch.id}`);router.refresh();return;}catch(err){setUploading(false);setError((err as Error).message);return;}}
    const max=6*1024*1024,oversized=files.filter(f=>f.size>max);if(oversized.length&&typeof window!=="undefined"&&!window.location.hostname.includes("localhost")){setUploading(false);setError(`Direct Supabase upload is not configured. These files exceed the 6 MB serverless fallback limit: ${oversized.map(f=>f.name).join(", ")}.`);return;}
    const formData=new FormData();Object.entries(sharedConfig).forEach(([k,v])=>formData.append(k,v));files.forEach(f=>formData.append("files",f));const xhr=new XMLHttpRequest();xhrRef.current=xhr;xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100));};xhr.onload=()=>{setUploading(false);if(xhr.status<200||xhr.status>=300){try{const parsed=JSON.parse(xhr.responseText);setError(parsed.detail??parsed.message??parsed.error??`Upload failed (HTTP ${xhr.status}).`);}catch{setError(`Upload failed (HTTP ${xhr.status}).`);}return;}const payload=JSON.parse(xhr.responseText);router.push(`/admin/content/batches/${payload.batch.id}`);router.refresh();};xhr.onerror=()=>{setUploading(false);setError("Network error while uploading.");};xhr.onabort=()=>{setUploading(false);setError("Upload canceled.");};xhr.open("POST","/api/admin/content/upload");xhr.setRequestHeader("x-csrf-token",csrfToken);xhr.send(formData);
  }
  return <form onSubmit={handleSubmit} className="mx-auto max-w-5xl space-y-7">
    <label className="grid gap-2 text-sm font-bold text-slate-200">CONTENT DESTINATION *<select value={contentDestination} onChange={e=>{setContentDestination(e.target.value as typeof contentDestination);setFiles([]);setError("");}} className="rounded-xl border border-white/10 bg-[#101a2f] px-4 py-3 text-white"><option value="">Select destination</option><option value="courses">COURSES / CURRICULUM</option><option value="marketplace">MARKETPLACE</option></select></label>
    {!contentDestination?null:<><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Batch name<input value={batchName} onChange={e=>setBatchName(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3" placeholder="Mixed curriculum upload"/></label><label className="grid gap-2 text-sm font-semibold">Source<input value={source} onChange={e=>setSource(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3"/></label></div>
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">{contentDestination==="courses"?"Fallback Course Title (optional)":"Batch / Marketplace Title *"}<input value={title} onChange={e=>setTitle(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3" placeholder={contentDestination==="courses"?"Used only when a package title cannot be inferred":""}/></label><label className="grid gap-2 text-sm font-semibold">{contentDestination==="courses"?"Fallback Language":"Language *"}<select value={language} onChange={e=>setLanguage(e.target.value as AdminContentLanguage)} className="rounded-xl bg-[#101a2f] px-4 py-3">{ADMIN_CONTENT_LANGUAGES.map(locale=><option key={locale} value={locale}>{ADMIN_CONTENT_LANGUAGE_LABELS[locale]}</option>)}</select></label>
    <label className="grid gap-2 text-sm font-semibold">Membership Access *<select value={membershipAccess} onChange={e=>setMembershipAccess(e.target.value as MembershipAccess)} className="rounded-xl bg-[#101a2f] px-4 py-3">{MEMBERSHIP_ACCESS.map(tier=><option key={tier} value={tier}>{tier.charAt(0).toUpperCase()+tier.slice(1)}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Publication Status *<select value={publicationStatus} onChange={e=>setPublicationStatus(e.target.value as typeof publicationStatus)} className="rounded-xl bg-[#101a2f] px-4 py-3"><option value="draft">Draft</option><option value="review">Review</option><option value="published">Published</option><option value="archived">Archived</option></select></label>
    {contentDestination==="courses"?<><label className="grid gap-2 text-sm font-semibold">Fallback Color Track<select value={courseTrack} onChange={e=>setCourseTrack(e.target.value as Track)} className="rounded-xl bg-[#101a2f] px-4 py-3">{TRACKS.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Fallback Level<select value={courseLevel} onChange={e=>setCourseLevel(e.target.value as typeof courseLevel)} className="rounded-xl bg-[#101a2f] px-4 py-3">{COURSE_LEVELS.map(l=><option key={l} value={l}>{l.replace("level-","Level ")}</option>)}</select></label></>:<><label className="grid gap-2 text-sm font-semibold">Marketplace Category *<select value={marketplaceCategory} onChange={e=>setMarketplaceCategory(e.target.value as typeof marketplaceCategory)} className="rounded-xl bg-[#101a2f] px-4 py-3">{MARKETPLACE_CATEGORIES.map(c=><option key={c} value={c}>{c.replaceAll("-"," ")}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Optional Course Association<div className="grid grid-cols-2 gap-2"><select value={associatedTrack} onChange={e=>setAssociatedTrack(e.target.value as typeof associatedTrack)} className="rounded-xl bg-[#101a2f] px-3 py-3"><option value="">Track</option>{TRACKS.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select><select value={associatedLevel} onChange={e=>setAssociatedLevel(e.target.value as typeof associatedLevel)} className="rounded-xl bg-[#101a2f] px-3 py-3"><option value="">Level</option>{COURSE_LEVELS.map(l=><option key={l} value={l}>{l.replace("level-","Level ")}</option>)}</select></div></label></>}</div>
    <label className="grid gap-2 text-sm font-semibold">{contentDestination==="courses"?"Fallback Description (optional)":"Description *"}<textarea value={description} onChange={e=>setDescription(e.target.value)} className="min-h-24 rounded-xl bg-[#101a2f] px-4 py-3" placeholder={contentDestination==="courses"?"Used when package-specific metadata does not provide a description":""}/></label><label className="grid gap-2 text-sm font-semibold">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="min-h-20 rounded-xl bg-[#101a2f] px-4 py-3"/></label>
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Thumbnail URL (optional)<input value={thumbnailUrl} onChange={e=>setThumbnailUrl(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3"/></label><label className="grid gap-2 text-sm font-semibold">Preview URL (optional)<input value={previewUrl} onChange={e=>setPreviewUrl(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3"/></label></div>
    <div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();appendFiles(e.dataTransfer.files);}} className="rounded-3xl border border-dashed border-blue-400/50 bg-[#101a2f] p-10 text-center"><p className="text-lg font-black">Drop files or ZIP curriculum packages here</p><p className="mt-2 text-sm text-slate-400">Mixed colors, levels, languages, and course titles are supported in the same selection. Recognized package metadata overrides the fallback fields above.</p><div className="mt-5 flex justify-center gap-3"><button type="button" onClick={()=>fileInputRef.current?.click()} className="rounded-xl bg-blue-600 px-5 py-3 font-black">Choose files</button>{uploading?<button type="button" onClick={()=>xhrRef.current?.abort()} className="rounded-xl border border-white/20 px-5 py-3">Cancel</button>:null}</div><input ref={fileInputRef} type="file" multiple onChange={e=>appendFiles(e.target.files)} className="hidden"/></div>
    {files.length?<div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-black">Package review: {files.length} file{files.length===1?"":"s"}</p>{contentDestination==="courses"?<p className="mt-1 text-xs text-slate-400">Inferred values are shown first; “fallback” means the shared field above will be used.</p>:null}</div><button type="button" onClick={()=>setFiles([])} className="text-sm font-bold text-red-300">Clear selection</button></div><div className="mt-4 max-h-96 space-y-3 overflow-auto">{files.map((f,i)=>{const inferredTrack=inferTrack(f.name),inferredLevel=inferLevel(f.name),inferredLanguage=inferLanguage(f.name),inferredTitle=inferTitle(f.name);return <div key={`${f.name}-${i}`} className="rounded-xl border border-white/10 bg-[#0c1528] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="break-all text-sm font-bold text-white">{f.name}</p><p className="text-xs text-slate-500">{(f.size/1024/1024).toFixed(2)} MB</p></div>{contentDestination==="courses"?<div className="mt-3 grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-slate-500">Color</span><p className={inferredTrack?"font-bold text-emerald-300":"font-bold text-amber-300"}>{inferredTrack?.toUpperCase()??`${courseTrack.toUpperCase()} (fallback)`}</p></div><div><span className="text-slate-500">Level</span><p className={inferredLevel?"font-bold text-emerald-300":"font-bold text-amber-300"}>{(inferredLevel??courseLevel).replace("level-","Level ")}{inferredLevel?"":" (fallback)"}</p></div><div><span className="text-slate-500">Language</span><p className={inferredLanguage?"font-bold text-emerald-300":"font-bold text-amber-300"}>{languageLabel(inferredLanguage??language)}{inferredLanguage?"":" (fallback)"}</p></div><div><span className="text-slate-500">Title</span><p className={inferredTitle?"font-bold text-emerald-300":"font-bold text-amber-300"}>{inferredTitle??(title.trim()||"Mixed curriculum upload (fallback)")}</p></div></div>:null}</div>;})}</div></div>:null}
    {uploading?<div><div className="mb-2 flex justify-between text-sm"><span>Uploading and preparing batch…</span><span>{progress}%</span></div><div className="h-2 overflow-hidden rounded bg-slate-800"><div className="h-full bg-blue-500" style={{width:`${progress}%`}}/></div></div>:null}{error?<p className="rounded-xl border border-red-500/30 bg-red-950/40 p-4 text-red-200">{error}</p>:null}{success?<p className="rounded-xl border border-emerald-500/30 bg-emerald-950/40 p-4 text-emerald-200">{success}</p>:null}
    <button disabled={uploading||!csrfToken} className="w-full rounded-2xl bg-emerald-600 px-6 py-4 text-lg font-black disabled:opacity-50">{uploading?"Processing batch…":"Upload for Review"}</button></>}</form>;
}
