"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ADMIN_CONTENT_LANGUAGES, ADMIN_CONTENT_LANGUAGE_LABELS, type AdminContentLanguage } from "@/lib/admin-content/languages";
import { MEMBERSHIP_ACCESS } from "@/lib/admin-content/constants";

const COURSE_LEVELS = ["level-1", "level-2", "level-3", "level-4", "level-5"] as const;
const MARKETPLACE_CATEGORIES = ["books","ebooks","pdf-guides","templates","worksheets","forms","downloads","zip-packages","audio","videos","images","software","digital-products","calculators","presentations","spreadsheets","future-products"] as const;
type Track = "red" | "white" | "blue" | "green" | "gold" | "purple" | "orange" | "black";
type MembershipAccess = (typeof MEMBERSHIP_ACCESS)[number];
const TRACKS: Array<{value:Track;label:string}> = [
  {value:"red",label:"🔴 Red — Real Estate"},{value:"white",label:"⚪ White — Paper Assets"},{value:"blue",label:"🔵 Blue — Business"},{value:"green",label:"🟢 Green — Taxes"},{value:"gold",label:"🟡 Gold — Investing"},{value:"purple",label:"🟣 Purple — Law"},{value:"orange",label:"🟠 Orange — Sales & Marketing"},{value:"black",label:"⚫ Black — Leadership & Executive Management"},
];

export default function UploadClient() {
  const router=useRouter(), fileInputRef=useRef<HTMLInputElement|null>(null), xhrRef=useRef<XMLHttpRequest|null>(null);
  const [files,setFiles]=useState<File[]>([]), [contentDestination,setContentDestination]=useState<""|"courses"|"marketplace">(""), [batchName,setBatchName]=useState(""), [source,setSource]=useState("Admin dashboard"), [notes,setNotes]=useState("");
  const [courseTrack,setCourseTrack]=useState<Track>("red"), [courseLevel,setCourseLevel]=useState<(typeof COURSE_LEVELS)[number]>("level-1"), [marketplaceCategory,setMarketplaceCategory]=useState<(typeof MARKETPLACE_CATEGORIES)[number]>("books");
  const [language,setLanguage]=useState<AdminContentLanguage>("en-US"), [membershipAccess,setMembershipAccess]=useState<MembershipAccess>("basic"), [publicationStatus,setPublicationStatus]=useState<"draft"|"review"|"published"|"archived">("draft");
  const [title,setTitle]=useState(""), [description,setDescription]=useState(""), [thumbnailUrl,setThumbnailUrl]=useState(""), [previewUrl,setPreviewUrl]=useState(""), [associatedTrack,setAssociatedTrack]=useState<""|Track>(""), [associatedLevel,setAssociatedLevel]=useState<""|(typeof COURSE_LEVELS)[number]>("");
  const [csrfToken,setCsrfToken]=useState(""), [error,setError]=useState(""), [success,setSuccess]=useState(""), [uploading,setUploading]=useState(false), [progress,setProgress]=useState(0);
  useEffect(()=>{void(async()=>{const response=await fetch("/api/admin/auth/session",{cache:"no-store"});const payload=await response.json();setCsrfToken(payload.csrfToken??"");})();},[]);
  function appendFiles(list:FileList|null){if(!list)return;setFiles(current=>{const seen=new Set(current.map(f=>`${f.name}:${f.size}:${f.lastModified}`)),next=[...current];for(const file of Array.from(list)){const key=`${file.name}:${file.size}:${file.lastModified}`;if(!seen.has(key)){seen.add(key);next.push(file);}}return next;});setError("");}
  function validateBeforeUpload(){if(!contentDestination)return"Choose CONTENT DESTINATION first.";if(!title.trim())return"Title is required.";if(!description.trim())return"Description is required.";if(files.length===0)return"Select at least one file or ZIP package.";return"";}
  function uploadFileDirect(file:File,url:string,method:string,headers:Record<string,string>,onProgress:(pct:number)=>void):Promise<void>{return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhrRef.current=xhr;xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(Math.round(e.loaded/e.total*100));};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error(`Direct upload failed (HTTP ${xhr.status}): ${xhr.responseText}`));xhr.onerror=()=>reject(new Error("Network error during file upload."));xhr.onabort=()=>reject(new Error("Upload canceled."));xhr.open(method,url);Object.entries(headers).forEach(([k,v])=>xhr.setRequestHeader(k,v));xhr.send(file);});}
  async function handleSubmit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const validation=validateBeforeUpload();if(validation){setError(validation);return;}setUploading(true);setError("");setSuccess("");setProgress(0);
    const sharedConfig:Record<string,string>={batchName:batchName||`Content Upload ${new Date().toISOString().slice(0,10)}`,source,notes,contentDestination,language,membershipAccess,publicationStatus,title,description,thumbnailUrl,previewUrl};if(contentDestination==="courses"){sharedConfig.courseTrack=courseTrack;sharedConfig.courseLevel=courseLevel;}else{sharedConfig.marketplaceCategory=marketplaceCategory;sharedConfig.associatedTrack=associatedTrack;sharedConfig.associatedLevel=associatedLevel;}
    let presignResult:{batchId:string;uploads:Array<{uploadId:string;storagePath:string;safeName:string;signedUrl:string|null;directUpload:{url:string;headers:Record<string,string>}|null}>}|null=null;
    try{const response=await fetch("/api/admin/content/upload/presign",{method:"POST",headers:{"Content-Type":"application/json","x-csrf-token":csrfToken},body:JSON.stringify({...sharedConfig,files:files.map(f=>({name:f.name,size:f.size,type:f.type}))})});if(!response.ok){const parsed=await response.json().catch(()=>({}));throw new Error(parsed.error??"Failed to prepare upload.");}presignResult=await response.json();}catch(err){if(err instanceof Error&&err.message!=="Failed to fetch"){setUploading(false);setError(err.message);return;}}
    const allDirect=presignResult&&presignResult.uploads.every(u=>u.signedUrl||u.directUpload);if(presignResult&&allDirect){try{for(let i=0;i<files.length;i++){const file=files[i],spec=presignResult.uploads[i],base=Math.round(i/files.length*85);if(spec.signedUrl)await uploadFileDirect(file,spec.signedUrl,"PUT",{"Content-Type":file.type||"application/octet-stream"},pct=>setProgress(base+Math.round(pct/100*(85/files.length))));else if(spec.directUpload)await uploadFileDirect(file,spec.directUpload.url,"POST",{...spec.directUpload.headers,"Content-Type":file.type||"application/octet-stream"},pct=>setProgress(base+Math.round(pct/100*(85/files.length))));}setProgress(90);const response=await fetch("/api/admin/content/upload/finalize",{method:"POST",headers:{"Content-Type":"application/json","x-csrf-token":csrfToken},body:JSON.stringify({...sharedConfig,batchId:presignResult.batchId,uploads:files.map((file,i)=>({uploadId:presignResult!.uploads[i].uploadId,originalFilename:file.name,mimeType:file.type||"application/octet-stream",sizeBytes:file.size,storagePath:presignResult!.uploads[i].storagePath}))})});if(!response.ok){const parsed=await response.json().catch(()=>({}));throw new Error(parsed.error??"Upload processing failed.");}const payload=await response.json();setProgress(100);setSuccess("Upload complete. Opening batch review.");router.push(`/admin/content/batches/${payload.batch.id}`);router.refresh();return;}catch(err){setUploading(false);setError((err as Error).message);return;}}
    const max=6*1024*1024,oversized=files.filter(f=>f.size>max);if(oversized.length&&typeof window!=="undefined"&&!window.location.hostname.includes("localhost")){setUploading(false);setError(`Direct Supabase upload is not configured. These files exceed the 6 MB serverless fallback limit: ${oversized.map(f=>f.name).join(", ")}.`);return;}
    const formData=new FormData();Object.entries(sharedConfig).forEach(([k,v])=>formData.append(k,v));files.forEach(f=>formData.append("files",f));const xhr=new XMLHttpRequest();xhrRef.current=xhr;xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100));};xhr.onload=()=>{setUploading(false);if(xhr.status<200||xhr.status>=300){try{setError(JSON.parse(xhr.responseText).error??"Upload failed.");}catch{setError("Upload failed.");}return;}const payload=JSON.parse(xhr.responseText);router.push(`/admin/content/batches/${payload.batch.id}`);router.refresh();};xhr.onerror=()=>{setUploading(false);setError("Network error while uploading.");};xhr.onabort=()=>{setUploading(false);setError("Upload canceled.");};xhr.open("POST","/api/admin/content/upload");xhr.setRequestHeader("x-csrf-token",csrfToken);xhr.send(formData);
  }
  return <form onSubmit={handleSubmit} className="mx-auto max-w-5xl space-y-7">
    <label className="grid gap-2 text-sm font-bold text-slate-200">CONTENT DESTINATION *<select value={contentDestination} onChange={e=>{setContentDestination(e.target.value as typeof contentDestination);setFiles([]);setError("");}} className="rounded-xl border border-white/10 bg-[#101a2f] px-4 py-3 text-white"><option value="">Select destination</option><option value="courses">COURSES / CURRICULUM</option><option value="marketplace">MARKETPLACE</option></select></label>
    {!contentDestination?null:<><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Batch name<input value={batchName} onChange={e=>setBatchName(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3" placeholder="RED Level 2 expansion"/></label><label className="grid gap-2 text-sm font-semibold">Source<input value={source} onChange={e=>setSource(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3"/></label></div>
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Batch / Course Title *<input value={title} onChange={e=>setTitle(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3"/></label><label className="grid gap-2 text-sm font-semibold">Language *<select value={language} onChange={e=>setLanguage(e.target.value as AdminContentLanguage)} className="rounded-xl bg-[#101a2f] px-4 py-3">{ADMIN_CONTENT_LANGUAGES.map(locale=><option key={locale} value={locale}>{ADMIN_CONTENT_LANGUAGE_LABELS[locale]}</option>)}</select></label>
    <label className="grid gap-2 text-sm font-semibold">Membership Access *<select value={membershipAccess} onChange={e=>setMembershipAccess(e.target.value as MembershipAccess)} className="rounded-xl bg-[#101a2f] px-4 py-3">{MEMBERSHIP_ACCESS.map(tier=><option key={tier} value={tier}>{tier.charAt(0).toUpperCase()+tier.slice(1)}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Publication Status *<select value={publicationStatus} onChange={e=>setPublicationStatus(e.target.value as typeof publicationStatus)} className="rounded-xl bg-[#101a2f] px-4 py-3"><option value="draft">Draft</option><option value="review">Review</option><option value="published">Published</option><option value="archived">Archived</option></select></label>
    {contentDestination==="courses"?<><label className="grid gap-2 text-sm font-semibold">Color Track *<select value={courseTrack} onChange={e=>setCourseTrack(e.target.value as Track)} className="rounded-xl bg-[#101a2f] px-4 py-3">{TRACKS.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Level *<select value={courseLevel} onChange={e=>setCourseLevel(e.target.value as typeof courseLevel)} className="rounded-xl bg-[#101a2f] px-4 py-3">{COURSE_LEVELS.map(l=><option key={l} value={l}>{l.replace("level-","Level ")}</option>)}</select></label></>:<><label className="grid gap-2 text-sm font-semibold">Marketplace Category *<select value={marketplaceCategory} onChange={e=>setMarketplaceCategory(e.target.value as typeof marketplaceCategory)} className="rounded-xl bg-[#101a2f] px-4 py-3">{MARKETPLACE_CATEGORIES.map(c=><option key={c} value={c}>{c.replaceAll("-"," ")}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Optional Course Association<div className="grid grid-cols-2 gap-2"><select value={associatedTrack} onChange={e=>setAssociatedTrack(e.target.value as typeof associatedTrack)} className="rounded-xl bg-[#101a2f] px-3 py-3"><option value="">Track</option>{TRACKS.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select><select value={associatedLevel} onChange={e=>setAssociatedLevel(e.target.value as typeof associatedLevel)} className="rounded-xl bg-[#101a2f] px-3 py-3"><option value="">Level</option>{COURSE_LEVELS.map(l=><option key={l} value={l}>{l.replace("level-","Level ")}</option>)}</select></div></label></>}</div>
    <label className="grid gap-2 text-sm font-semibold">Description *<textarea value={description} onChange={e=>setDescription(e.target.value)} className="min-h-24 rounded-xl bg-[#101a2f] px-4 py-3"/></label><label className="grid gap-2 text-sm font-semibold">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="min-h-20 rounded-xl bg-[#101a2f] px-4 py-3"/></label>
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Thumbnail URL (optional)<input value={thumbnailUrl} onChange={e=>setThumbnailUrl(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3"/></label><label className="grid gap-2 text-sm font-semibold">Preview URL (optional)<input value={previewUrl} onChange={e=>setPreviewUrl(e.target.value)} className="rounded-xl bg-[#101a2f] px-4 py-3"/></label></div>
    <div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();appendFiles(e.dataTransfer.files);}} className="rounded-3xl border border-dashed border-blue-400/50 bg-[#101a2f] p-10 text-center"><p className="text-lg font-black">Drop files or a ZIP curriculum package here</p><p className="mt-2 text-sm text-slate-400">Multiple files are supported. Large packages upload directly to private Supabase storage.</p><div className="mt-5 flex justify-center gap-3"><button type="button" onClick={()=>fileInputRef.current?.click()} className="rounded-xl bg-blue-600 px-5 py-3 font-black">Choose files</button>{uploading?<button type="button" onClick={()=>xhrRef.current?.abort()} className="rounded-xl border border-white/20 px-5 py-3">Cancel</button>:null}</div><input ref={fileInputRef} type="file" multiple onChange={e=>appendFiles(e.target.files)} className="hidden"/></div>
    {files.length?<div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="font-black">Selected: {files.length} file{files.length===1?"":"s"}</p><div className="mt-3 max-h-48 space-y-1 overflow-auto text-sm text-slate-400">{files.map((f,i)=><p key={`${f.name}-${i}`}>{f.name} — {(f.size/1024/1024).toFixed(2)} MB</p>)}</div><button type="button" onClick={()=>setFiles([])} className="mt-3 text-sm font-bold text-red-300">Clear selection</button></div>:null}
    {uploading?<div><div className="mb-2 flex justify-between text-sm"><span>Uploading and preparing batch…</span><span>{progress}%</span></div><div className="h-2 overflow-hidden rounded bg-slate-800"><div className="h-full bg-blue-500" style={{width:`${progress}%`}}/></div></div>:null}{error?<p className="rounded-xl border border-red-500/30 bg-red-950/40 p-4 text-red-200">{error}</p>:null}{success?<p className="rounded-xl border border-emerald-500/30 bg-emerald-950/40 p-4 text-emerald-200">{success}</p>:null}
    <button disabled={uploading||!csrfToken} className="w-full rounded-2xl bg-emerald-600 px-6 py-4 text-lg font-black disabled:opacity-50">{uploading?"Processing batch…":"Upload for Review"}</button></>}</form>;
}
