"use client";

import { useEffect, useRef, useState } from "react";

type TransitionType = "cut" | "fade" | "wipeleft" | "wiperight" | "slideleft" | "slideright";
type SceneDraft = { file: File; assetId?: string; durationSeconds: number; overlayText: string; fitMode: "contain" | "cover"; transitionType: TransitionType; transitionSeconds: number };

function csrfToken() { const match = document.cookie.match(/(?:^|; )edunancial_admin_csrf=([^;]+)/u); return match ? decodeURIComponent(match[1]) : ""; }
async function jsonRequest(url: string, init: RequestInit) { const response = await fetch(url, { ...init, headers: { "content-type": "application/json", "x-csrf-token": csrfToken(), ...(init.headers ?? {}) }, cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok || data.success === false) throw new Error(data.error || `Request failed (${response.status}).`); return data; }
async function uploadSigned(url: string, file: Blob, mimeType: string) { const response = await fetch(url, { method: "PUT", headers: { "content-type": mimeType }, body: file }); if (!response.ok) throw new Error(`Private asset upload failed (${response.status}).`); }

export default function MarketingShortClient() {
  const [title, setTitle] = useState(""); const [scenes, setScenes] = useState<SceneDraft[]>([]);
  const [narration, setNarration] = useState<Blob | null>(null); const [narrationName, setNarrationName] = useState("narration.webm"); const [narrationVolume, setNarrationVolume] = useState(1);
  const [music, setMusic] = useState<File | null>(null); const [musicVolume, setMusicVolume] = useState(0.18);
  const [recording, setRecording] = useState(false); const [projectId, setProjectId] = useState<string | null>(null); const [jobId, setJobId] = useState<string | null>(null); const [status, setStatus] = useState("Ready"); const [outputUrl, setOutputUrl] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const recorderRef = useRef<MediaRecorder | null>(null); const chunksRef = useRef<Blob[]>([]);

  useEffect(() => { if (!jobId) return; let stopped = false; const poll = async () => { try { const response = await fetch(`/api/admin/video/jobs/${jobId}`, { cache: "no-store" }); const data = await response.json(); if (stopped) return; if (data?.status) setStatus(data.status); if (data?.lastError) setError(data.lastError); if (data?.outputUrl) setOutputUrl(data.outputUrl); if (data?.status === "succeeded" || data?.status === "failed") stopped = true; } catch {} }; void poll(); const timer = window.setInterval(() => { if (!stopped) void poll(); }, 2500); return () => { stopped = true; window.clearInterval(timer); }; }, [jobId]);
  function addFiles(files: FileList | null) { if (!files) return; const next = Array.from(files).slice(0, Math.max(0, 30 - scenes.length)).map((file) => ({ file, durationSeconds: 6, overlayText: "", fitMode: "contain" as const, transitionType: "cut" as const, transitionSeconds: 0.35 })); setScenes((current) => [...current, ...next]); }
  function moveScene(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= scenes.length) return; const copy = [...scenes]; [copy[index], copy[target]] = [copy[target], copy[index]]; setScenes(copy); }
  async function startRecording() { setError(null); try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const recorder = new MediaRecorder(stream); chunksRef.current = []; recorder.ondataavailable = (event) => { if (event.data.size) chunksRef.current.push(event.data); }; recorder.onstop = () => { setNarration(new Blob(chunksRef.current, { type: recorder.mimeType || "audio/webm" })); setNarrationName(`narration-${Date.now()}.webm`); stream.getTracks().forEach((track) => track.stop()); }; recorderRef.current = recorder; recorder.start(); setRecording(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "Microphone access failed."); } }
  function stopRecording() { recorderRef.current?.stop(); setRecording(false); }
  function resetStudio() { setTitle(""); setScenes([]); setNarration(null); setNarrationName("narration.webm"); setNarrationVolume(1); setMusic(null); setMusicVolume(0.18); setProjectId(null); setJobId(null); setOutputUrl(null); setError(null); setStatus("Ready"); }

  async function createShort() {
    if (!title.trim() || scenes.length === 0) return; setBusy(true); setError(null); setOutputUrl(null);
    try {
      setStatus("Creating project…"); const first = scenes[0].file;
      const created = await jsonRequest("/api/admin/video/projects", { method: "POST", body: JSON.stringify({ title: title.trim(), fileName: first.name, mimeType: first.type || "application/octet-stream", byteSize: first.size }) }); setProjectId(created.projectId); await uploadSigned(created.signedUploadUrl, first, first.type || "application/octet-stream");
      const uploadedScenes = [...scenes]; uploadedScenes[0] = { ...uploadedScenes[0], assetId: created.assetId };
      for (let i = 1; i < uploadedScenes.length; i += 1) { setStatus(`Uploading scene ${i + 1} of ${uploadedScenes.length}…`); const file = uploadedScenes[i].file; const asset = await jsonRequest(`/api/admin/video/projects/${created.projectId}/assets`, { method: "POST", body: JSON.stringify({ fileName: file.name, mimeType: file.type || "application/octet-stream", byteSize: file.size }) }); await uploadSigned(asset.signedUploadUrl, file, file.type || "application/octet-stream"); uploadedScenes[i] = { ...uploadedScenes[i], assetId: asset.assetId }; } setScenes(uploadedScenes);
      let narrationAssetId: string | null = null; if (narration) { setStatus("Uploading narration…"); const mimeType = narration.type || "audio/webm"; const asset = await jsonRequest(`/api/admin/video/projects/${created.projectId}/assets`, { method: "POST", body: JSON.stringify({ fileName: narrationName, mimeType, byteSize: narration.size }) }); await uploadSigned(asset.signedUploadUrl, narration, mimeType); narrationAssetId = asset.assetId; }
      let musicAssetId: string | null = null; if (music) { setStatus("Uploading background music…"); const mimeType = music.type || "audio/mpeg"; const asset = await jsonRequest(`/api/admin/video/projects/${created.projectId}/assets`, { method: "POST", body: JSON.stringify({ fileName: music.name, mimeType, byteSize: music.size }) }); await uploadSigned(asset.signedUploadUrl, music, mimeType); musicAssetId = asset.assetId; }
      setStatus("Saving composition…"); await jsonRequest(`/api/admin/video/projects/${created.projectId}/composition`, { method: "PUT", body: JSON.stringify({ scenes: uploadedScenes.map((scene) => ({ assetId: scene.assetId, durationSeconds: scene.durationSeconds, overlayText: scene.overlayText, fitMode: scene.fitMode, transitionType: scene.transitionType, transitionSeconds: scene.transitionSeconds })), narration: narrationAssetId ? { assetId: narrationAssetId, locale: "en-US", volume: narrationVolume } : null, backgroundMusic: musicAssetId ? { assetId: musicAssetId, locale: "und", volume: musicVolume } : null }) });
      setStatus("Starting 9:16 render…"); const queued = await jsonRequest("/api/admin/video/jobs", { method: "POST", body: JSON.stringify({ projectId: created.projectId, editRecipe: { trimStart: 0, trimEnd: null, durationSeconds: uploadedScenes[0].durationSeconds } }) }); setJobId(queued.jobId); setStatus("queued");
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create Marketing Short."); setStatus("Failed"); } finally { setBusy(false); }
  }

  return <section className="grid gap-6 lg:grid-cols-[1.25fr_0.75fr]">
    <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6 sm:p-8">
      <h2 className="text-2xl font-black">Marketing Short editor</h2><p className="mt-2 text-sm leading-6 text-slate-400">Build a vertical Short from up to 30 scenes, narration, transitions, text overlays, and optional background music.</p>
      <label className="mt-6 block text-sm font-bold text-slate-200">Project title</label><input value={title} onChange={(e) => setTitle(e.target.value)} maxLength={200} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-950/50 px-4 py-3" />
      <label className="mt-5 block text-sm font-bold text-slate-200">Artwork / video scenes</label><input type="file" multiple accept="image/png,image/jpeg,image/webp,video/mp4,video/webm" onChange={(e) => addFiles(e.target.files)} className="mt-2 block w-full rounded-xl border border-dashed border-white/20 bg-slate-950/30 p-4 text-sm" />
      <div className="mt-4 space-y-3">{scenes.map((scene, index) => <div key={`${scene.file.name}-${index}`} className="rounded-2xl border border-white/10 bg-slate-950/40 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-bold">Scene {index + 1}: {scene.file.name}</p><div className="flex gap-2"><button type="button" onClick={() => moveScene(index,-1)} className="rounded-lg border border-white/15 px-3 py-2 text-xs">Up</button><button type="button" onClick={() => moveScene(index,1)} className="rounded-lg border border-white/15 px-3 py-2 text-xs">Down</button><button type="button" onClick={() => setScenes((c) => c.filter((_,i) => i !== index))} className="rounded-lg border border-red-400/30 px-3 py-2 text-xs text-red-200">Remove</button></div></div><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-xs text-slate-400">Duration (sec)<input type="number" min={1} max={60} value={scene.durationSeconds} onChange={(e) => setScenes((c) => c.map((x,i) => i===index ? {...x,durationSeconds:Number(e.target.value)} : x))} className="mt-1 w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-2" /></label><label className="text-xs text-slate-400">Fit<select value={scene.fitMode} onChange={(e) => setScenes((c) => c.map((x,i) => i===index ? {...x,fitMode:e.target.value as "contain"|"cover"} : x))} className="mt-1 w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-2"><option value="contain">Contain</option><option value="cover">Cover</option></select></label><label className="text-xs text-slate-400">Optional overlay<input value={scene.overlayText} onChange={(e) => setScenes((c) => c.map((x,i) => i===index ? {...x,overlayText:e.target.value} : x))} maxLength={500} className="mt-1 w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-2" /></label></div>{index < scenes.length - 1 ? <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-400">Transition to next scene<select value={scene.transitionType} onChange={(e) => setScenes((c) => c.map((x,i) => i===index ? {...x,transitionType:e.target.value as TransitionType} : x))} className="mt-1 w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-2"><option value="cut">Cut</option><option value="fade">Crossfade</option><option value="wipeleft">Wipe left</option><option value="wiperight">Wipe right</option><option value="slideleft">Slide left</option><option value="slideright">Slide right</option></select></label>{scene.transitionType !== "cut" ? <label className="text-xs text-slate-400">Transition duration: {scene.transitionSeconds.toFixed(2)} sec<input type="range" min="0.1" max="1.5" step="0.05" value={scene.transitionSeconds} onChange={(e) => setScenes((c) => c.map((x,i) => i===index ? {...x,transitionSeconds:Number(e.target.value)} : x))} className="mt-2 w-full" /></label> : null}</div> : null}</div>)}</div>
      <div className="mt-6 rounded-2xl border border-blue-400/20 bg-blue-950/20 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">Narration</p><p className="text-xs text-slate-400">Record your voice or upload audio.</p></div>{!recording ? <button type="button" onClick={startRecording} className="rounded-lg bg-blue-400 px-4 py-2 text-sm font-black text-slate-950">Start recording</button> : <button type="button" onClick={stopRecording} className="rounded-lg bg-red-400 px-4 py-2 text-sm font-black text-slate-950">Stop recording</button>}</div><input type="file" accept="audio/*" onChange={(e) => { const f=e.target.files?.[0]; if(f){setNarration(f);setNarrationName(f.name);} }} className="mt-3 block w-full text-sm" />{narration ? <label className="mt-3 block text-xs text-slate-300">Narration volume: {Math.round(narrationVolume*100)}%<input type="range" min="0" max="2" step="0.05" value={narrationVolume} onChange={(e)=>setNarrationVolume(Number(e.target.value))} className="mt-1 w-full" /></label> : null}</div>
      <div className="mt-4 rounded-2xl border border-purple-400/20 bg-purple-950/20 p-4"><p className="font-bold">Background music</p><p className="mt-1 text-xs text-slate-400">Upload music you have permission to use. It will be mixed underneath narration.</p><input type="file" accept="audio/*" onChange={(e)=>setMusic(e.target.files?.[0] ?? null)} className="mt-3 block w-full text-sm" />{music ? <><p className="mt-2 text-xs text-green-300">Music ready: {music.name}</p><label className="mt-3 block text-xs text-slate-300">Music volume: {Math.round(musicVolume*100)}%<input type="range" min="0" max="1" step="0.01" value={musicVolume} onChange={(e)=>setMusicVolume(Number(e.target.value))} className="mt-1 w-full" /></label></> : null}</div>
      <button type="button" disabled={busy || scenes.length===0 || !title.trim()} onClick={createShort} className="mt-7 w-full rounded-xl bg-yellow-400 px-5 py-4 text-base font-black text-slate-950 disabled:opacity-40">{busy ? "Preparing…" : `Render ${scenes.length || ""} Scene Marketing Short`}</button>
    </div>
    <aside className="rounded-3xl border border-white/10 bg-slate-950/40 p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.25em] text-blue-300">Render status</p><p className="mt-4 text-2xl font-black capitalize">{status}</p>{outputUrl ? <video src={outputUrl} controls playsInline preload="metadata" className="mt-6 aspect-[9/16] max-h-[520px] w-full rounded-2xl border border-white/10 bg-black object-contain" /> : <div className="mt-6 aspect-[9/16] max-h-[520px] rounded-2xl border border-white/10 bg-black/40 p-5 text-center text-sm text-slate-400"><div className="flex h-full items-center justify-center">1080 × 1920 vertical output</div></div>}{outputUrl ? <div className="mt-5 grid gap-3"><a href={outputUrl} download={`${title.trim().replace(/[^a-z0-9]+/giu,"-").replace(/^-|-$/gu,"") || "edunancial-short"}.mp4`} className="rounded-xl bg-green-400 px-5 py-3 text-center font-black text-slate-950">Download MP4</a><button type="button" onClick={resetStudio} className="rounded-xl border border-white/15 px-5 py-3 font-bold">Create another video</button></div> : null}{projectId ? <p className="mt-4 break-all text-xs text-slate-500">Project: {projectId}</p> : null}{jobId ? <p className="mt-1 break-all text-xs text-slate-500">Job: {jobId}</p> : null}{error ? <div className="mt-5 rounded-xl border border-red-400/30 bg-red-950/30 p-4 text-sm text-red-200">{error}</div> : null}</aside>
  </section>;
}
