import { getKpiSupabaseAdmin } from "@/lib/kpi/supabaseAdmin";

export type LiveValue = { value: number | null; status: "LIVE" | "UNAVAILABLE"; source: string };
export interface ExecutiveOperationsSnapshot {
  asOf: string; grossRevenue: LiveValue; netRevenue: LiveValue; activeMembers: LiveValue; newMembers30d: LiveValue; basicMembers: LiveValue; proMembers: LiveValue; goldMembers: LiveValue; activeSubscriptions: LiveValue; mrr: LiveValue; arr: LiveValue; failedPayments: LiveValue; refunds: LiveValue; salesTaxCollected: LiveValue; salesTaxRemitted: LiveValue; salesTaxDue: LiveValue; totalBusinessTaxDue: LiveValue; taxJurisdictionsDue: LiveValue;
  video: { projects: LiveValue; mastersReady: LiveValue; queuedJobs: LiveValue; processingJobs: LiveValue; successfulRenders: LiveValue; failedRenders: LiveValue; renders30d: LiveValue; successRate: LiveValue };
  upload: { status: "READY" | "DEGRADED" | "BLOCKED"; signedUploadConfigured: boolean; fallbackAvailable: boolean; githubPublishingConfigured: boolean; failures24h: number | null; fallbacks24h: number | null; lastFailure: string | null; problems: string[] };
}
type PaymentRow={amount:number|string|null;status:string|null}; type MemberRow={membership_tier:string|null;active:boolean|null}; type SubRow={plan_id:string;status:string|null}; type TaxRow={country_code:string;jurisdiction_code:string|null;tax_type:string;tax_collected:number|string|null;tax_remitted:number|string|null;amount_due:number|string|null}; type UploadOp={status:string;error_message:string|null}; type VideoProject={status:string|null}; type VideoJob={status:string|null;completed_at:string|null};
const live=(value:number|null,source:string):LiveValue=>({value,status:value===null?"UNAVAILABLE":"LIVE",source}); const num=(v:unknown)=>{const p=Number(v??0);return Number.isFinite(p)?p:0}; const no=(s:string)=>live(null,s);
const monthlyPlanPrice=(id:string)=>{const p=id.toLowerCase(); if(p.includes("basic"))return 39.99; if(p.includes("premium")||p.includes("pro"))return 69.99; if(p.includes("enterprise")||p.includes("gold"))return 99.99; return 0};
export async function getExecutiveOperationsSnapshot():Promise<ExecutiveOperationsSnapshot>{
 const asOf=new Date().toISOString(), since30=new Date(Date.now()-30*86400000).toISOString(), since24=new Date(Date.now()-86400000).toISOString();
 const signedUploadConfigured=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL?.trim()&&process.env.SUPABASE_SERVICE_ROLE_KEY?.trim()&&(process.env.EDUNANCIAL_UPLOAD_STORAGE_BUCKET?.trim()||process.env.EDUNANCIAL_UPLOAD_STORAGE_KEY?.trim())); const githubPublishingConfigured=Boolean(process.env.EDUNANCIAL_GITHUB_TOKEN?.trim()&&process.env.EDUNANCIAL_GITHUB_OWNER?.trim()&&process.env.EDUNANCIAL_GITHUB_REPO?.trim()); const fallbackAvailable=process.env.NODE_ENV!=="production"||Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL?.trim()); const problems:string[]=[]; if(!signedUploadConfigured)problems.push("Signed upload configuration incomplete."); if(!githubPublishingConfigured)problems.push("GitHub publishing configuration incomplete.");
 try{
  const db=getKpiSupabaseAdmin();
  const [pr,mr,nr,sr,tr,ur,vpr,vjr]=await Promise.all([
   db.from("payment_transactions").select("amount,status"), db.from("members").select("membership_tier,active"), db.from("members").select("id",{count:"exact",head:true}).gte("created_at",since30), db.from("subscriptions").select("plan_id,status"), db.from("business_tax_ledger").select("country_code,jurisdiction_code,tax_type,tax_collected,tax_remitted,amount_due"), db.from("admin_upload_operations").select("status,error_message").gte("created_at",since24).order("created_at",{ascending:false}).limit(500), db.from("video_projects").select("status"), db.from("video_jobs").select("status,completed_at")
  ]);
  const payments=pr.error?null:(pr.data??[]) as PaymentRow[], members=mr.error?null:(mr.data??[]) as MemberRow[], subs=sr.error?null:(sr.data??[]) as SubRow[], taxes=tr.error?null:(tr.data??[]) as TaxRow[], ops=ur.error?null:(ur.data??[]) as UploadOp[], projects=vpr.error?null:(vpr.data??[]) as VideoProject[], jobs=vjr.error?null:(vjr.data??[]) as VideoJob[];
  const completed=payments?.filter(r=>r.status==="completed")??null, refunded=payments?.filter(r=>r.status==="refunded")??null, failed=payments?.filter(r=>r.status==="failed")??null; const gross=completed?completed.reduce((s,r)=>s+num(r.amount),0):null, refundTotal=refunded?refunded.reduce((s,r)=>s+num(r.amount),0):null, net=gross===null||refundTotal===null?null:gross-refundTotal;
  const active=members?.filter(r=>r.active)??null, tier=(name:string)=>active?active.filter(r=>(r.membership_tier??"").toLowerCase().includes(name)).length:null; const activeSubs=subs?.filter(r=>r.status==="active")??null; const mrr=activeSubs?activeSubs.reduce((s,r)=>s+monthlyPlanPrice(r.plan_id),0):null;
  const sales=taxes?.filter(r=>r.tax_type==="SALES_CONSUMPTION")??null, collected=sales?sales.reduce((s,r)=>s+num(r.tax_collected),0):null, remitted=sales?sales.reduce((s,r)=>s+num(r.tax_remitted),0):null, salesDue=sales?sales.reduce((s,r)=>s+num(r.amount_due),0):null, totalDue=taxes?taxes.reduce((s,r)=>s+num(r.amount_due),0):null, jurisdictions=taxes?new Set(taxes.filter(r=>num(r.amount_due)>0).map(r=>`${r.country_code}:${r.jurisdiction_code??""}`)).size:null;
  const failures=ops?.filter(r=>r.status==="FAILED")??null, fallbacks=ops?.filter(r=>r.status==="FALLBACK")??null, lastFailure=failures?.[0]?.error_message??null; if(failures?.length)problems.push(`${failures.length} upload pipeline failure(s) recorded in the last 24 hours.`); const uploadStatus=!signedUploadConfigured||!githubPublishingConfigured?"BLOCKED":failures?.length?"DEGRADED":"READY";
  const succeeded=jobs?.filter(r=>r.status==="succeeded")??null, videoFailed=jobs?.filter(r=>r.status==="failed")??null, terminal=succeeded&&videoFailed?succeeded.length+videoFailed.length:null, successRate=terminal===null?null:terminal===0?0:(succeeded!.length/terminal)*100, renders30d=jobs?jobs.filter(r=>r.completed_at&&r.completed_at>=since30).length:null;
  return {asOf,grossRevenue:payments?live(gross,"payment_transactions"):no("payment_transactions"),netRevenue:payments?live(net,"payment_transactions"):no("payment_transactions"),activeMembers:active?live(active.length,"members"):no("members"),newMembers30d:nr.error?no("members"):live(nr.count??0,"members"),basicMembers:active?live(tier("basic"),"members"):no("members"),proMembers:active?live(tier("premium")!+tier("pro")!,"members"):no("members"),goldMembers:active?live(tier("enterprise")!+tier("gold")!,"members"):no("members"),activeSubscriptions:activeSubs?live(activeSubs.length,"subscriptions"):no("subscriptions"),mrr:activeSubs?live(mrr,"subscriptions"):no("subscriptions"),arr:activeSubs?live((mrr??0)*12,"subscriptions"):no("subscriptions"),failedPayments:failed?live(failed.length,"payment_transactions"):no("payment_transactions"),refunds:refunded?live(refundTotal,"payment_transactions"):no("payment_transactions"),salesTaxCollected:sales?live(collected,"business_tax_ledger"):no("business_tax_ledger"),salesTaxRemitted:sales?live(remitted,"business_tax_ledger"):no("business_tax_ledger"),salesTaxDue:sales?live(salesDue,"business_tax_ledger"):no("business_tax_ledger"),totalBusinessTaxDue:taxes?live(totalDue,"business_tax_ledger"):no("business_tax_ledger"),taxJurisdictionsDue:taxes?live(jurisdictions,"business_tax_ledger"):no("business_tax_ledger"),video:{projects:projects?live(projects.length,"video_projects"):no("video_projects"),mastersReady:projects?live(projects.filter(r=>r.status==="master_ready").length,"video_projects"):no("video_projects"),queuedJobs:jobs?live(jobs.filter(r=>r.status==="queued").length,"video_jobs"):no("video_jobs"),processingJobs:jobs?live(jobs.filter(r=>r.status==="processing").length,"video_jobs"):no("video_jobs"),successfulRenders:succeeded?live(succeeded.length,"video_jobs"):no("video_jobs"),failedRenders:videoFailed?live(videoFailed.length,"video_jobs"):no("video_jobs"),renders30d:jobs?live(renders30d,"video_jobs"):no("video_jobs"),successRate:jobs?live(successRate,"video_jobs"):no("video_jobs")},upload:{status:uploadStatus,signedUploadConfigured,fallbackAvailable,githubPublishingConfigured,failures24h:failures?.length??null,fallbacks24h:fallbacks?.length??null,lastFailure,problems}};
 }catch{return {asOf,grossRevenue:no("payment_transactions"),netRevenue:no("payment_transactions"),activeMembers:no("members"),newMembers30d:no("members"),basicMembers:no("members"),proMembers:no("members"),goldMembers:no("members"),activeSubscriptions:no("subscriptions"),mrr:no("subscriptions"),arr:no("subscriptions"),failedPayments:no("payment_transactions"),refunds:no("payment_transactions"),salesTaxCollected:no("business_tax_ledger"),salesTaxRemitted:no("business_tax_ledger"),salesTaxDue:no("business_tax_ledger"),totalBusinessTaxDue:no("business_tax_ledger"),taxJurisdictionsDue:no("business_tax_ledger"),video:{projects:no("video_projects"),mastersReady:no("video_projects"),queuedJobs:no("video_jobs"),processingJobs:no("video_jobs"),successfulRenders:no("video_jobs"),failedRenders:no("video_jobs"),renders30d:no("video_jobs"),successRate:no("video_jobs")},upload:{status:"BLOCKED",signedUploadConfigured,fallbackAvailable,githubPublishingConfigured,failures24h:null,fallbacks24h:null,lastFailure:null,problems:[...problems,"Executive data source unavailable."]}}}
}
