"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useInternationalPreferences } from "@/components/international/InternationalPreferencesProvider";
import { getPrivacyRegistrationDecision } from "@/lib/age-consent";
import { useAuth, validatePassword } from "@/lib/authContext";
const COUNTRIES=["United States","Canada","Mexico","United Kingdom","Australia","Nigeria","Ghana","Jamaica","Trinidad and Tobago","Barbados","Other"];
export default function RegisterForm(){
 const {register}=useAuth();const {t}=useInternationalPreferences();const router=useRouter();
 const [form,setForm]=useState({firstName:"",lastName:"",email:"",password:"",confirmPassword:"",country:"",dateOfBirth:"",agree:false});const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 const passwordErrors=validatePassword(form.password);function set(field:string,value:string|boolean){setForm(p=>({...p,[field]:value}));}
 async function handleSubmit(e:React.FormEvent){e.preventDefault();setError("");if(!form.firstName||!form.lastName||!form.email||!form.password||!form.country||!form.dateOfBirth){setError(t("register.error.required"));return;}if(passwordErrors.length){setError(t("register.error.passwordRequirements"));return;}if(form.password!==form.confirmPassword){setError(t("register.error.passwordMismatch"));return;}if(!form.agree){setError(t("register.error.agree"));return;}const d=getPrivacyRegistrationDecision(form.country,form.dateOfBirth);if(!d.allowed){setError(d.reason==="manual-review"?"A parent or legal guardian must contact Edunancial before this free account can be created so we can apply the correct privacy requirements.":"A parent or legal guardian must authorize the privacy processing for this free account before it can be created. Please contact privacy@edunancial.com.");return;}setLoading(true);const r=await register({firstName:form.firstName,lastName:form.lastName,email:form.email,password:form.password,country:form.country,dateOfBirth:form.dateOfBirth});setLoading(false);if(r.success)router.push("/verify-email");else setError(r.error??t("register.error.failed"));}
 return <main className="mx-auto max-w-xl px-6 py-16"><div className="rounded-2xl border border-slate-700 bg-slate-900/60 p-10"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[0.35em] text-yellow-400">{t("register.label")}</p><h1 className="mt-4 text-4xl font-bold">{t("register.title")}</h1><p className="mt-3 text-slate-400">{t("register.subtitle")}</p></div>{error&&<div className="mt-6 rounded-lg border border-red-700 bg-red-950/40 px-4 py-3 text-sm text-red-300">{error}</div>}<form onSubmit={handleSubmit} className="mt-8 space-y-5" noValidate>
 <div className="grid gap-4 sm:grid-cols-2"><input className="rounded-lg border border-slate-700 bg-slate-950 p-3" placeholder={t("register.firstNamePlaceholder")} value={form.firstName} onChange={e=>set("firstName",e.target.value)} required/><input className="rounded-lg border border-slate-700 bg-slate-950 p-3" placeholder={t("register.lastNamePlaceholder")} value={form.lastName} onChange={e=>set("lastName",e.target.value)} required/></div>
 <input type="email" className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3" placeholder={t("register.emailPlaceholder")} value={form.email} onChange={e=>set("email",e.target.value)} required/>
 <div><label className="mb-2 block text-sm font-semibold">Country or jurisdiction <span className="text-red-400">*</span></label><select className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3" value={form.country} onChange={e=>set("country",e.target.value)} required><option value="">Select country</option>{COUNTRIES.map(c=><option key={c}>{c}</option>)}</select></div>
 <div><label htmlFor="reg-dob" className="mb-2 block text-sm font-semibold">Date of birth <span className="text-red-400">*</span></label><input id="reg-dob" type="date" autoComplete="bday" className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3" value={form.dateOfBirth} onChange={e=>set("dateOfBirth",e.target.value)} required/><p className="mt-2 text-xs text-slate-400">Used to apply age-appropriate privacy and purchasing rules. Free access does not require adult payment authorization.</p></div>
 <input type="password" autoComplete="new-password" className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3" placeholder={t("register.passwordPlaceholder")} value={form.password} onChange={e=>set("password",e.target.value)} required/>
 <input type="password" autoComplete="new-password" className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3" placeholder={t("register.confirmPasswordPlaceholder")} value={form.confirmPassword} onChange={e=>set("confirmPassword",e.target.value)} required/>
 <label className="flex items-start gap-3 text-sm text-slate-300"><input type="checkbox" checked={form.agree} onChange={e=>set("agree",e.target.checked)} className="mt-0.5"/><span>{t("register.agreePrefix")} <Link href="/terms" className="text-blue-400 underline">{t("register.termsLabel")}</Link> {t("register.agreeAnd")} <Link href="/privacy" className="text-blue-400 underline">{t("register.privacyLabel")}</Link>.</span></label>
 <button type="submit" disabled={loading} className="w-full rounded-xl bg-blue-600 py-3 font-bold disabled:opacity-60">{loading?t("register.creating"):t("register.createAccount")}</button></form><div className="mt-6 text-center text-sm"><Link href="/login" className="text-blue-400 hover:underline">{t("register.loginLink")}</Link></div></div></main>;
}
